microsoft/react-native-macos

React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm
Cherry-pick a **react-native@0.71** commit into the current main branch:
https://github.com/facebook/react-native/commit/904b3b67e29
`_forceDispatchNextScrollEvent` is already called inside `- (void)scrollToOffset:(CGPoint)offset animated:(BOOL)animated`. No need to call it before.
Changelog: [internal]
CircleCI
=> Cherry-pick: Remove redundant _forceDispatchNextScrollEvent calls

React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm
Cherry-pick a **react-native@0.71** commit into the current main branch:
https://github.com/facebook/react-native/commit/dfbf7d4e142
Calling `scrollToOffset` with already set content offset doesn't make sense.
changelog: [internal]
CircleCi
=> Cherry-pick: Early exit in scrollToOffset if contentOffset wouldn't change

ReactCommon/react/renderer/core/EventDispatcher.cpp, ReactCommon/react/renderer/core/EventDispatcher.h, ReactCommon/react/renderer/core/EventListener.cpp, ReactCommon/react/renderer/core/EventListener.h, ReactCommon/react/renderer/scheduler/Scheduler.cpp, ReactCommon/react/renderer/scheduler/Scheduler.h
https://github.com/facebook/react-native/commit/e51e19ecc1d1b8ac5c860eac55338ef13471844f
Minimal set of changes to intercept events in external modules. Current intended use-case is for Reanimated to handle events for the Animated properties.
Changelog: [Added] Add listeners to allow intercepting events in C++ core.
Build rn-tester with Fabric enabled
`
`
and run it. 
```
flow
Version mismatch! Server binary is Flow v0.170.0 but we are using v0.170.0
Restarting command using the same binary as the server
No errors!
```
=> Cherry-pick: Add event listeners to Scheduler

React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm
Cherry-pick a **react-native@0.71** commit into the current main branch: 
https://github.com/facebook/react-native/commit/27fe6f10796
Fixes https://github.com/facebook/react-native/issues/34165 and [Large title fails](https://github.com/reactwg/react-native-new-architecture/discussions/43) on the new React Native architecture.
There are problems with setting `contentInsetAdjustmentBehavior` to `automatic` on the `ScrollView` component in the new React Native architecture. The `automatic` setting matters to navigation libraries (like [my Navigation router](https://github.com/grahammendick/navigation)) because it stops the `ScrollView` from overlapping the `UINavigationBar`. The setting also powers important native features like large titles and search bars on iOS.
The `automatic` setting …
=> Cherry-pick: Fix contentInsetAdjustmentBehavior set to automatic on ScrollView in the new architecture (#34217)

React/Fabric/RCTScheduler.h, React/Fabric/RCTScheduler.mm, React/Fabric/RCTSurfacePresenter.h, React/Fabric/RCTSurfacePresenter.mm
https://github.com/facebook/react-native/commit/614aa869163
Exposes event listener through iOS scheduler wrapper (`RCTScheduler`) and exposes scheduler itself through `RCTSurfacePresenter`.
Changelog: [Changed] Exposed `RCTScheduler` to allow setting event listeners.
Build rn-tester with Fabric enabled
`
`
and run it:
=> Expose scheduler through RCTSurfacePresenter

React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm
https://github.com/facebook/react-native/commit/c032401b672
Fix sticky headers for scrollviews by sending onScroll event to legacy RCTEventDispatcher
Changelog: [Internal][Bridgeless] Fix sticky headers for scrollviews by sending onScroll event to legacy RCTEventDispatcher
Build rn-tester with Fabric enabled
`
`
and run it:
```
react-native-macos % flow
Version mismatch! Server binary is Flow v0.170.0 but we are using v0.170.0
Restarting command using the same binary as the server
No errors!
```
=> Cherry-pick: Fix sticky headers for scrollviews by sending onScroll event to legacy RCTEventDispatcher

React/Fabric/Mounting/ComponentViews/SafeAreaView/RCTSafeAreaViewComponentView.mm
Summary:
Cherry-pick a **react-native@0.71 commit** into the current main branch:
https://github.com/facebook/react-native/commit/d9f93d30e09
This behavior diverges from the original SafeAreaView implementation and causes issues when you try to use SafeAreaView in non-root placements (not recommended)
Changelog: [iOS][Internal]
CirclecI
=> Cherry-pick: Disable default clipping in Fabric's SafeAreaView implementation

React/Fabric/RCTSurfacePresenter.mm
https://github.com/facebook/react-native/commit/cefc0562417
This is shipped on iOS, let's remove gating.
changelog: [internal]
CircleCI
=> Cherry-pick: Remove flag react_native_new_architecture:runtimescheduler_enable_yielding_ios

React/Base/RCTConstants.h, React/Base/RCTConstants.m, React/Fabric/Mounting/RCTComponentViewFactory.mm, React/Fabric/Mounting/RCTComponentViewRegistry.h, React/Fabric/Mounting/RCTComponentViewRegistry.mm, React/Fabric/RCTSurfacePresenter.mm, React/Tests/Mounting/RCTComponentViewRegistryTests.mm
Cherry-pick a react-native@0.70 commit into the current main branch:
https://github.com/facebook/react-native/commit/71dd83afcab
preemtive view allocation has been disabled on iOS for over a year. We kept the code in but didn't do anything with it. This diff removes the code and related mobile config.
changelog: [internal]
Just deleting code
=> Cherry-pick: Delete preemptive view allocation on iOS

React/Fabric/RCTSurfacePresenter.mm
https://github.com/facebook/react-native/commit/88814d52ddd
There is retain cycle because RCTSurfacePresenter is keeping an array of  RCTSurfacePresenterObserver, which is strongly retaining the class that owns this RCTSurfacePresenter.
This diff makes RCTSurfacePresenter weakly retain observers instead.
Changelog: [Fabric][iOS] Fix: Make RCTSurfacePresenter weakly retain its observers
Build iOS with Fabric enabled and test a few examples:
https://user-images.githubusercontent.com/484044/201446166-d0f290a1-20fb-4386-866e-1623bdd86708.mov
=> Cherry-pick: Fix: Make RCTSurfacePresenter weakly retain its observers

React/Fabric/RCTScheduler.h, React/Fabric/RCTScheduler.mm, ReactCommon/react/renderer/scheduler/Scheduler.cpp, ReactCommon/react/renderer/scheduler/Scheduler.h
https://github.com/facebook/react-native/commit/54db5f20129
Exposes `UIManager` instance for access from third-party modules.
Changelog: [Changed] Exposes `UIManager` instance for third-party access.
Run rn-tester-ios with Fabric enabled:
=> Cherry-pick: Expose UIManager from Scheduler (#33545)

React/Base/RCTEventDispatcherProtocol.h, React/CoreModules/RCTEventDispatcher.mm, React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm
Cherry-pick a react-native@0.70 commit into the current main branch:
https://github.com/facebook/react-native/commit/8dded42b68b
ScrollView sticky headers rely on this bit of code to work:
```
AnimatedImplementation.attachNativeEvent(
this._scrollViewRef,
'onScroll',
[{nativeEvent: {contentOffset: {y: this._scrollAnimatedValue}}}],
);
```
What this code means:
When the ScrollView host component receives the "onScroll" event, assign event.nativeEvent.contentOffSet.y to the this._scrollAnimatedValue AnimatedValue.
How this subscription mechanism is set up:
NativeAnimatedTurboModule subscribes to events dispatched by RCTEventDispatcher sendEvent. Then, whenever RCTEventEmitter sendEvent executes, NativeAnimatedTurboModule also updates the AnimatedValue for that event.
Previously, in …
=> Cherry-pick: Make ScrollView sticky headers work w/o dispatching RCTEventEmitter.receiveEvent

React/Fabric/RCTSurfacePresenter.mm, ReactCommon/react/renderer/runtimescheduler/RuntimeScheduler.cpp, ReactCommon/react/renderer/runtimescheduler/RuntimeScheduler.h
https://github.com/facebook/react-native/commit/83631848d2a
Summary: Changelog: [Internal] Emit touch-equivalent W3C pointer events on iOS
Run rn-tester-iOS with Fabric enabled:
https://user-images.githubusercontent.com/484044/201482049-72b404f1-cbd4-4ab7-a1e5-04454e9e2f78.mov
=> Cherry-pick: Permanently enable yielding in runtime scheduler

React/Base/RCTAssert.h, React/Base/RCTAssert.m, React/Base/RCTBridge.m, React/Fabric/Mounting/ComponentViews/LegacyViewManagerInterop/RCTLegacyViewManagerInteropComponentView.mm, React/Modules/RCTUIManager.m, React/Views/RCTViewManager.m
https://github.com/facebook/react-native/commit/743d0706e20
Previously, we only had violation reporting APIs for when **Bridge APIs** are used in **Bridgeless mode**, which was only enabled in Bridgeless mode.
This diff adds violation reporting APIs to use when **pre-Fabric Bridge APIs** are used in **Bridge or Bridgeless mode**. This allows us to add RCTAssert/RCTError/RCTLog to more APIs in Bridge mode. The main purpose is to distinguish between Bridge APIs that still work in Fabric, versus Bridge APIs that are no longer used in Fabric, so that the latter can be removed.
Changelog: [Internal][iOS] Add validation reporting APIs for unexpected uses of Paper when Fabric is enabled
Run rn-iOS with Fabric enabled. Created …
=> Cherry-pick: 1/3 Add validation reporting APIs for unexpected uses of Paper when Fabric is enabled, in Bridge mode

ReactCommon/react/debug/react_native_assert.h, ReactCommon/react/renderer/mounting/StubViewTree.cpp
https://github.com/facebook/react-native/commit/ece1dd4ed9b6b3cbf367f9b3d0380db6349e588e
This is only defined on Windows, and thus code that compiles on all platforms may successfully build on Linux/macOS, but not on Windows, making it potentially harder to detect and debug. Let's unify all platforms to solve this.
Build rn-tester-iOS with Fabric enabled
=> Cherry-pick: BUCK: define GLOG_NO_ABBREVIATED_SEVERITIES everywhere

Libraries/Text/Text/RCTTextView.m, React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, React/Fabric/Mounting/RCTMountingManager.mm, React/Views/RCTView.m
A cherry-pick from facebook/react-native@0.72:
https://github.com/facebook/react-native/commit/c0f06e8bbac4a962a01ec093b74275415302268f
These headers are needed on react-native-macOS, but not explicitly imported all the time.
It seems that some UIKit header will implicitly import them.
We have other use case in react-native(-iOS) in which we also explicitly importing them - https://github.com/facebook/react-native/search?q=QuartzCore- , hence use following 'that' practice 'here'.
Run rn-tester-macOS:
=> Cherry-pick: Adding missing #import <QuartzCore/QuartzCore.h> imports (#35315)

React/Fabric/Mounting/ComponentViews/LegacyViewManagerInterop/RCTLegacyViewManagerInteropComponentView.mm, React/Fabric/Mounting/RCTComponentViewFactory.mm
Cherry-pick a react-native@0.70 commit into the current main branch:
https://github.com/facebook/react-native/commit/b834d5869fd
Changelog: [Internal][iOS]
Build rn-tester-iOS with Fabric enabled:
=> Cherry-pick: Minor: Move RCTLogNewArchitectureValidation in RCTLegacyViewManagerInteropComponentView

React/Views/ScrollView/RCTScrollView.m
RCTScrollView forwards some of its methods to its underlying `_scrollView` of type RCTCustomScrollView. Some of these always return YES, instead of properly implementing the logic. Let's remove the faulty forwarding, so that instead inherited superclass implementation (RCTView) is used. 
Normally, you expect a 1:1 mapping between the JS and native component (e.g: `<View>` maps to `RCTView`). There are notable exceptions, like `<ScrollView>`.
`<ScrollView>`maps to `RCTScrollView` which is a subclass of `RCTView`, not `UIScrollView / NSScrollView`. So how does `RCTScrollView` do its scrolling logic if the underlying component is just a subclass of `RCTView`? It turns out,`RCTScrollView` contains a member variable `_scrollView` (the _real_ NSScrollView / UIScrollView). It then forwards …
=> Remove faulty logic in ScrollView

React/CoreModules/RCTLogBox.h, React/CoreModules/RCTLogBox.mm, React/CoreModules/RCTLogBoxView.h, React/CoreModules/RCTLogBoxView.mm
These files have some 'unnecessary' changes which make it hard(er) to merge in recent changes as: https://github.com/facebook/react-native/commit/37e5fa3a6ce 
Hence un-forking them were possible
[macOS][Fixed] Unfork RCTLogBox
CircleCi for macOS and iOS
Show some beautiful logboxes ...
https://user-images.githubusercontent.com/484044/201546620-6d3bf508-391b-4393-9a40-17322519dc2d.mov
=> Unfork RCTLogBox

React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, React/Fabric/Mounting/RCTComponentViewProtocol.h, React/Fabric/Mounting/RCTMountingManager.mm, React/Fabric/Mounting/UIView+ComponentViewProtocol.h, React/Fabric/Mounting/UIView+ComponentViewProtocol.mm, ReactCommon/react/renderer/components/view/ViewPropsInterpolation.h, ReactCommon/react/renderer/core/ComponentDescriptor.h, ReactCommon/react/renderer/core/ConcreteComponentDescriptor.h, ReactCommon/react/renderer/core/ConcreteShadowNode.h, ReactCommon/react/renderer/core/Props.h, ReactCommon/react/renderer/core/ShadowNode.cpp, ReactCommon/react/renderer/core/ShadowNode.h, ReactCommon/react/renderer/core/tests/ComponentDescriptorTest.cpp, ReactCommon/react/renderer/mounting/StubView.h
Cherry-pick a react-native@0.70 commit into the current main branch:
https://github.com/facebook/react-native/commit/a42170e0f8d
Similarly to https://github.com/facebook/react-native/commit/13a0556aaa3976245ec065b0da68ef865bd03b70, standardize on one type to refer to this.
CircleCI
=> Cherry-pick: Replace SharedProps with Props::Shared

Libraries/NativeAnimation/Nodes/RCTColorAnimatedNode.h, Libraries/NativeAnimation/Nodes/RCTColorAnimatedNode.m, Libraries/NativeAnimation/Nodes/RCTPropsAnimatedNode.m, Libraries/NativeAnimation/Nodes/RCTStyleAnimatedNode.m, Libraries/NativeAnimation/RCTNativeAnimatedNodesManager.m, Libraries/NativeAnimation/React-RCTAnimation.podspec, React/Fabric/Mounting/RCTMountingManager.mm, ReactCommon/react/renderer/graphics/platform/ios/Color.h
There are a number of changes from react-native 0.69 - 0.71:
https://gist.github.com/christophpurrer/9d4d5e893b9637d8f6460cb8663f4143
which we can back port in the current react-native-macOS 0.68 version to smooth future work on Fabric.
Original commit: https://github.com/facebook/react-native/commit/49f3f47b1e9b840e4374d46b105604f4d2c22dd5
Adds support for Animated.Color with native driver for iOS. Reads the native config for the rbga channel AnimatedNodes, and on update(), converts the values into a SharedColor.
Followup changes will include support for platform colors.
[iOS] [Added] - Support color animation with native driver for iOS
Built rn-tester for iOS with and w/o Fabric enabled
=> Cherry-pick: Support color animation with native driver for iOS

React/CoreModules/RCTLogBox.mm, React/CoreModules/RCTLogBoxView.h, React/CoreModules/RCTLogBoxView.mm
https://github.com/microsoft/react-native-macos/commit/55c4a7f2dd2a03ebbb6d84a93815210ee2699501
If an RN app is embedded in a Mac Catalyst app that uses the UIWindowScene API to manage multiple windows, LogBox would fail to render because it didn't know which UIWindowScene to render to. This diff fixes that situation by ensuring that the LogBox window gets rendered in the key window's scene.
[iOS][Fixed] - Update iOS LogBox to render its UIWindow with the key window's UIWindowScene
Open LogBox on rn-tester w/o Fabric enabled
https://user-images.githubusercontent.com/484044/202144881-4fa97eff-2111-4b5a-9194-69165eafd455.mov
=> Cherry-pick: Update iOS LogBox to render its UIWindow with the key window's UIWindowScene

React/Base/Surface/SurfaceHostingView/RCTSurfaceHostingView.mm, React/CoreModules/RCTLogBox.mm, React/CoreModules/RCTLogBoxView.h, React/CoreModules/RCTLogBoxView.mm, React/Fabric/RCTSurfacePresenter.h, React/Fabric/RCTSurfacePresenter.mm, React/Modules/RCTSurfacePresenterStub.h
https://github.com/facebook/react-native/commit/37e5fa3a6ce2445b17d56dd6fd22fbda926537ef
This diff main purpose is to add `RCTErrorNewArchitectureValidation(RCTNotAllowedInAppWideFabric)` in `RCTSurface`, to ensure Paper surfaces are never created in FBiOS.
Before this diff, in Bridged Fabric, `[RCTLogbox show]` initializes a Paper `RCTSurface`, [using `[RCTLogBoxView initWithWindow]`](https://github.com/facebook/react-native/blob/main/React/CoreModules/RCTLogBoxView.mm#L46))
In this diff,  in Bridged and Bridgeless Fabric, `[RCTLogbox show]` initializes a Fabric `RCTFabricSurface`.
Before this diff, in Bridgeless Fabric,  RCTLogBox posts a "CreateLogBoxSurface" notification to RCTInstance.
In this diff, the notification …
=> Cherry-pick: Refactor: Migrate Logbox surface initialization to Fabric when available, in Bridge and Bridgeless modes

package.json
Resolves #1190
[General] [Fixed] - Fixed missing dependency `@react-native-community/cli-tools`
n/a
=> fix: cannot resolve `@react-native-community/cli-tools`

package.json
Cherry-pick of #1529.
Resolves #1190.
[General] [Fixed] - Fixed missing dependency `@react-native-community/cli-tools`
n/a
=> fix: cannot resolve `@react-native-community/cli-tools` (#1529)

package.json, yarn.lock
This gets rid of a dependency on `decode-uri-component@0.2.0`, which has a [known vulnerability](https://github.com/advisories/GHSA-w573-4hg7-7wgq). While there is [a PR](https://github.com/SamVerschueren/decode-uri-component/pull/7) out to fix this, we can temporarily work around it using this forced resolution.
[Internal] [Security] - Temporarily remove dependency on `decode-uri-component`
=> Resolve micromatch to ^4.0.0

React/Fabric/Mounting/ComponentViews/Modal/RCTModalHostViewComponentView.mm
#1533 Added a unterminated conditional that I didn't catch during my testing.
For testing, I build Paper first, then Fabric but for this run I swapped the order.
NOTE: This might be a good reminder that we should setup a CI job to build Fabric for iOS
[FIX] [MacOS] - Fix unterminated conditional that was breaking Fabric iOS build
Build w/ Fabric
https://user-images.githubusercontent.com/96719/206294852-ee6c39b6-ac92-418d-b156-1c035e9e7394.mp4
Build w/ Paper
https://user-images.githubusercontent.com/96719/206295953-af6af4a1-ba23-4011-b4e6-da3a1190a8a1.mp4
=> [Fabric] Fix unterminated conditional that was breaking Fabric iOS build

Libraries/Text/Text.js
The PropTypes package is deprecated on RN Core.
To help folks get off of the package, this deprecation path was left in place.
Removing the reference fixes #1433 
NOTE: This was recently un-deprecated by the core team to allow more time for folks to migrate: https://github.com/facebook/react-native/commit/b966d297245a4c1e2c744cfe571396cfa7e5ffd3
I'm assuming desktop doesn't have the same legacy issues so I think it's fine to remove.
[macOS] [Fix] - Remove reference to deprecated package in TextView
https://user-images.githubusercontent.com/96719/202828000-c3b32a27-25b3-4397-acea-1bcbc1538df2.mp4
https://user-images.githubusercontent.com/96719/202828373-943d5b15-8311-41c9-b275-ff47cd517697.mp4
=> Remove deprecated prop-types reference for Text

React/Base/RCTUIKit.h
#1576 overwrote a change from #1527 in `RCTUIKit.h`
building from `main` was broken after it was merged.
[macOS] [Fabric] - Fix bad merge that removed `RCTUISwitch` definition
[x] Build RNTester - iOS w/ Paper - should work
=> [Fabric] Fix bad merge that removed `RCTUISwitch` definition from #1576

React/Base/RCTUIKit.h, React/Base/macOS/RCTUIKit.m, React/Views/RCTSwitch.h, React/Views/RCTSwitch.m, React/Views/RCTSwitchManager.m
While implementing Fabric for React Native macOS, we created a few new shim classes in RCTUIKit that we could potentially use in our paper implementation as well. This change extends the simple `RCTUISwitch` shim to implement what we need for it to work on Paper (aka, use it in RCTSwitch). The end result is a few less macOS diffs and overall cleaner code in my opinion =)
[macOS] [Chenged] - Use RCTUISwitch shim for RCTSwitch
Test page still works fine. 
https://user-images.githubusercontent.com/6722175/207714665-4b73bb4e-e3ce-4cd5-a03e-809a0577b683.mov
=> Use RCTUISwitch shim in Paper (RCTSwitch)

packages/rn-tester/js/examples/NewAppScreen/NewAppScreenExample.js
75f853dd708be9c4f5eb11fa77019f92bce021ad had fixed this all the way back in RN 0.62, but we seemed to never pick it up. Let's pick it up now.
[macOS] [Changed] - Remove a diff around the NewAppScreen example
CI passes.
=> [Cherry-pick] Pick up upstream fix to NewAppScreen to remove a diff

Libraries/Core/ReactNativeVersion.js, React/Base/RCTVersion.m, ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, ReactCommon/cxxreact/ReactNativeVersion.h, scripts/versiontemplates/RCTVersion.m.template, scripts/versiontemplates/ReactNativeVersion.h.template, scripts/versiontemplates/ReactNativeVersion.java.template, scripts/versiontemplates/ReactNativeVersion.js.template
Back in #944 , I had added a comment about merging _stable branches_ into our main branch. We have then since learned [and documented](https://github.com/microsoft/react-native-macos/blob/main/docs/GitFlow.md) that we shouldn't be doing that: main should merge to main, and stable should either have merges from upstream stable, or cherry picks. 
Let's remove the comment, removing another diff from our repo. 
[Internal] [Removed] - Remove comment on merging stable branches -> main
Removing a comment, nothing should be affected.
=> Remove comment on merging stable branches -> main

Libraries/Image/RCTImageView.h, React/Base/RCTUIKit.h
This came up while resolving conflicts in the 0.71 merge.
Move a typedef associated with `UIImage` to the macOS part of `RCTUIKit`. Once done, we can remove a `#if !TARGET_OS_OSX` if/else block, since `#import <React/RCTUIKit.h>` will bring in either `Appkit` or `UIKit` based on the platform. 
[macOS] [Changed] - Move typdef from RCTImageView -> RCTUIKit
CI should pass
=> Move typdef from RCTImageView -> RCTUIKit

Libraries/Image/RCTImageLoader.mm, React/Base/macOS/RCTUIKit.m
This came up during the 0.71 merge. There was an iOS only method we had already shimmed in [RCTUIKit](https://github.com/microsoft/react-native-macos/blob/71e7ccfc29585c438681042c8ef82c38ad1a1736/React/Base/macOS/RCTUIKit.m#L127):
```objective-c
NSData *UIImagePNGRepresentation(NSImage *image) {
return NSImageDataForFileType(image, NSBitmapImageFileTypePNG, @{});
}
NSData *UIImageJPEGRepresentation(NSImage *image, CGFloat compressionQuality) {
return NSImageDataForFileType(image,
NSBitmapImageFileTypeJPEG,
@{NSImageCompressionFactor: @(1.0)});
}
```
As it turns out, we can't depend on RCTUIKit here, because this file's podspec (React-RCTImage) doesn't take a dependency on RCTUIKit's pod React-Core. The #import <React/RCTUIKit.h> most likely worked out of happenstance. I went with copying …
=> Remove diff in RCTImageLoader

React/Base/RCTTouchHandler.m
This is a back port of the recent change to master: [1619](https://github.com/microsoft/react-native-macos/pull/1619) Fix coordinates of touch.pageX/pageY coordinates when RCTRootView is not at the origin of the NSWindow.
The change touches the same code where a similar fix for touch.locationX/locationY: [1288](https://github.com/microsoft/react-native-macos/pull/1288) Fix event.locationX/Y to be in view's coordinate space
Both changes are back ported in this change.
f the `RCTRootView` is not positioned at the origin of the `NSWindow`, then `touch.pageX/pageY` events will not have the correct coordinates. This can make it difficult for a user to click on Touchable and Pressable components unless there are no mouse moves between the mouse down and the mouse up events. The touch down and …
=> Back port 1619 and 1288 to 0.68: Fix coordinates of touch.pageX/pageY coordinates when RCTRootView is not at the origin of the NSWindow

Libraries/Pressability/Pressability.js, React/Views/RCTView.m
Cherry pick 400430adc968bc51108956a60cbf7c07ad03f29e to 0.68-stable.
=> [0.68] Return and Space keys do not trigger onPress events 

ReactCommon/react/renderer/scheduler/Scheduler.cpp
Due to an early cherry-pick from a more recent facebook/react-native version > https://github.com/microsoft/react-native-macos/pull/1498 this broke.
In https://github.com/microsoft/react-native-macos/pull/1498 I must have only build for rn-iOS + Paper. I think we need a CircleCI job now for rn-iOS + Fabric
Here is the fix.
- std::optional's function signature is has_value()
- where as folly::Optional used hasValue()
[macOS] [Fixed] - Fix compilation error in Schedule.cpp when building for rn-iOS + Fabric
In packages/rn-tester I ran:
```
USE_FABRIC=1 pod install
```
And then build and launched the app
=> Fix compilation error in Schedule.cpp when building for rn-iOS + Fabric

React/Base/RCTMultipartDataTask.m
This was already removed from facebook/react-native early 2019: https://github.com/facebook/react-native/commit/06c6c7c673682629073dbcb3811b6a6806253a74#diff-02c60e5ee54665cfda52b1e88843db83a725867cd8404959fd328adaa6391c7b
It is not linked anywhere in the code at this time
[macOS] [Removed] - Remove OS check in RCTMultiPartDataTask.m
Compiled and ran rn-tester locally
=> Remove OS check in RCTMultiPartDataTask.m #1600

packages/rn-tester/NativeComponentExample/MyNativeView.podspec, packages/rn-tester/NativeComponentExample/js/MyNativeView.js, packages/rn-tester/Podfile, packages/rn-tester/js/utils/RNTesterList.ios.js
While we are implementing Fabric for macOS, we need to ensure that we aren't breaking the Fabric for iOS.
We can ensure the `NativeComponentExample` will build for Fabric & be accessible on iOS.
Once Fabric on macOS is working, this Native Example will not throw an error.
To enable the Native Component, run this during installation
`USE_CODEGEN_DISCOVERY=1 USE_FABRIC=1 bundle exec pod install --verbose`
[macOS] [Added] - Enable NewArchitectureExample Fabric example in RNTester iOS 
https://user-images.githubusercontent.com/96719/203673083-3852d55f-a1f5-42d2-baa5-77b4e54b25cf.mp4
https://user-images.githubusercontent.com/96719/203673121-09198b4c-9f28-4b2f-9098-ea67d85c58c5.mp4
=> [Fabric] Enable NewArchitectureExample Fabric example in RNTester iOS

packages/rn-tester/RNTester-macOS/ViewController.mm, packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj
This simply makes the ViewController an ObjC++ file so that we can more easily add a Fabric example as shown in: https://github.com/christophpurrer/react-native-macos/commit/1316ae18ffd628deac062b31c54a9730097fdea6
Changelog:
[macOS][Added] Rename rn-tester-macOS ViewController.m to .mm
Ran RNTester on macOS
=> Rename rn-tester-macOS ViewController.m to .mm

.ado/apple-pr.yml, .ado/templates/apple-job-react-native.yml, .circleci/config.yml, React/Fabric/RCTSurfacePresenter.mm, ReactAndroid/src/main/java/com/facebook/react/fabric/jni/Binding.cpp, ReactCommon/react/renderer/runtimescheduler/RuntimeScheduler.cpp, ReactCommon/react/renderer/runtimescheduler/RuntimeScheduler.h, ReactCommon/react/renderer/runtimescheduler/tests/RuntimeSchedulerTest.cpp, packages/rn-tester/Podfile, packages/rn-tester/RNTester/NativeExampleViews/FlexibleSizeExampleView.m, packages/rn-tester/RNTester/NativeExampleViews/UpdatePropertiesExampleView.m
- Add a new job to build Fabric iOS on Azure Pipelines. While here, let's also rename the jobs to better reflect what they do
- Make some Fabric code fixes to get the new Fabric iOS job passing
- Disable the CircleCI tests that are failing while we are mid 0.71-merge
End result: Green CI checks 🎉
[Type] [Added] - Build Fabric iOS on Azure Pipelines
CI passes
=> [CI] Build & Test Fabric iOS, Disable failing CircleCI checks

packages/rn-tester/RNTester-macOS/ViewController.mm
This aligns with the current iOS example:
https://github.com/microsoft/react-native-macos/blob/main/packages/rn-tester/RNTester/AppDelegate.mm#L45
[macOS] [Added] - Add Fabric example to rn-tester-macOS
This code compiles and runs with other Fabric related changes which are still in flight or need to be pushed against this repo.
Here is my demo branch:
https://github.com/christophpurrer/react-native-macos/commits/road2fabric
=> Add Fabric example to rn-tester-macOS

Libraries/Components/ScrollView/ScrollView.js, Libraries/Components/ScrollView/ScrollViewViewConfig.js, React/Views/ScrollView/RCTScrollView.h, React/Views/ScrollView/RCTScrollView.m, React/Views/ScrollView/RCTScrollViewManager.m, packages/rn-tester/js/examples/ScrollView/ScrollViewExample.js
NSScrollView can have overlay style explicitly set.
https://developer.apple.com/documentation/appkit/nsscrollerstyle/nsscrollerstyleoverlay
Overlay style will **not** take up any space in the ContentView so content can be flush with insets.
Default uses the legacy style, not the overlay.
[macOS] [ADDED] - Add ScrollView Indicator Overlay style 
Overlay style can be enable/disabled 
https://user-images.githubusercontent.com/96719/213046667-0b09b0f9-a0ad-4758-9ad8-7dfefa729d71.mp4
=> Add ScrollView Indicator Overlay style

packages/rn-tester/NativeComponentExample/js/MyNativeView.js
The `NativeComponentExample` is currently not rendering when building for fabric on iOS.
`ref._internalInstanceHandle?.stateNode?.canonical` is undefined.
https://github.com/microsoft/react-native-macos/blob/main/packages/rn-tester/NativeComponentExample/js/MyNativeView.js#L38
Upstreamed the latest `MyNativeView.js` from https://github.com/facebook/react-native/blob/main/packages/rn-tester/NativeComponentExample/js/MyNativeView.js
[macOS][Fabric] - Fix NativeComponentExample to render correctly
**Before**
https://user-images.githubusercontent.com/96719/213311648-2b5641cd-7754-4048-8808-2ee6f5f061e9.mp4
**After**
https://user-images.githubusercontent.com/96719/213311320-097131ab-1978-4376-951f-76fc20c70460.mp4
=> [Fabric] Fix NativeComponentExample not rendering on Fabric

package.json, yarn.lock
Resolve `debug` to at least 3.1.0 to mitigate [this ReDoS vulnerability](https://security.snyk.io/vuln/npm:debug:20170905).
I wish there was a way to only apply this to particular versions (since some places use 2.6.9 proper). I got slightly excited when I saw [this section of the Selective Versions Resolutions RFC](https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md#mapping-version-specifications), but then got disappointed at the fact that this was merely mentioned as a possible extension. But considering that [`debug`](https://www.npmjs.com/package/debug) is a relatively small debugging module, I don't think the impact of forcing an upgrade everywhere will be that damaging.
=> Resolve debug to at least 3.1.0

Gemfile.lock, template/Gemfile.lock
0.68-stable counterparts of #1665 and #1666.
=> [0.68-stable] Update activesupport to 6.1.7.1

React/Fabric/Mounting/ComponentViews/Modal/RCTFabricModalHostViewController.h, React/Fabric/Mounting/ComponentViews/Modal/RCTFabricModalHostViewController.mm, React/Fabric/Mounting/ComponentViews/Text/RCTParagraphComponentView.mm
Shim RCTFabricModalHostViewControllerDelegate to work w/ Fabric
closes #1558 
[macOS][Added] - Shim RCTFabricModalHostViewControllerDelegate for Fabric
[x] Build RNTester-macOS w/ Fabric - doesn’t run yet, but no RCTFabricModalHostViewControllerDelegate errors
[x] Build RNTester - iOS w/ Paper -
=> [Fabric] Shim RCTFabricModalHostViewControllerDelegate

React/Base/RCTUIKit.h, React/Fabric/RCTSurfaceTouchHandler.mm
Shim RCTSurfaceTouchHandler to work w/ Fabric
closes #1542 
[macOS][Added] - Shim RCTSurfaceTouchHandler for Fabric
[x] Build RNTester-macOS w/ Fabric - doesn’t run yet, but no RCTSurfaceTouchHandler errors
[x] Build RNTester - iOS w /Paper -
=> [Fabric] Shim RCTSurfaceTouchHandler

React/Fabric/Mounting/RCTComponentViewDescriptor.h, React/Fabric/Mounting/RCTComponentViewRegistry.mm
Shim RCTComponentViewDescriptor to work w/ Fabric
closes #1543 
[macOS][Added] - Shim RCTComponentViewDescriptor for Fabric
[x] Build RNTester-macOS w/ Fabric - doesn’t run yet, but no RCTComponentViewDescriptor errors
[x] Build RNTester-macOS w/ Paper
[x] Build RNTester - iOS w/ Paper
=> [Fabric] Shim RCTComponentViewDescriptor

React/Fabric/Mounting/ComponentViews/InputAccessory/RCTInputAccessoryComponentView.mm, React/Fabric/Mounting/ComponentViews/LegacyViewManagerInterop/RCTLegacyViewManagerInteropComponentView.mm, React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm, React/Fabric/Mounting/RCTComponentViewRegistry.mm, React/Fabric/Mounting/UIView+ComponentViewProtocol.mm
Fix misc rendering & build issues
closes #1573 #1570 #1571 #1566 #1565 
[macOS][Added] - Fix misc rendering & build issues
[x] Build RNTester-macOS w/ Fabric - doesn’t run yet, but no RCTLegacyViewManagerInteropComponentView errors
[x] Build RNTester - iOS w/ Paper -
=> [Fabric] Fix misc rendering & build issues

Libraries/Text/TextInput/Singleline/RCTUITextField.m
Takes care of [#1395](https://github.com/microsoft/react-native-macos/issues/1395)
[General] [Fixed] - Fixes caret changing sizes if text field is empty
Set a larger font size on a single line text field and watch the caret change sizes when the field is empty
=> GH#1395 Fixes caret changing sizes if text field is empty

React/Fabric/Mounting/ComponentViews/Switch/RCTSwitchComponentView.mm
Shim RCTSwitchComponentView to work w/ Fabric
closes #1559 
[macOS][Added] - Shim RCTSwitchComponentView for Fabric
[x] Build RNTester-macOS w/ Fabric - doesn’t run yet, but no RCTSwitchComponentView errors
[x] Build RNTester - iOS w/ Paper -
=> [Fabric] Shim RCTSwitchComponentView

React/Base/RCTUtils.m, React/Fabric/Mounting/ComponentViews/Image/RCTImageComponentView.mm, React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
Shim RCTImage to work w/ Fabric
closes #1564 
[macOS][Added] - Shim RCTImage
[x] Build RNTester-macOS w/ Fabric - doesn’t run yet, but no RCTImage errors
[x] Build RNTester - iOS w/ Paper - should work
=> [Fabric] Shim RCTImage

React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm, React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputUtils.h, React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputUtils.mm
Shim RCTTextInput to work w/ Fabric
closes #1547 
[macOS][Added] - Shim RCTTextInput for Fabric
[x] Build RNTester-macOS w/ Fabric - doesn’t run yet, but no RCTTextInput errors
[x] Build RNTester - iOS w/ Paper -
=> [Fabric] Shim RCTTextInput

React/Base/RCTUIKit.h, React/Base/macOS/RCTUIKit.m, React/Fabric/Mounting/ComponentViews/Slider/RCTSliderComponentView.mm, React/Fabric/Mounting/ComponentViews/UnimplementedComponent/RCTUnimplementedNativeComponentView.mm, React/Fabric/Mounting/ComponentViews/UnimplementedView/RCTUnimplementedViewComponentView.mm, React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, React/Fabric/RCTSurfacePresenter.mm
Remaining fixes/shims for Fabric successfully building on macOS target
Closes #1567 
[macOS][Added] - Remaining fixes for Fabric building on macOS target
Interactions are broken so any input will result in a crash.
Follow on PR will address these issues.
**NOTE: To test, this should to be merged after the remaining Fabric PR's**
[x] Build RNTester-macOS w/ Fabric - Builds! 🚀
[x] Build RNTester-macOS w/ Paper
[x] Build RNTester - iOS w/ Paper
=> [Fabric] Remaining fixes for Fabric building on macOS target

React/Base/RCTUIKit.h, React/Base/macOS/RCTUIKit.m, React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, React/Fabric/Mounting/RCTComponentViewDescriptor.h, React/Fabric/Mounting/RCTComponentViewProtocol.h, React/Fabric/Mounting/RCTComponentViewRegistry.mm, React/Fabric/Mounting/UIView+ComponentViewProtocol.h, React/Fabric/Mounting/UIView+ComponentViewProtocol.mm, React/Fabric/RCTSurfaceTouchHandler.mm, ReactCommon/react/renderer/components/view/Touch.cpp, ReactCommon/react/renderer/components/view/Touch.h, ReactCommon/react/renderer/components/view/TouchEventEmitter.cpp
Update the RCTSurfaceTouchHandler to support mouse events on macOS Fabric and convert them to touch events.
[macOS] [Added] - Touch events for Fabric
[x] Build RNTester-macOS w/ Fabric
[x] Click around RNTester-macOS w/ Fabric
https://user-images.githubusercontent.com/151054/214643298-c550a516-2710-40a1-8025-d4f5f9431bdb.mov
[x] Build RNTester-macOS w/ Paper
[x] Build RNTester - iOS w/ Paper
=> [Fabric] RCTSurfaceTouchHandler for macOS

.github/ISSUE_TEMPLATE/config.yml
We use Github's issue tracker for our Github projects related to Fabric. However, it's not easy for outside collaborators to create issues right now as they need to use one of our pre-filled templates. This change would allow outside collaborators to make blank issues, which will help me sort them into our Fabric Github project.
=> Allow blank issues via Github Issue template

React/Views/RCTView.m
NSAccessibilityRadioButtonRole has a separate enum for accessibility state, let's add it so that VoiceOver announces accessibility states for radio button and checkbox.
[macOS] [FIXED] - Update accessibilityValue
Tested the accessibility scenario in an external app
=> Update accessibilityValue to include radio button state attribute

Libraries/Text/Text/RCTTextView.m, Libraries/Text/TextInput/RCTBaseTextInputView.m, Libraries/Text/TextInput/Singleline/RCTUITextField.m, React/Fabric/Mounting/ComponentViews/SafeAreaView/RCTSafeAreaViewComponentView.mm, React/Fabric/Mounting/ComponentViews/ScrollView/RCTEnhancedScrollView.h, React/Fabric/Mounting/ComponentViews/ScrollView/RCTPullToRefreshViewComponentView.mm, React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.h, React/Fabric/Mounting/ComponentViews/Slider/RCTSliderComponentView.mm, React/Fabric/Mounting/ComponentViews/Text/RCTAccessibilityElement.h, React/Fabric/Mounting/ComponentViews/Text/RCTAccessibilityElement.mm, React/Fabric/Mounting/ComponentViews/Text/RCTParagraphComponentAccessibilityProvider.h, React/Fabric/Mounting/ComponentViews/Text/RCTParagraphComponentAccessibilityProvider.mm, React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, React/Fabric/RCTConversions.h, React/Fabric/Surface/RCTFabricSurface.mm, ReactCommon/react/renderer/textlayoutmanager/platform/ios/RCTTextLayoutManager.mm
[Fabric] Convert remaining legacy macOS tags
[macOS] [Fixed] - Convert remaining legacy macOS tags
[x] macOS - Fabric
[x] macOS - Paper
[x] iOS - Fabric
[x] iOS - Paper
=> [Fabric] Convert remaining legacy macOS tags

scripts/set-rn-version.js
Resolved #1630. Edits our nightly versions to include a better timestamp so that cocoa pods is less confused
[Internal] [Fixed ] - react-native-macos@canary randomly fails installing
=> Include timestamp in nightly versions

Libraries/WebSocket/RCTSRWebSocket.m, packages/rn-tester/Podfile.lock, yarn.lock
This brings a solution discussed in [this issue](https://github.com/facebook/react-native/issues/29408) into react-native-macos.
Verified via a downstream client.
=> Respect system proxy settings for WebSocket

packages/babel-plugin-codegen/__tests__/__snapshots__/index-test.js.snap, yarn.lock
This is a run of `yarn upgrade` to ensure that `@sideway/formula` is at 3.0.1 or higher to resolve [this vulnerability](https://security.snyk.io/vuln/SNYK-JS-SIDEWAYFORMULA-3317169).
Validated that the vulnerability is no longer an issue via `yarn audit`.
=> Update yarn.lock to resolve @sideway/formula vulnerability

packages/babel-plugin-codegen/__tests__/__snapshots__/index-test.js.snap, yarn.lock
0.68-stable counterpart of #1729. Resolves [this vulnerability](https://security.snyk.io/vuln/SNYK-JS-SIDEWAYFORMULA-3317169).
`yarn audit` vulnerability count drops from 16 to 3.
=> [0.68-stable] `yarn upgrade`

.circleci/config.yml, packages/react-native-macos-init/package.json, packages/react-native-macos-init/src/cli.ts, repo-config/package.json, yarn.lock
The NPM package `request` is deprecated, and shows up in our component governance alerts. Let's remove references to it.
It is a transitive dependency of two packages:
- `coveralls` used by a CircleCI test for code coverage
- I'll just remove the dependency, and comment out the test. I'll also look into an upstream fix to React Native Core. 
- `npm-registry` used by `react-native-macos-init`
- Turns out the windows team already removed this dependency for their `react-native-windows-init`... so I just copied their solution: https://github.com/microsoft/react-native-windows/pull/8139
[Security] [Fixed] - Remove dependency on NPM package `request`
=> Remove dependency on NPM package `request`

.ado/publish.yml
Our pipeline to publish new versions of react-native-macos 0.68.x is broken. The fix is to remove this deprecated group from publish.yml.
If the CIs pass, we should be good.
=> Remove group: InfoSec-SecurityResults from publish.yml

Libraries/Core/ReactNativeVersion.js, React/Base/RCTVersion.m, ReactAndroid/gradle.properties, ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, ReactCommon/cxxreact/ReactNativeVersion.h, package.json, packages/rn-tester/Podfile.lock, template/package.json
Manual bump to 0.68.67 to unblock publishing pipelines.
Script run: `node scripts/set-rn-version.js -v 0.68.67 -n -S`
=> Manual bump to 0.68.67

.ado/get-next-semver-version.js, .ado/gitTagRelease.js, .ado/publish.yml, .ado/templates/apple-job-publish.yml, .ado/templates/configure-git.yml, .ado/variables/vars.yml, .ado/versionUtils.js, scripts/prepare-package-for-release.js, scripts/publish-npm.js
We still had NPM publish problems... and after lots of testing, I believe I have found the fix.
The previous refactors attempted to use the nodejs scripts from React Native Core to perform tasks like `git tag`, `git push`, and `npm publish`. However, for whatever reason when those scripts are run in Azure Pipelines, they don't have access our secrets (AKA: `githubAuthToken`, and `npmAuthToken`), and those steps would always fail. This is partially because (as I learned), you must explicitly pass secrets down to each individual step as an environment variable, even if they're already set elsewhere (soemthing about scoping of variables to individual tasks..).
So now, we do the following:
- run `prepare-package-for-release.js` as a dry-run so it skips the `git tag / git push` phase
- Comment …
=> Refactor publish pipeline (Take 4) 

.ado/get-next-semver-version.js, .ado/gitTagRelease.js, .ado/publish.yml, .ado/templates/apple-job-publish.yml, .ado/templates/configure-git.yml, .ado/variables/vars.yml, .ado/versionUtils.js, scripts/prepare-package-for-release.js, scripts/publish-npm.js, scripts/release-utils.js
Same as #1777 but to 0.71-stable
=> [0.71] Refactor Publish Pipeline (Take 4)

.ado/apple-pr.yml, .ado/templates/apple-job-react-native.yml, packages/rn-tester/NativeCxxModuleExample/NativeCxxModuleExample.podspec, packages/rn-tester/Podfile
RCT_NEW_ARCH_ENABLED flag is what RN core uses for enabling the new architecture
[GENERAL] [FIXED] - Use build flag from RN mobile for enabling new architecture
**Fabric builds**
`RCT_NEW_ARCH_ENABLED=1 bundle exec pod install --verbose`
=> [Fabric] Use RCT_NEW_ARCH_ENABLED flag for enabling new arch

.ado/publish.yml
Our CI would generate the SBOM, and then commit all files and push back to Github as part of a version update. That meant the SBOM manifest was also picked up. Let's move the "Generate and Publish SBOM" steps to _after_ the "Push back to Github" steps so they aren't picked up. Let's also remove the manifest files.
[INTERNAL] [CHANGED] - Don't publish the SBOM back to Github
I'll keep an eye on the next publish.
=> Don't publish the SBOM back to Github

React/Views/ScrollView/RCTScrollView.m
A client downstream reported a bug in Flatlist where the clip view does not get scrolled to the offset that's being passed in when in RTL mode. Turns out this issue only repros when animation is enabled, #725 which was added a while back. Since scrollToPoint is not animatable, let's call it alongside setBoundsOrigin so that the animation is still present.
Verified downstream
=> [0.68] Handle edge case for setContentOffset with animation

Libraries/Components/TextInput/RCTTextInputViewConfig.js, Libraries/Components/TextInput/TextInput.js, Libraries/Text/TextInput/Multiline/RCTUITextView.h, Libraries/Text/TextInput/Multiline/RCTUITextView.m, Libraries/Text/TextInput/RCTBaseTextInputView.h, Libraries/Text/TextInput/RCTBaseTextInputViewManager.m, Libraries/Text/TextInput/Singleline/RCTUITextField.m, packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js
In the current implementation of TextInput, there is no reliable way to specify cursorColor (caret color). This limitation blocks us from launching one of the features as in our case we have part of the screen in the opposite theme (white/black).
This prop is already supported in Android and documented in the main doc https://reactnative.dev/docs/textinput#cursorcolor-android This pull request adds support to macOS as well. 
To demonstrate, here cursor is actually rendered, but you cannot see it as it is black on black.
https://user-images.githubusercontent.com/963490/231438442-1ab5fb56-7a6e-4f56-bb4e-5af03c1b40a3.mov
TextInput implementation seems to be different between MacOS and iOS, so creating a pull request here.
[MACOS] [ADDED] - Added support for cursorColor prop in TextInput
Run …
=> Add cursorColor support to TextInput

Libraries/Text/TextInput/Multiline/RCTUITextView.m, packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js
The caret color on macOS should stay visible at all times. This changes the behavior of the singleline and multiline TextInput to avoid changing the caret color.
[macOS] [CHANGED] - TextInput selectionColor won't change cursorColor
In the following recordings, the caret color is set to the system default for a TextInput with a non-default selection color.
Light mode:
https://user-images.githubusercontent.com/151054/231832629-eb4b52b7-3568-4f7a-8484-c79743d930e5.mov
Dark mode:
https://user-images.githubusercontent.com/151054/231832648-ab9c3a7a-baf2-4d33-a5ed-cef958d084c8.mov
=> Remove TextInput cursor color changes with selectionColor prop changes

.ado/publish.yml, .ado/variables/vars.yml
This PR fixes two changes:
1) The `react-native-macos-init` publish job was missing a step to set up some tools, like node and ruby. This caused the pipeline to fail. This should be a relatively simple fix. 
2) Backports to `0.68-stable` were getting tagged as "latest" on NPM. This is because our Publish pipeline has a variable `latestStableBranch` defined in its build settings, set to `0.68-stable`. I thought I could override that locally in `vars.yml`, but that change didn't carry down to the `068-stable` branch. Therefore, when a new change was published to `0.68-stable`, it still thought that was the latest released and tagged it on NPM as such. To fix this, we can remove the variable from our yml, add back the note it's expected to be defined in the pipelines' build settings, and …
=> Fix back ports getting tagged as `latest` on NPM + react-native-macos-init publish

docs/Releases.md
Update the Releases.md doc with actual info
[GENERAL] [ADDED] - Update the Releases.md doc with actual info
N/A
=> Document releases flow

Libraries/Image/RCTImageView.mm
During the 71 merge, I accidentally removed a macOS ifdef block that implemented tintColor for macOS. Thanks @ospfranco for catching! Let's add it back by copying it from the `0.68-stable` branch :)
[MACOS] [FIXED] - Add back macOS tintColor implementation
TintColor went from not working to working:
=> Add back macOS tintColor implementation

Libraries/Image/RCTImageView.mm
Backport of #1801 to 0.71-stable
=> [0.71] Add back macOS tintColor implementation

.ado/publish.yml
As it turns out, this job runs on Ubuntu. So we shouldn't do anything related to home-brew. We also shouldn't need to, since it's a JS package. Revert the setup steps to what they were like in [0.68-stable](https://github.com/microsoft/react-native-macos/blob/4696d347c9cf9110a7ded81a9db7b1b3f35b3b52/.ado/publish.yml#L152-L159)
[INTERNAL] [FIXED] - Remove apple specific steps from `react-native-macos-init` publish
I'll run the web validator again.
=> Remove apple specific steps from `react-native-macos-init` publish

packages/rn-tester/js/examples/ASAN/ASANCrashExample.js
This patches the ASAN RNTester example (which is RNTester specific) to import from 'react' instead of 'React'. There are two other RNTester modules that import from 'React' (ActivityIndicatorExample and CrashExample) that will get fixed once react-native-macos syncs past facebook/react-native#37185.
[GENERAL] [FIXED] - Fixes import for ASANCrashExample in RNTester
GitHub CI passes
=> Resolve from `react` instead of `React`

React/Views/ScrollView/RCTScrollView.m
Cherry-pick of e5d4368421cec4219ee2ba1c7f32ee30ae99fd35
=> Handle edge case for setContentOffset with animation

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m, Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m
- The delegate method for submitting text input changes to JS changed in https://github.com/facebook/react-native/pull/33653 
- The new api is `textInputShouldSubmitOnReturn`
https://github.com/facebook/react-native/blob/43bd29fb22b2b9993f68dc545bd1f84612e879ba/packages/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegate.h#L28
- I also noticed that `onChange` was not being called correctly for MutliLine TextInput.
- The reason was this change: https://github.com/microsoft/react-native-macos/commit/277129c7e270026e58923e63cd44535c25e1e8dd
- We overrode `textInputDidChange` but forgot to call `[super textInputDidChange]`
closes #1788 
[MACOS] [FIXED] - Fix TextInput to submit value to onChange & onSubmitEditing
https://user-images.githubusercontent.com/96719/236112608-f262c3a9-4 …
=> Fix text input not correctly submitting events

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m, Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m
Picking #1811 to 0.71.1
[MACOS][FIX] Pick to 0.71 - Fix TextInput to submit value to onChange & onSubmitEditing (#1811)
See testplan in #1811
=> [0.71] Fix TextInput to submit value to onChange & onSubmitEdit

React/Fabric/RCTSurfaceTouchHandler.mm
There are 11 active touch identifiers available in the surface touch handler. We were not returning identifiers when completing a touch on mouse up which led to the app hanging looking for a free touch identifier when all 11 slots were used up.
[macOS] [FIXED] - App hanging after multiple clicks in fabric
Tested by running RNTester on macOS with fabric (`RCT_NEW_ARCH_ENABLED=1`) and clicking around the app to check that the app doesn't hang anymore after a couple of click.
Without the fix RNTester becomes unresponsive (the beachball at the end is not captured by the screen recording):
https://user-images.githubusercontent.com/151054/236255098-50c78ecc-5333-4d91-b2c4-ba7fd7ea6e3d.mov
With the fix RNTester keeps working no matter how many times you click around: …
=> [Fabric] Return active touch identifiers in surface touch handler on mouse up.

ReactCommon/react/renderer/graphics/platform/ios/RCTPlatformColorUtils.mm
Extracting color components from a color in fabric was throwing an exception because some colors need to manually be converted to a color space supporting the RGBA components. This adds the necessary color space conversion for macOS.
[macOS] [FIXED] - Color RGBA component extraction throwing exception in fabric
Tested by running RNTester on macOS with fabric (`RCT_NEW_ARCH_ENABLED=1`) and launching the API Border example.
Without the fix the app crashes with the following exception:
```
libc++abi: terminating due to uncaught exception of type NSException
terminating due to uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -getRed:green:blue:alpha: not valid for the NSColor Catalog color: System separatorColor; …
```
=> [Fabric] Add mandatory color space conversion for macOS.

React/Base/RCTUIKit.h, React/Base/macOS/RCTUIKit.m, React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, React/Views/UIView+React.m
The RCTUIView extends RCTPlatformView now which allows to remove the macOS specific hit testing logic that was added for the implementation of the RCTSurfaceTouchHandler in fabric.
The only macOS specific part that is still required is the implementation of a 
```- (RCTPlatformView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event```
method to support the iOS-style hit test calls coming from the betterHitTest implementation.
[macOS] [REMOVED] - Removed custom hit test implementation used for macOS fabric
Tested by running RNTester on macOS with fabric (`RCT_NEW_ARCH_ENABLED=1`) and clicking around the app to check that hit testing works as expected.
https://user-images.githubusercontent.com/151054/236241920-36bdae96-6212-42eb-b0c6-7e918fac6bcd.mov
=> [Fabric] Clean up hit testing now that RCTUIView extends RCTPlatformView

React/Fabric/Mounting/ComponentViews/SafeAreaView/RCTSafeAreaViewComponentView.mm, React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
Fabric does not provide guarantees for the order of creation of host views, which means a view could be created before being added to a window. This causes issues when reading the `backingScaleFactor` within a view because it returns a nil window and the returned value is 0.
This caused border rendering issues in the `<View />` component since the border was generated before the view hierarchy was added to a window.
The layout metrics of the shadow node provides the current scale factor through the `pointScaleFactor` property. This is set when initializing the layout context, which guarantees that the value will be available when a view is being created and inserted.
[macOS] [FIXED] - Use the layout metrics scale factor in view components to fix scale dependent rendering
Tested by running …
=> [Fabric] Use the layout metrics to get the scale factor in component views.

packages/rn-tester/RNTester/AppDelegate.mm
This fix sets the auto-resizing masks on the `SurfaceHostingProxyRootView` of the RNTester app so that when using fabric, resizing the window would also resize the `SurfaceHostingProxyRootView` to fit the new frame size of the window.
[macOS] [FIXED] - Fix RNTester window content not resizing
Tested by running RNTester on macOS with fabric (RCT_NEW_ARCH_ENABLED=1) and paper and resizing the window.
Without the fix in Fabric:
With the fix in Fabric:
With the fix in Paper:
=> [Fabric] Fix RNTester content not resizing with window.

ReactCommon/react/renderer/textlayoutmanager/platform/ios/RCTAttributedTextUtils.mm
This change adds back a working maximum font line height calculation method for macOS on fabric by using the common `UIFontLineHeight` method that works for UIKit and AppKit. This is required for the correct calculation of the baseline offset for text having a line height greater than the text's font height.
[macOS] [FIXED] - Fixed the vertical text position in Fabric when setting a line height
Tested by running RNTester on macOS with paper and fabric (RCT_NEW_ARCH_ENABLED=1) and launching the TextInput example. As a regression test for iOS, the RNTester app was tested on iOS with fabric.
Without the fix on Fabric (text is too high and clipped by the view):
With the fix on Fabric:
With the fix on Paper:
With the fix on Fabric iOS:
=> [Fabric] Fix wrong text offset when a line height is set.

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m
- #1438 had overrides for MultilineTextView methods w/o calling `[super ...]`
- This broke Multiline text inputs when text was being set from JS via `onChange`
- TextInputDidChange was fixed in #1811 
[MACOS] [FIXED] - Fix Multiline Text Input cursor position being reset to end of line
https://github.com/microsoft/react-native-macos/assets/96719/6ff2c2cb-ae2c-4fe8-8260-84cde759cc5e
https://github.com/microsoft/react-native-macos/assets/96719/6175f35b-4fb2-41d9-ba74-9a3e72faf6d3
=> Fix Multiline Text Input cursor position being reset to end of line

React/CoreModules/RCTActionSheetManager.mm
Resolves #1680 
On macOS, we implement ActionSheetIOS to be an NSMenu (not confusing at all). During the 0.71 merge, `RCTActionSheetManager.mm` was refactored a bit, and the macOS implementation wasn't properly updated. Thus, callbacks wouldn't get fired when you clicked on menu items.
While the fix is simple (initialize `_callbacks` on init), I decided to go ahead and refactor the diffs so that the iOS and macOS blocks are much closer to each other and share more code. I also added a few comments explaining some macOS differences we needed. This should help ensure that future merges are less likely to break this module.
Things to note:
- This PR also fixes the ability to disable menu items, which previously didn't work. Yay code sharing :D.
- NSMenu doesn't have a "cancel" menu item like …
=> Fix callbacks not being fired on macOS ActionSheetIOS

README.md
Some of the links in the Contents section of the Readme.md are broken. This PR fix those links.
[General] [Fixed] - Fix contents links in Readme.md
Just click on the links
=> Fix contents links in Readme.md

Libraries/Image/RCTUIImageViewAnimated.h, React/Base/RCTUIKit.h, React/Base/macOS/RCTUIKit.m, React/Fabric/Mounting/ComponentViews/Image/RCTImageComponentView.mm
This PR adds the `RCTUIImageView` class to RCTUIKit offering the same API as the UIImageView on iOS for setting the content mode and the tint color. The implementation uses CALayer and NSImage for scale settings which matches the iOS scaling methods.
Using this image view implementation on fabric removes most of the macOS specific code changes that the `RCTImageComponentView` required previously.
[macOS] [FIXED] - Image content mode and tinting in Fabric
Tested by running RNTester on macOS with fabric (`RCT_NEW_ARCH_ENABLED=1`) and launching the Image example.
With the fix:
Without the fix:
=> [Fabric] Add support for image content mode and tint features

Libraries/Text/TextInput/Multiline/RCTUITextView.m
We have a component using RCTUITextView, and the placeholder text looks too big on macOS. The placeholder text font size was hardcoded to 17px (which according to [this](https://developer.apple.com/design/human-interface-guidelines/typography#Specifications) is the iOS default font size for body text), but for macOS it should be the system font size, i.e. 13px. 
[macOS] [FIXED] - Update RCTUITextView to use the systemFontSize
| - | macOS | iOS (no change) |
| - | - | - |
| Before | <img width="600" alt="macOS before" src="https://github.com/microsoft/react-native-macos/assets/78454019/24ff5741-5063-45e7-8c61-3e234274af59"> | <img width="300" alt="iOS before" src="https://github.com/microsoft/react-native-macos/assets/78454019/71db9ed6-e81f-4f66-a458-f43278b35c43"> |
| After | <img …
=> Update RCTUITextView to use the systemFontSize for macOS

Libraries/Image/RCTImageView.mm
In some rare cases a react native app on macOS would crash with the following message:
```
-[RCTImageView windowDidChangeBackingProperties:]: unrecognized selector sent to instance 0x10b0c2c00
```
The notification center is supposed to check if the object subscribed to the notification still exists before calling the registered selector for the notification. This is supposed to relieve us from having to remove the observer when deallocating the observing object.
In these rare crashes I assume another NSObject got allocated at the same address as what was previously an observing RCTImageView and the notification center may have considered the observer still active and sent the registered selector to it.
To fix the potential bug and also remove a couple differences with React Native this PR …
=> Use viewDidChangeBackingProperties to remove the use of notifications in RCTImageView

React/Views/ScrollView/RCTScrollView.m, packages/rn-tester/js/examples/ScrollView/ScrollViewExample.js
* Text centering with `centerContent` prop only worked after content was first scrolled.
https://reactnative.dev/docs/scrollview#centercontent-ios
* With this change, the content is centered vertically/horizontally when rendered
[MACOS] [FIXED] - Scrollview - fix text centered on render when centerContent is true
https://github.com/microsoft/react-native-macos/assets/96719/2a6c0827-43c5-4340-9f8c-faa7d25526c3
https://github.com/microsoft/react-native-macos/assets/96719/5ea27364-b16f-437a-a325-d8f24269b919
https://github.com/microsoft/react-native-macos/assets/96719/420cc7cd-b945-4b94-9b1b-b97f2fb14f33
=> Scrollview - fix text centered on render when centerContent is true

Libraries/Text/TextInput/Multiline/RCTUITextView.h, Libraries/Text/TextInput/Multiline/RCTUITextView.m, Libraries/Text/TextInput/RCTBackedTextInputViewProtocol.h, Libraries/Text/TextInput/Singleline/RCTUITextField.h, Libraries/Text/TextInput/Singleline/RCTUITextField.m, React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm
The `<TextInput />` component in fabric was querying the pixel scale factor through the window. But since fabric does not guarantee that host views are added to a window when being created and/or inserted, the TextInput views don't have a window and the return scale was 0.0 which caused crashes while loading RNTester.
This changes the behavior for fabric by adding a `pixelScaleFactor` to the `RCTBackedTextInputViewProtocal` so that the component view can provide the layout metrics pixel scale factor to the backing text input view.
The behavior on Paper stays unchanged since the `pixelScaleFactor` won't be set and the scale defaults back to using the window query (`self.window.backingScaleFactor`).
[macOS] [FIXED] - Fix text input rendering crashing on fabric
Tested by running RNTester on …
=> [Fabric] Fix text input rendering crashing by using layout metrics pixelScaleFactor

Libraries/StyleSheet/PlatformColorValueTypes.macos.js
When the colorWithSystemEffect object gets normalized, we should be calling @react-native/normalize-colors not processColor. This is a regression from 68 because in 68 we return the unprocessed color, not the noralized color object https://github.com/microsoft/react-native-macos/blob/0.68-stable/Libraries/StyleSheet/normalizeColor.js#L25
Before:
After:
=> Fix ColorWithSystemEffect not returning the correct base color

React/Modules/MacOS/RCTAccessibilityManager.m
Specifically, NSAccessibilityPostNotificationWithUserInfo. Other methods such as `getCurrentHighContrastState` provide cached state (cached on main thread via `observeValueForKeyPath` et al). Some other methods such as `setAccessibilityFocus` dispatch to the main thread.
Not doing so could lead to AppKit further firing selectors on UI logic in app code and lead to downstream issues.
I've verified that original badness I observed in Office that led to discovering this no longer reproduces. Announcement posts in Accessibility Inspector.
=> -[RCTAccessibilityManager announceForAccessibility:] calls into AppKit from background thread

React/Modules/MacOS/RCTAccessibilityManager.m
Specifically, NSAccessibilityPostNotificationWithUserInfo. Other methods such as `getCurrentHighContrastState` provide cached state (cached on main thread via `observeValueForKeyPath` et al). Some other methods such as `setAccessibilityFocus` dispatch to the main thread.
Not doing so could lead to AppKit further firing selectors on UI logic in app code and lead to downstream issues.
I've verified that original badness I observed in Office that led to discovering this no longer reproduces. Announcement posts in Accessibility Inspector.
=> [0.71] -[RCTAccessibilityManager announceForAccessibility:] calls into AppKit from background thread

Libraries/Components/Pressable/Pressable.js, Libraries/Components/Pressable/__tests__/__snapshots__/Pressable-test.js.snap, Libraries/Components/View/ReactNativeViewAttributes.js, Libraries/Components/View/ViewPropTypes.d.ts, Libraries/Components/View/ViewPropTypes.js, Libraries/NativeComponent/BaseViewConfig.macos.js, React/Base/RCTUIKit.h, React/Base/macOS/RCTUIKit.m, React/Views/RCTView.m, React/Views/RCTViewManager.m, packages/rn-tester/Podfile.lock, packages/rn-tester/RNTester/AppDelegate.mm
WIP, there's still some test code laying around.
When you host RN inside a window with a movable background, we don't want clicks inside Buttons/Controls/Pressables to move the window. We instead want to be able to click and drag off the Button to "cancel" the mouse interaction.This matches native Appkit controls. There's a convenient prop on NSView to do this, [mouseDownCanMoveWindow](https://developer.apple.com/documentation/appkit/nsview/1483666-mousedowncanmovewindow), let's just expose it to React Native and set it to false on Pressable (the closest thing we have to an `NSControl` subclass in JS land).
[MACOS] [FIXED] - Mouse drags inside Pressable don't move the window
Made RNTester's window movable via `  [self.window setMovableByWindowBackground:YES];` inside AppDelegate.mm. I …
=> [Pressable] Mouse drags inside Pressable don't move the window

React/Base/RCTTouchHandler.m
macOS has an inverted Y coordinate for its screen coordinate system compared to other OS'es. This led to a bug where pressIn/pressOut on Pressables was calculated with the wrong rect, and click hold->move mouse out of button rect was doing weird stuff. Also some animation code was off. It's easier to explain with a video:
https://github.com/microsoft/react-native-macos/assets/6722175/ac08339e-91ca-4080-8a6a-a3255b335a74
The solution is to flip the Y coordinate in RCTTouchHandler when sending the touch (aka click) event to JS.
[MACOS] [FIXED] - nvert Y coordinate when sending to JS in RCTTouchHandler
Tested the same two demos and they work now :)
https://github.com/microsoft/react-native-macos/assets/6722175/53cf893e-8f75-4971-8cde-a6f3601eb0a5
=> [RCTTouchHandler] Invert Y coordinate when sending touch events to JS

React/Base/RCTTouchHandler.m
=> [0.71][RCTTouchHandler] Invert Y coordinate when sending touch events to JS

React/Base/RCTUIKit.h
When including react-native-macos public headers with Xcode 15, we get an error that the `clipsToBounds` property declared on RCTUIView doesn't match the one now declared in AppKit as of the macOS 14.0 SDK. AppKit has finally publicized this property, but it is marked as atomic rather than nonatomic.
When we're building exclusively with Xcode 15, we can remove this override. But for now, let's just make the property declarations match.
Note, this isn't actually blocking building react-native-macos because these warnings aren't turned on as errors (they probably should be). But if a consumer has warnings treated as errors, this will fail their builds.
[MACOS] [FIXED] - Silenced warnings with Xcode 15.
Just counting on CI since this really should be a non-functional change
=> [Xcode 15] Silence warning with mismatched NSView.clipsToBounds property

React/Base/RCTUIKit.h
Port #1864 to 0.71-stable. Note that RCTUIImageView doesn't exist in 0.71 so only one instance of the change comes over
=> [0.71] [Xcode 15] Silence warning with mismatched NSView.clipsToBounds property

React/Base/macOS/RCTUIKit.m
Implement image tinting using a CALayer with a compositing CIFilter instead of generating a tinted image. This fixes the wrong image aspect ratio of the generated tint image and removes the need to change the source image.
[macOS] [FIXED] - Image tint renders the images with the correct size on fabric.
Tested by running RNTester on macOS with fabric (RCT_NEW_ARCH_ENABLED=1) and launching the Image example.
With the fix:
Without the fix:
=> [Fabric] Tint images using CIFilter fixing wrong tinted image size

Libraries/Image/RCTImageView.mm
Cherry pick of https://github.com/microsoft/react-native-macos/pull/1834/ to 0.71-stable
[macOS] [CHANGED] - Use viewDidChangeBackingProperties for image reloads on backing properties change
Tested by running RNTester on macOS with paper:
=> [0.71] Use viewDidChangeBackingProperties to remove the use of notifications in RCTImageView

React/Base/RCTUIKit.h, React/Base/macOS/RCTUIKit.m, React/Views/RCTSwitchManager.m
Separating out a change from #1867 to reduce the footprint of that PR.
When a <Switch> is created on macOS with an initial value of on, it would not report it's change the first time you toggled it. This seems to be because an internal variable `_wasOn` was not  set properly on macOS, which the `onChange` handler relied on. Comparing Appkit to UIKit, I think this is because in UIKit, setting the property `on` will internally call `setOn:Animated`, which RN overrides to set `_wasOn`. We had to reimplement both `on` and `setOn:Animated` for macOS. Let's just have the setter for `on` call `setOn:Animated` to fix this issue.
Pick one each for the category and type tags:
[MACOS] [FIXED] - Make sure `wasOn` is set properly in Switch
Before (from #1867): …
=> [Switch] make sure `wasOn` is set properly

Libraries/Components/Pressable/Pressable.js, Libraries/Components/View/ReactNativeViewAttributes.js, Libraries/Components/View/ViewPropTypes.js, Libraries/NativeComponent/BaseViewConfig.macos.js, Libraries/Text/TextInput/Multiline/RCTUITextView.m, Libraries/Text/TextInput/RCTBaseTextInputView.m, React/Base/RCTConvert.h, React/Base/RCTConvert.m, React/Views/RCTHandledKey.h, React/Views/RCTHandledKey.m, React/Views/RCTSwitch.m, React/Views/RCTView.h, React/Views/RCTView.m, React/Views/RCTViewKeyboardEvent.m, React/Views/RCTViewManager.m, React/Views/ScrollView/RCTScrollView.m, packages/rn-tester/js/examples/KeyboardEventsExample/KeyboardEventsExample.js, packages/rn-tester/js/examples/TextInput/TextInputSharedExamples.js
There are scenarios where it might be necessary to look at the incoming events without removing from the system queue. Currently that's impossible today on React Native macOS, since views are required to specify `validKeysDown` or `validKeysUp`, and such events are always removed from the queue.
To mitigate, let's add a new `passthroughAllKeyEvents` prop to `RCTView`. We could keep it forever (towards an interest to reduce event spam from native to JS), or we could use it towards the path to making it the default behavior (stage 1: default false, i.e. opt in, stage 2: default true, i.e. opt out, stage 3: remove, is default behavior).
- React/Views/RCTView.h
- React/Views/RCTView.m
- React/Views/RCTViewManager.m
Note that this doesn't properly work with `RCTUITextField` (i.e. single line …
=> [Key handling] pass through all keys; allow specifying modifiers for validKeys[Down|Up]

Libraries/Components/Pressable/Pressable.js, Libraries/Components/View/ReactNativeViewAttributes.js, Libraries/Components/View/ViewPropTypes.js, Libraries/NativeComponent/BaseViewConfig.macos.js, Libraries/Text/TextInput/Multiline/RCTUITextView.m, Libraries/Text/TextInput/RCTBaseTextInputView.m, React/Base/RCTConvert.h, React/Base/RCTConvert.m, React/Views/RCTHandledKey.h, React/Views/RCTHandledKey.m, React/Views/RCTView.h, React/Views/RCTView.m, React/Views/RCTViewKeyboardEvent.m, React/Views/RCTViewManager.m, React/Views/ScrollView/RCTScrollView.m, packages/rn-tester/js/examples/KeyboardEventsExample/KeyboardEventsExample.js, packages/rn-tester/js/examples/TextInput/TextInputSharedExamples.js
There are scenarios where it might be necessary to look at the incoming events without removing from the system queue. Currently that's impossible today on React Native macOS, since views are required to specify `validKeysDown` or `validKeysUp`, and such events are always removed from the queue.
To mitigate, let's add a new `passthroughAllKeyEvents` prop to `RCTView`. We could keep it forever (towards an interest to reduce event spam from native to JS), or we could use it towards the path to making it the default behavior (stage 1: default false, i.e. opt in, stage 2: default true, i.e. opt out, stage 3: remove, is default behavior).
- React/Views/RCTView.h
- React/Views/RCTView.m
- React/Views/RCTViewManager.m
Note that this doesn't properly work with `RCTUITextField` (i.e. single line …
=> [0.71] [Key handling] pass through all keys; allow specifying modifiers for validKeys[Down|Up]

package.json, yarn.lock
0.71-stable counterpart of #1876.
If the CIs pass, we should be good
=> [0.71-stable] Resolve tough-cookie to ^4.1.3

React/Views/ScrollView/RCTScrollView.m
`RCTScrollView` was submitting `onScroll` events after an `onContentSizeChanged` event. This was caused by the `setFrame` call leading to a `DocumentViewBoundsChanged` notification that would get triggered a second time after the horizontal/vertical scrollers would be enabled/disabled.
This double notification would trigger a `scrollViewDidScroll` call with an `onScroll` event being sent because the scroll position would toggle temporarily due to the scrollers being shown/hidden.
This PR updates the scroll view to compare the scroll position with the last sent position after the scrollers were set. This fixes the wrong `onScroll` event during the `setFrame` because the scroll position is stable and valid by the time we do the comparison.
[macOS] [FIXED] - Update ScrollView to emit only …
=> Fix invalid onScroll events breaking FlatList

package.json, yarn.lock
0.71-stable counterpart of #1879.
Resolve `@grpc/proto-loader` to `^0.7.8`.
This version resolves a security issue with `protobufjs`.
If the CIs pass, we should be good
=> [0.71-stable] Resolve @grpc/proto-loader to ^0.7.8

React/Views/ScrollView/RCTScrollView.m
Cherry-pick of https://github.com/microsoft/react-native-macos/pull/1873 to 0.71-stable
=> [0.71] Fix duplicate onScroll events breaking flatlist. (#1873)

package.json, yarn.lock
Resolve `@grpc/proto-loader` to `^0.7.8`.
This version resolves a security issue with `protobufjs`.
If the CIs pass, we should be good
=> Resolve @grpc/proto-loader to ^0.7.8

React/Base/RCTConvert.m
Wrong macro -- use `RCT_ARRAY_CONVERTER`, not `RCT_JSON_ARRAY_CONVERTER`. The latter is for "directly representable json array values that require no conversion.":
```
/**
* This macro is used for creating converter functions for directly
* representable json array values that require no conversion.
*/
#if RCT_DEBUG
#define RCT_JSON_ARRAY_CONVERTER_NAMED(type, name) RCT_ARRAY_CONVERTER_NAMED(type, name)
#else
#define RCT_JSON_ARRAY_CONVERTER_NAMED(type, name) \
+(NSArray *)name##Array : (id)json               \
{                                                \
return json;                                   \
}
#endif
#define RCT_JSON_ARRAY_CONVERTER(type) RCT_JSON_ARRAY_CONVERTER_NAMED(type, type)
```
```
/**
* This macro is used for creating converter functions for typed arrays.
* …
```
=> [0.71] Fixing release-only crash for when specifying validKeys[Down|Up]

React/Base/RCTConvert.m
Cherry-pick of #1885 to 0.71-stable
=> [0.71][DynamicColorMacOS] Downgrade to warning if appearance is nil

React/Base/RCTConvert.m
When a user cuts/copies text from a `<TextInput>` that has it's text color styled using `DynamicColorMacOS`, we would get a Redbox saying that the current appearance could not be resolved. Looking into it, it seems that at this point in native code, Appkit returns an appearance of `NSAppearanceNameSystem`, which seems to correspond to the "Any" case of an asset catalog if you were specifying a color that way instead.
While I'm not sure why cutting/copying text gets us in this state, it seems this is a valid state to be in, where the OS doesn't have the current appearance and just reports back a generic one. Let's fall back to the light color (as you would with an asset catalog) with a warning instead of an error. 
[MACOS] [CHANGED] - Downgrade  DynamicColorMacOS error to warning if …
=> [DynamicColorMacOS] Downgrade to warning if appearance is nil

React-Core.podspec, React/CoreModules/React-CoreModules.podspec, packages/rn-tester/Podfile.lock
0.71-stable counterpart of #1887.
This upgrades the SocketRocket to 0.7.0, which fixes a number of retain cycle issues.
[GENERAL] [FIXED] - Fix retain cycle issues in SocketRocket
Validated that the WebSocket test page still works.
If the CIs also pass, we should be good.
=> [0.71] Upgrade SocketRocket to 0.7.0

React-Core.podspec, React/CoreModules/React-CoreModules.podspec, packages/rn-tester/Podfile.lock
This upgrades the SocketRocket to 0.7.0, which fixes a number of retain cycle issues.
[GENERAL] [FIXED] - Fix retain cycle issues in SocketRocket
Validated that the WebSocket test page still works.
If the CIs also pass, we should be good.
=> Upgrade SocketRocket to 0.7.0

Libraries/Text/Text.js
During the 0.71 merge, I accidentally clobbered over some macOS specific diffs that were introduced here: https://github.com/microsoft/react-native-macos/commit/cf48f8d6bc308f8d22ccd6351ef55e7fc4d6eddf#diff-8854d86a25d1052c7f65f4d7235198297464645255149b9700171beb00ca67ec
The solution is to cherry-pick a future change that should be more resistant to accidental-clobbering.
My notes from an internal thread about this:
> I couldn't figure out why isHighlighted was iOS only so I added it back for macOS. I see that I even commented about that, my bad. I think the issue was that Shawn's orginal PR deleted the original iOS code, and we don't have anything like // [macOS] tags for deleted lines. Because there were no tags, when I compared diffs, I just added them back. I'm not sure how to avoid …
=> [Cherry Pick] Only apply isHighlighted native prop on iOS

Libraries/Text/Text.js
Backport of #1892 to 0.71-stable
=> [0.71][Cherry Pick] Only apply isHighlighted native prop on iOS

Libraries/Components/TextInput/RCTMultilineTextInputNativeComponent.js, Libraries/Components/TextInput/RCTSingelineTextInputNativeComponent.js, Libraries/Components/TextInput/TextInput.flow.js, Libraries/Components/TextInput/TextInput.js, Libraries/Components/TextInput/TextInputNativeCommands.js, Libraries/Text/TextInput/Multiline/RCTUITextView.h, Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m, Libraries/Text/TextInput/RCTBackedTextInputViewProtocol.h, Libraries/Text/TextInput/RCTBaseTextInputView.h, Libraries/Text/TextInput/RCTBaseTextInputView.m, Libraries/Text/TextInput/RCTBaseTextInputViewManager.m, Libraries/Text/TextInput/Singleline/RCTUITextField.h, ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java, packages/rn-tester/js/examples/GhostText/GhostText.js, packages/rn-tester/js/utils/RNTesterList.ios.js
Ghost text is hint text that is inserted inline as a hint to the user (for example predictive text). Unlike autocomplete for combo boxes, which is "visible" to the model, ghost text is "invisible" or transparent to the model (i.e. not observable in any callback or imperative method). Ghost text isn't selectable by the user.
Ideally we do ghost text only in the display layer, meaning it isn't in the model. Unfortunately it doesn't look like we can render ghost text and still have Apple flow text for us (ghost text that is in the middle of regular text will want to reflow the regular text to make room for ghost text). Overriding all text box rendering seems like substantial rework (we need to deal with all drawing, including but not limited to the text box background, text, insertion …
=> [iOS/macOS] [TextInput] Implement ghost text

Libraries/Image/RCTUIImageViewAnimated.h, Libraries/Text/TextInput/Multiline/RCTUITextView.h, Libraries/Text/TextInput/Multiline/RCTUITextView.m, Libraries/Text/TextInput/RCTBackedTextInputViewProtocol.h, Libraries/Text/TextInput/Singleline/RCTUITextField.h, Libraries/Text/TextInput/Singleline/RCTUITextField.m, React/Base/RCTUIKit.h, React/Base/macOS/RCTUIKit.m, React/Fabric/Mounting/ComponentViews/Image/RCTImageComponentView.mm, React/Fabric/Mounting/ComponentViews/SafeAreaView/RCTSafeAreaViewComponentView.mm, React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm, React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, React/Fabric/RCTSurfaceTouchHandler.mm, React/Views/ScrollView/RCTScrollView.m, React/Views/UIView+React.m, ReactCommon/react/renderer/graphics/platform/ios/RCTPlatformColorUtils.mm, ReactCommon/react/renderer/textlayoutmanager/platform/ios/RCTAttributedTextUtils.mm, packages/rn-tester/RNTester/AppDelegate.mm
Cherry-pick to 0.71-stable of:
#1813 
#1814
#1816
#1817 
#1818 
#1819 
#1820 
#1828 
#1843
=> [0.71] Picking Fabric fixes from main

Libraries/Components/Pressable/Pressable.js, Libraries/Components/View/ViewPropTypes.d.ts, Libraries/Components/View/ViewPropTypes.js, Libraries/NativeComponent/BaseViewConfig.macos.js, React/Views/RCTView.h, React/Views/RCTView.m, React/Views/RCTViewManager.m
Appkit has a prop `allowsVibrancy` that will allow Appkit to subtly change the colors of an NSView inside an NSVisualEffectView to get that "vibrant" effect. There's a property we can override on NSView for custom NSViews so we can get the effect too. Let's expose it on macOS so that we can set it through Javascript. One caveat is the Appkit property is readonly, so I had to add a new RCTView property `allowsVibrancyInternal` that the RCTView getter then reads.
https://developer.apple.com/documentation/appkit/nsview/1483793-allowsvibrancy
[MACOS] [ADDED] - Add new macOS View prop `allowsVibrancy`
Prototyping this inside FluentUI React Native (by just.. making every RCTView set `allowsVibrancy = true`), you can clearly see a difference between the two Callouts. Both have a solid background …
=> Add new macOS View prop `allowsVibrancy`

.ado/apple-integration.yml, .ado/templates/react-native-macos-init.yml, .ado/templates/verdaccio-init.yml, .ado/templates/verdaccio-publish.yml, package.json
#1894 caused a few issues with some of our pipelines. We provide the following fixes:
* Manually bump `@react-native-mac/virtualized-lists` to `^0.1.0`. (I'm not sure why beachball didn't do this automatically, but at least we're doing it now.)
* Use a Verdaccio server in our Integration pipeline. The pipeline will probably still be broken, but it was broken anyway, so we're at least getting it back up to our previous baseline. We can fix it while finishing up the 0.72 merge.
[INTERNAL] [FIXED] - ADO pipeline fixes
Required pipelines should pass, and the `yarn install` phase should succeed for the Integration pipeline.
=> Fix some ADO pipeline stuff

React/Base/RCTTouchHandler.m
Back in #1862, we made a fix to make sure that macOS screen coordinates (where the Y coordinate is flipped) are converted before being sent to JS, where we assume the coordinate system that every other platform uses (AKA, origin at top left). @lenaic pointed out there's a simpler way to do this, so let's make a small optimization. To quote:
> Using this line to assign rootViewLocation instead of the weird _cachedRootView.window.contentView conversion fixes the flipping, allowing to remove the flipping you added below.
Note, it seems we've changed this particular block before, with #1619 . Seems it's a strongly-hit code path 😄
[MACOS] [CHANGED] - Add a small optimization to RCTTouchHandlers' coordinate conversion
Sanity checked the Pressable test page with and without the change and didn't …
=> [RCTTouchHandler] Add a small optimization to coordinate conversion

React/Base/RCTTouchHandler.m
Backport of #1902 to 0.71-stable
=> [0.71][RCTTouchHandler] Add a small optimization to coordinate conversion

Libraries/Core/ReactNativeVersion.js, React/Base/RCTVersion.m, ReactAndroid/gradle.properties, ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, ReactCommon/cxxreact/ReactNativeVersion.h, package.json, packages/rn-tester/Podfile.lock, template/package.json
I made an error, and now the 0.71-stable NPM package & Github branch are out of sync in package versions. This PR rectifies that. 
As it turns out, with my admin privileges, I can push directly to the repos' `0.71-stable` branch. This led to this unfortunate set of events:
1) I accidentally committed directly to `0.71-stable` with https://github.com/microsoft/react-native-macos/commit/3770a1ae8e80a42d6d34c8902f029d73c859e7b9, which caused the publish pipeline to run.
2) I tried to fix this issue by changing settings so that _nobody_ could push a commit to a `*-stable` branch. 
3) Unfortunately, that meant that even `rnbot` (the bot that publishes to NPM for us and pushes the version update back to Github) couldn't push to the branch, and the [publish pipeline …
=> Applying package update to 0.71.33 ***NO_CI***

package.json, packages/rn-tester/package.json, packages/rn-tester/react-native.config.js
This is an alternative to #1910 where we cherry-pick a commit from upstream that fixes the problem in a slightly different way.
This ensures that `PROJECT_ROOT` has the correct value so the JS bundler knows how to resolve things properly.
[INTERNAL] [FIXED] - Specify PROJECT_ROOT in rn-tester yarn start script
Launched RNTester using the bundler from `yarn start`, and it works.
=> Run packager from correct folder (cherry-pick of 40f816d)

.circleci/config.yml, Libraries/Components/TextInput/TextInput.js, Libraries/ReactNative/AppContainer.js, React/Base/RCTBundleURLProvider.h, React/Base/RCTBundleURLProvider.mm, ReactAndroid/src/main/java/com/facebook/react/devsupport/DevSupportManagerBase.java, ReactCommon/jsc/JSCRuntime.cpp, package.json, packages/rn-tester/RNTesterUnitTests/RCTBundleURLProviderTests.m, scripts/circle-ci-artifacts-utils.js, scripts/circleci/poll-maven.js, scripts/monorepo/bump-all-updated-packages/bump-utils.js, scripts/monorepo/bump-all-updated-packages/index.js, scripts/monorepo/for-each-package.js, scripts/npm-utils.js, scripts/publish-npm.js, scripts/release-utils.js, scripts/test-e2e-local-clean.js, scripts/test-e2e-local.js, scripts/testing-utils.js, scripts/trigger-react-native-release.js, scripts/update-template-package.js, yarn.lock
Merge the latest commits from 0.71-stable upstream (RN 0.71.13). Let's also pick a few commits that _should_ land in 0.71.14 that I wanted to bring to RNM anyway. Specifically: https://github.com/facebook/react-native/commit/8b1bf058c4bcbf4e5ca45b0056217266a1ed870c and https://github.com/facebook/react-native/commit/3eeee11d7ac4075d0917233d3be4a9469f802d35
[INTERNAL] [ADDED] - Merge latest upstream changes in 0.71-stable
CI should pass
=> Merge latest changes from RN 0.71.13 + a few cherry-picks

.ado/publish.yml, change/@react-native-mac-virtualized-lists-502c73bf-9001-46d1-9d12-648b6fd90294.json, packages/react-native/package.json, packages/virtualized-lists/package.json
After #1914, we had several issues with our publishing script.
* beachball unexpectedly tried to bump and publish react-native-macos from the main branch.
* The canary publish failed because we moved the core bits of react-native-macos to a new location.
While we don't have a full fix for the first issue yet, we can at least finish the job and bump all the relevant version numbers as needed.
The second issue gets resolved by 847315f.
[INTERNAL] [FIXED] - Fix publishing pipeline issues
As long as our publishing pipeline holds up, we should be good.
=> Publishing pipeline fixes

.ado/publish.yml
This is a follow-up to #1919 and addresses three things:
* Change some display names in our beachball publish pipeline so they line up with their newly generalized roles.
* Remove `packages/react-native` from the beachball publish scope so we don't try to publish it from the main branch. (Note that the beachball publish pipeline only gets run from the main branch.)
* Be explicit about the local file path that we publish react-native-macos from. (For some strange reason, `npm` was trying to interpret the original as a GitHub username and repository.)
[INTERNAL] [FIXED] - More pipeline fixes
Running `npm publish packages/react-native --dry-run` locally results in this weird error:
> npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote …
=> Fix scope and path names for publish pipeline

change/@react-native-mac-virtualized-lists-8dd7db33-b2cf-4f5c-b6e0-ca0ec377402a.json, packages/react-native/Libraries/Lists/__tests__/__snapshots__/FlatList-test.js.snap, packages/react-native/Libraries/Lists/__tests__/__snapshots__/SectionList-test.js.snap, packages/virtualized-lists/Lists/VirtualizedList.js, packages/virtualized-lists/Lists/__tests__/VirtualizedList-test.js, packages/virtualized-lists/Lists/__tests__/__snapshots__/VirtualizedList-test.js.snap, packages/virtualized-lists/Lists/__tests__/__snapshots__/VirtualizedSectionList-test.js.snap, packages/virtualized-lists/package.json
This is a manual cherry-pick of the changes that #1927 makes to `@react-native-mac/virtualized-lists`. This was done by running `git show 0.72-rest:path/to/relevant/file > path/to/relevant/file` for all files that were updated. (For reference, `0.72-rest` is the name of the branch that #1927 is operating from.)
By applying them to the main branch, our publish pipeline will be able to release a new version for consumption in `0.72-stable`.
[GENERAL] [FIXED] - Bring in RNCore's 0.72-stable changes to virtualized-lists
Our CI cases should still pass.
=> Bring in RNCore's 0.72-stable changes to virtualized-lists

.ado/versionUtils.js
Our ADO pipeline didn't get the news that the package.json file with the right version information now lives in a new spot.
[INTERNAL] [FIXED] - Use correct package.json file when publishing new versions
This only affects the publishing pipeline. We'll know when this gets checked in.
=> Use correct package.json file when publishing new versions

.ado/get-next-semver-version.js, docs/Releases.md, packages/react-native/package.json, packages/rn-tester/Podfile.lock
Right now, our publishing pipeline doesn't elegantly handle the case of promoting from a prerelease to a proper release. We fix this by adding a special prerelease name, `ready`, that indicates that we're ready to release.
We opt for this instead of just going to `0.72.0` directly because our publishing pipeline will bump again to `0.72.1`, which isn't ideal. While it would be nice to get beachball up and running so we don't have to worry about this stuff manually, it would undoubtedly be more expensive to get beachball up and running, so this should be a satisfactory workaround for now.
[INTERNAL] [FIXED] - More pipeline fixes
We'll have to test this against our actual publishing pipeline.
=> Mark 0.72 as ready for release

scripts/publish-npm.js
Yet another path that needs to be fixed.
[INTERNAL] [FIXED] - Pipeline fixes
Ran the script and confirmed that it pointed to the correct package.json file.
=> Fix one more package.json path

.ado/apple-integration.yml, .ado/get-next-semver-version.js, .ado/publish.yml, .ado/versionUtils.js, docs/Releases.md, packages/rn-tester/react-native.config.js, scripts/publish-npm.js
When getting 0.72 ready for release, we had to make a few changes to our publishing pipeline to account for the new monorepo. This brings those changes over.
Here's a list of changes we're cherry-picking along with a description of what they do and how they affect the main branch:
* 174eff58871dc971a5b7c3b8f87af856ac7d1cc0 - Enables publishing from 0.72-stable, has no effect on the main branch
* 362af5c8555207fae1c2b303523451eed0b31a8d - Hardening up of react-native-test-app integration pipeline
* a3bb438f049a87b1d6115820fb7dfb48c061ce2a - Fix to RNTester config - may not be necessary right now, but we will need it eventually
* f5d699e6920dd4d1e2779ab1e2710fdd767b38e4 - Fixes path to correct package.json file, doesn't affect main branch because both RN and the monorepo are at 1000.0.0
* …
=> Pull in a few pipeline fixes from 0.72-stable

docs/Releases.md
Change a few reference to 0.71 to 0.72 to reflect latest release.
As we use the macOS fork as the basis for our visionOS fork, I noticed that some explicit references to 0.71 are now out-of-date given the 0.72 release last week.
[INTERNAL] [FIXED] - Update internal port documentation references to 0.72
Markdown lint is clear.
=> Accomodate 0.72 release

packages/react-native/ReactCommon/react/runtime/platform/ios/ReactCommon/RCTHermesInstance.h
- Builds w/ Hermes + New Arch were failing on 0.73-stable
`RCT_NEW_ARCH_ENABLED=1 USE_HERMES=1 bundle exec pod install`
[MACOS] [FIXED] - Use correct import for RCTUIKit for RCTHermesInstance.h
RN Tester w/ Hermes enabled:
=> [Hermes] Use correct import for RCTUIKit in RCTHermesInstance.h

packages/rn-tester/RNTester-macOS/Info.plist
This applies the same settings as used in iOS:
https://github.com/microsoft/react-native-macos/blob/main/packages/rn-tester/RNTester/Info.plist#L38-L44
See:
https://developer.apple.com/documentation/bundleresources/information_property_list/nsapptransportsecurity/nsallowsarbitraryloads?language=objc
CircleCI
=> Align App Transport Security setting with rntester-ios and rntester-macOS

packages/react-native/ReactAndroid/src/main/java/com/facebook/react/shell/MainReactPackage.java, packages/react-native/package.json, yarn.lock
https://github.com/microsoft/react-native-macos/pull/1952 pulled in two extra commits that were in upstreams' `0.72-stable` but not in the `0.72.6` release. Lets undo them to keep our release aligned.
[INTERNAL] [CHANGED] - Revert post 0.72.6 commits from upstream
CI should pass
=> [0.72] Revert post 0.72.6 commits from upstream

yarn.lock
This is a run of `yarn upgrade` to upgrade `@babel/traverse` to 7.23.2. This resolves a security issue as described [here](https://security.snyk.io/vuln/SNYK-JS-BABELTRAVERSE-5962462).
[INTERNAL] [SECURITY] - Update @babel/traverse to 7.23.2
If CIs pass, we should be good.
=> Run `yarn upgrade` to upgrade @babel/traverse to 7.23.2

package.json, yarn.lock
#1954 bumped `readable-stream` to 4.4.2, which depends on an old version of `string_decoder`. Luckily, we can avoid having to use this by capping `readable-stream` at 4.4.1.
[INTERNAL] [SECURITY] - Cap readable-stream at 4.4.1
If CIs pass, we should be good.
=> Cap readable-stream at 4.4.1

package.json, yarn.lock
Cherry-pick of #1954 and #1955.
[INTERNAL] [SECURITY] - Upgrade @babel/traverse and cap readable-stream at 4.4.1
If the CIs pass, we should be good.
=> [0.72-stable] Run yarn upgrade and cap readable-stream at 4.4.1

scripts/monorepo/get-and-update-nightlies.js
Right now, our nightly publishing pipelines are broken, which prevents our scripts from running component detection. This was caused by 52104c6ee30b8fe3e59b6be417e65d2d51cdba52, which we inherited from RNCore, and their publishing process is slightly different.
This reverts to the previous, more lenient way of checking things.
[INTERNAL] [FIXED] - Fix build scripts
The spot we changed is where the error we were logging came from, so this reversion should work.
=> Ignore publish errors in get-and-update-nightlies

React/CxxBridge/JSCExecutorFactory.h, React/CxxBridge/JSCExecutorFactory.mm, ReactCommon/jsc/JSCRuntime.cpp, ReactCommon/jsc/JSCRuntime.h
Cherry pick of https://github.com/facebook/react-native/pull/38942 and https://github.com/facebook/react-native/pull/39549 to React Native macOS. The upstream change hasn't landed yet, but we would like to use this change internally regardless.
[IOS] [CHANGED] - Add facebook::jsc::runtimeConfig to set enable debugger and set debugger
Running RNTester with JSC shows the JSContext with the updated name.
=> [0.71][JSCRuntime] Add runtimeConfig to set debugger options

packages/react-native/React/CxxBridge/JSCExecutorFactory.h, packages/react-native/React/CxxBridge/JSCExecutorFactory.mm, packages/react-native/ReactCommon/jsc/JSCRuntime.cpp, packages/react-native/ReactCommon/jsc/JSCRuntime.h
Cherry pick of https://github.com/facebook/react-native/pull/38942 and https://github.com/facebook/react-native/pull/39549 to React Native macOS. The upstream change hasn't landed yet, but we would like to use this change internally regardless.
[IOS] [CHANGED] - Add facebook::jsc::runtimeConfig to set enable debugger and set debugger
Running RNTester with JSC shows the JSContext with the updated name.
=> [0.72][JSCRuntime] Add runtimeConfig to set debugger options

packages/react-native/React/CxxBridge/JSCExecutorFactory.h, packages/react-native/React/CxxBridge/JSCExecutorFactory.mm, packages/react-native/ReactCommon/jsc/JSCRuntime.cpp, packages/react-native/ReactCommon/jsc/JSCRuntime.h
Cherry pick of https://github.com/facebook/react-native/pull/38942 and https://github.com/facebook/react-native/pull/39549 to React Native macOS. The upstream change hasn't landed yet, but we would like to use this change internally regardless.
[IOS] [CHANGED] - Add facebook::jsc::runtimeConfig to set enable debugger and set debugger
Running RNTester with JSC shows the JSContext with the updated name.
=> [JSCRuntime] Add runtimeConfig to set debugger options

.ado/variables/vars.yml
Ci seems to be failing because we request `iOS 17.0` instead of `iOS 17.0.1`. This should be a one line fix. 
[INTERNAL] [CHANGED] - Update CI to iOS 17.0.1
CI should pass
=> [CI] Update to iOS 17.0.1

packages/react-native/React/Views/RCTView.m
We've seen an issue where mouse events sometimes behave strangely. The exact cause is unknown, but we found that one problem is that we're constantly recalculating the `NSTrackingArea` despite the fact that the size of the view isn't changing.
To resolve this, we limit the recreation of a new `NSTrackingArea` to when its size would actually change.
Pick one each for the category and type tags:
[MACOS] [FIXED] - Remove unnecessary recreation of NSTrackingAreas
This was tested with the following test component in RNTester (not included as part of this change):
```jsx
<View>
<View
width="20%"
height={50}
style={{backgroundColor: 'red'}}
onMouseEnter={() => {
console.log('onMouseEnter');
}}
/>
</View>
```
I validated that the `NSTrackingArea` is correct by moving the mouse into the view from …
=> Don't recreate identical NSTrackingAreas

packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/RCTUtils.h, packages/react-native/React/Base/RCTUtils.m, packages/react-native/React/CoreModules/RCTDeviceInfo.mm, packages/react-native/React/UIUtils/RCTUIUtils.h, packages/react-native/React/UIUtils/RCTUIUtils.m
In 0.73 on Paper, `StyleSheet.hairlineWidth` would throw an `NaN` error when `PixelRatio.get()` returned 0.
https://github.com/microsoft/react-native-macos/blob/43122d4e34e1b950530bfacc706d687ada6cb45a/packages/react-native/Libraries/StyleSheet/StyleSheet.js#L166-L169
This was because we were calculating the scale before the window was created and returning zero.
https://github.com/microsoft/react-native-macos/blob/43122d4e34e1b950530bfacc706d687ada6cb45a/packages/react-native/React/UIUtils/RCTUIUtils.m#L51
With the New Arch Enabled flag, the `RCTDeviceInfo` Turbomodule will run after the window is created so it will always have a current window.
[MACOS] [FIXED] - Default dimensions `scale` value to 1.0 if window is nil
**Paper - Before window is created**
**Paper - After window is …
=> Default dimensions `scale` value to 1.0 if window is nil

packages/react-native/React/CxxBridge/JSCExecutorFactory.h, packages/react-native/React/CxxBridge/JSCExecutorFactory.mm, packages/react-native/ReactCommon/jsc/JSCRuntime.cpp, packages/react-native/ReactCommon/jsc/JSCRuntime.h
Cherry pick of https://github.com/facebook/react-native/pull/38942 and https://github.com/facebook/react-native/pull/39549 to React Native macOS. The upstream change hasn't landed yet, but we would like to use this change internally regardless.
[IOS] [CHANGED] - Add facebook::jsc::runtimeConfig to set enable debugger and set debugger
Running RNTester with JSC shows the JSContext with the updated name.
=> [0.73][JSCRuntime] Add runtimeConfig to set debugger options

packages/react-native/React/CxxBridge/JSCExecutorFactory.h
https://github.com/microsoft/react-native-macos/pull/1957 set the JSC debugging to always be true, even on Release builds. Let's ifdef the default so it's only true for debug. This way, we can continue to support allowing a user to enable debugging for release builds if they wish. 
[GENERAL] [CHANGED] - Only enable JSC debugging in DEBUG by default
CI should pass. I couldn't get a good ship build of RN, but this is a fairly simple change.
=> [JSCRuntime] Only enable the JSC debugging in DEBUG by default

packages/react-native/React/DevSupport/RCTInspectorDevServerHelper.mm
We've seen a crash when we have multiple instances of React Native running in an app. It appears to be caused by multiple threads accessing `+[RCTInspectorDevServerHelper connectWithBundleURL:]` at the same time.
To fix this, we put all accesses to the `socketConnections` dictionary in a `@synchronized` block. This brings the iOS/macOS implementations up to speed with [Android](https://github.com/facebook/react-native/blob/050a5a379766318c3a9f322ceb5e13ef4cd8e7d2/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/websocket/WebSocketModule.java#L47), which uses a `ConcurrentHashMap`.
[IOS] [FIXED] - Improve `RCTInspectorDevServerHelper` thread safety
Tested this change in an internal app that consumes React Native and confirmed that it doesn't crash. (Without this …
=> Make socketConnections NSDictionary thread-safe

packages/react-native/local-cli/generator-macos/templates/macos/Podfile
With 0ab8b40fd64ad86b4598293faa0b77e71fc9d349, the Xcode 12.5 post-install workaround is now gone. Let's remove it from one other place where we used to call it.
[GENERAL] [FIXED] - Remove call to Xcode 12.5 post-install workaround
The CIs for #1987 saw a failure related to the existence of this call. If the CI passes, we should be good.
=> Remove call to Xcode 12.5 post-install workaround

packages/react-native-codegen/package.json
In pnpm setups, codegen will fail during build because it cannot find its dependencies. Some of the dependencies it relies on at runtime are currently declared under `devDependencies`. This change moves them to `dependencies`.
Cherry-picks c58e19e89aadcc01c2ac8ead876831ed8a2f6c5d.
[GENERAL] [FIXED] - Fix `react-native/codegen` not being able to resolve dependencies in pnpm setups
We are currently trying to [enable pnpm mode](https://github.com/microsoft/rnx-kit/pull/2811) in rnx-kit and hit this issue. We've patched this package locally and it works.
=> Correctly declare runtime dependencies

packages/react-native/scripts/cocoapods/__tests__/codegen-test.rb, packages/react-native/scripts/cocoapods/codegen.rb
`build_codegen!` currently assumes that `@react-native/codegen` gets installed next to `react-native`. In a pnpm setup, it's found under `/~/react-native/node_modules/@react-native/codegen` instead.
However, as @dmytrorykun pointed out, we don't actually need to build it outside of this repository.
Cherry-picks https://github.com/facebook/react-native/commit/3dd6a83c0e39c54b4ff050589e4e13f1ccc66a5d
[GENERAL] [FIXED] - `@react-native/codegen` shouldn't be built unless it's in the repo — fixes `pod install` failures in pnpm setups
We have a patched version of `react-native` working in a pnpm setup here: https://github.com/microsoft/rnx-kit/pull/2811
=> Fix `build_codegen!` not finding `@react-native/codegen` in pnpm setups

packages/react-native/React/DevSupport/RCTInspectorDevServerHelper.mm
Cherry-pick of commits from #1980.
[IOS] [FIXED] - Improve `RCTInspectorDevServerHelper` thread safety
Tested this change in an internal app that consumes React Native and confirmed that it doesn't crash. (Without this change, crashes happened intermittently but frequently enough that it was noticeable.)
=> [0.72-stable] Make socketConnections NSDictionary thread-safe

packages/react-native/local-cli/runMacOS/runMacOS.js, packages/react-native/package.json
`runMacOS.js` uses `chalk` but relies on other dependencies also depending on it and specific hoisting mechanisms to access it. This fails in a pnpm setup.
[GENERAL] [FIXED] - `runMacOS.js` depends on `chalk` but doesn't declare it
n/a
=> fix(react-native): `runMacOS.js` depends on `chalk`

.ado/Brewfile, .ado/Brewfile.lock.json, .ado/ado-test-cleanup.sh, packages/react-native/Libraries/Components/Button.js, packages/react-native/Libraries/Components/__tests__/__snapshots__/Button-test.js.snap, packages/react-native/Libraries/Text/Text/RCTTextView.m
RCTTextView does not override reactAccessibilityElement to the RCTUnfocusableTextView child.  This causes various properties, like accessible, to not get applied correctly.
In VoiceOver, there's a bug where if you have a Touchable like so:
```
<TouchableOpacity
accessibilityRole="button"
accessibilityLabel="Button with accessibility role as button and label"
onPress={onPress}>
<Text>Button with A11y Label Defined</Text>
</TouchableOpacity>
```
It reads "button, group".  By making the accessible prop apply correctly, the user can set the `<Text accessible={false} />` and VoiceOver will just read "button".
Before:
After:
[INTERNAL] [FIXED] - Make accessibility props apply correctly to <Text> components on macOS.
See Summary
=> Override reactAccessibilityElement for RCTTextView

packages/react-native/React/DevSupport/RCTInspectorDevServerHelper.mm
Cherry-pick of commits from #1980.
[IOS] [FIXED] - Improve `RCTInspectorDevServerHelper` thread safety
Tested this change in an internal app that consumes React Native and confirmed that it doesn't crash. (Without this change, crashes happened intermittently but frequently enough that it was noticeable.)
=> [0.73-stable] Make socketConnections NSDictionary thread-safe

packages/react-native/React/Views/RCTViewManager.m
In the merges for 0.73, accessibilityRole was inadvertently moved behind a #if block removing it from macOS.  This restores the 0.72 behavior, but more work is coming for the new role prop.  This is the main version of #1997
See #1997
=> Fix accessibilityRole

packages/react-native/React/Views/RCTViewManager.m
During the merge for 0.73, accessibilityRole was accidentally put behind an #if block removing it from macOS's implementation.  This simply restores the functionality of the prop to what it was in 0.72, but more changes are forthcoming to refactor and support the new role prop.
[MACOS] [FIXED] - Fixed accessibilityRole
See before/after of Accessibility Inspector for accessibilityRole="button" changing from AXUnknown to AXButton
=> [0.73] Fix accessibilityRole

packages/react-native/Libraries/Image/RCTImageView.mm
~~ImageView tint color was broken after this change on core:
https://github.com/facebook/react-native/commit/ce7c0b735f476a4618fd0d68fc39157a0bdb4f57~~
This change was from 2015 😅!
Paper should use the RCTUIImageView class for rendering which has the same tintColor property as the iOS UIImageView class.
[MACOS] [FIXED] - Fix ImageView tint color
**RN Tester**
=> Fix ImageView tint color

packages/react-native/Libraries/Image/RCTImageView.mm
0.73 stable version of #1996 
Cherry pick of 3d9b2470533554299511498d6cbaa9b287eeb278 & 7757c0160c3ce881d296ab9441572f74f4fe4df4
=> [0.73-stable] Fix imageview tintcolor

packages/react-native/Libraries/Image/RCTImageView.mm
0.72 stable version of #1996 
Cherry pick of a339db765bf7f51365ef9a2f43863acf1ccb2317 & 005fe1be1230792411310f79459a69be9d14573c
=> [0.72-stable] Fix imageview tintcolor

change/@react-native-mac-virtualized-lists-ff168bbc-375a-451a-859e-a599045a960a.json, packages/virtualized-lists/package.json
Since 0.73-stable now depends on a specific version of virtualized-lists, we need to publish said version from the main branch.
The latest version that we're requesting is 0.73.3. We set the patch version to 1 less than what we want because beachball will increment the patch number.
[INTERNAL] [CHANGED] - Bump virtualized-lists to 0.73.3
No functional changes.
=> Force publish virtualized lists 73.3

.ado/publish.yml, packages/community-cli-plugin/package.json
Our CI was not properly running `beachball publish`. I traced this to two issues:
1) We weren't actually passing in the NPM auth token to beachball. This seems to be a typo from an [earlier PR](https://github.com/microsoft/react-native-macos/pull/1963/) refactoring the publish yml. 
2) One of the packages we inherit from upstream (`@react-native/community-cli-plugin`) was trying to get published. This was probably introduced / added in a merge, and we didn't add the `beachball : { shouldPublish: false }` section to our package.json to account. Let's just fix that
[INTERNAL] [FIXED] - Fix beachball publish
=> [CI] Fix beachball publish

change/@react-native-mac-virtualized-lists-ff168bbc-375a-451a-859e-a599045a960a.json, packages/virtualized-lists/package.json, scripts/npm-utils.js
This PR fixes two followup issues uncovered on our publish pipeline:
1) `@react-native-mac/virtualized-lists v0.73.3` got published to NPM, but the followup git commit to delete the change file and bump versions never happened. Let's manually sync by doing both.
2) In `0.73-stable`, some of the upstream NPM publish scripts got refactored that removed some of our diffs to not use the `process.env.CIRCLE_TAG` variable. Let's just bring back our diff to use the `package.json` version instead of relying on a CircleCI environment variable.
[INTERNAL] [FIXED] - Fix more CI issues
=> [CI] Fix more CI issues

packages/community-cli-plugin/package.json, packages/virtualized-lists/package.json, scripts/npm-utils.js
Pick #2002 and #2003 into `0.73-stable`, to unblock the publish pipeline
=> [CI] Pick fixes from main

packages/react-native/third-party-podspecs/boost.podspec
Workaround for https://github.com/facebook/react-native/issues/42180
=> Download boost from `archives.boost.io`

packages/react-native/third-party-podspecs/boost.podspec
Workaround for https://github.com/facebook/react-native/issues/42180
=> [0.73] Download boost from `archives.boost.io`

packages/react-native/third-party-podspecs/boost.podspec
Workaround for https://github.com/facebook/react-native/issues/42180
=> [0.72] Download boost from `archives.boost.io`

.ado/templates/apple-job-publish.yml, scripts/npm-utils.js
The "Javascript PR" CI checks were failing, because the jest tests would call an RNM-only JS function `getPkgJsonVersion`, which used some NodeJS built in modules like `path` and `fs`.  Apparently, such modules need to be mocked out in `jest`. Rather than write the appropriate mocks (and further our diffs from upstream), let's instead retactor away the use of that extra JS function.
Upstream, the CircleCI publish job is triggered by a new tag getting pushed to the React Native repo. The tag would set the environment variable `CIRCLE_TAG`, and run the steps and scripts needed to publish a new React Native NPM package. The script `publish-npm.js` would reference this environment variable to find out the version to publish. In React Native macOS, because nothing set `CIRCLE_TAG`, we instead …
=> [CI] Set and use `CIRCLE_TAG` in Azure pipelines publish job

.ado/templates/apple-job-publish.yml, scripts/npm-utils.js
Backport of #2021 to `0.73-stable`
=> [0.73][CI] Set and use `CIRCLE_TAG` in Azure pipelines publish job

packages/react-native/local-cli/generator-macos/templates/macos/Podfile
Closes #2015 
As of https://github.com/facebook/react-native/commit/0ab8b40fd64ad86b4598293faa0b77e71fc9d349 we no longer need the post_install script `__apply_Xcode_12_5_M1_post_install_workaround`. However, we forgot to remove it from the template app that ships with `0.73`. Let's remove it.
=> [0.73] Remove Xcode 12.5 workaround from template app

.ado/templates/apple-job-publish.yml
Fix a nit from #2021 - we were printing a variable before using it.
[INTERNAL] [CHANGED] - Only echo `RNM_PACKAGE_VERSION` after it has been set
CI should pass
=> [CI] Only echo `RNM_PACKAGE_VERSION` after it has been set

packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/rn-tester/Podfile.lock
React Native macOS 0.73.3 is published in CI, but our local repo only has 0.73.2, presumably because of a CI pipeline issue. Let's realign and fix by running `node scripts/prepare-package-for-release -d -v 0.73.3` and committing the result.
=> [0.73] Align Github version number with NPM package

packages/react-native/Libraries/PushNotificationIOS/NativePushNotificationManagerIOS.js, packages/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.h, packages/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.mm, packages/rn-tester/RNTester/AppDelegate.mm
This change is part of a series of cherry-picks intended to bring visionOS support to React Native macOS. Thes
Prior to these commits, `RCTPushNotificationManager used [UILocalNotification](https://developer.apple.com/documentation/uikit/uilocalnotification) on iOS, and we ifdef'ed macOS to use to use [NSUserNotification](https://developer.apple.com/documentation/foundation/nsusernotification). Both are deprecated and replaced with the cross-apple-platform [UNNotification](https://developer.apple.com/documentation/usernotifications/unnotification) API. Let's cherry pick these changes to make adding visionOS support easier.
Notably excluded from these PRs was properly supporting remote notification on macOS. I didn't see an obvious equivalent for that, and I don't think we supported it …
=> [Cherry Pick] Refactor RCTPushNotificationManager to use `UNNotification`

packages/react-native/Libraries/Text/Text/RCTTextView.mm, packages/react-native/React/Base/RCTUtils.m, packages/react-native/React/CoreModules/RCTAlertController.mm, packages/react-native/React/CoreModules/RCTDevLoadingView.mm, packages/react-native/React/Fabric/Mounting/ComponentViews/Text/RCTParagraphComponentView.mm, packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/UIUtils/RCTUIUtils.m, packages/react-native/React/Views/RCTViewManager.m, packages/rn-tester/RCTTest/FBSnapshotTestCase/FBSnapshotTestController.m, packages/rn-tester/RCTTest/FBSnapshotTestCase/UIImage+Compare.m
Cherry pick several commits that will help make adding visionOS support easier. These will be back ported to `0.73-stable` and `0.72-stable`.
Specific commits:
- https://github.com/facebook/react-native/commit/e08a1973f67d85acc157111c749c43572469e4c2 Refactors deprecated uses of `UIMenuController` which is no longer available on visionOS
- https://github.com/facebook/react-native/commit/ace81ff7d81b2eb547ad93b8000c5906dfefd9d3 Removes `[UIScreen mainScreen]` usage
- https://github.com/facebook/react-native/commit/88e39136037ac338179579e6c48504c068a6618b Removes more `[UIScreen mainScreen]` usage
- https://github.com/facebook/react-native/commit/90fb73e83caf087659b6b3173edd457b4f1d1987 Optimise a call to `RCTKeyWindow`
- https://github.com/facebook/react-native/commit/782e9eace974baefba7d89 …
=> [Cherry Pick] Remove some usages of APIs deprecated in iOS & removed in visionOS

packages/react-native/Libraries/Text/Text/RCTTextView.mm, packages/react-native/React/Base/RCTUtils.m, packages/react-native/React/CoreModules/RCTAlertController.mm, packages/react-native/React/CoreModules/RCTDevLoadingView.mm, packages/react-native/React/Fabric/Mounting/ComponentViews/Text/RCTParagraphComponentView.mm, packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/UIUtils/RCTUIUtils.m, packages/react-native/React/Views/RCTViewManager.m, packages/rn-tester/RCTTest/FBSnapshotTestCase/FBSnapshotTestController.m, packages/rn-tester/RCTTest/FBSnapshotTestCase/UIImage+Compare.m
Backport of #2034 to `0.73-stable`
=> [0.73][Cherry Pick] Remove some usages of APIs deprecated in iOS & removed in visionOS

packages/react-native/Libraries/Text/Text/RCTTextView.m, packages/react-native/React/Base/RCTUtils.m, packages/react-native/React/CoreModules/RCTAlertController.m, packages/react-native/React/CoreModules/RCTDevLoadingView.mm, packages/react-native/React/Fabric/Mounting/ComponentViews/Text/RCTParagraphComponentView.mm, packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/UIUtils/RCTUIUtils.m, packages/react-native/React/Views/RCTViewManager.m, packages/rn-tester/RCTTest/FBSnapshotTestCase/FBSnapshotTestController.m, packages/rn-tester/RCTTest/FBSnapshotTestCase/UIImage+Compare.m
Backport of #2034 to `0.72-stable`. Notably different for this branch is that we're missing https://github.com/facebook/react-native/commit/42d67452eb9a507651078882d00df44dd6720049 , so instead of updating `RCTAlertController.mm`, we are updating `RCTAlertController.m`
=> [0.72][Cherry Pick] Remove some usages of APIs deprecated in iOS & removed in visionOS

packages/react-native/sdks/hermes-engine/hermes-engine.podspec, packages/react-native/sdks/hermes-engine/hermes-utils.rb
The hermes script ([hermes-utils.rb](https://github.com/microsoft/react-native-macos/compare/main...gabrieldonadel:fix-hermes-version-mismatch?expand=1#diff-ff9ad29b570f869cc7f919efbe9d306bd5f90e8fa17dd6b51f8eb83d15c120e4)) uses the react-native-macos version to check for available hermes artifacts on maven but the problem is that whenever react-native-macos version gets ahead of react-native there are no prebuilds to be found and hermes will try to build from source (which does not work). 
This PR fixes this by checking the latest available patch version for a given version and using that as the hermes-version 
[MACOS] [FIXED] - Fix Hermes version mismatch
Enable hermes on rntester, set react-native package.json version to 0.73.2, run pod install and certify it's downloading the prebuild …
=> [react-native] Fix Hermes version mismatch

packages/react-native/sdks/hermes-engine/hermes-engine.podspec, packages/react-native/sdks/hermes-engine/hermes-utils.rb
Backport of https://github.com/microsoft/react-native-macos/pull/2014 to 0.73-stable
=> [0.73][Cherry Pick] Fix Hermes version mismatch (#2014)

packages/react-native/scripts/cocoapods/utils.rb, packages/react-native/scripts/react_native_pods.rb, packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj
This PR aims to reduce the number of changes needed to add visionOS support, see: https://github.com/microsoft/react-native-macos/pull/2019
Fix two issues:
1. Fix some typos where we were using the iOS deployment target for macOS, and had duplicated the definition of the `min_supported_versions` helper method (😵‍💫)
2. Delete some stale pbxproj entries that don't do anything. These show up every now and then, and I didn't feel it was worth a separate PR to fix up.
[GENERAL] [FIXED] - Fix some typos and merge errors 
=> fix(macOS): Don't use iOS deployment target for macOS

packages/react-native/scripts/cocoapods/utils.rb, packages/react-native/scripts/react_native_pods.rb
Backport of #2042 to `0.73-stable
=> [0.73] fix(macOS): Don't use iOS deployment target for macOS

packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/react-native/template/package.json, packages/rn-tester/Podfile.lock
The last 0.72 publish successfully published to NPM, but failed to push the version bump back to Github. Let's fix that misalignment to fix the publish pipeline.
=> [0.72] Re-align Github and NPM versions

packages/react-native/scripts/cocoapods/__tests__/codegen_utils-test.rb, packages/react-native/scripts/cocoapods/helpers.rb, packages/react-native/scripts/cocoapods/utils.rb, packages/react-native/scripts/react_native_pods.rb
This PR is part of a series of PRs for adding support for visionOS to the repository. See #2019 .
Add the ruby helper methods to add `visionos` to  all of our podspecs. Because RNTester doesn't yet have a scheme targetting visionOS, cocoapods won't generate the extra visionOS targets when we run `pod install`. Therefore, this change should mostly be a no-op. 
[IOS] [CHANGED] - [visionOS] Add min_visionos_version_supported to ruby methods
=> [visionOS] Add min_visionos_version_supported to ruby methods

packages/react-native/scripts/cocoapods/__tests__/codegen_utils-test.rb, packages/react-native/scripts/cocoapods/helpers.rb, packages/react-native/scripts/cocoapods/utils.rb, packages/react-native/scripts/react_native_pods.rb
Backport of #2050 to `0.73-stable`
=> [0.73][visionOS] Add min_visionos_version_supported to ruby methods

packages/react-native/scripts/cocoapods/__tests__/codegen_utils-test.rb, packages/react-native/scripts/cocoapods/helpers.rb, packages/react-native/scripts/cocoapods/utils.rb, packages/react-native/scripts/react_native_pods.rb
Backport of #2050 to `0.72-stable`
=> [0.72][visionOS] Add min_visionos_version_supported to ruby methods

packages/react-native/scripts/react_native_pods.rb, packages/react-native/third-party-podspecs/SocketRocket.podspec
This PR is part of a series of PRs for adding support for visionOS to the repository. See #2019 .
The way cocoapods works, the platforms a pod targets must be specified in its' pod spec, otherwise the generated Xcodeproj target won't output that platform's static library. AKA, if Pod A targets `{:iOS => 13.4, :osx => 10.15}`, then  targets that output `libA-iOS.a` and `libA-macOS.a` will be generated, but not targets that output `libA-visionOS.a`.  For most pod dependencies of react native, we set the platforms using `min_supported_versions` helper method, which we can override to return as many platforms as we want. However, there are a few pods where we don't control the podspec because we're getting it from the cocoapods registry. Without updating the pod in its own repo, we wouldn't …
=> [visionOS] Add local podspecs to override supported platforms

packages/react-native/ReactAndroid/src/main/jni/third-party/fmt/CMakeLists.txt, packages/react-native/ReactCommon/React-Fabric.podspec, packages/react-native/ReactCommon/ReactCommon.podspec, packages/react-native/ReactCommon/cxxreact/React-cxxreact.podspec, packages/react-native/ReactCommon/hermes/React-hermes.podspec, packages/react-native/ReactCommon/jsi/React-jsi.podspec, packages/react-native/ReactCommon/jsiexecutor/React-jsiexecutor.podspec, packages/react-native/scripts/react_native_pods.rb, packages/react-native/third-party-podspecs/RCT-Folly.podspec, packages/react-native/third-party-podspecs/SocketRocket.podspec, packages/react-native/third-party-podspecs/fmt.podspec, packages/rn-tester/Podfile.lock, packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj
Backport of #2047 to 0.72-stable. This PR also cherry-picks https://github.com/facebook/react-native/commit/bb9ed0e9061288e56796fe6fe6a69541c3e09c90 to override `fmt` and then downgrades `fmt` to `6.2.1`, the version that was already used on this branch.
=> [0.72][visionOS] Add local podspecs to override supported platforms

packages/react-native-macos-init/src/cli.ts
Recently in React Native Community CLI we added bumping Yarn version in every new project created to Yarn v3 ([PR](https://github.com/react-native-community/cli/pull/2134) for more context). And In Yarn v3 flag `-s` doesn't exists anymore, so the `react-native-macos-init` tool won't work.  
I've replaced usage of `-s` with `--silent` flag. Also this change is backward compatible, since Yarn v1 support `--silent` flag. 
[GENERAL] [FIXED] - Initialising `react-native-macos` in project using Yarn v3 with `react-native-macos-init`
1. Create new project with `npx react-native@latest init` and bump Yarn version to 3 (we didn't released changes with bumping version by default yet.
2. Try running `react-native-macos-init`
=> fix(cli): initialising in projects using Yarn v3

packages/react-native/Libraries/Text/React-RCTText.podspec, packages/react-native/React/CoreModules/RCTDeviceInfo.mm
Some followup fixes to #2019 :
- Exclude `RCTUISecureTextField` from visionOS. This is a macOS specific file
- Fix a mismatching ifdef, where some code inside `#if !TARGET_OS_OSX` called code only defined in `#if TARGET_OS_IOS`. This is not needed to be back ported to 0.73 and 0.72 as their corresponding PRs already had this fix.
CI should pass
=> [visionOS] Followup fixes

packages/rn-tester/package.json, yarn.lock
After #2030 landed, running `yarn start` (an alias of `react-native start`)  in `packages/rn-tester` leads to this error:
> command not found: react-native
This seems to be because Yarn 4 is much stricter about only using declared dependencies as compared to Yarn 1, and RNTester's package.json only specifies react-native as a peer dependency (a `"*"` at that!):
```
...
"peerDependencies": {
"react": "18.2.0",
"react-native": "*"
},
...
``` 
What we want is tell RNTester ( a private package that will never be published) to use the workspace copy of react-native, rather than download from NPM. Luckily, modern package managers have the `workspace:*` syntax for exactly that! Let's update our package.json. I also had to specify `react-native-macos` as the dependency instead of react-native. …
=> [RNTester] Correctly specify React Native dependency

packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld.xcodeproj/project.pbxproj
As of Expo SDK50 it's possible to use Expo modules in `react-native-macos` projects. During `pod install` and a build phase script, `expo-modules-autolinking` generates a Swift file called `ExpoModulesProvider.swift` and adds it programmatically to the pbxproj using CocoaPods tooling.
The problem is that the template project doesn't have `SWIFT_VERSION` build setting, which causes the below error when building:
> Value for SWIFT_VERSION cannot be empty.
If we manually add a Swift file through Xcode, it automatically adds `SWIFT_VERSION`, `SWIFT_OPTIMIZATION_LEVEL` and `CLANG_ENABLE_MODULES` build settings to the target. These settings are already present in the target for iOS.
To made these changes, I simply manually added a dummy Swift file to the HelloWorld project and let Xcode update …
=> Set build settings required for Swift in the template project

packages/react-native/local-cli/runMacOS/runMacOS.js
In future we would like to replace custom implementation of `run-macos` with the one that is inside created [`cli-platform-app`](https://github.com/react-native-community/cli/tree/main/packages/cli-platform-apple) package inside https://github.com/react-native-community/cli. To unify implementations between all Apple's OOT platforms.  To avoid creating _many_ breaking changes I'm deprecating old options that are under different name in new implementation. 
[GENERAL] [DEPRECATED] - Deprecate `--configuration` option from `run-macos` command.
1. Setup CLI locally.
2. Run `run-macos --configuration` -> you should see the warning.
3. Run `run-macos --project-path` -> you should also see the warning.
=> chore(cli): deprecate `--configuration` option in `run-macos` 

packages/react-native/Libraries/Image/React-RCTImage.podspec
While working on https://github.com/microsoft/react-native-test-app/pull/1803 , I ran into this issue where we don't link the system framework `accelerate` on visionOS. Let's make that fix.
[VISIONOS [FIXED] - Link Accelerate Framework on visionOS
CI should pass. Local build of visionOS (since that's not on CI yet) should also pass.
=> [visionOS] Link Accelerate Framework on visionOS

packages/react-native/Libraries/Image/React-RCTImage.podspec
Backport of #2072 to 0.73-stable
=> [0.73][visionOS] Link Accelerate Framework on visionOS

packages/react-native/Libraries/Image/React-RCTImage.podspec
Backport of #2072 to 0.72-stable
=> [0.72][visionOS] Link Accelerate Framework on visionOS (#2072)

packages/react-native/Libraries/Utilities/Platform.android.js, packages/react-native/Libraries/Utilities/Platform.d.ts, packages/react-native/Libraries/Utilities/Platform.flow.js, packages/react-native/Libraries/Utilities/Platform.ios.js, packages/react-native/Libraries/Utilities/Platform.macos.js, packages/react-native/React/CoreModules/RCTPlatform.mm
Cherry pick a couple of changes to introduce the `isVision` API so that we can write visionOS specific JS. This is a cherry pick of two commits already upstream, plus an extra one to add the method to `Platform.macos.js`,
[VISIONOS] [ADDED] - Implement isVision interfaceIdiom
CI should pass
=> [visionOS] Implement isVision interfaceIdiom

packages/react-native/Libraries/Utilities/Platform.android.js, packages/react-native/Libraries/Utilities/Platform.d.ts, packages/react-native/Libraries/Utilities/Platform.flow.js, packages/react-native/Libraries/Utilities/Platform.ios.js, packages/react-native/Libraries/Utilities/Platform.macos.js, packages/react-native/React/CoreModules/RCTPlatform.mm
Backport of #2077 to 0.73-stable
=> [0.73][visionOS] Implement isVision interfaceIdiom 

packages/react-native/Libraries/Utilities/Platform.android.js, packages/react-native/Libraries/Utilities/Platform.d.ts, packages/react-native/Libraries/Utilities/Platform.ios.js, packages/react-native/Libraries/Utilities/Platform.macos.js, packages/react-native/React/CoreModules/RCTPlatform.mm
Backport of #2077 to 0.72-stable
=> [0.72][visionOS] Implement isVision interfaceIdiom 

packages/react-native/React/Views/ScrollView/RCTScrollViewManager.m
Backport of #2091 to 0.73-stable
=> [0.73][visionOS] Bring back missing ScrollView prop converters

packages/react-native/React/Views/ScrollView/RCTScrollViewManager.m
Backport of #2091 to 0.72-stable
=> [0.72][visionOS] Bring back missing ScrollView prop converters

packages/react-native/React/Base/RCTBridgeModule.h
Backport of #2096 to 0.73-stable
=> [0.73] Remove dangling semicolons from RCT macros

packages/react-native/React/Base/RCTBridgeModule.h
back port of #2096 to 0.72-stable
=> [0.72] Remove dangling semicolons from RCT macros

packages/react-native/React/Base/RCTBridgeModule.h
Internally, we enabled `-Wsemicolon-before-method-body` which exposed that React Native has a dangling semicolon after some of its macros. This leads to a bunch of code that looks like this to suppress the warning:
```objective-c
// ADO ~~: RCT macros have bad semicolons
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wsemicolon-before-method-body"
RCT_EXPORT_METHOD(logError
: (NSString *)error)
#pragma clang diagnostic pop
{
```
This is fixed upstream with https://github.com/facebook/react-native/commit/cf4963feb3acd22755e768bc22c20e3136049999 . Let's pick part of the fix so we can remove  the macro supression internally. 
CI should pass
=> Remove dangling semicolons from RCT macros

packages/react-native/React/Base/RCTConvert.h, packages/react-native/React/Base/RCTConvert.m, packages/react-native/React/Views/RCTView.m, packages/react-native/React/Views/RCTViewManager.m
main targeted PR of #2100 
Prior to 0.73, the new `role` prop was remapped to `accessibilityRole` on the JS-side.  Starting with #37304, the work needs to be completed on the native side.  Since the new prop is ARIA inspired, the mappings are taking from the [ARIA Core AAM](https://www.w3.org/TR/core-aam-1.2/#mapping_role_table) which disagrees with some of the mappings used in the old `accessibilityRole` prop.  Users of the old prop are unaffected, but the new prop will take the mappings from the spec.
Tested a variety of permutations of accessibilityRole and role to confirm the behavior looks correct in Accessibility Inspector
=> Fix new role prop after JS-Shim was removed by Meta

packages/react-native/React/Views/RCTView.m, packages/react-native/React/Views/UIView+React.h, packages/react-native/React/Views/UIView+React.m
=> [0.73-stable] Fix `transform` prop on `View` component

packages/react-native/Libraries/Text/TextInput/RCTBaseTextInputView.mm
Right now, the ghost text feature is quite incompatible with undo/redo support. Since we weren't filtering out ghost text from a text input's contents when registering undoable actions, we were susceptible to a bunch of weird side effects, such as ghost text becoming editable or even crashes.
The fix here is to make sure any undoable actions ignore ghost text. Ghost text is very transient and is designed to disappear as soon as you make any sort of change, so the easiest way to do this is to just remove it directly before doing anything.
A related issue pops up where a write to `setAttributedText:` also triggers a call to set the ghost text to `nil`. Since `setAttributedText:` already gets rid of the ghost text when we ask it to, the subsequent call to `setGhostText:` may not need any …
=> Ensure ghost text doesn't appear when performing undos

packages/react-native/React/Base/RCTTouchHandler.m
Fix for issue #2111 (NSTabView doesn't send mouseUp event because it doesn't inherit from NSControl).
NSTabView inherits from NSView, not NSControl, so its click events aren't recorded in the _nativeTouches cache leading to mouseUp and mouseDown not firing consistently when clicking on the tab buttons.
Code for custom TabView component provided in the linked issue.
=> Send mouseUp events for NSTabView

packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
We have a crash internally due to the following error:
> uncaught ObjC exception, reason: -[RCTUITextField selectedRange]: unrecognized selector sent to instance 0x347fc2d70
This reproes when you move focus programmatically (I.E: through JS with `ref.current.focus()`) to a TextInput with 2-Set Korean text already typed. For some reason, that exact code path means that Appkit calls the selector on our TextInput (backed by RCTUITextField in natively) and we crash on the uncaught exception. 
Fix is to implement the selector. 
CI should pass. Locally, no longer get an `unrecognized selector` exception.
=> Implement `[RCTUITextField selectedRange]`

packages/react-native/React/CoreModules/RCTAlertController.mm, packages/react-native/React/CoreModules/RCTAppearance.mm
Cherry pick https://github.com/facebook/react-native/commit/d00d35e8723293b0c1e098fa2e02756884a0f7f9 to fix a bug we're seeing internally
CI should pass
=> [CherryPick] Fix retrieving current appearance in multi-window apps

packages/react-native/React/CoreModules/RCTDeviceInfo.mm
Pick up https://github.com/facebook/react-native/commit/44159e35ce21910a7c1f0f66807f43512b442b3c#diff-4608929083e7d44679638b322e0f5297664b0106fd1ddaf39a3039af0fd3e89f from upstream to fix a potential hang we're seeing internally.
CI should pass
=> [0.73][Hotfix] Pick up RCTDeviceInfo fix from upstream

packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/Views/RCTView.h, packages/react-native/React/Views/RCTView.m
=> [0.73-stable] New events for RCTUIView

packages/react-native/Libraries/Text/Text/RCTTextView.h, packages/react-native/Libraries/Text/Text/RCTTextView.mm
See primary PR https://github.com/microsoft/react-native-macos/pull/2140
Add a function to return the bounding rect of a character range in the string hosted by RCTTextView. Having such a function will enable referencing nested text runs for relative positioning of transient UI: callouts, tooltips, etc.
=> Backport getRectForCharRange to 0.73-stable

packages/react-native/Libraries/Text/Text/RCTTextShadowView.mm, packages/react-native/Libraries/Text/Text/RCTTextView.h, packages/react-native/Libraries/Text/Text/RCTTextView.mm, packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/Views/RCTShadowView.h, packages/react-native/React/Views/RCTShadowView.m, packages/react-native/React/Views/RCTView.m
We have a feature request to allow mouse hover events for subelements inside a `Text` element. This builds off #2137 to get things all set.
For now we're only pushing this into 0.73-stable because we want to take more time to consider the native-side architecture for 0.74 onwards.
One slight drawback is that this only works completely properly when there is only one level of onMouseEnter events underneath the main box. For example, if we move the mouse from red to blue in the below example, we see a "leave red" event immediately before an "enter blue" event. The reason for this is that at the native level, all `RCTVirtualTextView`s that represent internal `Text` nodes are direct children of the parent `RCTTextView` instead of directly reflecting the DOM hierarchy. This can potentially be …
=> [0.73-stable] Add mouse hover events to `RCTTextView`

packages/react-native/Libraries/Text/Text.d.ts, packages/react-native/Libraries/Text/Text/RCTTextShadowView.mm, packages/react-native/Libraries/Text/Text/RCTTextView.h, packages/react-native/Libraries/Text/Text/RCTTextView.mm, packages/react-native/Libraries/Text/TextProps.js, packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/Views/RCTShadowView.h, packages/react-native/React/Views/RCTShadowView.m, packages/react-native/React/Views/RCTView.h, packages/react-native/React/Views/RCTView.m, packages/rn-tester/js/examples/Text/TextExample.ios.js
This mainly brings over #2137 and #2143 from 0.73-stable into the main branch. We also add an example in RNTester and do some housekeeping on our TypeScript types.
Commit descriptions:
* Move various Mac-specific props from `RCTView` to its parent class `RCTUIView`. Theoretically these can be used for any sort of view, not just `<View>`. They're still "opt-in" from the JS side, so there won't be any side effects for other views that don't care about these properties.
* Hooks up `onMouseEnter` and `onMouseLeave` to `<Text>` views.
Validated the new test case in RNTester as well as in other external test apps.
=> Add onMouseEnter and onMouseLeave to Text (cherry-picked from 0.73-stable)

packages/react-native/React/Base/RCTRootView.h, packages/react-native/React/Base/RCTRootView.m, packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/CoreModules/RCTDevLoadingView.mm, packages/react-native/React/CoreModules/RCTLogBox.mm, packages/react-native/React/CoreModules/RCTLogBoxView.h, packages/react-native/React/CoreModules/RCTLogBoxView.mm, packages/react-native/React/CoreModules/RCTRedBox.mm, packages/react-native/React/Modules/RCTRedBoxExtraDataViewController.h, packages/react-native/React/Modules/RCTRedBoxExtraDataViewController.m, packages/rn-tester/Podfile.lock
Upstream in React Native 0.74, RCTRedbox got heavily rewritten (see https://github.com/facebook/react-native/commit/e2eb26c951c3d2a0a4721428d00ffc02b501ecfa and https://github.com/facebook/react-native/commit/b311c3e0a00bf8051194bbb5072a9341cf3f6e10) . As such, we needed to update our macOS implementation. This proved to be quite difficult, as NSTableView is quite... obtuse. Many thanks to @falselobster for doing much of that part of the rewrite. I am cherry picking the rewrite commits here so we can reduce churn on the larger "0.74 merge" PR.
While we are touching this code, I realized that a natural presentation pattern for the red box would be to use a [sheet](https://developer.apple.com/design/human-interface-guidelines/sheets). In fact, that would also apply to RCTDevLoadingView …
=> Refactor Redbox, Logbox, and DevLoadingView as Sheets

.ado/publish.yml, change/@react-native-mac-virtualized-lists-d397b7c8-5ac3-4deb-8d0f-58f565bd418f.json, packages/react-native/package.json, packages/virtualized-lists/package.json, yarn.lock
To publish React Native macOS 0.74, we need to publish `@react-native-mac/virtualized-lists` first. This change prepares us to do by doing the following:
- Updates our pipeline to allow the beachball publish job to run from non-main branches (like 0.74-stable)
- Lowers virtualized-lists by a patch version
- Adds a change file for virtualized-lists. This will add back the patch version. I also took care to make sure this doesn't cause a dependent patbumph to React Native macOS.
Manually ran `npx beachball publish` to see what the change would be, and it looked right.
=> [0.74] Publish virtualized-lists in preparation for 0.74 release

packages/react-native/local-cli/generator-macos/templates/macos/Podfile
Flipper is dropped in react-native 0.74, however react-native-macos's Podfile used in the default template still reference it, causing error when running `pod install`.
=> Remove Flipper references from Podfile template

packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
While working on #2159, I noticed that a single-line `<TextInput>` with a placeholder causes spurious `onBlur` and `onEndEditing` events. For some strange reason, setting `placeholderAttributedString` on macOS causes the `NSTextDelegate` to call `textDidEndEditing`. This PR blocks these events from reaching the JS side.
Validated in RNTester that `onBlur` and `onEndEditing` don't get called unexpectedly when dealing with a `<TextInput>` with placeholder text.
=> Prevent spurious onBlur/onEndEditing events in `<TextInput>` elements with placeholder text

packages/react-native/Libraries/Text/TextInput/RCTBaseTextInputView.mm, packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
0.74-stable port of #2159 and #2160.
=> [0.74-stable] Make TextInput events more reliable (#2159 + #2160)

README.md, packages/react-native/Libraries/Text/RCTTextAttributes.mm, packages/react-native/Libraries/Text/TextInput/RCTBaseTextInputView.mm, packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm, packages/react-native/React/Base/RCTConvert.mm, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextPrimitivesConversions.h, packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld.xcodeproj/project.pbxproj, packages/react-native/local-cli/generator-macos/templates/macos/Podfile, packages/react-native/scripts/cocoapods/__tests__/codegen_utils-test.rb, packages/react-native/scripts/cocoapods/helpers.rb, packages/rn-tester/Podfile.lock
Bump the minimum macOS requirement to 11.0. This aligns closer to our internal company organization policy of only supporting N-2 releases for macOS. We are still supporting N-3 here, but I figured let's bump one version at a time.  
Ci should pass
=> Bump minimum macOS requirement to 11.0

.ado/publish.yml
I missed a line to remove a check to let beachball publish run on stable branches. We previously did the same change in `0.74-stable` with https://github.com/microsoft/react-native-macos/pull/2158
=> [0.75] Let beachball publish run on stable branches

.ado/publish.yml, packages/react-native/package.json, yarn.lock
Uncomment the bit of the publish job that will start publishing on the 0.75-stable branch
CI should pass
=> [0.75] Publish React Native macOS 0.75.0

.ado/publish.yml, .ado/templates/apple-steps-publish.yml
We forgot to port some changes from https://github.com/microsoft/react-native-macos/commit/98dc782254a1a9b10b9c803e796453ed63601635 to `0.75-stable` which caused the publish pipeline to fail. Let's do that now. I also prepared #2180 to make sure the changes are in the main branch too. 
=> [0.75] Publish React Native macOS 0.75.0 (Take 2)

.ado/publish.yml, .ado/templates/apple-steps-publish.yml
We made a couple of fixes to the `0.74-stable` and `0.75-stable` branches that we should bring to our main branch, so `0.76-stable` and onwards get them. Namely:
1. Move the `latestStableBranch` variable out of the pipeline config and into YAML. Due to recent security measures, it is much harder to edit the pipeline config, so this should help maintainability. The downside is we have to remember to set this on multiple branches now every time we cut a release.
2. Use the correct script to set the React Native version across the templated files every release
3. Let the beachball publish job run on stable branches, so that virtualized-lists can publish. 
CI should pass
=> fix: Port publish pipeline changes from 0.74 and 0.75 stable branches

packages/react-native/package.json
`local-cli` is missing in published packages, making `run-macos` unavailable:
```
% yarn react-native run-macos
error: unknown command 'run-macos'
(Did you mean run-ios?)
```
This needs to be cherry-picked to [0.75-stable](https://github.com/microsoft/react-native-macos/tree/0.75-stable)
n/a
=> fix: `local-cli` is missing from published package

packages/react-native/package.json
Cherry pick #2182 to `0.75-stable`
=> [0.75] fix: local-cli is missing from published package

change/react-native-macos-init-27af1077-e8dd-498f-9813-622bd400487c.json
Let's try to publish a new version of react-native-macos-init, to pick up https://github.com/microsoft/react-native-macos/commit/b15e16827f5cfc2afb46bfe0d6d95f77ca7f4d9e
=> [react-native-macos-init] Push change files for a new version

change/react-native-macos-init-f8ea158b-582a-420c-8fb7-8a1f75eb2cbe.json, packages/react-native-macos-init/src/cli.ts
Back in #1754 , we switched `react-native-macos-init` from using `npm-registry` to `npm-registry-fetch`. But we never replaced the import.. so let's fix that now. 
Tested using `yarn link` with a newly initialized project, and got it to work.
=> fix: Properly import `npm-registry-fetch` in `react-native-macos-init`

packages/react-native-macos-init/package.json
Fix a version mismatch from a previous failed beachball publish.
=> Sync `react-native-macos-init` vesrion with NPM registry using beachball

packages/react-native/local-cli/generator-macos/templates/macos/Podfile
When building a new project with React Native MacOS, it would fail with this error:
```
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: uninitialized constant Pod::Podfile::FlipperConfiguration.
>      :flipper_configuration => FlipperConfiguration.disabled,
```
As, for example, here: https://github.com/microsoft/react-native-macos/issues/2164
The ongoing solution was to remove that line from the Podfile, I'm sending this PR to edit the template so that line is removed by default.
I'm probably going to need some help here, not quite sure how I can create a project against my local version of react-native-macos to test this one, but I'm sure that with this line removed (and as many other issues point) the …
=> fix: Remove flipper config from the Podfile template

packages/react-native/local-cli/generator-macos/templates/macos/Podfile
We've discussed this on #2195, this is for the `0.75` version
When building a new project with React Native MacOS, it would fail with this error:
```
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: uninitialized constant Pod::Podfile::FlipperConfiguration.
>      :flipper_configuration => FlipperConfiguration.disabled,
```
As, for example, here: https://github.com/microsoft/react-native-macos/issues/2164
The ongoing solution was to remove that line from the Podfile, I'm sending this PR to edit the template so that line is removed by default.
I'm probably going to need some help here, not quite sure how I can create a project against my local version of react-native-macos to test this one, but I'm sure …
=> [0.75] fix(): Remove flipper config from the Podfile template

packages/react-native/React/Views/RCTShadowView.h, packages/react-native/React/Views/RCTViewManager.h
In React Native macOS, we have two "shim" classes to help make the iOS codebase of React Native compatible with macOS
- `RCTPlatformView`:a typedef of `NSView` on macOS, and `UIView` on iOS / visionOS)
- `RCTUIView`: A subclass of `NSView` with extra methods and properties to be closer to the iOS `UIView`
Additionally, in React Native's old architecture, there is this line that we forked as follows in 0.73 and earlier versions:
React Native:
>typedef void (^RCTViewManagerUIBlock)(RCTUIManager *uiManager, NSDictionary<NSNumber *, **UIView** *> *viewRegistry);
React Native macOS:
> typedef void (^RCTViewManagerUIBlock)(RCTUIManager *uiManager, NSDictionary<NSNumber *,
**RCTUIView***> *viewRegistry); // [macOS]`
In React Native macOS 0.74+, I changed the definition as follows, thinking the …
=> fix: Allow viewRegistry to accept subclasses of NSView

packages/react-native/React/Views/RCTShadowView.h, packages/react-native/React/Views/RCTViewManager.h
Backport of #2196 to `0.75-stable`
=> [0.75] fix: Allow viewRegistry to accept subclasses of NSView

packages/react-native/React/Views/RCTShadowView.h, packages/react-native/React/Views/RCTViewManager.h
Backport of #2196 to `0.74-stable`
=> [0.74] fix: Allow viewRegistry to accept subclasses of NSView

packages/react-native/React/CoreModules/RCTDevLoadingView.mm
Fixes #2183 
This PR fixes two issues with RCTDevLoadingView:
- In the macOS implementation of `RCTDevLoadingView`, we forgot to do some cleanup of instance variables on `hide`, which was causing the loading view to stick around. 
- The NSWindow that RCTDevLoadingView used would return false for `canBecomeKeyWindow`. Somewhere internal to Appkit, `makeKeyWindow` was called, would fail, and produce a warning in the Xcode console. By making the window an [NSPanel](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/WinPanel/Concepts/UsingPanels.html#//apple_ref/doc/uid/20000224) instead, we can avoid this issue.
Loaded RNTester a couple of times and didn't observe an issue with the loading view sticking around.
=> fix: Properly clean up RCTDevLoadingView on hide

packages/react-native/React/CoreModules/RCTDevLoadingView.mm
Port https://github.com/microsoft/react-native-macos/pull/2201 to 0.74-stable
=> [0.74] fix: Properly clean up RCTDevLoadingView on hide

.ado/jobs/build-test-rntester.yml
Due to https://github.com/actions/runner-images/issues/10559 , we need to manually download the visionOS SDK on appropriate jobs. 
CI should pass
=> fix(CI): Download visionOS if necessary

.ado/jobs/build-test-rntester.yml
Backport of #2204 to `0.75-stable`
=> [0.75] fix(CI): Download visionOS if necessary

.ado/jobs/build-test-rntester.yml
Backport of #2204 to `0.74-stable`
=> [0.74] fix(CI): Download visionOS if necessary

packages/react-native/React/CoreModules/RCTDevLoadingView.mm
This is attempt #2 to fix issues with the [refactor of RCTDevLoadingView](#2151 ) , the first being #2201 . Namely, the RCTDevLoadingView sheet doesn't always dismiss, and sticks around blocking the app. 
This PR addresses two main things:
1. React Native seems to not balance its' own calls to `[RCTDevLoadingView showMessage]` and `[RCTDevLoadingView hide]`. As a result, we might end up calling `beginSheet` more times than we call `endSheet`. My theory is we're ending up with multiple sheets/modals, which is why the sheet is sticking around. We can fix this by only calling `beginSheet` if we aren't already presented.
2. Digging around a couple of places in StackOverflow, it seems it's also important to call `[mySheetWindow orderOut:]` I the `beginSheet` completion handler to make the …
=> fix: Properly dismiss RCTDevLoadingView

packages/react-native/React/CoreModules/RCTDevLoadingView.mm
Backport of #2211 to `0.75-stable`
=> [0.75] fix: Properly dismiss RCTDevLoadingView

packages/react-native/React/CoreModules/RCTDevLoadingView.mm
Backport of #2211 to `0.74-stable`
=> [0.74] fix: Properly dismiss RCTDevLoadingView

packages/react-native/Libraries/Image/RCTImageBlurUtils.mm, packages/react-native/Libraries/Image/RCTImageUtils.mm, packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/Views/RCTBorderDrawing.m, packages/rn-tester/RCTTest/FBSnapshotTestCase/UIImage+Diff.m
Related upstream PRs:
- Rename the function `RCTUIGraphicsImageRenderer()` (which conflicts with my shim) upstream to `RCTMakeUIGraphicsImageRenderer()`: https://github.com/facebook/react-native/pull/46772
- Fix backgroundColor not getting retained/released: https://github.com/facebook/react-native/pull/46797
Back in https://github.com/facebook/react-native/commit/d70d7fd0b3984ee54622afc4692a6c945618c345 , React Native switched their usages of `UIGraphicsBeginImageContext()` / `UIGraphicsEndImageContext()` with `UIGraphicsImageRenderer`. There is no macOS equivalent to this class, so we kept maintaining larger ifdefs with our old shims for the deprecated methods. With React Native 0.76+, I'm starting to see more usage of `UIGraphicsImageRenderer` (specifically, to render web-style box …
=> feat(RCTUIKit): Shim RCTUIGraphicsImageRenderer

packages/react-native/Libraries/Text/TextInput/Multiline/RCTUITextView.mm
Consider a hypothetical situation where a multiline TextInput handles (by dequeueing from the event queue) Cmd+Enter. If the focus is on another control that also handles Cmd+Enter, then hitting Cmd+Enter will *not* reach this other control -- in fact it will perform the action for the former TextInput, as if it were focused!
performKeyEquivalent is [documented](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/EventOverview/EventArchitecture/EventArchitecture.html#//apple_ref/doc/uid/10000060i-CH3-SW10) to be called even if a view isn't first responder (this is for example how "Enter" binds to the default button on a dialog -- the default button doesn't need to be focused to respond to Enter), but since we override performKeyEquivalent to properly support certain …
=> Multiline TextInput key handling: add check for first responder

packages/react-native/Libraries/Text/TextInput/Multiline/RCTUITextView.mm
=> [0.74] Multiline TextInput key handling: add check for first responder

packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/Fabric/RCTConversions.h, packages/react-native/React/Views/RCTBorderDrawing.h, packages/react-native/React/Views/RCTBorderDrawing.m, packages/react-native/React/Views/RCTView.m
Cherry pick https://github.com/facebook/react-native/commit/6a09fc09af8eedbf409ab870d5714e44892b2a16 and https://github.com/facebook/react-native/commit/b70709dbc27c75c69e9fd2b082ffa27e7e8db7fd to help prevent invalid memory access crashes with our `RCTUIGraphicsImageRenderer` shim.
As a consequence, we can also remove a diff we had where we had added an extra `scaleFactor` parameter to `RCTGetBorderImage()`, now that the shim doesn't take that argument.
=> cherrypick: Bring changes to improve our RCTUIGraphicsImageRenderer shim 

.ado/jobs/build-test-rntester.yml, .ado/jobs/test-react-native-macos-init.yml, packages/react-native-macos-init/package.json
Fix a couple of issues with the `verify react-native-macos-init` job:
- `react-native-macos-init` is listed as 2.1.1 in our repository, but is 2.1.2 in NPM, which caused failures
- Use RN 0.75 as the template
- Update the scripts to have `set -eox pipefail` for better debugging
- Fix an issue with `yarn install`, presumably due to updating to Yarn 3 
CI should pass
=> fix(CI): Fix `verify react-native-macos-init` job

packages/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegate.h
Avoid UBSAN error for expected behavior in environments where enabled.
=> [RCTBackedTextInputDelegate] Add nullable annotation to method

packages/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegate.h
Avoid UBSAN error for expected behavior in environments where enabled.
=> [0.75] [RCTBackedTextInputDelegate] Add nullable annotation to method

packages/react-native/Libraries/Text/TextInput/RCTBackedTextInputDelegate.h
Avoid UBSAN error for expected behavior in environments where enabled.
=> [0.74] [RCTBackedTextInputDelegate] Add nullable annotation to method

.ado/publish.yml
This PR configures Component Governance to ignore the helloworld package, which is an internal template that is not used.
=> Configure CG to ignore helloworld.

packages/react-native-macos-init/package.json, yarn.lock
This is blocking the 0.76 merge (#2190 ), let's do it ahead of time outside of the merge branch.
=> chore(react-native-macos-init): Update Typescript and just-scripts

packages/react-native/local-cli/runMacOS/runMacOS.js, packages/react-native/react-native.config.js
We should implement the config command (?) first so that the `.xcworkspace` path, scheme, etc. get passed to us via the CLI. But this will at least unblock users who need `build-macos`.
n/a
=> fix(react-native): implement `build-macos` command

packages/react-native/local-cli/runMacOS/runMacOS.js, packages/react-native/react-native.config.js
We should implement the config command (?) first so that the `.xcworkspace` path, scheme, etc. get passed to us via the CLI. But this will at least unblock users who need `build-macos`.
Cherry-picks #2225
n/a
=> fix(react-native): implement `build-macos` command (#2225)

packages/react-native/local-cli/runMacOS/runMacOS.js
`xcodeProject.path` may not always be present
n/a
=> fix(react-native): `xcodeProject.path` may not always be present

packages/react-native-macos-init/package.json, packages/react-native-macos-init/src/cli.ts, packages/react-native-macos-init/tsconfig.json, yarn.lock
Use `@rnx-kit/tsconfig` as base for TypeScript and fix build issues.
n/a
=> chore(init): use a stricter `tsconfig.json`

.ado/jobs/test-react-native-macos-init.yml, .ado/scripts/verdaccio.sh, .ado/templates/verdaccio-publish.yml, .gitignore, packages/react-native-macos-init/src/cli.ts, packages/react-native/local-cli/runMacOS/runMacOS.js
The pipeline wasn't actually publishing anything and we've been testing against latest on npm all this time.
=> ci: fix the `react-native-macos-init` pipeline

.ado/publish.yml
Before we cut `0.76-stable`, let's disable publishing on that branch. 
=> ci: temporarily disable publish pipeline on 0.76-stable

packages/react-native/package.json, packages/virtualized-lists/package.json, yarn.lock
In the most recent 0.76 merge, a dependency cycle was introduced, causing Beachball to throw up. Reverting the change to unblock publishing.
Also removed a `resolutions` section ignored by Yarn.
n/a
=> fix(virtualized-lists): revert dependency change to break cycle

packages/react-native/package.json, packages/virtualized-lists/package.json, yarn.lock
Cherry pick #2244 to `0.76-stable`
CI should pass
=> fix(0.76, virtualized-lists): revert dependency change to break cycle

.ado/publish.yml
Before cutting the `0.76-stable` branch, we made sure to special case it in our publish pipeline to tempoarily disable publishing. Let's remove that special case on main.
=> ci: remove special case for `0.76-stable`

.ado/publish.yml
I noticed we were still using `macOS-13`, which was causing publish to fail. Let's fix that
=> ci: Use the same VM image for PR and publish

.ado/publish.yml, change/@react-native-mac-virtualized-lists-ea506566-9d65-477c-a749-d3252327432b.json, packages/react-native/package.json, packages/virtualized-lists/package.json, yarn.lock
Our publish pipelines are still a mess, in between [beachball](https://microsoft.github.io/beachball/), the custom scripts we inherit from React Native Core, and our own Azure Pipelines publish pipeline. This means that publishing a new minor looks like:
1. Set up  the monorepo packages we fork (only `virtualized-lists` right now) to publish a new `0.N.0` release by downgrading to `0.N-1.99` and adding a change file to publish the new minor. We did this in [0.75 as well](https://github.com/microsoft/react-native-macos/commit/d9e7ee9effbb6914ebddeb019a54c63cfb071540#diff-18bf2abf141c729ca075d35babc61e205e3c8c5d1dbb72130446cc0426e3e0ebR116).
2. Publish the new `react-native-macos` minor afterwards.
This PR does step 1, with step 2 as a followup
CI should pass
=> ci(0.76): prepare to publish @react-native-mac/virtualized-lists version `0.76.0`

.ado/publish.yml, .ado/templates/apple-steps-publish.yml
#2255 removed the `os` key from the YAML, which broke our publish. Also apparently I'm not allowed to use variables. 
Since it's hard to find a suitable macOS image and I probably don't need a macOS image for what is just a JS publish.. let's switch to Ubuntu. Specifically, the same image/pool as the other publish job so we know it will work.
Ran a publish pipeline run on a clone of this branch and it ran successfully.
=> ci: Use Ubuntu for publish job

.ado/publish.yml, .ado/templates/apple-steps-publish.yml, packages/react-native/package.json, yarn.lock
> [!NOTE]  
> Needs #2251 to land first
Publish React Native macOS 0.76.0. This change uses the `-ready` prefix introduced with https://github.com/microsoft/react-native-macos/commit/a4ac549b42bd881afa4e3f1d0f5c7451876d51e7 to try and publish `0.76.0` instead of `0.76.1`
CI should pass
=> ci(0.76): prepare to publish 0.76.0

.ado/templates/apple-steps-publish.yml
https://github.com/facebook/react-native/commit/4a6b889e9343652adebedc075c97463af0f1c1f2 moved the React Native publish scripts to call `set-version` instead of `set-rn-version`. This wasn't reflected in our publish pipeline. 
Theoretically the "NPM Publish Dry Run" job tests this, but it doesn't. So.. I'll need to look into that.
=> fix(0.76, publish): use `set-version` instead of `set-rn-version`

Gemfile.lock, yarn.lock
This PR fixes various CG alerts in main. Specifically, it:
- Updates ws to 6.2.3 and 7.5.10.
- Updates serve-static to 1.16.2.
- Updates send to 0.19.0.
- Updates rexml to 3.3.9,
=> Component Governance Fixes (0.76)

.ado/templates/apple-steps-publish.yml
Apparently the script doesn't take positional arguments anymore 🤦🏽‍♂️
I added more `set -eox pipefail` which might help
=> ci: fix usage of `set-version` script

.ado/templates/apple-steps-publish.yml
Backport of #2262 , along with a typo fix.
=> ci(0.76): fix usage of set-version script

.ado/templates/apple-steps-publish.yml
Our publish pipeline called `set-version.js`, which would change version numbers in package.json files. This invalidated our `yarn.lock` file. Then, `npm publish` would calls the lifecycle script `pack` , which calls `prepack`, which Meta defined to run `packages/react-native/scripts/prepack.js`. This will build `react-native-codegen` if it hasn't been (I guess we want the build output packed) and run `yarn install`. In CI, `yarn install` is by default immutable. However, as I pointed out above, our `yarn.lock` is invalidated, so `yarn install --immutable` will fail because we need to update the lock file. 
So.. let's fix this by building codeine and mutably running yarn install. Also, we don't need to call the `publish-npm` script anymore methinks. We're doing it in our pipeline …
=> ci(0.76): Make sure to build codegen and update the lockfile before publish

package.json, yarn.lock
It doesn't look like we're using `hermes-inspector-msggen` and `react-native-bots` anywhere, so I think it makes sense to not include them when installing packages. This should also reduce the number of dependencies we need to download/install.
n/a
=> chore: exclude unused packages from workspaces

.ado/jobs/test-react-native-macos-init.yml, .ado/variables/vars.yml, packages/react-native/local-cli/generate-macos.js, packages/react-native/local-cli/generator-macos/index.js
Two changes:
Reverts microsoft/react-native-macos#2207
Changes in ADO's images means we don't have Xcode 16 on macOS 14, and macOS 15 isn't guaranteed to have visionOS. So we're stuck until we move to GitHub Actions or we get an Arm64 only image of macOS 15. 
This caused a failure in CI, and we probably shouldn't do this anyway.
=> ci: Downgrade to Xcode 15, don't run `pod install` with `react-native-macos-init`

.ado/publish.yml, .ado/templates/apple-steps-publish.yml
> [!NOTE] 
> Needs #2251 and #2252 to land first
Set the `latestStableBranch` variable in our CI pipeline to 0.76-stable, so that `0.75.x` releases are no longer tagged as `latest` on NPM.
CI should pass
=> ci(0.75): Set `latestStableBranch` to `0.76-stable`

.ado/publish.yml, yarn.lock
Remove dependency on ip v2.0.0 to resolve CG alerts.
Also updates latestStableBranch in publish.yml.
=> Remove dependency on ip

yarn.lock
Remove dependency on ip v2.0.0 to resolve CG alerts.
=> Remove dependency on ip (0.76)

packages/helloworld/Gemfile.lock, yarn.lock
Remove dependency on ip v2.0.0 to resolve CG alerts.
Also updates rexml to 3.3.9 in helloworld.
=> Remove dependency on ip (0.75)

packages/react-native/React/Fabric/Mounting/ComponentViews/LegacyViewManagerInterop/RCTLegacyViewManagerInteropComponentView.mm, packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/Views/RCTView.m
This is part of a series of PRs where we are cherry-picking fixes from https://github.com/microsoft/react-native-macos/pull/2117 to update our Fabric implementation on macOS. 
These particular fixes looked to be easy low hanging fruit.
CI should pass
=> fix(fabric): cherry-pick some View related fixes

packages/react-native/Libraries/Text/TextInput/RCTBackedTextInputViewProtocol.h, packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm
We already have this iOS only prop disabled on macOS in Paper, let's disable it in Fabric. Otherwise the TextInput test page crashes
TextInput page no longer crashes
=> fix(fabric): disable TextInput prop `enablesReturnKeyAutomatically`

packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm
Cherry pick a couple of changes to have TextInput call focus and blur (natively, `makeFirstResponder` and `resignFirstResponder`) through its window instance variable rather than through its' self. 
RNTester runs fine while focusing and blurring some text inputs.
=> fix(fabric, text input): use window to focus and blur TextInput

packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/Fabric/Mounting/RCTMountingManager.mm, packages/react-native/React/Views/RCTView.h, packages/react-native/React/Views/RCTView.m, packages/react-native/React/Views/UIView+React.h, packages/react-native/React/Views/UIView+React.m
For whatever reason, the default transform origin on iOS is the center of a view, while on macOS it is the top left corner. I think this is because `layer.anchorPoint` is getting nilled out into `{0,0}` at some point. Regardless, because of this difference, we've maintained a diff to make the React Native macOS behavior matches iOS (See #1035 ). The diff involved storing the transform in an instance variable and manually applying a new transform on top to adjust the transform origin.
As of React Native 0.73+, there is a new style prop `transformOrigin` (see https://github.com/facebook/react-native/pull/38626/ and …
=> refactor(transforms): simplify macOS transform logic on old and new architecture

.ado/variables/vars.yml
Update back to Xcode 16 after we had to back it out with https://github.com/microsoft/react-native-macos/pull/2271
CI should pass
=> ci: upgrade to Xcode 16

packages/react-native/Libraries/Lists/__tests__/__snapshots__/FlatList-test.js.snap, packages/react-native/Libraries/Lists/__tests__/__snapshots__/SectionList-test.js.snap, packages/virtualized-lists/Lists/VirtualizedList.js, packages/virtualized-lists/Lists/VirtualizedListCellRenderer.js, packages/virtualized-lists/Lists/__tests__/__snapshots__/VirtualizedList-test.js.snap, packages/virtualized-lists/Lists/__tests__/__snapshots__/VirtualizedSectionList-test.js.snap
Pick a few commits that disable view flattening in Flatlist / VirtualizedList
CI should pass
=> fix(fabric, lists): disable view flattening in VirtualizedList

packages/react-native/React/Fabric/Mounting/ComponentViews/Text/RCTParagraphComponentView.mm, packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.h, packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextLayoutManager.mm
Cherry pick the first couple of fixes to Text. Notable changes from the initial commits:
- Since these commits were made, React Native upstream added https://github.com/facebook/react-native/commit/f4609dbb5fd8b2db986b9341ab866d03a56c8640 which heavily refactors TextInput on iOS. Specifically, it moves Text rendering from the Paragraph component view to its' inner content view. As such, I refactor the macOS implementation in b33797f5a986e9f148829e97d47218fbf0d08707 to match iOS. 
- The macOS implementation involves direct access to `NSTextStorage` through `RCTTextLayoutManager`. However, since …
=> fix(fabric, text): render Text in an NSTextView

packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm
Unlike UIKit,  AppKit hit testing requires the point to be in the superview coordinate system. As such, we have to override hit testing in React Native macOS to match the assumed iOS semantics. 
Followup change I made to the original commit: I removed the `RCTView` import/check for hit testing in `RCTViewComponentView` because I don't think we'll ever be moving paper and fabric views like that. 
CI should pass, maybe also try picking 71fae19c0b and see if selection works now
=> fix(fabric): Add conditional coordinate space conversion for native view hit testing

.ado/jobs/build-test-rntester.yml
These test tend to be flaky, giving a false negative for many PRs. They tend to be disabled upstream as well. Let's disable them here in our CI while we are mass merging Fabric commits
CI should pass
=> ci: Disable Xcode tests

packages/react-native/Libraries/Components/TextInput/RCTTextInputViewConfig.js, packages/react-native/Libraries/Text/TextInput/RCTBackedTextInputViewProtocol.h, packages/react-native/Libraries/Text/TextInput/RCTBaseTextInputViewManager.mm, packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputComponentView.mm, packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputUtils.h, packages/react-native/React/Fabric/Mounting/ComponentViews/TextInput/RCTTextInputUtils.mm, packages/react-native/ReactCommon/react/renderer/components/textinput/platform/ios/react/renderer/components/iostextinput/TextInputEventEmitter.cpp, packages/react-native/ReactCommon/react/renderer/components/textinput/platform/ios/react/renderer/components/iostextinput/TextInputEventEmitter.h, packages/react-native/ReactCommon/react/renderer/components/textinput/platform/ios/react/renderer/components/iostextinput/primitives.h, packages/react-native/ReactCommon/react/renderer/components/textinput/platform/ios/react/renderer/components/iostextinput/propsConversions.h
React Native macOS on the old architecture has some macOS specific props for toggling some of the built-in autocorrect / spell check / grammer check in text inputs. This change cherry-picks the changes to bring them to the new architecture.  
I needed to make a couple of followup changes:
- I needed to add the emitted events to the static view config. I think this is because when the commits were made, static view config validation wasn't enabled in React Native yet. 
-I changed the paper event types to direct events. These feel like they should be direct events, and now they are for both paper and fabric
Testing...
=> fix(fabric, textinput): enable spelling and grammer props

.ado/templates/npm-publish.yml
The syntax `${{ variables.foo }}` in Azure Pipelines yml is only valid for _template_ variables. For our `npm-publish.yml` steps, we are setting a _runtime_ variable, so it cannot be accessed in a `${{ }}` in a successive steps' condition. We can fix this by slightly refactoring the condition so that it now evaluates at runtime. The solution was taken from here: https://learn.microsoft.com/en-us/azure/devops/pipelines/process/conditions?view=azure-devops&tabs=yaml#variables-created-in-a-step-used-in-subsequent-step-conditions
While we're at it, let's add the `--verbose` flag too.
CI should pass
=> ci(0.76): check publish_react_native_macos with a runtime condition

.ado/jobs/npm-publish-dry-run.yml, .ado/publish.yml
On CI, checkouts start by creating a new Git repo, then adding a remote and performing a checkout to a specific commit. This means that we're usually left in a headless state. Switching to a blobless clone should allow us to access full Git history without the cost of a full clone.
Verified that `git show HEAD` works:
Logs: https://dev.azure.com/ms/react-native/_build/results?buildId=617877&view=logs&j=31c9baed-b2a6-554c-7a70-551207daefaf&t=7e256de5-d29e-5b82-98c8-a05e66789a98
=> ci: use blobless clones in publishing pipelines

.ado/jobs/npm-publish-dry-run.yml, .ado/publish.yml
On CI, checkouts start by creating a new Git repo, then adding a remote and performing a checkout to a specific commit. This means that we're usually left in a headless state. Switching to a blobless clone should allow us to access full Git history without the cost of a full clone.
Cherry-pick 5bf84b10.
n/a
=> ci(0.76): use blobless clones in publishing pipelines (#2315)

.ado/templates/npm-publish.yml
Even though we do a blobless clone, ADO still leaves us in a detached state. At least now we have all the information needed to switch branch.
n/a
=> ci: switch branch before publishing artifacts

.ado/jobs/npm-publish-dry-run.yml, .ado/scripts/prepublish-check.mjs, .ado/templates/apple-tools-setup.yml, .ado/templates/apple-xcode-select.yml, .ado/templates/npm-publish-steps.yml, packages/react-native/package.json, yarn.lock
A couple of fixes:
1. `nx release` won't publish `react-native-macos` because we use Yarn with what they call a local dependency protocol (AKA: `workspace:*` in our package.json for react-native-macos). `nx` thinks that Yarn doesn't support this, but it has since Yarn 2+. This is a bug in nx, and I've filed https://github.com/nrwl/nx/issues/29242 . Meanwhile, let's just remove the use that protocol to unblock publish. 
2. `nx release` creates a graph of dependent tasks for it's command `nx-release-publish`. This seems to be include publishing a bunch of other packages (You can see the graph with `nx graph`, I've also pasted it here). There's an `--excludeTaskDependencies` option for `nx release publish` (the subcommand) but not `nx release`. So.. I'm splitting the command into 2: Run `nx …
=> ci(0.76): more publish pipeline fixes

packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.mm
RNM 0.76 apps created with `react-native-macos-init` fails to load the javascript bundle at start due to a missing implementation of RCTAppDelegate::bundleURL in the template, as described in #2305 
this PR just updates the template to add the missing method
Run react-native-macos-init and check that the created project builds and run
=> fix: RCTAppDelegate::bundleURL not implemented

packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.mm
Bring template fix done in `0.76-stable` (#2309) to main
=> fix(react-native): RCTAppDelegate::bundleURL not implemented from `0.76-stable` to main

packages/react-native/src/private/animated/NativeAnimatedHelper.js, yarn.lock
=> fix(0.76, animated): load NativeAnimatedModule on macOS

packages/react-native/React/Base/RCTRootView.m
Consider a React Native experience occurring inside an `NSPanel`. On macOS, this `NSPanel` will keep track of its own first responder. In other words, if you click off that panel and into somewhere else (be it another `NSWindow` in the same app or another app altogether), the `NSPanel` never relinquishes its first responder, so we never send the [blur or focus events](https://github.com/microsoft/react-native-macos/blob/d924f34796ea655e1afe8c7ebe89028a0196017c/packages/react-native/React/Views/RCTView.m#L923-L946) to the JS side.
In [this example](https://www.w3schools.com/JSREF/tryit.asp?filename=tryjsref_onfocus_eventdelegation) of blur and focus events in Web, we see that the blur and focus events still take effect when switching windows. Therefore, it's reasonable to try to do the …
=> Send JS blur/focus events when switching to another NSWindow

.ado/jobs/build-test-rntester.yml, .ado/scripts/xcodebuild.sh, .ado/templates/apple-tools-setup.yml, .ado/variables/vars.yml
A couple of fixes:
- Xcode 16.0 was removed from the macOS 14 image. Use Xcode 16.2
- We needed to both remove the step to download the visionOS SDK and add a step to download all platforms in Xcode because.. well.. that was the combo that got visionOS to keep building. 
- React Native Test App (off main) uses Node 23's typescript stripping, and we have a job that tests RNTA integration. That means we now need Node 23 as well (@tido64 fyi)
CI should pass
=> ci: Various fixes

packages/react-native/Libraries/Image/RCTImageView.mm, packages/react-native/Libraries/Image/RCTImageViewManager.mm, packages/rn-tester/js/examples/Image/ImageExample.js
Problem: Setting the accessible prop to false on RN Image does not remove the image from the accessibility tree on macOS. This is because the accessible prop is mapped to the accessibilityElement property but is set on NSImageView which has no effect. Instead, the accessibilityElement prop should be set on NSImageCell.
Solution: Add a way to retrieve NSImageCell from NSImageView and map RN's accessible prop to the accessibilityElement property on it.
Added a toggle to the 'Accessibility' test example in ImageExamples.js to test the value of the accessible prop. Hovered over the image with Accessibility Inspector and verified that the image is not found when accessible is false. Also verified by turning on VoiceOver and confirmed the image did not get read when the accessible prop is …
=> Fix accessible prop for Image

packages/react-native/React/Base/RCTRootView.m
This is a follow-up to #2323. I found that the first responder may not necessarily have a React tag (e.g., a `<TextInput>`, as explained in the code's comments). To fix this, we just crawl up the view hierarchy to find the first ancestor that has a React tag and dispatch the relevant event there.
The test app made for #2323 has been updated to include a `<TextInput>`, and I validated that blur and focus events still come through as before.
The base for the test app can be found [here](https://github.com/amgleitman/react-native-test-app/tree/experimental/panel-test), although you'll have to add the changes to RCTRootView.m manually.
=> Enable searching through a view's parents for a React tag to call blur/focus on

packages/rn-tester/package.json, yarn.lock
With the switch to our new publish pipeline, some state is currently in flux (should we use `workspace:*`, or hardcode the version, etc). But while that isn't resolved, let's fix this to unblock merges. 
CI should pass
=> ci(0.76) use `workspace:*` for `@react-native/oss-library-example` in RNTester

.ado/jobs/build-test-rntester.yml, .ado/templates/apple-tools-setup.yml
Backporting a change I added to #2314, The Azure Runner images sometimes swap what Xcode platforms / simulators they have pre-installed in the interest of disk space. To help mitigate our risk, I'll just add a step to download all the Xcode platforms as part of our tools setup. 
=> ci(0.76): Download All Platforms with Xcode

.ado/apple-pr.yml, Gemfile, packages/helloworld/Gemfile, packages/rn-tester/Gemfile
Cherry pick https://github.com/facebook/react-native/commit/198adb47af3676c85b35adb308c110c1d87120c8 to fix an issue with Ruby, where the gem `concurrent-ruby` updated and broke our workflow
CI should pass
=> ci: fix ruby, disable integration tests

packages/react-native/Libraries/Components/TextInput/TextInput.d.ts, packages/react-native/Libraries/Components/TextInput/TextInput.flow.js, packages/react-native/Libraries/Components/TextInput/TextInput.js, packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap, packages/react-native/ReactCommon/react/renderer/components/textinput/platform/ios/react/renderer/components/iostextinput/TextInputEventEmitter.cpp, packages/rn-tester/Podfile.lock, packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js
> [!NOTE]
> https://github.com/microsoft/react-native-macos/pull/2290 must merge first
macOS TextInput has some specific "Spelling And Grammar" properties that can be enabled or disabled by the user. We had events/callbacks to listen for these changes, with a simple "enabled" as the payload. While working on https://github.com/microsoft/react-native-macos/pull/2290 I realized it would make more sense to have seprate payloads for each event (spellCheckEnabled, etc). This is however, a breaking change, as it changes what is sent to JS. 
Testing...
BREAKING CHANGE: textinput spelling and grammar callbacks event changed
=> refactor(textinput): rename event payload properties for spelling and grammer callbacks

packages/react-native/Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.mm
In certain scenarios, the internal dimensions of elements are returned as floating point numbers because of variables such as view scaling. The current comparison for showing / hiding the scrollbar in the multiline text input does not account for this. If it's the case where the ClipView within the multiline text input is a fraction smaller than the text itself, then the scrollbar persistently shows. 
Tested on local app - scrollview still shows at appropriate times.
=> fix(textinput): Account for float dimensions when showing scroller

packages/react-native/Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.mm
Backporting changes from #2341, see PR for details.
=> fix(0.74, textinput): Account for float dimensions when showing scroller

packages/react-native/Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.mm
Backporting changes from #2341, see PR for details.
=> fix(0.76, textinput): Account for float dimensions when showing scroller 

packages/react-native/Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.mm
Backporting changes from #2341, see PR for details.
=> fix(0.75, textinput): Account for float dimensions when showing scroller 

packages/react-native/React/Base/RCTRootView.m
Cherry-pick of https://github.com/microsoft/react-native-macos/pull/2323 and https://github.com/microsoft/react-native-macos/pull/2325 to 0.74-stable.
=> [0.74-stable] Send JS blur/focus events when switching to another NSWindow

packages/react-native/Libraries/Utilities/Platform.macos.js, packages/react-native/Libraries/Utilities/__tests__/Platform-test.js
During the merge up to 0.77, `Platform.select` was accidentally broken. This fixes it.
https://github.com/microsoft/react-native-macos/blame/5c43268b1c28538c517702ce83d0ca5adffcb05a/packages/react-native/Libraries/Utilities/Platform.macos.js#L87
The newly added unit tests properly cover this case.
=> Fix `Platform.select` on Mac

packages/react-native/Libraries/Utilities/Platform.macos.js, packages/react-native/Libraries/Utilities/__tests__/Platform-test.js, yarn.lock
Cherry picks #2374 into 0.77-stable.
=> [0.77-stable] Fix `Platform.select` on Mac

packages/react-native/Libraries/Network/RCTDataRequestHandler.mm, packages/react-native/Libraries/Network/RCTFileRequestHandler.mm
Backport of #2383 to 0.76-stable
=> fix(0.76): avoid race condition crash in `[RCTDataRequestHandler invalidate]`

packages/react-native/Libraries/Network/RCTDataRequestHandler.mm, packages/react-native/Libraries/Network/RCTFileRequestHandler.mm
Upstreaming a fix by @ntre that fixes a crash we saw internally related to `[_queue cancelAllOperations]`.
>Calling [_queue cancelAllOperations] will release all references to any active operations.
>If the blocks of those operations have a reference to itself, it will result in dangling pointers, which could conceptually trigger a later crash if there's a race between the operation completing and it being pulled out of the queue.
>
>Add explicit strong reference while block is running.
>For good measure, fix same pattern also in RCTFileRequestHandler.
>
>Note: separately, that this code is passing the op itself as a requestToken to [delegate URLRequest:] methods is suspect. That delegate can retain said token.
Tested internally.
=> fix: avoid race condition crash in `[RCTDataRequestHandler invalidate]`

packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformTouch.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewEventEmitter.cpp, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewEventEmitter.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewEvents.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewProps.cpp, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewProps.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewTraitsInitializer.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/KeyEvent.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/MouseEvent.h
react-native-macos extends BaseViewProps and BaseViewEventEmitter with additional functionality (e.g., validKeysUp, focusable, onMouseEnter, etc.).
This set of changes unblocks prop parsing and event capabilities for desktop specific behaviors in RCTViewComponentView.
=> Fabric view props & events

packages/react-native/React/Views/UIView+React.m
I first noticed this while working on SwiftUI views for https://github.com/expo/expo/pull/35078. Calling `reactViewController` on iOS always returns the correct view controller but on macOS, this same function will return nil for nested views.
So this PR addresses the differences in responder chain behavior between iOS and macOS when aliasing UIViewController to NSViewController. On iOS, a view's nextResponder is naturally its own UIViewController, ensuring that helper functions like reactViewController work as expected. However, on macOS, an NSView's nextResponder does not include its NSViewController by default, which causes issues when trying to retrieve the view controller directly from the responder chain. 
This change ensures that traversals will properly locate the NSViewController …
=> Fix responder chain in reactViewController on macOS

packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextPrimitivesConversions.h
=> [0.76-stable] Update deprecated enums in RCTTextPrimitivesConversions.h (#2377)

packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextPrimitivesConversions.h
=> [0.74-stable] Update deprecated enums in RCTTextPrimitivesConversions.h (#2377)

packages/react-native/ReactCommon/react/renderer/textlayoutmanager/platform/ios/react/renderer/textlayoutmanager/RCTTextPrimitivesConversions.h
=> [0.77-stable] Update deprecated enums in RCTTextPrimitivesConversions.h (#2377)

packages/react-native/Libraries/Text/Text.js
For some odd reason, if you set `backgroundColor` on a Text component, the color spills out past the frame to the parent. We can work around this by setting border radius... which somehow prevents this behavior. I need to debug the native side more (and may update this PR with a proper fix if I find one), but for now let's patch the JS to set a dummy value for borderRadius if we create a Text Element with backgroundColor and without borderRadius
A bunch of examples in RNTester are now visible... like the "Recently Viewed" section.
=> fix(macos): <Text> with backgroundColor spills color past it's frame

packages/react-native/React/Base/RCTTouchHandler.m, packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/Views/RCTView.m, packages/react-native/React/Views/UIView+React.m
=> fix(0.76, macOS): reconcile coordinate systems for mouse events (#2403)

packages/react-native/React/Base/RCTTouchHandler.m, packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/Views/RCTView.m, packages/react-native/React/Views/UIView+React.m
=> fix(0.75, macOS): reconcile coordinate systems for mouse events (#2403)

packages/react-native/React/Base/RCTTouchHandler.m, packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/Views/RCTView.m, packages/react-native/React/Views/UIView+React.m
=> fix(0.74, macOS): reconcile coordinate systems for mouse events (#2403)

docs/WritingNativeComponents.md, packages/react-native/React/Base/RCTTouchHandler.m, packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/React/Views/RCTView.m, packages/react-native/React/Views/UIView+React.m
=> fix(0.77, macOS): reconcile coordinate systems for mouse events (#2403)

packages/react-native/React/Base/RCTTouchHandler.m, packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/macOS/RCTUIKit.m, packages/react-native/React/Views/RCTView.m, packages/react-native/React/Views/UIView+React.m
=> fix(0.73, macOS): reconcile coordinate systems for mouse events (#2403)

.ado/scripts/prepublish-check.mjs, .ado/templates/npm-publish-steps.yml
Addresses inconsistencies in the prepublish script by moving the Azure Pipelines checks after the correct tag has been determined.
Ensure tag is correctly set on `main`:
```
~/S/react-native-macos (main) % node .ado/scripts/prepublish-check.mjs --verbose
❌ .ado/templates/npm-publish-steps.yml: 'publishTag' needs to be set to 'nightly'
```
Ensure tag is correctly set for `0.76-stable` (previous):
```
~/S/react-native-macos (0.76-stable) % node .ado/scripts/prepublish-check.mjs --verbose
ℹ️ react-native-macos@latest: 77
ℹ️ Current version: 76
ℹ️ Expected npm tag: v0.76-stable
❌ 'release.version.generatorOptions.currentVersionResolverMetadata.tag' must be set to 'v0.76-stable'
❌ Nx Release is not correctly configured for the current branch
```
Ensure tag is correctly set for `0.77-stable` …
=> chore: fix prepublish script inconsistencies

.ado/scripts/prepublish-check.mjs
Backport #2414 to `0.77-stable`
=> chore(0.77): use fallback resolver for new tags

.ado/scripts/prepublish-check.mjs, .ado/templates/npm-publish-steps.yml, nx.json
Backport of #2410 to 0.76-stable. I'm also updating the nx config tag.
=> chore(0.76): fix prepublish script inconsistencies

nx.json, packages/nx-release-version/generators.json, packages/nx-release-version/index.js, packages/nx-release-version/package.json, packages/nx-release-version/schema.json, packages/nx-release-version/tsconfig.json, yarn.lock
Adds a post-version step to Nx Release for updating generated artifacts (e.g., `RCTVersion.m`).
Bump the version and run `nx release`:
```
yarn nx release plan --only-touched=false patch
yarn nx release --skip-publish --verbose
```
Verify that generated artifacts have been updated with the latest version number.
=> chore: add post-version step to Nx Release

nx.json, packages/nx-release-version/generators.json, packages/nx-release-version/index.js, packages/nx-release-version/package.json, packages/nx-release-version/schema.json, packages/nx-release-version/tsconfig.json, yarn.lock
Adds a post-version step to Nx Release for updating generated artifacts (e.g., `RCTVersion.m`).
Bump the version and run `nx release`:
```
yarn nx release plan --only-touched=false patch
yarn nx release --skip-publish --verbose
```
Verify that generated artifacts have been updated with the latest version number.
---------
=> chore(0.77): add post-version step to Nx Release (#2418)

.nx/version-plans/version-plan-1741765321082.md
Create a new version plan to prep CI for the release of RNM 0.77.1
Output of `nx release --dry-run`
```
sanajmi@Saads-MacBook-Pro-14 react-native-macos % yarn nx release --dry-run
NX   Running release version for project: @react-native-mac/virtualized-lists
@react-native-mac/virtualized-lists 🔍 Reading data for package "@react-native-mac/virtualized-lists" from packages/virtualized-lists/package.json
@react-native-mac/virtualized-lists 📄 Resolved the current version as 0.77.0 for tag "latest" from registry https://registry.npmjs.org/
@react-native-mac/virtualized-lists 📄 Resolved the specifier as "patch" using version plans.
@react-native-mac/virtualized-lists ✍️  New version 0.77.1 written to packages/virtualized-lists/package.json
@react-native-mac/virtualized-lists ✍️  Applying new …
```
=> chore(0.77): prepare for patch release 

packages/nx-release-version/index.js
`nx release` will bump local packages that are referenced in our lock file, thus invalidating the lock file till we run `yarn install` again. Let's run `yarn install` as part of our generator
Tested by cherry picking this commit to a local `0.77-stable` branch, creating a version plan, and running `nx release --dry-run`. `yarn install` was run.
=> ci: update `yarn.lock` as part of nx release

packages/react-native/scripts/cocoapods/__tests__/new_architecture-test.rb, packages/react-native/scripts/cocoapods/new_architecture.rb
This reverts commit b9f3186ee6314f56863c05272640d47643709a39.
The new architecture isn't ready on macOS yet. Specifically, the Fabric renderer isn't ready. This is causing issue for new projects off the macOS template. Let's disable it until we're ready.
CI should pass
=> chore: don't set the new architecture by default for macOS yet

packages/nx-release-version/index.js, yarn.lock
Backport of #2426 
`nx release` will bump local packages that are referenced in our lock file, thus invalidating the lock file till we run `yarn install` again. Let's run `yarn install` as part of our generator
Tested by cherry picking this commit to a local `0.77-stable` branch, creating a version plan, and running `nx release --dry-run`. `yarn install` was run.
---------
=> ci(0.76): update `yarn.lock` as part of nx release (#2426)

packages/nx-release-version/index.js, yarn.lock
Backport of #2426 
`nx release` will bump local packages that are referenced in our lock file, thus invalidating the lock file till we run `yarn install` again. Let's run `yarn install` as part of our generator
Tested by cherry picking this commit to a local `0.77-stable` branch, creating a version plan, and running `nx release --dry-run`. `yarn install` was run.
---------
=> ci(0.77): update `yarn.lock` as part of nx release (#2426)

packages/react-native/scripts/cocoapods/__tests__/new_architecture-test.rb, packages/react-native/scripts/cocoapods/new_architecture.rb
Backport of #2423 
This reverts commit b9f3186ee6314f56863c05272640d47643709a39.
The new architecture isn't ready on macOS yet. Specifically, the Fabric renderer isn't ready. This is causing issue for new projects off the macOS template. Let's disable it until we're ready.
CI should pass
=> chore(0.76): don't set the new architecture by default for macOS yet

packages/react-native/scripts/cocoapods/__tests__/new_architecture-test.rb, packages/react-native/scripts/cocoapods/new_architecture.rb
Backport of #2423 
This reverts commit b9f3186ee6314f56863c05272640d47643709a39.
The new architecture isn't ready on macOS yet. Specifically, the Fabric renderer isn't ready. This is causing issue for new projects off the macOS template. Let's disable it until we're ready.
CI should pass
=> chore(0.77): don't set the new architecture by default for macOS yet

.ado/scripts/prepublish-check.mjs
`prerelease` can be `undefined` while `generatorOptions.preid` is an empty string. Update the check to handle that
CI should pass
=> ci(0.78): update prepublish check to check prerelease existence

.ado/templates/npm-publish-steps.yml
I noticed NPM publish failing still. My guess is the second addition of this line to our `.npmrc` is messing it up
Testing on 0.78 release.
=> ci(0.78): Don't add NPM auth token to npmrc twice

.ado/scripts/prepublish-check.mjs
`prerelease` can be `undefined` while `generatorOptions.preid` is an empty string. Update the check to handle that
CI should pass
=> ci: update preid check in prepublish.mjs

packages/react-native/Libraries/AppDelegate/RCTDefaultReactNativeFactoryDelegate.mm, packages/rn-tester/RNTester/AppDelegate.mm
Cherry pick https://github.com/facebook/react-native/commit/8b33668c4338d31c27e6bd90b2a0e6fc0a077588 to fix an issue where new apps made with the old architecture never call metro and therefore show a blank screen. 
Tested on a new app using `@react-native-community/cli init && react-native-macos-init`
=> fix(0.78): Add missing loadFromSource method in the DefaultRNFactoryDelegate

.ado/scripts/prepublish-check.mjs, nx.json
Backport of #2432 to 0.78-stable
CI should pass
=> ci(0.78): update preid check in prepublish.mjs (#2432)

.ado/templates/npm-publish-steps.yml
I noticed NPM publish failing still. My guess is the second addition of this line to our `.npmrc` is messing it up
Testing on 0.78 release.
=> ci: properly pass NPM auth token secret to script

.ado/templates/npm-publish-steps.yml, .nx/version-plans/version-plan-1742941422258.md
Backport of #2434 to 0.78-stable, along with a change file to publish a new version
As with Publish pipeline changes, merge and hope for the best 🙏
=> ci(0.78): properly pass NPM auth token secret to script

.ado/templates/npm-publish-steps.yml
We aren't yet ready to publish nightlies, so unconditionally running `publish` on the main branch might accidentally publish versions of React Native macOS we don't want. Let's disable it for now.
As with all publish pipeline changes, merge and hope for the best.
=> ci: disable nightlies on the main branch

.ado/scripts/prepublish-check.mjs, .ado/templates/npm-publish-steps.yml
Backport #2422 , #2432 , and #2434 to 0.77-stable
CI should pass
=> ci(0.77): backport publish pipeline changes

.ado/templates/npm-publish-steps.yml, .nx/version-plans/version-plan-1743111896868.md, nx.json
Now that `0.78` is marked as latest, `0.77` needs to have its tag updated. 
=> ci(0.77): Downgrade `0.77` from latest to stable

.ado/templates/npm-publish-steps.yml, packages/nx-release-version/index.js
Only publish packages if there are changes to push
n/a
=> ci: only publish if there are changes to push

packages/react-native/Libraries/Network/RCTDataRequestHandler.mm, packages/react-native/Libraries/Network/RCTFileRequestHandler.mm
Backport #2450 to `0.74-stable`
=> fix(0.74): cherry pick "[iOS] Reland: avoid race condition crash in [RCTDataRequestHandler invalidate]"

.nx/version-plans/version-plan-1744150643671.md, packages/react-native/Libraries/Network/RCTDataRequestHandler.mm, packages/react-native/Libraries/Network/RCTFileRequestHandler.mm
Backport #2450 to `0.78-stable`
=> fix(0.78): cherry pick "[iOS] Reland: avoid race condition crash in [RCTDataRequestHandler invalidate]"

.nx/version-plans/version-plan-1744150643671.md, packages/react-native/Libraries/Network/RCTDataRequestHandler.mm, packages/react-native/Libraries/Network/RCTFileRequestHandler.mm
Backport #2450 to `0.76-stable`
=> fix(0.76): cherry pick "[iOS] Reland: avoid race condition crash in [RCTDataRequestHandler invalidate]"

.ado/templates/npm-publish-steps.yml, .nx/version-plans/version-plan-1744150643671.md, nx.json, packages/react-native/Libraries/Network/RCTDataRequestHandler.mm, packages/react-native/Libraries/Network/RCTFileRequestHandler.mm
Backport #2450 to `0.77-stable`
=> fix(0.77): cherry pick "[iOS] Reland: avoid race condition crash in [RCTDataRequestHandler invalidate]"

packages/react-native/React/CoreModules/RCTDevLoadingView.mm
We've had a recurring bug where `RCTDevLoadingView` stick around blocking the whole app even after it's dismissed. As far as I can tell, this is a race condition where we have multiple devloadingviews at once (each setting and nilling the same `self->_window` property), which is causing a race condition. Rather than figure out how to make this class only ever show one window or race-safe, for now I will just make sure to dismiss _all_ sheets when `hide` is called.
While we're at it, a couple of other changes:
1. Change the type from `NSPanel` to `NSWindow`. Panels don't release when closed, which may be causing them to stick around longer than we like
2. Move the iOS only variable `mainWindow` into the iOS ifdef, and remove the diffs and diff tag around it. 
Initial testing shows RNTester …
=> fix: dismiss all sheets created by `RCTDevLoadingView` when `hide` is called

packages/react-native/React/CoreModules/RCTDevLoadingView.mm, packages/rn-tester/package.json, yarn.lock
Backport of #2448 to 0.77-stable
=> fix(0.77): dismiss all sheets created by `RCTDevLoadingView` when `hide` is called

packages/react-native/React/CoreModules/RCTDevLoadingView.mm, packages/rn-tester/package.json, yarn.lock
Backport of #2448 to 0.78-stable
=> fix(0.78): dismiss all sheets created by `RCTDevLoadingView` when `hide` is called

packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.h
`typingAttributes` was added in a recent React Native release, but not brought to `RCTUITextField` (where we have to port some iOS only props to macOS). This caused an `unrecognized selector` style crash when trying to set `typingAttributes`.
Booting RNTester-macOS with the new architecture no longer crashes,
=> fix(fabric): Add `typingAttributes` to `RCTUITextField` to fix crash

packages/react-native/Libraries/Components/TextInput/TextInput.d.ts, packages/react-native/Libraries/Components/TextInput/TextInput.flow.js, packages/react-native/Libraries/Components/TextInput/TextInput.js, packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap
[These two functions](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInputState.js#L60C1-L70C2) are used to [properly handle onFocus\onBlur for TextInput implementations](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInput.js#L1623C1-L1635C5), specifically they are used to track the currently focused TextInput control and as such cause [focusTextInput](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInputState.js#L106C1-L106C48) and …
=> [0.78] [TextInput] Export TI State's focusInput/blurInput

packages/react-native/Libraries/Components/TextInput/TextInput.d.ts, packages/react-native/Libraries/Components/TextInput/TextInput.flow.js, packages/react-native/Libraries/Components/TextInput/TextInput.js, packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap
[These two functions](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInputState.js#L60C1-L70C2) are used to [properly handle onFocus\onBlur for TextInput implementations](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInput.js#L1623C1-L1635C5), specifically they are used to track the currently focused TextInput control and as such cause [focusTextInput](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInputState.js#L106C1-L106C48) and …
=> [0.77] [TextInput] Export TI State's focusInput/blurInput

packages/react-native/Libraries/Components/TextInput/TextInput.d.ts, packages/react-native/Libraries/Components/TextInput/TextInput.flow.js, packages/react-native/Libraries/Components/TextInput/TextInput.js, packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap
[These two functions](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInputState.js#L60C1-L70C2) are used to [properly handle onFocus\onBlur for TextInput implementations](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInput.js#L1623C1-L1635C5), specifically they are used to track the currently focused TextInput control and as such cause [focusTextInput](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInputState.js#L106C1-L106C48) and …
=> [0.75] [TextInput] Export TI State's focusInput/blurInput

packages/react-native/Libraries/Components/TextInput/TextInput.d.ts, packages/react-native/Libraries/Components/TextInput/TextInput.flow.js, packages/react-native/Libraries/Components/TextInput/TextInput.js, packages/react-native/Libraries/__tests__/__snapshots__/public-api-test.js.snap
[These two functions](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInputState.js#L60C1-L70C2) are used to [properly handle onFocus\onBlur for TextInput implementations](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInput.js#L1623C1-L1635C5), specifically they are used to track the currently focused TextInput control and as such cause [focusTextInput](https://github.com/microsoft/react-native-macos/blob/9ea059c33143e6766582a1f682e4f144e00cc740/packages/react-native/Libraries/Components/TextInput/TextInputState.js#L106C1-L106C48) and …
=> [0.74] [TextInput] Export TI State's focusInput/blurInput

nx.json, packages/nx-release-version/index.js
This reverts commit 791012b8f08270baa940a4f0e9125162d27a0f7b.
We had some custom logic to update the lock file after the "version" step of release happened. Turns out you can just do that directly through `nx`... so let's remove the logic and do it that was instead. 
Ran `nx release --skip-publish` locally (and cmd+c'ed it before it committed anything...) to see if the lock would update with the new versions and it did.
=> ci: update lock file through `nx.json` flag instead

nx.json, packages/nx-release-version/index.js
Backport of #2476 to 0.78-stable
=> ci(0.78): update lock file through `nx.json` flag instead

.ado/templates/npm-publish-steps.yml, .nx/version-plans/version-plan-1744766603658.md, .yarn/patches/@nx-js-npm-20.0.7-30719000fd.patch, package.json, yarn.lock
Patch nx to add some logging to help figure out why `yarn nx run react-native-macos:nx-release-publish --excludeTaskDependencies` fails
I expect CI to fail after merge :D
=> ci(0.78): Add some logging to the pubish phase

nx.json
Guess the config doesn't like trailing commas.
CI should pass
=> ci(0.76): fix typo in `nx.json`

.ado/templates/npm-publish-steps.yml
We separate our CI to run `nx release` as two steps: `nx release --skip-publish` and `nx release publish`. The latter seems to not pick up the NPM dist-tag we want to set packages to release with, so it defaults to `latest`. This seems solvable by simply passing in `--tag`., since that gets picked up [in this line of code](https://github.com/nrwl/nx/blob/745abdaecfffbf09278dd576ef32afb8a7da9735/packages/js/src/executors/release-publish/release-publish.impl.ts#L123).
Locally ran `nx release-publish` with extra console.logs to make sure the tag was passed in.
=> ci: set the npm dist-tag in `nx release publish`

.ado/templates/npm-publish-steps.yml
Backport of #2484 to `0.78-stable`
=> ci(0.78): set the npm dist-tag in `nx release publish`

.ado/templates/npm-publish-steps.yml
Backport of #2484 to `0.77-stable`
=> ci(0.77): set the npm dist-tag in `nx release publish`

.ado/templates/npm-publish-steps.yml
Backport of #2484 to `0.76-stable`
=> ci(0.76): set the npm dist-tag in `nx release publish`

packages/assets/package.json, packages/babel-plugin-codegen/package.json, packages/community-cli-plugin/package.json, packages/core-cli-utils/package.json, packages/debugger-frontend/package.json, packages/dev-middleware/package.json, packages/eslint-config-react-native/package.json, packages/eslint-plugin-react-native/package.json, packages/eslint-plugin-specs/package.json, packages/gradle-plugin/package.json, packages/metro-config/package.json, packages/normalize-color/package.json, packages/polyfills/package.json, packages/react-native-babel-preset/package.json, packages/react-native-babel-transformer/package.json, packages/react-native-codegen/package.json, packages/react-native-popup-menu-android/package.json, packages/typescript-config/package.json, packages/virtualized-lists/package.json
It's not clear (both to humans and to build tools like `nx`) that the only packages we fork from the React Native monorepo upstream are ` 'react-native' --> 'react-native-macos'` and `'@react-native/virtualized-lists' --> '@react-native-mac/virtualized-lists'`. The rest of the packages should essentially only ever be used in local development, while the published package `react-native-macos` uses the upstream versions of these packages. We can solve this by marking the packages as private. 
IIRC, this caused some build failure last time I tried this.. let's see how CI reacts to this change. Further testing with `nx release` should be done locally to make sure the nx build graph stops marking the unforked monoreppo packages as dependencies.
=> ci: mark unforked monorepo packages as private

packages/react-native/sdks/hermes-engine/hermes-utils.rb
`findLastestVersionWithArtifact` fails to find older versions of Hermes prebuilds because the Maven endpoint it uses does not return all versions.
Resolves #2499
`pod install` output from RNTA with RN 0.78.2 and RNM 0.78.3
=> fix: fix build failure with older versions and Hermes

packages/react-native/sdks/hermes-engine/hermes-utils.rb
`findLastestVersionWithArtifact` fails to find older versions of Hermes prebuilds because the Maven endpoint it uses does not return all versions.
Resolves #2499
`pod install` output from RNTA with RN 0.78.2 and RNM 0.78.3
=> fix(0.76): fix build failure with older versions and Hermes

packages/react-native/Libraries/Text/Text.d.ts
`TextPropsMacOS` has been using `MouseEvent` defined by web as opposed to React's.
See #2507.
n/a
=> fix(0.78): fix `TextPropsMacOS` using the wrong `MouseEvent` type

packages/react-native/Libraries/Text/Text.d.ts
`TextPropsMacOS` has been using `MouseEvent` defined by web as opposed to React's.
See #2507.
n/a
=> fix(0.77): fix `TextPropsMacOS` using the wrong `MouseEvent` type

packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
Internally, we build with [UndefinedBehaviorSanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html), which caught an instance of a method returning nil while marked as non null. Apple documentation says that method should return an empty array as a fallback, so let's do that. 
Tested internally.
=> fix(UBSAN): ensure `[RCTUITextField validAttributesForMarkedText]` Is non null

packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
Backport of #2515 to 0.74-stable
=> fix(0.74, UBSAN): ensure `[RCTUITextField validAttributesForMarkedText]` is nonnull

packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
Backport of https://github.com/microsoft/react-native-macos/pull/2515 to 0.78-stable
=> fix(0.78, UBSAN): ensure `[RCTUITextField validAttributesForMarkedText]` is nonnull

.ado/jobs/build-test-rntester.yml, packages/rn-tester/Podfile.lock
On 0.75-stable, Xcode's integration tests are consistently failing. These tests are generally flaky, and this version of RNM is about to go out of support. Upstream, I believe these tests have also been disabled and replaced with maestro E2E tests. Let's just disable these tests so we can unblock other fixes. 
CI should pass
=> chore(0.75): disable xcode rntester tests in CI

packages/react-native/Libraries/Text/Text.d.ts
`TextPropsMacOS` has been using `MouseEvent` defined by web as opposed to React's.
See #2507.
n/a
=> fix(0.75): fix `TextPropsMacOS` using the wrong `MouseEvent` type

packages/react-native/React/Base/macOS/RCTUIKit.m
Suppress a warning caught in our internal build system.
CI should pass
=> fix(0.75, Xcode 26): Add explicit cast for enum type to suppress a warning

packages/react-native/sdks/hermes-engine/hermes-utils.rb
Discovered when cherry-picking #2531 into #2530. I didn't catch it before because we don't actually run through this part on the main branch.
No effects on main branch, but #2530 CIs should succeed now.
=> fix: Fix a typo in Hermes-utils.rb

.ado/jobs/build-test-rntester.yml, packages/react-native/package.json, packages/react-native/scripts/cocoapods/utils.rb, packages/react-native/sdks/hermes-engine/hermes-engine.podspec, packages/react-native/sdks/hermes-engine/hermes-utils.rb, packages/rn-tester/Podfile, yarn.lock
This is a cherry-pick of #2524 with some more reliable logic for stable branches. The latter will be brought into the main branch in #2531.
CIs should pass.
=> ci(0.74): Add Hermes to test matrix

.ado/jobs/build-test-rntester.yml, packages/react-native/package.json, packages/react-native/scripts/cocoapods/utils.rb, packages/react-native/sdks/hermes-engine/hermes-engine.podspec, packages/react-native/sdks/hermes-engine/hermes-utils.rb, packages/rn-tester/Podfile, yarn.lock
Based on #2524 and #2530.
CI should pass
=> ci(0.78): Add Hermes to test matrix

.ado/apple-pr.yml, docs/Releases.md
This enforces and explains the existence of a peer dependency on RNCore for Hermes builds.
The added CI should pass.
=> ci(0.75): Add docs and CI checks for RN peer dependency

.ado/apple-pr.yml, docs/Releases.md
This enforces and explains the existence of a peer dependency on RNCore for Hermes builds.
The added CI should pass.
=> ci(0.74): Add docs and CI checks for RN peer dependency

packages/react-native/React/Views/RCTViewKeyboardEvent.m
Function keys on macOS currently get dispatched with the value from the underlying NS*FunctionKey code point. For instance, a `F12` event gets dispatched as `\uf70f` for [NS12FunctionKey](https://developer.apple.com/documentation/appkit/nsf12functionkey?language=objc). To clean this up, we should dispatch the same strings we use on other platforms (i.e. `'F12'` for the F12 key).
I used a pressable component with a `onKeyDown` handler in `RNTester-macOS` to test keyboard events. With this change, the function keys come in as `F12`, `F11` etc... instead of the underlying NS*FunctionKey code points.
=> fix: Support Function Key Handling in macOS Views

packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.mm
Fixes #2558 
This was missing from our template, which meant 3rd party fabric components would not get registered
Working on it...
=> fix: add RCTAppDependencyProvider to template

packages/react-native/Libraries/Components/TextInput/TextInputState.js, packages/react-native/React/Views/RCTViewKeyboardEvent.m
=> chore(0.78): backport some changes

.ado/publish.yml
Our publish pipeline on 0.76-stable was failing due to some mismatched YML. This was updated 0.77+, let's just copy that version down.
=> ci: update .ado/publish.yml to match 0.77-stable --> main

packages/react-native-test-library/package.json, yarn.lock
This got out of sync with the local workspace version, let's use the workspace protocol here.
=> chore(0.76): update dependency in @react-native/oss-library-example

packages/react-native-test-library/package.json, yarn.lock
This got out of sync with the local workspace version, let's use the
workspace protocol here.
=> chore(0.77): update dependency in @react-native/oss-library-example 

.ado/jobs/npm-publish.yml, packages/nx-release-version/index.js
Two fixes:
1. After #2560 , I forgot to update the CI step that reads the `nx.json` tag. Let's do that, and have it properly fail if it can't find the tag. 
2, Fix #2580 by calling `yarn npm publish` directly.
3. Use `console.table()` to print the react native artifacts updated in a release. Why? Because it looks cool.
Seriously, this looks cool!
```shell
NX   No files would be changed as a result of running versioning
✅ Updated React Native artifacts
┌─────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ (index) │ Values                                                                                                           │
├─────────┼─────────────────────────────────────────────────────────────── …
```
=> ci: "update to nx 21" followup fixes

.ado/jobs/npm-publish.yml, packages/nx-release-version/index.js
=> ci(0.78): "update to nx 21" followup fixes

.ado/jobs/npm-publish.yml, packages/nx-release-version/index.js
=> ci(0.76): "update to nx 21" followup fixes

packages/react-native/React/CoreModules/RCTDevLoadingView.mm, packages/react-native/React/CoreModules/RCTLogBoxView.mm, packages/react-native/React/DevSupport/RCTPausedInDebuggerOverlayController.mm, packages/rn-tester/Podfile
With Hermes and React Native Devtools, pausing the JS debugger presents an overlay over your app, with a "play" button to unpause. I had this ifdefed out during a merge, let's go back and fully implement it.
The overlay is presented as a sheet, like the other floating UI (DevLoadingView, log box, etc)
=> feat: Implement RCTPausedInDebuggerOverlayController

packages/react-native/React/DevSupport/RCTPausedInDebuggerOverlayController.mm
RCTUILabel doesn't like it if we set message to nil, which we accidentally did by loading our viewController into a window (which calls viewDidLoad, which creates our label and sets message) before we have set our property. Simple fix to call code in the right order.
=> fix: ensure PausedInDebuggerOverlay has message set before presenting

.ado/jobs/npm-publish.yml
YAML syntax wrong, publish failed.
=> ci: use ADO variable syntax for publish tag

.ado/jobs/npm-publish.yml, .github/CODEOWNERS, .nx/version-plans/version-plan-1753834798331.md, packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/virtualized-lists/package.json
Backport https://github.com/microsoft/react-native-macos/pull/2595
=> ci(0.77): use ADO variable syntax for publish tag

.nx/version-plans/version-plan-1753834774679.md, packages/nx-release-version/index.js, packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/virtualized-lists/package.json
=> ci(0.76): fix nx release not updating our lock file

.ado/jobs/npm-publish.yml
With #2560 and followup changes, we call `yarn npm publish` directly instead of `nx release publish` (Which indirectly used npm publish). Yarn's NPM publish command grabs its auth token from `.yarnrc.yml`, not `.npmrc`. Let's update our CI steps that set this. 
Tested that I can call `yarn config set / unset` to set and unset these values.
=> ci: set npmAuthToken in yarnrc, not npmrc

.ado/scripts/prepublish-check.mjs
Our `prepublish-check` assumed we used a `.npmrc` file to publish. However, we're now using Yarn V4 which uses its' `.yarnrc.yml` to set your registry and auth token. Update the check to handle both.
=> ci: check yarnrc if it exists

.ado/jobs/npm-publish.yml, .ado/scripts/prepublish-check.mjs
Fixes #2612 . Add a variable to switch between using Yarn or NPM to publish. Long term we should wait till Yarn publish fix (https://github.com/yarnpkg/berry/pull/6850) is integrated into NX, and then move to the nx release programmatic API.
=> ci: use npm to publish directly rather than yarn

.ado/jobs/npm-publish.yml, .ado/scripts/prepublish-check.mjs
=> ci(0.78): use npm to publish directly rather than yarn

.ado/jobs/npm-publish.yml, .ado/scripts/prepublish-check.mjs
=> ci(0.77): use npm to publish directly rather than yarn

.github/workflows/publish-release.yml, .nx/version-plans/version-plan-1754531007010.md, build.gradle.kts, packages/gradle-plugin/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/utils/DependencyUtils.kt, packages/gradle-plugin/react-native-gradle-plugin/src/test/kotlin/com/facebook/react/utils/DependencyUtilsTest.kt, scripts/releases/utils/release-utils.js
There doesn't seem to be a release to sync to, but we still want to sync and make a new release. Let's do so.
=> chore(0.76): Merge the rest of the React Native 0.76 stable branch

packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
Previously, we always centered the window, which got a bit annoying during debugging when I'd like to have it remember the last position as I relaunch it. This is probably a good thing to do in general, so let's do it in `RCTAppDelegate`.
Removed any saved frame by running `defaults delete Microsoft.RNTester-macOS`: window is centered
Resize window and move it and close and relaunch: old position is remembered.
=> chore: remember RCTAppDelegate main window position

packages/react-native/React/Fabric/Mounting/ComponentViews/LegacyViewManagerInterop/RCTLegacyViewManagerInteropComponentView.mm
In general, we prefer to use `RCTPlatformView` (`#define NSView`) over `RCTUIView` (subclass of NSView for iOS interop) as it tends to have less "Expected NSView, but got subclass of NSView" style errors. This changes fixes one of those errors
=> chore: Move one instance of `RCTUIView` --> `RCTPlatformView` 

packages/react-native/React/CoreModules/RCTRedBox.mm
We had a bug where if you tried to Reload RNTester (via the dev menu) after a Redbox, the following error was thrown:
```
Thread 1: "dismissViewController:: Error: maybe this view controller was not presented?"
```
This fixes it by checking if there's a presentingViewController first
Reloads work now after a Redbox.
=> fix: dismiss redbox only if presented

packages/react-native/React/CoreModules/RCTDevSettings.h, packages/react-native/React/CoreModules/RCTDevSettings.mm
This was added for an old internal use case that is no longer valid. Let's remove it.
=> chore: remove diff for `[RCTDevSettings overridenKeys]`

packages/react-native-compatibility-check/package.json, yarn.config.cjs
Followup to #2651 , make sure our constraint `enforcePrivateReactNativeScopedPackages` (makes sure the unforked `@react-native/*` packages in this repo are marked private) uses _workspaces_ instead of _dependencies_. The former seems to map to packages, while the latter maps to things in our Yarn lock file. 
Tested on the 0.79-stable branch with #2650
=> fix(constraints): `enforcePrivateReactNativeScopedPackages` checks workspaces instead of dependencies

.github/workflows/microsoft-pr.yml
Verdaccio still hangs on 0.79-stable, so let's disable this altogether for now.
=> chore(ci): disable integration tests

package.json, scripts/run-ci-javascript-tests.js, yarn.lock
This PR gets rid of the dependency on @definitelytyped/dtslint in order to mitigate CVE-2025-7783. We are essentially cherry-picking the following commits from facebook upstream.
- https://github.com/facebook/react-native/commit/2e0c2c6df11316ed293dd022d68b8e96d742b793
- https://github.com/facebook/react-native/commit/67a63804f8709448e59cd5478575171583025a08
=> chore(0.75): Remove @definitelytyped/dtslint dependency

.github/workflows/microsoft-pr.yml
On older stable branches, our Github repo ruleset looked for a job named "PR", which we have now named "all" in Github Actions. Let's rename the GHA job so that Azure Pipelines and GHA both report success on the same job and we don't need to fork our ruleset.
Testing in #2650
=> ci: rename GHA job to match Azure Pipelines to satisfy checks

packages/react-native/React/Views/RCTView.m
When updating RCTView in https://github.com/microsoft/react-native-macos/pull/2642, we end up slightly changing the behavior when `didUpdateShadow` is called, causing transparent shadows to crash the app. This breakage occurs because `NSColor colorWithCGColor:` doesn’t accept a `NULL` `CGColorRef`; instead, it raises an exception rather than gracefully returning `nil`.
Run RNTester
=> fix: null shadow color crash

packages/nx-release-version/index.js
=> ci(0.78): only create .rnm-publish sentinel file if versioning happened

packages/nx-release-version/index.js
=> ci(0.77): only create .rnm-publish sentinel file if versioning happened

.github/actions/microsoft-setup-toolchain/action.yml
Currently all Hermes slices in PR are failing to build (but build locally).
```
2025-09-17T00:55:31.8097360Z CMake Error at CMakeLists.txt:42 (cmake_policy):
2025-09-17T00:55:31.8097720Z   Policy CMP0026 may not be set to OLD behavior because this version of CMake
2025-09-17T00:55:31.8098290Z   no longer supports it.  The policy was introduced in CMake version 3.0.0,
2025-09-17T00:55:31.8098600Z   and use of NEW behavior is now required.
2025-09-17T00:55:31.8098750Z 
2025-09-17T00:55:31.8098940Z   Please either update your CMakeLists.txt files to conform to the new
2025-09-17T00:55:31.8099330Z   behavior or use an older version of CMake that still supports the old
2025-09-17T00:55:31.8099700Z   behavior.  Run cmake --help-policy CMP0026 for more information.
2025-09-17T00:55:31.8099900Z …
```
=> ci: pin cmake to 3.31.6

packages/react-native/React/Fabric/Mounting/ComponentViews/ScrollView/RCTPullToRefreshViewComponentView.mm, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformTouch.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewEventEmitter.cpp, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewEventEmitter.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewProps.cpp, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewProps.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/HostPlatformViewTraitsInitializer.h, packages/react-native/ReactCommon/react/renderer/components/view/platform/macos/react/renderer/components/view/MacOSViewEvents.h
Add a new macOS host platform folder, with overrides for some of the HostPlatform* files to implement some macOS only props. This follows the pattern in React Native Core that Android uses, and what React Native Windows does. 
Some notes:
- I also needed to fix a casting issue in `RCTPullToRefreshViewComponentView.mm`. This is later fixed upstream so we can remove the diff then. 
- These new props are not implemented on the component (`RCTViewComponentView` yet, that will be in a future PR)
=> feat(fabric): Add macOS host platform to ReactCommon

packages/rn-tester/js/examples/AccessibilityShowMenu/AccessibilityShowMenu.js, packages/rn-tester/js/utils/RNTesterList.ios.js
We have a bunch of macOS API examples in the "components" category. Let's just move them out and add a category to them.
CI should pass
=> fix(rn-tester): move macOS API examples
