microsoft/react-native-macos

Folly/folly/detail/dirs, Folly/folly/dirs, ReactAndroid/dirs, ReactAndroid/src/dirs, ReactAndroid/src/main/dirs, ReactAndroid/src/main/jni/dirs, ReactAndroid/src/main/jni/first-party/dirs, ReactAndroid/src/main/jni/first-party/fb/dirs, ReactAndroid/src/main/jni/first-party/fb/jni/dirs, ReactAndroid/src/main/jni/first-party/yogajni/dirs, ReactAndroid/src/main/jni/first-party/yogajni/jni/dirs, ReactAndroid/src/main/jni/react/dirs, ReactCommon/cxxreact/dirs, ReactCommon/jschelpers/dirs, ReactCommon/jsi/dirs, ReactCommon/jsiexecutor/jsireact/dirs, ReactCommon/privatedata/dirs, ReactCommon/v8helpers/dirs, ReactCommon/yoga/yoga/dirs, dirs, double-conversion/dirs, double-conversion/double-conversion/dirs, glog/dirs, glog/src/dirs, processor/dirs
=> Build changes for internal build

ReactCommon/jsi/jsicore/sources, ReactCommon/jsi/jsiv8/sources
=> Fix Office droid build

ReactAndroid/ReactAndroid.nuspec
Including more files needed in the nuget
=> Include more files in droid nuget

ReactCommon/cxxreact/V8Executor.cpp, ReactCommon/cxxreact/V8Executor.h
**Setting Cache path from Environment**
The location to the cache file formed by V8 engine is provided as an environment variable.
The current branch is tested with V8 engine and validated with the help of RNTester application.
=> cache path added

ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagerRegistry.java
Removing the line that I think rohit meant to remove in his last PR.
(optional)
=> Remove ReactHorizontalScrollViewManager mapping

Libraries/Components/Button.js, Libraries/Components/ScrollView/ScrollView.js, Libraries/Components/TextInput/TextInput.js
Removing some more code that is specific to react-native-windows.
https://github.com/microsoft/react-native-windows/pull/2774 will make these changes unnecessary for react-native-windows.
=> Remove some react-native-windows platform code

.ado/android-pr.yml, .ado/publish.js, .ado/publish.yml, ReactAndroid/NuGet.Config, ReactAndroid/build.gradle, ReactAndroid/packages.config, ReactCommon/CMakeLists.txt
=> Use standard ubuntu pool for PR

jest/hasteImpl.js, package.json, rn-cli.config.js, scripts/run-ci-e2e-tests.js
Minor change removing some unneeded code now that react-native-windows is properly extracted.
=> Remove some final uses of uwp

.ado/publish.js, .ado/publish.yml, .github/workflows/publish.yml, package.json
=> Move publishing back to Azure Dev Ops ***NO_CI***

RNTester/js/TextExample.macos.js, RNTester/js/TouchableExample.js, scripts/auto-sync-reactnative-to-sdxplatform.js, scripts/auto-sync-sdxplatform-to-reactnative.js
Fixing a few minor lint warnings.
(mostly testing CI)
=> Minor lint fixes

README.md
=> Remove merge conflict artifacts in Readme

ReactAndroid/build.gradle
=> Fix typo in gradle file

.ado/android-pr.yml, ReactCommon/turbomodule/core/TurboCxxModule.cpp, ReactCommon/turbomodule/core/TurboModule.cpp, ReactCommon/turbomodule/core/TurboModuleBinding.cpp, ReactCommon/turbomodule/core/TurboModuleBinding.h
Unlike BUCK in Facebook, our build system doesn't make aliases for folders. In this change I fixed a few `#include<...>` lines to make the code compile.
Also removed a warning for x64, which is introduced in `TurboModule.cpp` by passing a `size_t` value to a `unsigned int` parameter.
General Fixed - Preparing work for adding JSI and TurboModule to ReactCommon in Microsoft/react-native-windows
N/A
=> Preparing work for adding JSI and TurboModule to ReactCommon in Microsoft/react-native-windows

.ado/android-pr.yml, .ado/apple-pr.yml
Cherry-picking https://github.com/microsoft/react-native/pull/202 
(optional)
=> Add 0.59-stable branch to PR build trigger

local-cli/generate-macos.js, local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.h, local-cli/generator-macos/templates/macos/HelloWorld-macOS/AppDelegate.m, local-cli/generator-macos/templates/macos/HelloWorld-macOS/ViewController.h, local-cli/generator-macos/templates/macos/HelloWorld-macOS/ViewController.m, local-cli/generator-macos/templates/macos/HelloWorld-macOS/main.m, local-cli/generator-macos/templates/macos/HelloWorld.xcodeproj/project.pbxproj, local-cli/generator-macos/templates/macos/HelloWorld/AppDelegate.h, local-cli/generator-macos/templates/macos/HelloWorld/AppDelegate.m, local-cli/generator-macos/templates/macos/HelloWorld/main.m, packages/react-native-macos-init/package.json
Addresses some of the feedback I left on https://github.com/microsoft/react-native/pull/291
=> Minor macOS generator related changes

.ado/publish.yml
Fix authentication for publishing
=> Publishing fix

.ado/publish.js
Fix in the build pipeline.
Fixing a syntax error in the git command by completed the double quotes around the commit message string
Fixing a syntax error in the git command by completed the double quotes around the commit message string
Verify publish works
=> Fixing a syntax error in the git commit command 

.ado/android-pr.yml, .ado/npmOfficePack.js, .ado/publish.yml, package.json
=> Publish verification in PR job

.ado/android-pr.yml, android-patches/patches-0.62.2/BasicBuild/ReactAndroid/ReactAndroid.nuspec
I have a suspicion that the NuGet isn't succeeding, so I want to add a check to verify that for future PRs.  (I'll need to fix the NuGet as part of this PR too if I'm correct)
nuspec file needs to be case sensitive now that the NuGet is getting created on a unix box.
=> Verify that NuGet was actually created

RNTester/Podfile.lock, React/CoreModules/RCTRedBox.mm, React/Modules/RCTRedBoxExtraDataViewController.h, package.json
Fixes #553 
See the commit messages.
=> Fix a few v0.62 issues

.ado/publish.yml
Same as #582 but for `master`.
=> [ado] Fix dist-tag determination

.ado/publish.yml
Same as #584 but for `master`.
=> [ado] Get rid of trailing quote in npm dist-tag

React/CoreModules/RCTRedBox.mm
The RedBox could get an app in a “stuck” state because it would completely pause the main dispatch queue. This was especially evident by changing a style to be an incompatible value (e.g. `width: '50px'`), which would get you in a state where you'd need to just kill and restart the application.
Calling `[NSApp runModalForWindow:]` will result in a new runloop that does not process the main dispatch queue. This change instead runs a modal session on the main runloop that still processes the main dispatch queue.
Further reading:
- https://www.thecave.com/2015/08/10/dispatch-async-to-main-queue-doesnt-work-with-modal-window-on-mac-os-x/
- https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/WinPanel/Concepts/UsingModalWindows.html
[macOS] [Fixed] - Fix modal RedBox not …
=> Fix modal RedBox not running main dispatch queue

Libraries/Lists/VirtualizedList.js
Applying the changes from https://github.com/microsoft/react-native-macos/pull/532 to 0.62-stable branch. 
According to the comments in the source code
`"Note that this._scrollRef might not be a ScrollView" that is already in the codebase this._scrollRef.scrollTo can not always be called directly.`
This was already fixed in https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js#L373 and on Microsoft's RN master (https://github.com/microsoft/react-native-macos/pull/532).
Adding safeguard-checks for all the places where _scrollRef.scrollTo() is called.
This problem was spotted when some components using VirtualizedList in some conditions started to fail in runtime.
Digging deeper it became apparent that it is a bug inside VirtualizedList and it was already …
=> Apply the patch for VirtualizedList throwing an error to 0.62-stable

.ado/templates/prep-android-nuget.yml
=> [ado] Try to fix android/office publish task

.ado/publish.yml, .ado/waitForVerdaccio.js
Add back localhost
[iOS/macOS] [Fix] - CI fix
CI passes
=> change back to localhost

.ado/templates/apple-node-setup.yml
=> [ado] Fix homebrew issue

Libraries/Components/Button.js, Libraries/Components/View/ReactNativeViewViewConfig.js, Libraries/Components/View/ViewAccessibility.js, RNTester/js/examples/AccessibilityShowMenu/AccessibilityShowMenu.js, RNTester/js/examples/KeyboardEventsExample/KeyboardEventsExample.js, RNTester/js/utils/RNTesterList.ios.js, React/Base/RCTConvert.m, React/Views/RCTView.h, React/Views/RCTView.m, React/Views/RCTViewManager.m
Cherry pick https://github.com/microsoft/react-native-macos/pull/691 to 0.62 branch. This change made improvements to the keyboarding support for macOS.
Tested keyboarding support in RNTester.
=> Cherry pick d3acc6d for 0.62 branch

React/Modules/RCTI18nUtil.h, React/Modules/RCTI18nUtil.m
Cherry Pick 24c16b1527c071e8f37d8dbdd5319ca992ac4628 into 0.62-stable
[iOS] [Fixed] - Fix deadlock on RCTi18nUtil
=> Cherry Pick 0.62-stable deadlock fix

Libraries/Animated/src/nodes/AnimatedValue.js, RNTester/Podfile.lock
cherry-pick https://github.com/microsoft/react-native-macos/pull/763
[General] [Fixed] - cherry-pick animation fix
=> cherry-pick animation fix to 0.63

Libraries/WebSocket/RCTSRWebSocket.m
* Update RCTCxxBridge.mm
* Update RCTCxxBridge.mm
* run loop nil check
Co-authored-by: Chris Hogan <chrishogan@Chriss-MacBook-Pro-2.local>
=> Nil check our run loop thread (#771)

RNTester/Podfile, RNTester/Podfile.lock, RNTester/RNTesterPods.xcodeproj/project.pbxproj, React/CoreModules/RCTWebSocketModule.mm
`git cherry-pick 415abb553e33e93586e7c74a36f8eddb0266dc6d`
=> Url nil check

Libraries/StyleSheet/PlatformColorValueTypes.macos.js, Libraries/StyleSheet/PlatformColorValueTypesMacOS.js, Libraries/StyleSheet/PlatformColorValueTypesMacOS.macos.js, RNTester/Podfile.lock, RNTester/js/examples/PlatformColor/PlatformColorExample.js, React/Base/RCTConvert.m, React/Base/macOS/RCTDynamicColor.m, index.js
This is just ` git cherry-pick 5a3ee83efeec124b3aedbcccc90f2a878b75917e`
=> Cherry pick "ColorWithSystemEffectMacOS" into 0.63-stable

android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec
=> Remove another duplicate in nuspec file

React/Base/RCTJSInvokerModule.h
Some downstream dependencies have non null checks that fail here if we don't tag appropriately. This is also a virtuous change as it adds clarity to the method header.
[Bug] [iOS/macOS] - Nonnull compatibility check
No functional change
=> Nullable compatibility

React/Base/RCTJSInvokerModule.h
=> Port #896 to 0.64

Libraries/Image/RCTImageLoader.mm, React/Base/RCTDefines.h, React/Base/RCTRootView.m, React/CoreModules/RCTDevLoadingView.mm, React/CoreModules/RCTDevMenu.mm, React/CoreModules/RCTDevSettings.h, React/CoreModules/RCTDevSettings.mm, React/CxxBridge/RCTCxxBridge.mm
[Summary is here](https://github.com/microsoft/react-native-macos/pull/888)
[Link to changelog](https://github.com/microsoft/react-native-macos/pull/888)
`git cherry-pick 2bb6d93ed6443c0fbbddf2748deb2945316cb7ce` to pull our change from master into our stable branch.
=> Disable ship debugging cherry-pick

React/CoreModules/RCTActionSheetManager.mm
Cherry pick from master into 0.64
`git cherry-pick 2e9dd121f2d0377827a594fc011d0d59e10b4991`
=> Don't pass nil objects into error logging dict

.ado/apple-integration.yml
Make whatever changes I need to have the CI pass on the 0.66 branch.
[Internal] [Fixed] - Fix / comment out tests in CI till it passes
=> [0.66] Fix Integration CI check

.ado/android-pr.yml
Building the rn-tester app for Android was broken due to a missed patch update. Building the rn-tester app wasn't done as part of the PR pipeline, which is why it wasn't caught.
[Android] [Added] - Adding step in PR pipeline to build the rn-tester app for android
=> Adding step to build rn-tester app for android in PR pipeline

.ado/android-pr.yml, android-patches/patches/Build/ReactAndroid/Android-prebuilt.mk
[Android] [Fixed] - Ensuring rn-tester app for Android builds successfully and adding step in pr pipeline to do so
Already checked into main, just a cherry-pick
=> Cherry pick changes to fix building rn-tester app for android from main to 0.64-stable

.github/workflows/codeql-analysis.yml
use github action template to sape javascript code
=> creaate codeql-analysis.yml

.ado/apple-integration.yml, Libraries/Text/TextInput/RCTBackedTextInputDelegate.h, Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m, Libraries/Text/TextInput/RCTBaseTextInputView.m, packages/rn-tester/Podfile.lock
Cherry-pick #1044 into 0.64-stable
=> [0.64] Handle "Escape" key for TextInput

.github/workflows/codeql-analysis.yml
remove running codeql for stable branches.
=> run codeql only for main branch

.ado/android-pr.yml, .ado/publish.yml, .ado/variables/vars.yml
Update ubuntu pools to use a compliant pool
[Internal] [changed] - Update release pipelines
N/A
=> Move to compliant pool for Ubuntu

.ado/android-pr.yml, .ado/publish.yml, .ado/templates/apple-job-javascript.yml, .ado/templates/react-native-macos-init.yml, .config/CredScanSuppressions.json, GuardianCustomConfiguration.json, package.json, repo-config/package.json, yarn.lock
Update the publish pipeline to run the required compliance tasks.
This also moves the pipeline from dev.azure.com/ms to dev.azure.com/office/iss
[Internal] [Changed] - Updated publish pipeline with tasks required for compliance 
N/A
=> Add compliance jobs

React/Base/macOS/RCTPlatformDisplayLink.m
The `_modes` added to the display link were being ignored in favor of always running on `kCFRunLoopDefaultMode`. This would cause animations to not run when in `NSEventTrackingRunLoopMode`, which is a member of `NSRunLoopCommonModes`. This fixes that by passing the `_modes` into `CFRunLoopPerformBlock`, which does accept an array:
> A CFString that identifies a runloop mode, or a CFArray of CFStrings that each identify a runloop mode.
This also protects `_runloop` and `_modes` with the existing spin lock that is meant to protect them (see the `invalidate` method below).
Reviewed By: lyahdav
Differential Revision: D27721006
[macOS] [Fixed] - Pass in correct runLoopMode in RCTPlatformDisplayLink
Fixes long press on selectable text (in Messenger Desktop):
=> Fix RCTPlatformDisplayLink runloop modes

.ado/publish.yml
[Internal] [Changed] - CG is no longer auto-injected. Adding manually for now
N/A
=> CG is no longer auto-injected. Adding manually for now

React/Base/RCTConvert.m
Same as #1079 except to the 0.66 branch
[macOS] [Fixed] - Fix AccessibilityRole of MenuItem
=> [0.66] Fix AccessibilityRole of MenuItem

.github/CODEOWNERS
Let's just fix this so we don't ping the wrong people anymore
=> [0.66] Update CODEOWNERS

bots/datastore.js, bots/package.json, bots/report-bundle-size.js, bots/yarn.lock, scripts/circleci/report-bundle-size.sh
Cherry-pick 3024ec7ce667e1526197ddd38da0e3b663bf06c6. This resolves a security issue in an older version of `firebase`.
=> Upgrade to `firebase^9.0.2` in ./bots (#32218)

Libraries/Components/AccessibilityInfo/AccessibilityInfo.js
This is a cherry-pick of #1084.
Command run:
`git cherry-pick fbb7ca800b99c137551f735451457a2e48bc6ed1 fa75b96462cea537eafab974a922ee7f400d6701`
=> [0.66-stable] Rearrange the logic in AccessibilityInfo.js to ensure it works nicely with macOS

bots/datastore.js, bots/package.json, bots/report-bundle-size.js, bots/yarn.lock, scripts/circleci/report-bundle-size.sh
This is a cherry-pick of https://github.com/microsoft/react-native-macos/pull/1083.
Command run:
git cherry-pick 3024ec7ce667e1526197ddd38da0e3b663bf06c6
=> [0.64-stable] Upgrade to firebase^9.0.2 in ./bots (#32218)

bots/datastore.js, bots/package.json, bots/report-bundle-size.js, bots/yarn.lock, scripts/circleci/report-bundle-size.sh
This is a cherry-pick of #1083.
Command run:
`git cherry-pick 3024ec7ce667e1526197ddd38da0e3b663bf06c6`
=> [0.66-stable] Upgrade to firebase^9.0.2 in ./bots (#32218)

Libraries/Text/Text/RCTTextView.m, React/Views/RCTView.m, packages/rn-tester/Podfile.lock
`git cherry-pick e68278c5880ab2c1b5ae8545ea76e0b23d2ce7d1`
=> [64] Remove assumptions on super's description (#1088)

android-patches/patches/Build/ReactAndroid/build.gradle, android-patches/patches/Build/ReactAndroid/packages.config, android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8ExecutorFactory.cpp, android-patches/patches/V8/ReactAndroid/src/main/jni/third-party/v8jsi/Android.mk
The version of v8 jsi being consumed is outdated, resulting in ABI changes causing crashes for consumers outside of Office.
[Android] [Fixed] - Update v8jsi package version
Built locally, ensuring the new package was downloaded.
=> Update v8jsi package version for Android

android-patches/patches/Build/ReactAndroid/build.gradle, android-patches/patches/Build/ReactAndroid/packages.config, android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8ExecutorFactory.cpp, android-patches/patches/V8/ReactAndroid/src/main/jni/third-party/v8jsi/Android.mk
The version of v8 jsi being consumed is outdated, resulting in ABI changes causing crashes for consumers outside of Office.
[Android] [Fixed] - Update v8jsi package version
Built locally, ensuring the new package was downloaded.
=> Backport - Update v8jsi package version for Android

React/CoreModules/RCTActionSheetManager.mm
Cherry-pick of #1115.
Done by running `git cherry-pick 0807422e8a950c5ad48f2b34c53d9a0fadd64d76`
=> [0.66-stable] Synthesize -[RCTActionSheetManager bridge] on macOS

Libraries/Text/TextInput/RCTBaseTextInputView.m
Cherry-pick of 57c8333ddcd932e981416dff4f44b49ab08455aa (#1120).
=> [0.66-stable] Add a nil check to prevent a crash

bots/package.json, bots/yarn.lock
=> [0.66-stable] Update Danger JS to v11

React/Views/ScrollView/MacOS/RCTScrollContentLocalData.h, React/Views/ScrollView/MacOS/RCTScrollContentLocalData.m, React/Views/ScrollView/RCTScrollContentView.m
Backport #1132  to 0.66-stable
=> [0.66] Backport scrollview fix

Libraries/WebSocket/RCTSRWebSocket.m
=> [0.66-stable] Add debug logging to -[RCTSRWebSocket _connect]

.ado/variables/vars.yml, packages/rn-tester/Podfile.lock
Updating the pipeline to be run in internal-macos12 with xcode13.3.1 version.
=> update the pipeline to xcode13.3.1

React/Modules/RCTUIManager.m
Cherry pick of #1147.
Done by running `git cherry-pick 6cf8991 9ffb30b 13bd620 4d1722a 82b9f9a`.
=> [0.66-stable] Improve red box error logging in `moduleConstantsForComponent(...)`

.github/CODEOWNERS
Fixes [AB#6046400](https://office.visualstudio.com/e853b87d-318c-4879-bedc-5855f3483b54/_workitems/edit/6046400)
Allows rnandroid to have ownership of android specific pipeline related files.
[Android] [Internal] - Update ownership of ado files
Non-testable change.
=> Update ado file ownership

.github/CODEOWNERS
Cherry-pick the change to codeowners to 0.66-stable as we are still doing development there
[Android] [Internal] - Update code owners
Verified this is working as expected in main.
=> cherry pick - update ado file ownership

.ado/android-pr.yml, .ado/templates/download-android-dependencies.yml
Now that 0.66-stable is publishing successfully, we need to port the changes to consume maven-dependency-utils to the main branch
[Android] [Internal] - Cherry-pick fixes from 0.66-stable publishing to main
PR build succeeds
=> Cherry pick android publish fixes

.ado/templates/apple-node-setup.yml, Brewfile, Brewfile.lock.json, android-patches/patches/Hermes/yarn.lock, package.json, yarn.lock
=> [0.66-stable] Resolve workspace-tools to at least 0.18.4

bots/yarn.lock
This resolves a vulnerability in an old version of `protobufjs@6.11.2` as described [here](https://snyk.io/test/npm/protobufjs/6.11.2).
=> Run `yarn upgrade` in bots/ folder

bots/yarn.lock
Cherry pick of #1185, although I ran `yarn upgrade` afterwards anyway to resolve merge conflicts.
=> [0.66-stable] Run `yarn upgrade` in bots/ folder

android-patches/patches/Focus/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java, package.json
Fixing the line numbers in the patch file so that it gets applied correctly.
Fixing the line numbers in the focus patch file so that it gets applied correctly.
Fixing the line numbers in the focus patch file so that it gets applied correctly.
Verified the local bulid.
=> Fixing the focus patch

bots/yarn.lock, packages/eslint-config-react-native-community/yarn.lock
Run `yarn upgrade` in some places besides the root of the repo to get rid of some dependabot alerts.
[Internal] [Security]
=> Run `yarn upgrade` in a couple more places

.ado/publish.yml, .ado/templates/react-native-macos-init.yml, scripts/set-rn-version.js
source -> . and add [test] comment
=> Attempt to fix 0.68 publish pipeline

package.json, yarn.lock
=> [0.68-stable] Update shell-quote to ^1.7.3

.ado/templates/react-native-macos-init.yml, package.json, yarn.lock
=> [0.66-stable] Upgrade shell-quote to ^1.7.3

android-patches/patches/V8/packages/rn-tester/android/app/build.gradle
This change disables fabric through a patch for rn-tester, since we are not packaging fabric related native libraries.
[Android] [Internal] - Disable fabric for rn-tester
Tested rn-tester and ensured the app works
=> Disable fabric for rn-tester through patch

android-patches/patches/V8/packages/rn-tester/android/app/build.gradle, android-patches/patches/V8/packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterApplication.java
This PR adds a v8 variant for rn-tester and ensures each variant loads the appropriate executor.
[Android] [Internal] - Add V8 variant for rn-tester
Tested the built apks and verified the appropriate executor was being used.
=> Create v8 variant for rn-tester 0.68-stable

android-patches/patches/V8/packages/rn-tester/android/app/build.gradle, android-patches/patches/V8/packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterApplication.java
This change cherry-picks some changes made in 0.68-stable to ensure that we build a variant for v8 for rn-tester and that rn-tester chooses the appropriate variant.
[Android] [Internal] - Cherry-pick rn-tester v8 variant changes
Tested built rn-tester apks and ensured the appropriate executor was being used.
=> Cherry pick rn tester fixes

android-patches/patches/V8/packages/rn-tester/android/app/build.gradle
Building the v8 variant of rn-tester standalone might fail due to task dependencies not being configured properly. Namely, we need to copy prebuilt libs to the rntester build dir, so that we can link against them.
[Android] [Internal] - Set up task dependencies for V8 configuration of rn-tester
Ensure the V8 variant builds correctly.
=> hook up v8 configuration dependencies

.ado/templates/download-android-dependencies.yml
Changing to the Office feed requires manually pip installing requests. 
[Android] [Internal] - Adding missing requests python package
Check that the publish pipeline succeeds.
=> Fix missing requests python package

Libraries/Lists/FlatList.js
I'm a derp who maked a macOS only method as iOS. Fixing that now!
=> Update comment in Flatlist.js

React/Views/RCTView.m
Cherry-pick ea192044d504b574eb82c9dd8c19a2d4d0d1d96f to 0.66-stable.
=> [0.66-stable] Textinput range fix

React/Views/RCTView.m
Cherry-pick ea192044d504b574eb82c9dd8c19a2d4d0d1d96f to 0.68-stable.
=> [0.68] Textinput range fix

.ado/android-pr.yml, .ado/publish.yml, .ado/templates/android-nuget-pack.yml, android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec
Cherry-pick some of the fixes made to the Android nuget-packing task in 0.68-stable to main. These fixes ensure that all paths referenced in the nuspec are correct, and that the nuget pack task doesn't silently fail.
[Android] [Internal] - cherry-pick nuget pack fixes from 0.68-stable
Ensure that the PR build succeeds.
=> Cherry pick nuget fixes

.ado/publish.yml
=> [0.68] Increase Office publish timeout to 120 minutes

.ado/publish.yml
=> [0.66] Increase Office publish timeout to 120 minutes

.ado/android-pr.yml, .ado/publish.yml, .ado/variables/vars.yml
Switching to an agent pool with VMs with better resources to improve PR times.
[Android] [Internal] - Switch agent pool to improve PR times
Ensure PR build succeed and is faster than before.
=> switch to large pool for faster PR times

.ado/android-pr.yml, .ado/publish.yml, .ado/variables/vars.yml
Switching to an agent pool with VMs with better resources to improve PR times.
[Android] [Internal] - Switch agent pool to improve PR times
Ensure PR build succeed and is faster than before.
=> Cherry-pick changes to agent pools from 0.68-stable to main

React/Views/RCTView.m
=> [0.66] Fix shadow consistency issue

React/Views/RCTView.m
=> [0.68] Fix shadow consistency issue

android-patches/patches/Build/ReactAndroid/build.gradle
Match Office NDK so that debug symbols can be stripped correctly
[Android] [Internal] - Match ndk with Office
Ensure PR build succeeds and locally test with new nuget package
=> Match ndk with Office

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m
Cherry-picking https://github.com/microsoft/react-native-macos/commit/96be39d8cddcc57c2dcfef737808c07402a3f24d to the 0.66-stable branch.
=> [0.68] Add scrollbar to multiline TextInput (#1366)

React/Views/RCTView.m, React/Views/UIView+React.h, React/Views/UIView+React.m, packages/rn-tester/js/examples/FocusOnMount/FocusOnMount.js, packages/rn-tester/js/utils/RNTesterList.ios.js
Cherry picking from main branch -- 8b8fc6196952be0c12bb0f7631465a655bdf39c1
=> [0.68] Fixing setting focus when RCTView is not yet in window (#1398)

React/Views/RCTView.m, React/Views/UIView+React.h, React/Views/UIView+React.m, packages/rn-tester/js/examples/FocusOnMount/FocusOnMount.js, packages/rn-tester/js/utils/RNTesterList.ios.js
Cherry picking from main branch -- https://github.com/microsoft/react-native-macos/commit/8b8fc6196952be0c12bb0f7631465a655bdf39c1
=> [0.66] Fixing setting focus when RCTView is not yet in window (#1398)

.ado/publish.yml
We would like to publish out of the main branch to internal npm feeds. As a result, we need to run the publishing tasks for main.
[Android] [Internal] - Publish out of main
Ensure the PR checks succeed and ensure the CD pipeline succeeds as well.
=> Remove branch check on publishing tasks

.ado/publish.yml
Reverts microsoft/react-native-macos#1430
=> Revert "Remove branch check on publishing tasks"

packages/react-native-macos-init/package.json, yarn.lock
=> [0.68-stable] Bump beachball to 2.30.1

Libraries/Text/TextInput/Multiline/RCTUITextView.m, Libraries/Text/TextInput/Singleline/RCTUITextField.m, React/Base/RCTTouchHandler.m
Cherry-picking 1d0e105ab399398cc6305dcb280c7d41394f70e3
=> [0.68] Fix insertion point and placeholder placement for TextInput

.ado/publish.yml
Cherry-picking 53971de9e29315d2bf2cbf66f283327563a433db
=> [0.68] Update yaml to add homebrew to PATH

android-patches/patches/Build/ReactAndroid/build.gradle, android-patches/patches/Build/ReactCommon/yoga/yoga/Yoga.cpp
Upgrade the NDK to 25 to match Office.
[Android] [Internal] - Upgrade NDK to match Office
Ensure PR build succeeds and we use NDK 25
=> Fixes AB#6847300 - Upgrade ndk 25 68

.ado/templates/download-android-dependencies.yml
The latest version of maven-dependency-utils automatically pulls in transitive python dependencies, so we do not need to explicitly pip install requests, which is never used directly.
[Android] [Internal] - Bump maven-dependency-utils and remove explicit dependency on requests
Ensure PR build succeeds.
=> Cherry-pick: Update maven dependency utils

android-patches/patches/Build/ReactAndroid/build.gradle, android-patches/patches/Build/ReactCommon/yoga/yoga/Yoga.cpp
Update the NDK to match Office.
[Android] [Internal] - Upgrade Android NDK to 25 to match Office.
Ensure PR build succeeds
=> Fixes AB#6828899 Update ndk to 25

Libraries/Lists/VirtualizedList.js
Copy of #1458 into 0.68-stable
=> [0.68] Flatlist: Let ArrowUp/ArrowDown bubble at the top/bottom of list

React/Fabric/Mounting/ComponentViews/ScrollView/RCTScrollViewComponentView.mm
https://github.com/facebook/react-native/commit/28a65f43878
Fix to reactwg/react-native-new-architecture#30
We have already applied this solution to both [pre-Fabric](https://www.internalfb.com/code/fbsource/[1da0f2e3164d6f87e8221e0f0462ae93fdc5cbdc]/xplat/js/react-native-github/React/Views/ScrollView/RCTScrollView.m?lines=361) and [Fabric](https://www.internalfb.com/code/fbsource/[1da0f2e3164d6f87e8221e0f0462ae93fdc5cbdc]/xplat/js/react-native-github/React/Fabric/Mounting/ComponentViews/ScrollView/RCTEnhancedScrollView.mm?lines=36) scroll views. However Fabric can reuse components, and this has to be reapplied at every reuse.
Changelog [iOS][Fixed] - ScrollView's contentInsetAdjustmentBehavior is reset to Never at every …
=> Cherry-pick: ScrollView fails when contentInsetAdjustmentBehavior is automatic

package.json, yarn.lock
0.68-stable counterpart of #1531.
=> [0.68] Resolve micromatch to ^4.0.0

.circleci/DockerTests.md, .circleci/Dockerfiles/Dockerfile.android, .circleci/Dockerfiles/scripts/run-android-ci-instrumentation-tests.js, .circleci/Dockerfiles/scripts/run-android-docker-instrumentation-tests.sh, .circleci/Dockerfiles/scripts/run-android-docker-unit-tests.sh, .circleci/Dockerfiles/scripts/run-ci-e2e-tests.sh, .circleci/Dockerfiles/scripts/run-instrumentation-tests-via-adb-shell.sh, .circleci/README.md, .circleci/config.yml
Reverts microsoft/react-native-macos#1360
=> [Draft] Revert "Remove .circleci folder"

package.json, yarn.lock
=> [0.68-stable] Resolve debug to at least 3.1.0

React/Views/RCTView.m
Cherry-picking 6a36bc7bf4e50ccc5fcaf3cfc3023a50d6261502
=> [0.68] Update accessibilityValue to include radio button state attribute

React/Base/RCTTouchHandler.m
Cherry-pick #1281 to 0.68-stable
=> [0.68 cherry-pick] Don't send events when clicking on scrollbars

Libraries/WebSocket/RCTSRWebSocket.m, packages/rn-tester/Podfile.lock, yarn.lock
For some reason #1725 didn't merge in the commits I made after feedback. This adds macOS tags and undoes the lock file changes.
=> Respect system proxy settings for WebSocket, take 2

Libraries/WebSocket/RCTSRWebSocket.m
Cherry pick of #1725 and #1726.
=> [0.68-stable] Respect system proxy settings for WebSocket

Gemfile.lock
Cherry pick of https://github.com/microsoft/react-native-macos/pull/1750
=> [0.68] Cherry pick of bumping activesupport to 6.1.7.3

bots/yarn.lock
Cherry pick of #1741 
Note - I wasn't sure how to resolve the merge conflict when cherry picking the change - I just took the incoming change.
=> [0.68] Cherry pick of bumping minimist from 1.2.5 to 1.2.8 in /bots (#1741)

template/Gemfile.lock
Cherry pick of https://github.com/microsoft/react-native-macos/pull/1749
=> [0.68] Cherry pick of bumping activesupport to 6.1.7.3 in /template (#1749)

.ado/publish.yml
... While we get the 0.71-stable release ready
=> Temporarily stop publishing stable branches

.ado/apple-pr.yml, .ado/templates/apple-job-react-native.yml, packages/rn-tester/NativeCxxModuleExample/NativeCxxModuleExample.podspec, packages/rn-tester/Podfile
Backport of #1782 to 0.71-stable
=> [0.71] Use RCT_NEW_ARCH_ENABLED flag for enabling new arch

React/Views/ScrollView/RCTScrollView.m
Cherry-pick of 4126fbe63d6bbfa90e7646871332f4d78179f1b5
=> [0.71] Handle edge case for setContentOffset with animation

Libraries/Text/TextInput/Multiline/RCTUITextView.m
Cherry pick of #1836 to 0.71-stable
=> [0.71] Update RCTUITextView to use the systemFontSize for macOS

Libraries/StyleSheet/PlatformColorValueTypes.macos.js
Cherry-pick of 1ae1543a6405e1df594fac9c2d48d24e9fcc671c
=> [0.71] Fix ColorWithSystemEffect not returning the correct base color

React/Base/RCTUIKit.h, React/Base/macOS/RCTUIKit.m, React/Views/RCTSwitchManager.m
=> [0.71][Switch] make sure `wasOn` is set properly

Libraries/Text/TextInput/RCTBaseTextInputView.m
Cherry pick https://github.com/microsoft/react-native-macos/pull/1895 to 0.71
=> [0.71] Add nil check to RCTBaseInputTextView

.github/workflows/autorebase.yml, .github/workflows/needs-attention.yml
Ignore workflow errors when comments are posted.
[INTERNAL] [FIXED] - Ignore workflow errors when comments are posted
n/a
=> chore: ignore workflow errors on issue comments

Libraries/Components/Pressable/Pressable.js, Libraries/Components/View/ViewPropTypes.d.ts, Libraries/Components/View/ViewPropTypes.js, Libraries/NativeComponent/BaseViewConfig.macos.js, React/Views/RCTView.h, React/Views/RCTView.m, React/Views/RCTViewManager.m
Cherry pick of #1889  to 0.71-stable
=> [0.71] Add new macOS View prop `allowsVibrancy`

packages/react-native/React/Views/RCTView.m
0.73-stable version of https://github.com/microsoft/react-native-macos/pull/1971.
Cherry-pick of [796412e](https://github.com/microsoft/react-native-macos/pull/1971/commits/796412ebc4c9bcca40f803ec1187de142489eea9).
=> [0.73-stable] Don't recreate identical NSTrackingAreas

packages/react-native/React/Views/RCTView.m
0.72-stable version of #1971.
Cherry-pick of [796412e](https://github.com/microsoft/react-native-macos/pull/1971/commits/796412ebc4c9bcca40f803ec1187de142489eea9).
=> [0.72-stable] Don't recreate identical NSTrackingAreas

packages/react-native/React/Base/RCTUIKit.h, packages/react-native/React/Base/RCTUtils.h, packages/react-native/React/Base/RCTUtils.m, packages/react-native/React/CoreModules/RCTDeviceInfo.mm, packages/react-native/React/UIUtils/RCTUIUtils.h, packages/react-native/React/UIUtils/RCTUIUtils.m
=> [0.73] Default scale to 1.0 on if window is nil

React/CxxBridge/JSCExecutorFactory.h
Cherry pick of #1976 to `0.71-stable`
=> [0.71][JSCRuntime] Only enable the JSC debugging in DEBUG by default

packages/react-native/React/CxxBridge/JSCExecutorFactory.h
Cherry pick of #1976 to `0.72-stable`
=> [0.72][JSCRuntime] Only enable the JSC debugging in DEBUG by default

packages/react-native/React/CxxBridge/JSCExecutorFactory.h
Cherry pick of #1976 to `0.73-stable`
=> [0.73][JSCRuntime] Only enable the JSC debugging in DEBUG by default

packages/react-native/package.json
I just fixed typo in package.json.
I noticed this because I couldn't move to this repository from npm site's repository link.
[INTERNAL] [FIXED] - Fixed repository url typo
=> fix typo in url

packages/react-native/package.json
=> [0.73] Fix typo in package.json URL

.ado/templates/apple-job-publish.yml
Backport of #2027 to 0.73-stable
=> [0.73][CI] Only echo `RNM_PACKAGE_VERSION` after it has been set

packages/react-native/Libraries/PushNotificationIOS/NativePushNotificationManagerIOS.js, packages/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.h, packages/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.mm, packages/rn-tester/RNTester/AppDelegate.mm
Backport of #2031 to `0.73-stable`
=> [0.73][Cherry Pick] Refactor RCTPushNotificationManager to use `UNNotification`

packages/react-native/Libraries/PushNotificationIOS/NativePushNotificationManagerIOS.js, packages/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.h, packages/react-native/Libraries/PushNotificationIOS/RCTPushNotificationManager.mm, packages/rn-tester/RNTester/AppDelegate.mm
Backport of #2031 to `0.72-stable`
=> [0.72][Cherry Pick] Refactor RCTPushNotificationManager to use `UNNotification`

.ado/variables/vars.yml
Update CI to use the latest available Xcode stable release.
=> Update to Xcode 15.2

packages/react-native/Libraries/Text/React-RCTText.podspec
Backport of #2060 to 0.73-stable
=> [0.73][visionOS] Followup fixes

packages/react-native/Libraries/Text/React-RCTText.podspec, packages/react-native/React/CoreModules/RCTDeviceInfo.mm
Backport of #2060 to 0.72-stable
=> [0.72][visionOS] Followup fixes

Gemfile.lock, packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/react-native/template/package.json, packages/rn-tester/Podfile.lock
Realign the Github and NPM package versions again to unblock the publish pipeline.
=> [0.72] Align NPM and Github versions again

packages/react-native/local-cli/generator-macos/templates/macos/HelloWorld.xcodeproj/project.pbxproj
Backport of #2067 to 0.73-stable
=> [0.73] Set build settings required for Swift in the template project

.circleci/configurations/executors.yml, .circleci/configurations/jobs.yml, packages/react-native/Libraries/LogBox/Data/__tests__/parseLogBoxLog-test.js, packages/react-native/Libraries/LogBox/Data/parseLogBoxLog.js, packages/react-native/React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm, packages/react-native/scripts/cocoapods/utils.rb, packages/react-native/scripts/react_native_pods.rb, packages/react-native/sdks/hermes-engine/hermes-utils.rb
Merge 0.73.6 from upstream into 0.73-stable
=> [0.73] Merge 0.73.6 from upstream 

packages/react-native/Libraries/Text/TextInput/RCTBaseTextInputView.mm
=> [0.73-stable] Ensure ghost text doesn't appear when performing undos

packages/react-native/React/Base/RCTTouchHandler.m
=> [0.73-stable] Send mouseUp events for NSTabView

packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
Backport of #2115 to 0.73-stable
=> [0.73] Implement `[RCTUITextField selectedRange]`

packages/react-native/React/CoreModules/RCTAlertController.mm, packages/react-native/React/CoreModules/RCTAppearance.mm
Backport of #2125 to 0.73-stable
=> [0.73][CherryPick]  Fix retrieving current appearance in multi-window apps

packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm, packages/react-native/React/Base/RCTConstants.h, packages/react-native/React/Base/RCTConstants.m, packages/react-native/React/Base/RCTRootContentView.m, packages/react-native/React/CoreModules/RCTDeviceInfo.mm
Pick up https://github.com/facebook/react-native/commit/d46d80d2ef6cdc05c5a1b2429ed1df93410ae36f and https://github.com/facebook/react-native/commit/44159e35ce21910a7c1f0f66807f43512b442b3c from upstream to fix a potential hang we're seeing internally
CI should pass
=> [Hotfix] Pick up RCTDeviceInfo fix from upstream

Gemfile.lock, yarn.lock
Delete the lock files and reinstall to address some CVEs
CI should pass
=> [0.73] chore: Update yarn and gem locks

packages/react-native/Libraries/Text/TextInput/RCTBaseTextInputView.mm, packages/react-native/Libraries/Text/TextInput/Singleline/RCTUITextField.mm
0.73-stable port of #2159 and #2160.
=> [0.73-stable] Make TextInput events more reliable (#2159 + #2160)

packages/react-native/React/CoreModules/RCTDevLoadingView.mm
=> [0.75] fix: Properly clean up RCTDevLoadingView on hide

packages/react-native/Libraries/Text/TextInput/Multiline/RCTUITextView.mm
=> [0.75] Multiline TextInput key handling: add check for first responder

packages/react-native/local-cli/runMacOS/runMacOS.js
Fix `run-macos` failing to find Xcode project
n/a
=> fix(react-native): fix `run-macos` failing to find Xcode project

packages/react-native/local-cli/runMacOS/runMacOS.js
Fix `run-macos` failing to find Xcode project
n/a
=> fix(0.75, react-native): fix `run-macos` failing to find Xcode project

packages/react-native/local-cli/runMacOS/runMacOS.js
Fix `run-macos` failing to find Xcode project
n/a
=> fix(0.74, react-native): fix `run-macos` failing to find Xcode project

.ado/templates/apple-steps-publish.yml
Same as #2257 , but targeting `main`
=> fix(publish): use `set-version` instead of `set-rn-version`

yarn.lock
Remove dependency on ip v2.0.0 to resolve CG alerts.
=> Remove dependency on ip (0.74)

.ado/templates/apple-tools-setup.yml
Somehow this changed. Lets' just remove the line
=> ci: don't print Brewfile.lock.json

packages/react-native/Libraries/Image/RCTImageView.mm, packages/react-native/Libraries/Image/RCTImageViewManager.mm, packages/rn-tester/js/examples/Image/ImageExample.js
See https://github.com/microsoft/react-native-macos/pull/2327 for summary of changes.
=> [0.74-stable] Fix accessible prop for image

packages/react-native/Libraries/Image/RCTImageView.mm, packages/react-native/Libraries/Image/RCTImageViewManager.mm, packages/rn-tester/js/examples/Image/ImageExample.js
See https://github.com/microsoft/react-native-macos/pull/2327 for summary of changes.
=> [0.75-stable] Fix accessible prop for image

packages/react-native/Libraries/Image/RCTImageView.mm, packages/react-native/Libraries/Image/RCTImageViewManager.mm, packages/rn-tester/js/examples/Image/ImageExample.js
See https://github.com/microsoft/react-native-macos/pull/2327 for summary of changes.
=> [0.76-stable] Fix accessible prop for image

packages/react-native/React/Base/RCTRootView.m
Cherry-pick of #2323 and #2325 to 0.76-stable.
=> [0.76-stable] Send JS blur/focus events when switching to another NSWindow

Gemfile, packages/rn-tester/Gemfile
Cherry pick https://github.com/facebook/react-native/commit/198adb47af3676c85b35adb308c110c1d87120c8 to fix an issue with Ruby, where the gem `concurrent-ruby` updated and broke our workflow
CI should pass
=> ci(0.74): fix ruby

Gemfile, packages/helloworld/Gemfile, packages/rn-tester/Gemfile
Cherry pick https://github.com/facebook/react-native/commit/198adb47af3676c85b35adb308c110c1d87120c8 to fix an issue with Ruby, where the gem `concurrent-ruby` updated and broke our workflow
CI should pass
=> ci(0.75): fix ruby

.ado/jobs/nuget-publish.yml
According to some internal 1ES docs, I need to do this.
Merge and hope for the best..
=> ci: specify name and os in release pipeline

.nx/version-plans/version-plan-1739175990049.md, nx.json
Run the steps listed in `docs/releases.md` to prepare for a new minor release. 
Watch pipelines, hope it works.
=> ci(0.77): prepare nx for release

docs/Releases.md
FIle path changed, lets update,
N/A
=> docs: fix typo in release docs

packages/react-native/Libraries/Network/RCTDataRequestHandler.mm, packages/react-native/Libraries/Network/RCTFileRequestHandler.mm
Backport of #2383 to 0.77-stable
=> fix(0.77): avoid race condition crash in `[RCTDataRequestHandler invalidate]`

packages/react-native/Libraries/Network/RCTDataRequestHandler.mm, packages/react-native/Libraries/Network/RCTFileRequestHandler.mm
backport of #2383 to 0.74-stable
=> fix(0.74): avoid race condition crash in `[RCTDataRequestHandler invalidate]`

packages/react-native/Libraries/Network/RCTDataRequestHandler.mm, packages/react-native/Libraries/Network/RCTFileRequestHandler.mm
backport of #2383 to 0.75-stable
=> fix(0.75): avoid race condition crash in `[RCTDataRequestHandler invalidate]`

.ado/scripts/prepublish-check.mjs, .ado/templates/npm-publish-steps.yml
Backport of #2410 to 0.77-stable
=> chore(0.77): fix prepublish script inconsistencies

.nx/version-plans/version-plan-1741844903183.md
Commit a change file to prepare CI for a patch release
=> chore(0.76): Prepare for patch release

nx.json
Looks like our release CI expects this for the latest stable release.
CI should pass
=> ci(0.78): set preid to ''

.ado/templates/npm-publish-steps.yml
This was unnecessary. Thanks @tido64 for pointing it out.
CI should pass
=> ci: remove unnecessary environment variable

.nx/version-plans/version-plan-1744766603658.md, .yarn/patches/@nx-js-npm-20.0.7-30719000fd.patch, nx.json, package.json, packages/nx-release-version/index.js, yarn.lock
Backport #2478 and #2477 to 0.76-stable
=> ci(0.76): Backport publish pipeline changes

.nx/version-plans/version-plan-1744766603658.md, .yarn/patches/@nx-js-npm-20.0.7-30719000fd.patch, nx.json, package.json, packages/nx-release-version/index.js, yarn.lock
Backport #2478 and #2477 to 0.77-stable
=> ci(0.77): Backport publish pipeline changes

.ado/jobs/build-test-rntester.yml, packages/react-native/package.json, packages/react-native/scripts/cocoapods/utils.rb, packages/react-native/sdks/hermes-engine/hermes-engine.podspec, packages/react-native/sdks/hermes-engine/hermes-utils.rb, packages/rn-tester/Podfile, yarn.lock
Based on #2530.
CIs should pass.
=> ci(0.75): Add Hermes to test matrix

.ado/scripts/prepublish-check.mjs
=> fix(0.78, ci): downgrade npm auth token list check to warning

packages/react-native/Libraries/Components/TextInput/TextInputState.js, packages/react-native/React/Views/RCTViewKeyboardEvent.m
=> chore(0.77): backport some changes

packages/react-native/Libraries/Components/TextInput/TextInputState.js, packages/react-native/React/Views/RCTViewKeyboardEvent.m
=> chore(0.74): backport some changes

.nx/version-plans/version-plan-1753834798331.md, packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/React/DevSupport/RCTPausedInDebuggerOverlayController.mm, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/virtualized-lists/package.json, yarn.lock
Update the yarn lock, add a .rnm-publish sentinel file, and try again
=> chore(0.77): fix yarn.lock and try publishing again

.ado/jobs/npm-publish.yml, .nx/version-plans/version-plan-1753834774679.md, packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/virtualized-lists/package.json, yarn.lock
=> ci(0.76): set npmAuthToken in yarnrc, not npmrc

.ado/jobs/npm-publish.yml, .nx/version-plans/version-plan-1753834838837.md, packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/virtualized-lists/package.json, yarn.lock
=> ci(0.78): set npmAuthToken in yarnrc, not npmrc

.ado/jobs/npm-publish.yml, .nx/version-plans/version-plan-1753834798331.md, packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/virtualized-lists/package.json, yarn.lock
=> ci(0.77): set npmAuthToken in yarnrc, not npmrc

.ado/scripts/prepublish-check.mjs
=> ci(0.78): check yarnrc if it exists

.ado/scripts/prepublish-check.mjs
=> ci(0.77): check yarnrc if it exists

.ado/jobs/npm-publish.yml, .nx/version-plans/version-plan-1754531007010.md, packages/react-native/Libraries/Core/ReactNativeVersion.js, packages/react-native/React/Base/RCTVersion.m, packages/react-native/ReactAndroid/gradle.properties, packages/react-native/ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java, packages/react-native/ReactCommon/cxxreact/ReactNativeVersion.h, packages/react-native/package.json, packages/virtualized-lists/package.json, yarn.lock
=> ci(0.76): fix typo

.nx/version-plans/version-plan-1754946145137.md
Looks like we missed adding a change file here. Let's do so to push a new release.
=> chore(0.77): push a new 0.77 release

.yarnrc.yml, package.json, packages/nx-release-version/package.json, yarn.lock
Mitigate https://github.com/nrwl/nx/security/advisories/GHSA-cxm3-wv7p-598c
=> ci(0.76): disable postinstall scripts and update nx

.ado/publish.yml
This file was removed with #2590 , let's remove the reference
=> ci(publish): exclude nonexistent vars.yml
