.github/PULL_REQUEST_TEMPLATE.md

Improves the PR template to help ensure people dont submit their PR to facebook/react-native by accident.

Expand PR template

---

RNTester/js/ActivityIndicatorExample.js
React/Views/RCTActivityIndicatorView.m

PROBLEM
ISS#3218502: LPC in Dark Mode: progress spinner doesn't spin/animate
The RCTActivityIndicatorView.m was flattening an NSColor and using its components to create layer contentFilter at the time that the `color` prop was being set.   In Mojave, NSColors should only ever be converted to colorspaces in one of four methods: updateLayer, drawRect:, layout, updateConstraints.  Since it was not performing the operation in any of these methods, the contentFilter was not responding to theme changes.
FIX
Override the updateLayer method and there flatten the _color prop to its components only if it exists, and then set the contentFilter.
PRODUCT IMPACT
Impacts any macOS SDX that uses the ActivityIndicator (LPC) and makes it render properly in all themes.
VERIFICATION 
Added semantic and …

Fix macOS ActivityIndicator to color properly in different themes

---

Libraries/WebSocket/WebSocket.js

See `WebSocket.js`, near [line 227](https://github.com/Microsoft/react-native/blob/master/Libraries/WebSocket/WebSocket.js#L227):
```
if (Platform.OS === 'android') {
WebSocketModule.close(statusCode, closeReason, this._socketId);
```
Currently, only Android ReactNative instances pass `closeReason` and `statusCode`.
For non-Android platforms, default values are hard-coded.
Windows Desktop (`win32`) has no reason to use these default values.
This change ensures those parameters are passed on from the JavaScript side.

For Windows Desktop, pass close code and reason to WebSocket.close()

---

Libraries/YellowBox/UI/YellowBoxList.js

Until we properly support % sizes in layout for win32, make yellowbox use something other than %'s

Temporary fix to make win32 yellowbox not use %'s for now

---

Libraries/Components/ActivityIndicator/ActivityIndicator.js

The `<ActivityIndicator>` for macOS was setting the `color` prop to a default grey color if the prop was absent in the JS.  This means that on macOS its never possible to have the default system color for the Activity Indicator because in the RCTActivityIndicator.m native implementation the setColor: method sets an NSColor ivar that if non-nil will set a contentFilter using that color.   So, even if the `color` prop was not set, the NSActivityIndicator would get a grey colored contentFilter applied.
The change essentially removes a delta from the original facebook ActivityIndicator.js file making it so that only the ios platform will ever default to grey.

Remove default color value for mac ActivityIndicator so that it uses

---

ReactAndroid/src/main/java/com/facebook/react/v8executor/OnLoad.cpp
ReactCommon/jsi/V8Runtime.h
ReactCommon/jsi/V8Runtime_droid.cpp
ReactCommon/jsi/V8Runtime_impl.h
ReactCommon/jsi/V8Runtime_shared.cpp

Adding logging support in V8Runtime for droid and logging failure message during exception.
Verified that V8Runtime is emitting error logs during V8 related exceptions.

Adding logging support on droid and logging failure message

---

ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java
ReactAndroid/src/main/jni/react/jni/OnLoad.cpp

RN 58 by default use JSC Runtime but we want to use V8 Executor, making necessary changes, which had been removed during merging to ensure that we fallback to V8 Executor in the absence of JavaScriptExecutorFactory.
Verified changes by commenting getJavaScriptExecutorFactory (where we are configuring V8 Runtime) that RN Tester is using V8 Executor flow.

Defaulting to V8 Executor flow on droid

---

ReactApple/ReactApple.nuspec

After merging with facebook react-native .58, the folly path in AppleReact.nuspec is out-of-date.  Update the path.

Updated folly path.

---

React/CMakeLists.txt

With RN58 some files were removed that are still references in the CMake builds.  This removes those references.

Cleanup dead files from cmake script

---

Folly/folly/portability/SysMman.cpp

(* pedantry alert! *)
Right-shifting a 32-bit value by 32 is, strictly, undefined behavior,
although every compiler worth its salt will understand that this is
just a funny way to generate 0. But anyways, this code causes VC++ to
emit warning C4293, which, per Office policy, may not be disabled.
Make sure that x64 and x86 both compile.

Fix C4293 warning in sysmman.cpp

---

ReactCommon/make.inc

Sync from internal

---

RNTester/android/app/build.gradle
ReactAndroid/build.gradle
ReactAndroid/src/main/jni/react/jni/Android.mk

Fixing few of the warning which come while building ReactAndroid.
Ensure project is building and RN Tester is running well.

Fixing few of the warning which come while building ReactAndroid

---

Folly/CMakeLists.txt
Folly/folly/Format.cpp
Folly/folly/String.cpp
Folly/folly/Utility.h
Folly/folly/container/detail/F14IntrinsicsAvailability.h
Folly/folly/dynamic.cpp
Folly/folly/json.cpp
Folly/folly/memory/detail/MallocImpl.h
Folly/folly/portability/Builtins.h
Folly/folly/portability/String.h
Folly/folly/portability/SysMman.cpp

Various fixes to get react-native-windows building with updated folly

---

RNTester/android/app/build.gradle
ReactAndroid/src/main/jni/Application.mk

Building RN droid for 64 bit plats
64 bit builds are passing

Building RN droid for 64 bit plats

---

ReactCommon/yoga/yoga/sources.inc

Fixing devmain build break for droid 64 bit platforms
Ensure arm64 and x64 flavor builds pass for droid

Fixing devmain build break for droid 64 bit platforms

---

Folly/folly/Conv.cpp
Folly/folly/Conv.h
Folly/folly/String-inl.h
Folly/folly/dirs
Folly/folly/hash/Hash.h
Folly/folly/json.cpp
Folly/folly/lang/Align.h
Folly/folly/lang/Bits.h
Folly/folly/sources.inc

Updated to build logic used internally, and supressions of some warnings that are treated as errors internally.

Fixes for internal builds

---

React/React.xcodeproj/project.pbxproj

The RCTSRWebSocket.h header is missing from the Copy Headers build phase.  The header is already a Project header but is just missing from the Copy Headers phase.
No code changes

Add RCTSRWebSocket.h to the Copy Headers phase.

---

RNTester/js/FlatListExample.js
RNTester/js/ListExampleShared.js
RNTester/js/RNTesterExampleList.js
React/Views/ScrollView/RCTScrollView.m

On macOS, when tabbing into a ScrollView the focus is going to the ScrollView itself instead of the first component inside the contents. There is already a JS prop called acceptsKeyboardFocus which is honored on View (RCTView). In macOS NSViews can be key focused if they respond YES to acceptsFirstResponder and YES to canBecomeKeyView. The RCTScrollView is a sublass of RCTView, and RCTView already has an acceptsFirstResponder implementation that regards the acceptsKeyboardFocus prop. But RCTScrollView also needs a canBecomeKeyView override that returns the value of acceptsKeyboardFocus prop.
Now ScrollView will honor the JS prop acceptsKeyboardFocus just as View does. But for Lists, the App may want focus to be settable on the List itself so that the arrow keys can adjust which item is …

Added canBecomeKeyView override to RCTScrollView

---

ReactCommon/jsi/V8Runtime_droid.cpp
ReactCommon/jsi/V8Runtime_shared.cpp
ReactCommon/jsi/V8Runtime_win.cpp
ReactCommon/jsi/dirs
ReactCommon/jsi/jsicore/sources
ReactCommon/jsi/jsiv8/sources
ReactCommon/jsi/sources.inc

Separate V8 code from the core JSI library (for internal Office linking purposes). Also move the folly:dynamic dependent constructor out of the shared runtime impl.
N/A

Separate V8 code from the core JSI library

---

Libraries/Text/Text/RCTTextView.m

On macOS when a large number of flex layouts are being performed, such as when a window is being resized, AppKit can throw an uncaught exception (-[NSConcretePointerArray pointerAtIndex:]: attempt to access pointer at index ...) during the dealloc of NSLayoutManager.  The _textStorage and its associated NSLayoutManager dealloc later from the time the ivar pointer is overwritten in an autorelease pool.
Manually removing the layout manager from _textStorage prior to release works around this issue in AppKit.
The same issue does not appear to impact the iOS version of NSLayoutManager.
A low risk fix: the _textStorage is only ever assigned via the [RCTTextView setTextStorage:contentFrame:descendantView:] method, and that method is only every called by RCTTextShadowView.m where it retrieved …

Workaround crash during layout on macOS

---

ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp

We introduced a hack in JSIExecutor to conditionally compile the creation of NativeModuleProxy as a JSI HostObject. This was needed in the days where the Chakra based JSI runtimes didn't support JSI HostObjects. We are now removing the conditional compilation as the Chakra based JSI runtimes do support HostObjects.
Tested that the native module dispatch is happening with ChakraJSIRuntime without pushing the native modules config upfront.

Remove Chakra specific conditional compilation hack from JSIExecutor 

---

Libraries/Text/Text/RCTTextView.m
React/React.xcodeproj/project.pbxproj

During the last merge of RN .58 into the Microsoft fork, the RCTWebViewManager.m accidentally got dropped from being compiled into the macOS target.   This results in a RedBox error when a WebView is rendered because the NativeModule is not available.
This was found in manual testing of the RNTester app.   It will impact an macOS app that uses a WebView.

RCTWebViewManager.m was missing from the macOS target

---

ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagerRegistry.java
yarn.lock

- I am making a change required for Microsoft usage of react-native
This is a temp fix suggested by @Rohit for fixing comments crash.
This should be reverted once an actual fix is applied.

Temp fix for comments crash

---

.ado/android-pr.yml
.ado/publish.yml

This adds verification to PRs that the android nuget is build able, so that we don't hit failures to pack it post check in.

Verify android nuget during pr

---

ReactAndroid/ReactAndroid.nuspec

Nuget should include build binaries.
Adds various built files to the nuget.

Include built binaries in droid nuget

---

RNTester/js/RNTesterExampleFilter.js
React/Views/ScrollView/RCTScrollView.m

The ScrollView components has props `showsVerticalScrollIndicator` and `showsHorizontalScrollIndicator`.   On iOS and Android the default values are `true`.   On iOS this happens because the JS prop is mapped to the UIScrollView properties of the same name.   On iOS these properties default to YES.   On macOS we map these props to NSScrollView hasHorizontalScroller and hasVerticalScroller which default to NO.
Let's change the macOS defaults to be consistent with the other plats on react-native.   If an App wants to deliberately suppress the scroll indicators it may do so by explicitly setting `showsVerticalScrollIndicator={false}` for all platforms.
The macOS implementation uses RCTCustomScrollView which is a subclass of NSScrollView.   In its designated initer init hasHorizontalScroll …

ScrollView on mac should default to scroll indicators being visible

---

.ado/android-pr.yml
.ado/publish.js
ReactAndroid/build.gradle

- I am making a change required for Microsoft usage of react-native
Giving an option to exclude all libs (using parameter "excludeLibs") from gets packaged inside ReactAndroid aar file.

Adding option to exclude all libs while building ReactAndroid aar

---

ReactAndroid/build.gradle
ReactAndroid/packages.config

Using optimized V8 bins which we are using in devmain, these bins exports only those syms which we are using in other bins and hence their size are less.
Ensuing build is green is sufficient.

Using optimized V8 bins

---

.ado/android-pr.yml
.ado/publish.js

- I am making a change required for Microsoft usage of react-native
When a param is passed in gradle command, it should be passed in double quotes instead of single quotes.

Param in gradle command requires double quotes instead of single

---

Libraries/Core/setUpGlobals.js

We've run into issues using fetch() with minified builds, that the FormData support detection was not working
Pick up change from https://github.com/facebook/react-native/commit/bccc92dfdd2d85933f2a9cb5c8d1773affb7acba#diff-3d750d038ea035cc40dd893c3a39e315

Pick up latest setUpGlobals.js

---

ReactAndroid/src/main/java/com/facebook/react/v8executor/OnLoad.cpp
ReactCommon/jsi/V8Runtime.h
ReactCommon/jsi/V8Runtime_droid.cpp
ReactCommon/jsi/V8Runtime_impl.h
ReactCommon/jsi/V8Runtime_shared.cpp
ReactCommon/jsi/V8Runtime_win.cpp

Adding logging support for droid and logging failure message

Adding logging support for droid and logging failure message

---

Libraries/ReactNative/UIManager.js

(Mirroring https://github.com/facebook/react-native/pull/25162)
Remote debugging stopped working (since 0.58, according to #23254). See https://github.com/facebook/react-native/issues/23254#issuecomment-474692753 for repro steps.
The root cause is incorrect checks for Chrome debugging environment in `UIManager.js`.
- In one place where sync function `lazilyLoadView` should be avoided, we effectively use `if (__DEV__ && !global.nativeCallSyncHook)` to check remote debugging, which misses ship flavor (i.e. `__DEV__` is false).
- In another place where we want to pre-populate view managers' constants to avoid calling sync function `getConstantsForViewManager`, `if (__DEV__)` is used, also missing ship flavor.
This PR fixes both checks, only using the absense of `global.nativeCallSyncHook` to …

Correctly bypass sync calls in UIManager during remote debugging

---

React/React.xcodeproj/project.pbxproj

Remove a duplicate file being built in the Yoga target of React. The Win tenant is hitting a duplicate symbol error here and we suspect it's related to this file getting built twice.
ios Fixed - Fix windows tenant build failure in the Mac loop.

Remove duplicate file build

---

ReactCommon/yoga/yoga/Yoga.cpp

Yoga leaf nodes in Win32 can be sub-trees which rely on the measure call (getMeasure) to perform the sub-tree layout passes.
Yoga layout

Yoga: call getMeasure even when YGMeasureModeExactly

---

ReactCommon/yoga/yoga/YGNode.h

Fix failing textRounding flag by changing YGNodeType field in YGNode struct. Top 7 bits will now be in agreement with enum value allowing for comparisions without masking bit values.
By fixing the textRounding flag in Yoga.cpp's RoundToPixelGrid method, Text components will no longer attempt to round their width value to align with a whole pixel value. This flag being broken caused issues when the text was scaled leading to truncation of the text at certain scaled sizes of view with fractional width values.
[General][Changed] - YGNode's nodeType_ field to work with comparisons with the YGNodeType enums.
Eliminates Text Clipping bug in the react-native-windows sample apps. Tested with this and custom apps.

Yoga Text Truncation bug fix 

---

Folly/folly/portability/Builtins.h

Adds macros to enable ARM64 compilation.

Enable ARM64.

---

Libraries/Components/Touchable/Touchable.js

Cherry picking error fix from facebook RN related to long press
https://github.com/facebook/react-native/pull/24238/files

Cherry picking error fix from facebook RN related to long press

---

ReactCommon/jsi/jsi/jsi.h

A minor fix in jsi.h to work around an MSVC bug on inheriting constructors . Without this change any file include jsi.h won't compile with MSVC compiler.
From: Yuriy Solodkyy yuriysol@microsoft.com
Sent: Monday, December 3, 2018 3:47:56 PM
To: Andrew Marino; Anandraj Govindan
Cc: Visual C++ Special Interest Group
Subject: RE: Protected base constructor and using
Hi Anandraj,
The fix to this issue should already be available via VS 2019 Preview 2 (possibly even Preview 1, I don’t have it handy to validate, but based on some other commits around that time it should have targeted that train). Let us know if you have any other issues with your port.
Thank you for reporting it to us!
Yuriy
From: Andrew Marino Andrew.Marino@microsoft.com
Sent: Monday, December 3, 2018 3:16 PM
To: Anandraj …

A hacky fix to work around MSVC bug.

---

Folly/folly/Traits.h

This change is same as PR https://github.com/microsoft/react-native/pull/123
Will abandon that PR after merging this.

Fixing folly related build failures

---

ReactCommon/CMakeLists.txt

Update CMake build logic for new jsi file location

Update cmake build for jsi file moves

---

ReactCommon/jsi/jsi/ScriptStore.h

Recently, we brought in an updated version of JSI through commit db6d02f4fda111c926390b0f1afad1765abb87a9. In the new version of JSI, jsi::Runtime::evaluateJavaScript takes in a shared_ptr instead of a unique_ptr. As a result, we need to refresh our ScriptStore interfaces accordingly.
N/A

Replace unique_ptrs in ScriptStore.h with shared_ptrs.

---

React/CxxBridge/RCTCxxBridge.mm

We've for a long time been running into a crash on startup in dev/debugging scenarios on mac with executeApplicationScript.  The problem is that a null check is done on self->_reactInstance, then a large object is created, then self->_reactInstance is used.  A parallel thread reset's _reactInstance if when bridge settings are reset (which happens when the remote js debugger is auto-enabled).  It may be that the debug build and/or the large size of our debug bundles (20mb in one case, 34 in another) make it more likely.
(optional)

apple: fix timing issue crash in executeApplicationScript

---

RNTester/js/RNTesterExampleList.js

The `accessibilityTraits` and `accessibilityLabel` props no longer exist in the official react-native code. I'm removing it to get rid of the errors during debugging of RNTester app.
(optional)
Remove obsolete accessibility props in RNTesterExampleList.js

Remove accessibility props that are no longer valid.

---

CMakeLists.txt
Folly/CMakeLists.txt
follybuild/CMakeLists.txt

We replaced the CMake build definition for folly, this moves our cmake build definition outside of folly, to get us closer to being able to revert back to using standard folly.

Reduce differences between our folly and facebook folly

---

.github/workflows/pr.yml

Start transitioning CI to use github actions

---

ReactCommon/cxxreact/NativeToJsBridge.cpp
ReactCommon/cxxreact/NativeToJsBridge.h

These changes will windows builds with systrace turned on. It contains two changes,
1. The change in NativeToJsBridge.cpp removes a statement that we added over the FB's change last year. In other words, it is removing an existing difference.
2. The change in NativeToJsBridge.h fixes a non-standard c++ statement. I've raised a PR in FB repo too : https://github.com/facebook/react-native/pull/26238
Build validation should suffice.

A couple of minor fixes in NativeToJsBridge

---

Libraries/Color/normalizeColor.js
Libraries/Color/normalizeColorObject.macos.js
Libraries/StyleSheet/processColor.js

The recent PR https://github.com/microsoft/react-native/pull/146 ("add normalize/processColorObject.js for ios and macos") caused a regression.   At runtime in ios and macOS a RedBox error saying that processColor is undefined.  The reason was because require('processColor') was returning an empty object due to circular dependencies between the new modules normalizeColor, normalizeColorObject, processColor and processColorObject.  The fix is to move the require()'s within the functions that need them so that they are executed after the module.exports.
It unclear how PR 146 passed validation.  I'm guessing one of the npm dependencies used for packaging changed since the PR impacting the module order.

Fix regression caused by PR 146: 'add normalize/processColorObject.js for ios and macos'

---

Libraries/Color/NativeOrDynamicColorType.js
Libraries/Color/normalizeColor.js
Libraries/Color/normalizeColorObject.android.js
Libraries/Color/normalizeColorObject.ios.js
Libraries/Color/normalizeColorObject.macos.js
Libraries/Components/ActivityIndicator/ActivityIndicator.js
Libraries/Components/ActivityIndicator/RCTActivityIndicatorViewNativeComponent.js
Libraries/Components/DrawerAndroid/AndroidDrawerLayoutNativeComponent.js
Libraries/Components/Picker/PickerIOS.ios.js
Libraries/Components/Picker/RCTPickerNativeComponent.js
Libraries/Components/Switch/SwitchNativeComponent.js
Libraries/Components/ToolbarAndroid/ToolbarAndroidNativeComponent.js
Libraries/Components/Touchable/TouchableNativeFeedback.android.js
Libraries/ReactNative/getNativeComponentAttributes.js
Libraries/StyleSheet/StyleSheetTypes.js
Libraries/StyleSheet/processColor.js
Libraries/StyleSheet/processColorObject.android.js
Libraries/StyleSheet/processColorObject.ios.js
Libraries/StyleSheet/processColorObject.macos.js

The previous Pull Request https://github.com/microsoft/react-native/pull/146 renamed and moved the Flow type NativeOrDynamicColorType.   It also created some circular references via the `import type` imports of this type.   Flow itself seems to be able to handle these circular references, but an internal tool in Microsoft cannot.   And these circular references are a bad practice.
Created a new file, Libraries/Color/NativeOrDynamicColorType.js, that contains the `export type NativeOrDynamicColorType = ...` definition.  Changed all the `import type {NativeOrDynamicColorType} from` instances to reference the new file.

Fixed `import type` circular references of NativeOrDynamicColorType

---

ReactAndroid/src/main/java/com/facebook/react/views/image/BUCK
ReactAndroid/src/main/java/com/facebook/react/views/text/BUCK

Reverting the changes in the BUCK files.
N/A

Reverting the changes in the BUCK files.

---

.ado/apple-pr.yml
.ado/templates/apple-job-react-native.yml

Switch the Azure Devops yaml script to use vmImage macOS-10.14

Switch AzureDevops to use vmImage macOS-10.14

---

package.json

This just adds metro as a declare dependency.  Most package managers already allow access to metro from react-native through the metro-babel-register dependency, but pnpm is more picky about actually declaring everything you use.

Add dependency required when using pnpm

---

ReactApple/ReactApple.nuspec

(TSIA) Use proper token, `$buildNumber$`, in ReactApple.nuspec.
(Can't make the same change in ReactAndroid.nuspec yet because it's built differently.)

Use $buildNumber$ token for NuGet

---

Libraries/Text/RCTText.xcodeproj/project.pbxproj

Include RCTBackedTextInputViewProtocol and RCTBackedTextInputDelegate in RCTText as they weren't getting built into the RCTTextLibrary, which is necessary for Polyester's consumption.
These headers must be included in the RCTText library so Polyester classes can import them.
It must get pushed into github, get pushed to SDX-Platform, and then we can see if there are any other issues hiding behind this header issue.

Include RCTBackedTextInputViewProtocol and RCTBackedTextInputDelegate in RCTText

---

package.json

**Issue**
Creation of RNTester app bundle is failing in sdx-platform even though it is getting created in MS React-Native GitHub repo.
**Fix**
Added dependency of metro-config in react-native package.json to resolve this issue.

Adding metro-config dependency

---

ReactAndroid/src/main/java/com/facebook/react/views/text/ReactFontManager.java
ReactAndroid/src/main/java/com/facebook/react/views/textinput/ReactTextInputManager.java
ReactCommon/cxxreact/Instance.cpp
ReactCommon/cxxreact/Instance.h
ReactCommon/cxxreact/NativeToJsBridge.cpp
ReactCommon/cxxreact/NativeToJsBridge.h

Add back jseConfigParams changes

---

.ado/publish.js
ReactAndroid/src/main/java/com/facebook/react/views/text/ReactFontManager.java
package.json

Add support for registering custom fonts by family+weight

---

Libraries/Text/RCTText.xcodeproj/project.pbxproj

iOS is copying these to RCTText, let's do the same on Mac so we don't need an "#ifdef" downstream when we need to reference the headers.
(optional)

Align with ios here and copy these to the same location on mac

---

React/CxxBridge/RCTCxxBridge.mm
React/CxxBridge/RCTObjcExecutor.mm
ReactAndroid/src/main/java/com/facebook/react/v8executor/InstanceManager.cpp
ReactAndroid/src/main/jni/react/jni/CatalystInstanceImpl.cpp
ReactAndroid/src/main/jni/react/jni/InstanceManager.cpp
ReactAndroid/src/main/jni/react/jni/ProxyExecutor.cpp
ReactAndroid/src/main/jni/react/jni/ProxyExecutor.h
ReactCommon/cxxreact/Instance.cpp
ReactCommon/cxxreact/Instance.h
ReactCommon/cxxreact/JSExecutor.h
ReactCommon/cxxreact/NativeToJsBridge.cpp
ReactCommon/cxxreact/NativeToJsBridge.h
ReactCommon/cxxreact/V8Executor.cpp
ReactCommon/cxxreact/V8Executor.h
ReactCommon/jsiexecutor/jsireact/JSIExecutor.cpp
ReactCommon/jsiexecutor/jsireact/JSIExecutor.h

See accompanying changes in react-native-windows in https://github.com/microsoft/react-native-windows/pull/3591

Remove scriptVersion/bundleVersion and bytecodeFileName Parameters

---

.ado/apple-pr.yml

Enable mac yml tests

---

metro.config.js

Adjust `projectRoot` to accommodate yarn hoisting.

Change projectRoot for internal yarn migration

---

package.json

Stop beachball from publishing internally

---

ReactApple/ReactApple.nuspec

The ReactApple/ReactApple.nuspec is used internally at Microsoft for publishing binary artifacts as NuGet packages.
Removed the libRCTGeolocation.a targets from the nuspec as they are not longer in the repo.
Added `<repository type="git" url="$repoUri$" commit="$commitId$" />` which is needed to record the relevant metadata about the publish.
Removed an obsolete comment.

Update nuspec file used for internal NuGet package publishing

---

.ado/android-pr.yml
.ado/apple-pr.yml

To unblock PRs targeting `0.59-stable` branch.
(optional)

Add 0.59-stable branch to PR build trigger

---

Libraries/Text/TextInput/Multiline/RCTUITextView.h
Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/Singleline/RCTUITextField.h
RNTester/Podfile
RNTester/Podfile.lock
RNTester/RNTesterPods.xcodeproj/project.pbxproj
ReactCommon/turbomodule/core/TurboCxxModule.cpp
ReactCommon/turbomodule/core/TurboModuleBinding.cpp
ReactCommon/turbomodule/core/TurboModuleBinding.h

This brings RNTester‘s setup back in line with upstream v0.60.0, which allows for usage of CocoaPods to bootstrap dependencies of the app. The main changes were reverting header import changes, so this might be breaking MS specific build steps that I’m unaware of.
[iOS] [Fixed] - Make RNTester work with CocoaPods again.
Both `RNTester.xcodeproj` (sans CocoaPods) and `RNTesterPods.xcworkspace` work, but if there are MS specificities integration tests I can perform to ensure these changes didn’t break anything there, that would be great.

[RNTester] Make iOS target work with CocoaPods again

---

KeepingRecent.md

- [X ] I am making a change required for Microsoft usage of react-native
Moving the FB version merge documentation here so it's public for anyone to leverage. Adding this file is a small deviation from Fb's repo, but seems worth it as it's fittingly a markdown on how to help us not deviate from Fb's repo.
Documentation change. Tested the links and markdown at https://stackedit.io/app#

Move FB version merge documentation to the repo it's used in

---

.ado/templates/apple-job-javascript.yml
.flowconfig
.flowconfig.android
.flowconfig.macos
Libraries/Components/AccessibilityInfo/AccessibilityInfo.macos.js
Libraries/Components/DrawerAndroid/DrawerLayoutAndroid.macos.js
Libraries/Components/SafeAreaView/SafeAreaView.js
Libraries/Components/StatusBar/StatusBarIOS.macos.js
Libraries/Components/TimePickerAndroid/TimePickerAndroid.macos.js
Libraries/Components/ToastAndroid/ToastAndroid.macos.js
Libraries/Components/ToolbarAndroid/ToolbarAndroid.macos.js
Libraries/Components/ViewPager/ViewPagerAndroid.macos.js
Libraries/Utilities/Platform.macos.js
package.json

There were hidden macOS Flow validation failures. As in the facebook repo this forks has a `.flowconfig` (which is really for ios) and a `.flowconfig.android`. The ios config ignores `*.android.js` files and the android config ignores `*.ios.js` files.   This fork which contains the macOS implementation needs a `.flowconfig.macos` that ignores ios and android and the other two need to ignore macos. 
Also added a `yarn flow-check-macos` to `package.json` and updated the Azure DevOps yaml files to check all three platforms.
Several stub JS files for macOS needed to be added similar to existing stubs for ios and android.
The macos `Platform` API needed a `isTV` method.
The Android `.flowconfig.android` needed to exclude `metro.config.js` the same as ios and macos in order for `yarn …

Fix Flow check for macos

---

KeepingRecent.md

The second level numbers weren't indented correctly. This should fix that up.
Checked this fix on commonmark.org since the markdown site I used initially didn't show this problem.

Fix up some spacing issues with KeepingRecent doc

---

RNTester/Podfile
RNTester/Podfile.lock

There’s no real need for RNTester to use MS specific versions. So simply
removing those from the system will make the lockfile stable, as far as
versions go, just like the upstream version.
Closes https://github.com/microsoft/react-native/issues/218

[RNTester] Remove need to update lockfile after cutting new build

---

ReactAndroid/src/main/java/com/facebook/react/modules/dialog/DialogModule.java
ReactAndroid/src/main/java/com/facebook/react/modules/dialog/PlatformAlertFragment.java

This change is essentially a revert of the following commit,
https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Freact-native%2Fcommit%2F243070afe2873c09c1149ca3ede3386abb88a529%23diff-8e3b74ad18aa49187acd4240321bc9b9&data=02%7C01%7Canandrag%40microsoft.com%7C11460df4f62b4dcb762b08d793fa26cb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637140574925336509&sdata=Ky1sCL4qcv3rO8OUBGYfNDvB0Ew9ib36XQ1oDhZl6XE%3D&reserved=0
With the above change, by design, the react-native stopped support for showing Dialogs over standard Android activities, since the required APIs are deprecated in platform 28, in favor of the newer Jetpack library controls. 
But, Office apps are still using the standard Android activities and it will take a while before the base app …

Bring back support for DialogModule over standard Android activities

---

.ado/android-pr.yml
.ado/publish.yml
.ado/setup_droid_deps.bat
ReactAndroid/build.gradle

This change is removing a few of the differences in the gradle script used for build setup. Instead of hardcoding our customization, with this change, we make use of the existing mechanisms already available in the open source code. i.e. by using environment variables to specific pre-setup build inputs.
Build.

Deforking - Cleaning up android gradle build script

---

react-native.config.js

When react-native-macos is installed alongside react-native in a repo, the react-native CLI scripts will discover both installations and run commands twice.   The react-native.config.js file will eventually refer to macos commands once we have an implementation for them.   In the meantime, and as long as react-native-macos is a fork of facebook/react-native, it is still useful to use the ios and android CLI locally for testing purposes.   But when installed in another repo, such as any of the react-native-community repos along side facebook react-native, we cannot allow the CLI commands to execute twice for each installation.
In react-native.config.js, check the basename of __dirname and if it is 'react-native-macos' as it will be when installed in a 'node_modules' folder, then use empty …

Remove react-native commands from cli when installed as 'react-native-macos'

---

RNTester/RNTester.xcodeproj/project.pbxproj
React/React.xcodeproj/project.pbxproj
yarn.lock

In previous commits changes were made to add `arm64e` as an arch for all iOS react libs.   In recent merges from facebook to the microsoft fork two new targets were added: `jsi` and `jsiExecutor`.   These two newer targets also need `arm64e`.
Test apps, like RNTester, also need the arm64e architecture when deploying to devices with A12 processors like the iPhone XS/XR and higher.

Fix for building and deploying arm64e to devices

---

.ado/publish.yml
.ado/renamePackageToMac.js
.ado/versionUtils.js

This change begins publishing a `react-native-macos` package to npmjs.org.
At this time we can't just rename the package from `react-native` to `react-native-macos` in the `package.json` because we still publish a `react-native` package to an internal npm feed used widely within Microsoft.   In the meantime a simple node script step renames the name in `package.json` just prior to performing `npm publish` to npmjs.   After we migrate all internal consumers to use the public npm package, this script step can go away and the `package.json` name can be changed to `react-native-macos`.

Change publish step to publish react-native-macos npm package.

---

.ado/templates/apple-xcode-build.yml
.ado/templates/apple-xcode-select.yml

The build pipeline was using XCode 11.0.   A recent change to the build agents broke the script method we used to select the XCode version.
Our old script method was designed to work in both the public build agents and the custom internal build agents.   We no longer use the later, so this change switches to the more conventional method of switching xcode version which is to `sudo xcode-select --switch 'path to xcode'` and then to use `xcodeVersion: default` in the `XCode@5` tasks.

Build break fix: set XCode version to 11.2.1

---

React/Base/RCTBridge+Cxx.h
React/Base/RCTBridge+Cxx.mm

The `RCTBridge (Cxx)` category is used internally by Microsoft Office to access the C++ `facebook::react::Instance` within an `RCTBridge`.   It has a `reactInstance` method that exposes the internal `reactInstance` on `RCTBridge`.   The internal `reactInstace` used to return a `shared_ptr` but in **https://github.com/facebook/react-native/commit/71a8944b3946beff7ba7d1e65c38aa56c30227ec** it changed to `weak_ptr`.  Since the category wrapper is returning `shared_ptr` the dtor of the copy passed to the caller can cause the facebook::react::Instance to be deleted which invalidates the bridge and causes crashes.

Change the `reactInstance` category method return `weak_ptr`

---

React/CxxBridge/RCTMessageThread.mm

To keep our memory footprint down, we can put each run loop cycle in its own autorelease pool.
Facebook made this fix which we're cherry picking now because it seems pretty far off until we're on the version of RN that has this fix (0.62 RC). We put each run loop in its own autorelease pool so the footprint stays small.
https://github.com/facebook/react-native/pull/27395/files#diff-e2928a0e8ce82f1c15bb062c5a51a407

Autorelease pool growth fix

---

Libraries/Image/RCTImageView.m
Libraries/react-native/react-native-implementation.macos.js
React/Base/RCTUtils.m
React/Modules/RCTRedBox.m

Since the last merge from upstream to the fork two manual merge errors impacted macOS:
- In `RCTImageView.m` the macOS version of the `_imageView` ivar was not being initialized breaking `<Image>` components.
- In `react-native-implementation.macos.js` the `ActionSheetIOS` component was not being exposed.   Although named `ActionSheetIOS` in the fork it creates `NSMenu` popups for macOS and `UIAlertControllers` for iOS.
Since iOS 13 the `RCTKeyWindow()` function is broken in apps that use `UIScene`'s for multi window support.   It also breaks `RCTRedBox`.   If an app that uses `UIScene`'s (like Office apps) show an `RCTRedBox` error message, the red box window is invisible.   Then if a `ActionSheetIOS` presents a `UIAlertController` it is presented on the invisible Red Box windows making …

Restore macOS <Image> and ActionSheetIOS.  Cherry pick multi windows UIScene support from upstream.

---

React/Views/UIView+React.m

The `UIView+React` category is overriding the properties `accessibilityRole`, `accessibilityStates`, and `accessibilityActions`.   Despite the naming, these properties are not UIKit or `UIAccessibility` properties, but are react-native specific properties.   In the react-native-macos fork, this same category is applying to `NSView`.   On macOS, `accessibilityRole` *is* an `NSAccessibility` property.   Overriding it breaks macOS accessibility scenarios.   In particular it breaks some Automated tests in Office because `NSToolbarView` and `NSToolbarViewItems` loose their accessibilityRoles making them not reachable by XCUITest queries.
This fix puts `#if !TARGET_OS_OSX` conditions around the `accessibilityRole` overrides.   
Long term the upstream code should either stop overriding these …

Do not override `accessibilityRole` on `NSView` for macOS.

---

React/React.xcodeproj/project.pbxproj

- [X ] I am making a change required for Microsoft usage of react-native
Apple has a hard deadline of Dec 2020 for all apps to ship without UIWebview. It's been deprecated for a while now, but in our December 2019 release, Apple warned us against using it.
Although we aren't using it, I found a stale ref to a file that doesn't exist in the pbxproj which matches the file in the libReact.a in our internal builds.
Anyone building with pods (read: >=0.61) won't have this problem.
I printed the contents of libReact.a and it doesn't contain UIWebView.
(optional)

Remove a stale ref to a deprecated file (UIWebView)

---

RNTester/js/ActionSheetMacOSExample.js

Our macOS actionsheet tests don't have an anchor on the button that drops the action sheet. Without this, we default on some functionality instead of hitting the codepaths that actually replicate how clients use the class (which only happen if we can find the anchor to drop from).
- I checked programmatically that dropping the contextual menu via the button in the ActionSheetMacOS test passes the anchor through to our ObjC module.
- Ran through the expected code paths and we're no longer providing default values to our action sheet, which also has the user impact that the action sheet appears relative to our anchor (the button that dropped it).

Provide an anchor to our ActionSheetMacOS test

---

Libraries/ActionSheetIOS/RCTActionSheetManager.m

There's a bug where mac os events are received with locations relative to either the screen or the window. Different click styles (light trackpad tap vs. harder trackpad click) appear to dictate which event type we have and thus, which coordinate system we're receiving events in. Right now we were treating every click as if the event location is relative to the window, but we receive some click events relative to the screen. We need to handle those and convert them properly to the right coordinate system.
There's an unknown of _why_ these aren't just MouseDown/MouseUp events. It's possible React Native is gobbling up the OS events somewhere and giving these back, but a search of the repo found no obvious …

MacOS mouse events show up at wrong locations

---

Libraries/Components/ScrollView/ScrollView.js
Libraries/Components/View/ViewPropTypes.js
Libraries/Lists/VirtualizedList.js
Libraries/Lists/VirtualizedSectionList.js
Libraries/Types/CoreEventTypes.js
React/Views/ScrollView/RCTScrollContentView.m
React/Views/ScrollView/RCTScrollView.h
React/Views/ScrollView/RCTScrollView.m
React/Views/ScrollView/RCTScrollViewManager.m

macOS scroll views are usually like iOS scroll views in that the scroll indicators only appear when scrolling and they overlay the content view.  But in System Preferences > General, the user may choose 'Show scroll bars: Always' in which case the content view shrinks and a horizontal and/or vertical scroll indicator appears to the right and/or below the content view.   In these cases the react-native content area was still being laid out as if the content view was the same size as the scroll view which would could cause the vertical scroll indicator to appear because the content was too wide.
This fix involves a change to the `RCTScrollContentView reactSetFrame:` method.   When the react frame is being set, the method checks if the `scrollerStyle` property on the `NSScrollView` is …

Add support for macOS legacy scroller system setting.

---

React/Base/RCTTouchHandler.m

- [ X] I am making a fix / change for the macOS implementation of react-native
When controls such as NSButton don't send the mouse up signal after a mouse down click, the mouse event gets stored in our cache and becomes stale. On the next click, we fail an assert that there are no stale events in our cache and no action is executed.
What we need to do is send the mouse up signal for all controls that can receive one so we clear out our cache properly. We need to pair the mouse down events 1:1 with the mouse up events we send.
Tested in a downstream app (Polyester). Clicking every time registers and sends the correct event (dropping a menu in this case). Tested with both soft trackpad and hard trackpad clicks.

Send mouse up notifications for all enabled NSControls

---

android-patches/patches-droid-office-grouped/DialogModule/ReactAndroid/src/main/java/com/facebook/react/modules/dialog/DialogModule.java

We have some custom code in fork to support DialogModule on Office apps. The code uses an API not available before Android sdk version 26. This fixes the code to not call the API.
Make sure that dialog/alert comes up on devices with new and old android sdks.

Fixing DialogModule for Android SDK version before 26

---

.ado/publish.yml
.ado/versionUtils.js
change/react-native-macos-init-2020-04-03-21-43-14-tomun-publish-react-native-init.json
change/react-native-macos-init-2020-04-03-21-47-57-tomun-publish-react-native-init.json
packages/react-native-macos-init/package.json
packages/react-native-macos-init/yarn.lock

This change adds a job to the existing publish pipeline to publish the `react-native-macos-init` packages to npmjs.org.
This package will allow the `react-native-macos-init` command line to work via `npx`.   See [PR 291](https://github.com/microsoft/react-native/pull/291)

Update scripts to publish react-native-macos-init

---

local-cli/generator-macos/index.js
local-cli/generator-macos/templates/macos/Podfile

Currently uses `@react-native-communit/cli-platform-ios`, but this is mostly semantics as they work the same. In the future this will move into a `@react-native-communit/cli-platform-apple` package which will hold common iOS and macOS tooling.
⚠️ One issue people might run into right now is that auto-linking tries to use _any_ podspec it finds among `node_modules`, but we’ll need to make it possible in the future to only link podspecs on the platforms they actually support. I.e. right now if you were to auto-link in a project that had iOS _only_ podspecs, `pod install` will fail. This work will all need to happen in the CLI package, though.
Here’s an example of auto-linking for macOS in the react-native-webview repo https://github.com/react-native-community/react-native-webview/pull/1328

[generator-macos] Enable auto-linking of native modules

---

local-cli/generator-macos/templates/macos/Podfile

Setting up our template to work with the changes in https://github.com/react-native-community/cli/pull/1126

[generator-macos] Update template for platform specificity during auto-linking

---

android-patches/patches-0.61.5/BasicBuild/ReactAndroid/ReactAndroid.nuspec

Non-code/functional change. This change is fixing a bug introduced in the last commit, in the Nuget spec that is used for creating packages.
Nuget Package creation.

Reverting the hardcoding of version number in the nuget spec

---

RNTester/Podfile
RNTester/Podfile.lock

This restores the behaviour we had to always treat RN versions as `1000.0.0` in RNTester, which broke when we dropped the `-microsoft.x` version segment.

[RNTester] Use stable versions to combat lockfile thrashing

---

.ado/android-pr.yml
.ado/apple-pr.yml
.ado/publish.yml
packages/react-native-macos-init/package.json

Prepping the build logic of the 0.60-stable branch to allow future hotfixes.

0.60-stable publish fixes

---

local-cli/generate-macos.js
local-cli/generator-macos/index.js

Fixes #306, #362
This PR adds automatic `pod` installation (but utilizing `pod-install` package from the Expo) to the `react-native-macos-init` NPX script. 
Unfortunately due to `react-native-config.js` content duplication issue `pod` installation will only work correctly when `react-native-macos-init` was executed in the project without `react-native-config.js` file.
Because of the issue above and not 100% clean testing procedures I suggest that this PR should be reviewed on the few machines before the merge.
[macOS] [Added] - automatically install and link Pods on macOS init
I have tested those changes locally by linking working copy of the `react-native-macos-init` package in the test macOS app.
Expected end of the successful output:

install and link macOS Pods automatically on init

---

local-cli/generator-macos/index.js

Refs #366 
This small PR adds `--quiet` flag also for the `npx` [itself](https://www.npmjs.com/package/npx#description) to get rid of the installation message in non verbose run. 
This changeset also includes missing `@param` annotations for the extracted and added methods in the referenced PR.
[Internal] [Changed] - `react-native-macos-init`: pass `verbose` flag also to `npx`
I have tested those changes locally by linking working copy of the `react-native-macos` package in the test macOS app.

local-cli: quiet npx messages before pod-install

---

.ado/templates/react-native-macos-init.yml

Since Pods are automatically installed during the `react-native-macos-init` (#366) the manual installation became redundant, so the CI step 'Install pods' can be removed.
[Internal] [Removed] - CI: remove 'Install pods' step from `react-native-macos-init` template
Run the CI!

CI: remove 'Install pods' step since Pods are installed by init

---

change/react-native-macos-init-2020-05-18-19-18-39-init-cli-improvements.json
packages/react-native-macos-init/src/cli.ts

This PR introduces the following changes to the `react-native-macos-init` script:
* check the currently installed version of `react-native-macos`, skip installation if it is latest available version
* refactor `getReactNativeVersion` to the `getPackageVersion` (more generalised)
* utilize `verbose` flag in `react-native-macos` installation exec
* store package names in the constants
* update and simplify display aspect of the script (`printPkg` method for pretty-printing packages and other tweaks), update colors (this can be easily changed now): 
* package name changed from the green to the yellow
* `prerelease` warning uses yellow background instead yellow text
* `printError` function which prints decorated error messages (red + bold)
* punctuation marks in CLI messages, ellipsis instead …

init cli improvements: check the current version of RNmacOS, other display tweaks

---

local-cli/generator-macos/index.js
local-cli/generator-macos/templates/macos/_gitignore
packages/react-native-macos-init/src/cli.ts

running `react-native-macos-init` in a react native project automatically runs pod install for macos, resulting a large diff.
I thought it would be nice if `react-native-macos-init` automatically adds `/macos/Pods` to `.gitignore` so the user does not need to worry about it.
[macOS] [Added] - [init] Add macos Pod folder to .gitignore
Tested running the cli locally to see that `/macos/Pods` was added to `.gitignore`

feat(react-native-macos-init): add pod folder to gitignore

---

local-cli/generator-macos/templates/macos/HelloWorld-macOS/Base.lproj/Main.storyboard

Fixes #376 
This small PR changes value of `autorecalculatesKeyView` inside the `init` template from `NO` to `YES` as requested in referenced issue (similar way to RNTester).
[Internal] [Changed] - set correct `autorecalculatesKeyView` property in the init template storyboard
The `Main.storyboard` in the test project generated form the local, working copy of RNmacOS had a correct value of `autorecalculatesKeyView`.

set autorecalculatesKeyView to YES in the init template

---

RNTester/js/components/RNTesterBlock.js

This small PR makes the descriptions of the TesterBlock component in the RNTesters readable on macOS in the DarkMode.
I have check the content of this file in the RN core package, but it seems that there is a different  DarkMode implementation based on the ThemeContext.
[Internal] [Changed] - RNTester: ensure that description is readable in DarkMode too
Locally run of RNTester app.

RNTester: fix TesterBlock description color in DarkMode

---

React/Views/RCTPicker.m

This small PR fixes the default Picker text and items color in DarkMode and changes the text size to match default styling on macOS.
[macOS] [Fixed] - Picker: fix default text color in DarkMode, adjust default text size
All the changes has been tested in the RNTester build from local working copy.

fix Picker text color in DarkMode, tweak text size

---

Libraries/Text/TextInput/Singleline/RCTUITextField.m

This small PR replaces the static default color of `TextInput` placeholder with `systemPlaceholderColor` platform color. This change improves the `TextInput` appearance in Dark Mode. 
Since whole code block is inside macOS target conditional I have just replaced the value.
[macOS] [Fixed] - TextInput: fix default placeholder appearanace in DarkMode
All the changes has been tested in the app generated form the init and build from the local working copy.

adjust default color of the TextInput placeholder

---

Libraries/ActionSheetIOS/RCTActionSheetManager.m

We can always just fallback to using the mouse location.
This change was approved in master, but we need it in the 0.60-stable branch to get into repos depending on the 0.60-stable branch this month.
When launching a menu, if the manager fails to find an event associated with the view then it enters an invalid fallback scenario for where to display the menu. We shouldn't ever launch the menu in the middle of the view.
It's more correct to fallback to the mouse location, which mirrors the actual intent of the presenter.
There could be an issue here if an SDX puts a control that drops a big menu too low then we'd redbox and go off the screen. That would require more refactoring and probably some of the …

Menu location fix

---

.ado/publish.yml

This is a cherry-pick of the PR https://github.com/microsoft/react-native-macos/pull/426 which just landed in master applied to the `0.60-stable` branch.
[macOS] [Fixed] - Fix npm publish pipeline to only tag `latest` when publishing from master
Publish works

Fix npm publish pipeline to only tag `latest` when publishing from master

---

.ado/android-pr.yml
.ado/android_symlink_ndk.bat
.ado/publish.yml

#419 ## Please select one of the following
This changes are only in ADO pipeline definitions.
Many Android build tools doesn't support spaces in the SDK/NDK paths. But we do sometimes find lab images with paths having spaces in it. This change creates a symlink to the NDK path and feed it into the build task to get around.
Many Android build tools doesn't support spaces in the SDK/NDK paths. But we do sometimes find lab images with paths having spaces in it. This change creates a symlink to the NDK path and feed it into the build task to get around.
Ensure build pipelines pass

Working around ndk paths containing spaces in it

---

React/Base/macOS/RCTDynamicColor.m

Xcode logs warnings to console about the use of the appearance API on a non-UI thread. This fix should allow the current behaviour.
Resolves #335
[macOS] [Fixed] - Allow `-[RCTDynamicColor effectiveColor]` to be called off UI thread
Xcode should warn about the use of the appearance API on a non-UI thread.

Fix -[RCTDynamicColor effectiveColor] being called off UI thread

---

Libraries/Text/TextInput/Singleline/RCTUITextField.h
Libraries/Text/TextInput/Singleline/RCTUITextField.m

In single line TextInput controls, most text stylings in the `style` prop are being ignored.
Resolves #447
[macOS] [Fixed] - Fix styling of single-line TextInput
|   |   |
| - | - |
| <img width="752" alt="image" src="https://user-images.githubusercontent.com/4123478/84508655-eabb5580-acc2-11ea-93b0-75e17736b7f4.png"> | <img width="752" alt="image" src="https://user-images.githubusercontent.com/4123478/84508564-c19ac500-acc2-11ea-8acd-3dcacc0e3983.png"> |

Fix styling of single-line TextInput

---

React/Views/UIView+React.m

`-resignFirstResponder` is not supposed to be called directly. See https://developer.apple.com/documentation/appkit/nsresponder/1532115-resignfirstresponder?language=objc
Resolves #432
[macOS] [Fixed] - Exception thrown when unfocusing multiline TextInput
1. Open RNTester and go to the TextInput screen
2. Find a multi-line TextInput and try focusing/unfocusing it several times

Fix exception thrown when unfocusing multiline TextInput

---

React/Views/RCTActivityIndicatorView.m

The window flickers when rendering a view with an `ActivityIndicator` and a custom colour. This is caused by setting `-[NSView setContentFilters:]`.
Resolves #412
[macOS] [Fixed] - Fix ActivityIndicator with custom color causing brief flicker

Fix ActivityIndicator with custom color causing brief flicker

---

Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m

`onSubmitEditing` is fired on delete/tab keys because we check `-[RCTBaseTextInputView textInputShouldReturn]`, which also sends a submit event, too early.
Resolves #429
[macOS] [Fixed] - Fix onSubmitEditing firing on delete/tab
1. Launch RNTester and go to TextInput screen
2. Filter on "submit"
3. Type something in the multiline TextInput instance and try deleting/tabbing.

Fix onSubmitEditing firing on delete/tab

---

Libraries/Text/TextInput/Singleline/RCTUITextField.m

Fixes `backgroundColor` not being applied correctly to `TextInput` (single-line).
Resolves #415
[macOS] [Fixed] - Fix `backgroundColor` not being applied correctly to TextInput
| Before | After |
| :----: | :---: |
| <img width="752" alt="image" src="https://user-images.githubusercontent.com/4123478/84276848-1a3b5800-ab33-11ea-8990-de1243ae00fa.png"> | <img width="752" alt="image" src="https://user-images.githubusercontent.com/4123478/84276905-28897400-ab33-11ea-9ee0-0f60c33c7db7.png"> |

Fix `backgroundColor` not being applied correctly to TextInput

---

.ado/publish.js
android-patches/patches-droid-office-grouped/OfficeRNHost/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactBridge.java

We are adding a line of patch which we missed by mistake earlier.
In addition the PR contains a fix for an error when running publish script in Ubuntu.
We are adding a line of patch which we missed by mistake earlier.
In addition the PR contains a fix for an error when running publish script in Ubuntu.
We are adding a line of patch which we missed by mistake earlier.
In addition the PR contains a fix for an error when running publish script in Ubuntu.
Branch should publish now. Also the app shouldn't crash in devmain.

Fixing another OS-specific issue in publish script and a patch

---

Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m

`onSubmitEditing` does not get called when pressing `Enter` in single-line `TextInput`.
Resolves #451
[macOS] [Fixed] - Fix onSubmitEditing not being called on single-line TextInput

Fix onSubmitEditing not being called on single-line TextInput

---

Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m
Libraries/Text/TextInput/RCTBaseTextInputView.m

The current multi-line `TextInput` `onSubmitEditing` behaviour in macOS deviates from upstream.
Setting `blurOnSubmit` to `true` means that pressing return will blur
the field and trigger the `onSubmitEditing` event instead of inserting
a newline into the field.
-- https://reactnative.dev/docs/textinput#bluronsubmit
[macOS] [Fixed] - Align multi-line TextInput onSubmitEditing with Android
1. Go to RNTester > TextInput
2. Search for "submit"
3. Enter something in the multi-line TextInput and press enter
4. An alert should appear and no newline is inserted
5. Modify the example to set `onSubmitEditing=false` (patch provided below)
6. Repeat step 1-3, no alert should appear and newlines should be inserted
```diff
diff --git a/RNTester/js/examples/TextInput/TextInputExample.ios.js …
```

Align multi-line TextInput onSubmitEditing with Android

---

Libraries/Lists/VirtualizedList.js

`FlatList` doesn't pass `isSelected` to `renderItem`.
Resolves #462 
[macOS] [Fixed] - Fix `isSelected` not being passed to `FlatList.renderItem`
1. Patch `RNTester/js/examples/FlatList/FlatListExample.js` to output `isSelected` (see patch below)
2. Go to RNTester > FlatList
3. Observe that `undefined` is no longer output, but proper boolean values
```diff
diff --git a/RNTester/js/examples/FlatList/FlatListExample.js b/RNTester/js/examples/FlatList/FlatListExample.js
index 733285229..4936ee212 100644
--- a/RNTester/js/examples/FlatList/FlatListExample.js
+++ b/RNTester/js/examples/FlatList/FlatListExample.js
@@ -191,6 +191,7 @@ class FlatListExample extends React.PureComponent<Props, State> {
renderItem: undefined,
[flatListPropKey]: ({item, isSelected, separators}) => {
// TODO(macOS …
```

Fix isSelected not being passed to FlatList.renderItem

---

React/Views/ScrollView/MacOS/RCTScrollContentLocalData.h
React/Views/ScrollView/MacOS/RCTScrollContentLocalData.m
React/Views/ScrollView/RCTScrollContentShadowView.m
React/Views/ScrollView/RCTScrollContentView.m
React/Views/ScrollView/RCTScrollView.h
React/Views/ScrollView/RCTScrollView.m

Always show the vertical scroll bar when **Show scroll bars** is set to **Always**. This makes it consistent with other system apps, such as Finder or Xcode.
Resolves #363
[macOS] [Fixed] - Fix RCTScrollContentView layout with fixed size
| Before | After |
| :-: | :-: |
| <img width="752" alt="image" src="https://user-images.githubusercontent.com/4123478/84790999-528adc80-aff2-11ea-973a-f9e3748fec3d.png"> | <img width="752" alt="image" src="https://user-images.githubusercontent.com/4123478/84790943-3dae4900-aff2-11ea-9b36-b8968ddfdf49.png"> |
| <img width="752" alt="image" src="https://user-images.githubusercontent.com/4123478/84791218-9c73c280-aff2-11ea-8b5a-0b9329ed52fa.png">  | <img width="752" alt="image" src="https://user-images.githubusercontent.com/4123478/84801261-3d687a80-afff-11e …

Fix RCTScrollContentView layout with fixed size

---

.ado/npmOfficePack.js

No code change. Only changes in the publish build pipeline
Fixing OS specific failure in publish task
Fixing OS specific failure in publish task[CATEGORY] [TYPE] - Message
Publish pipeline should pass.

Fixing OS specific failure in publish task

---

React/Views/RCTView.m

Fixes `overflow:'hidden'` #399 by setting`layer.masksToBounds = self.clipsToBounds;` in the `displayLayer:` method
`overflow: 'hidden'` doesn't work in macOS, but it does work in iOS and Android (not sure about Windows). This change brings functional parity with minimal complexity/conflict.
This also fixes borderRadius on `<Image>` which broke recently because the implementation of `RCTImage` changes from subclass to composition with the image view being a subview and thus now relies on functional clipping behavior.
Note we don't mutate `self.layer.masksToBounds` inside `setClipsToBounds` because modifying `self.layer` is undefined behavior on macOS and we have seen issues (e.g. with transforms) where the backing layer gets replaced by the system and mutations are not transferred over. …

Fix overflow:'hidden' github issue #399 (attempt 2)

---

React/Base/RCTRootView.m

Resize events overwhelm RN, causing seemingly infinite jittering when the window is resized. By throttling layout, we can help RN catch up. Resolves #322.
[macOS] [Fixed] - Alleviate excessive layout jittering when resizing window

Alleviate excessive layout jittering when resizing window

---

package.json

Not a code change..
Manually bump version to unblock publish
Manually bump version to unblock publish

Manually bumping version to unblock publish

---

Libraries/Text/TextInput/RCTBaseTextInputView.m

It seems that the returned string that we use to set `previousText` can be mutated while it is waiting to be processed by `RCTBridge `.
Resolves #486
[macOS] [Fixed] - Fix multiline `TextInput` crash when inserting/removing lots of text
Here's a screenshot showing that the length of `previousText` (`0x600000d952c0`) was 29483 when first accessed, but is 0 when the exception is thrown.

Fix multiline TextInput crash when inserting/removing lots of text

---

android-patches/patches-0.61.5/BasicBuild/ReactAndroid/ReactAndroid.nuspec

Not a code change
Fix the nuget spec to pass the nuget pack step
Fixes in the nuget spec to clear non-existing v8executor and a case sensitivity fix
Publish task should pass

Fixes in the Nuget spec to unblock the publish task

---

package.json

Manually bumping the 0.60-stable branch's version to 0.60.0-microsoft.83 to work around an npm publish script issue.
[macOS] [Fixed] - Manually bump version to .83
No code change

Manually bump version to .83

---

.ado/android-pr.yml
.ado/publish.js
.ado/publish.yml
package.json

No code change
Fixing the gradle task in publish task and adding publish validation in PR
Fixing the gradle task in publish task and adding publish validation in PR

Fixing the gradle task in publish task and adding publish validation in PR

---

.ado/publish.js

No code change
Making cleanup code in publish task cross platform
Making cleanup code in publish task cross platform
Publish should pass

Making cleanup code in publish task cross platform

---

.ado/publish.js
package.json

Manually bump to .87 since the last publish failed.
Inconsequential whitespace change to a .js file just to force the publish pipeline to run since it filters out package.json only changes.
[Fixed] [macOS] - Manually bump to .87.
No code changes.

Manually bump to .87.

---

.ado/publish.yml
package.json

The last publish attempt failed in the 'Publish final artifacts' because a path had a Windows separator instead of a Posix separator.
Bump the package.json version number again just in case.
[macOS] [Fixed] - Fix 'Publish final artifacts' publish step
no code changes.

Fix 'Publish final artifacts' publish step

---

.ado/publish.yml

Disable npmjs.orj publish slice from 0.60-stable branch.
[macOS] [Fixed] - Disable npmjs.orj publish slice from 0.60-stable branch.
No code changes.

Disable npmjs.orj publish slice from 0.60-stable branch.

---

.ado/publish.yml

Fixing publish script as the task argument uses wrong file path separator to be used on Linux/Ubuntu host
No code change
Fixing publish script as the task argument uses wrong file path separator to be used on Linux/Ubuntu host
Fixing publish script as the task argument uses wrong file path separator to be used on Linux/Ubuntu host

Publish script argument uses the wrong file path separator

---

Libraries/Text/RCTTextAttributes.m
Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/Singleline/RCTUITextField.m

Currently we are not using dynamic system colours for our text needs. Either it was hardcoded (such as `RCTUITextView`’s default placeholder colour) or it was implicitly using black as that’s the default for attributed strings (which you can find on slide 231 of [this WWDC deck](https://devstreaming-cdn.apple.com//videos/wwdc/2018/218o6oial8c68yom/218/218_advanced_dark_mode.pdf?dl=1))
[macOS] [Fixed] - Use text color defaults that respect light/dark mode settings

[Text] Fix color defaults for light/dark mode

---

React/React-Core.podspec
package.json

We have this fix in master already. We need to add it to the 0.60-stable branch which pulls it into downstream repos.
[macOS] [Bug] - Compile on Silicon from the 0.60-stable branch.
If CI passes then it's correct.

Don't exclude RCTProfileTrampoline for OS X

---

.ado/android-pr.yml
.ado/publish.yml
.ado/templates/android-build-office.yml

The publish build got out of sync during the 0.62 merge.  This moves more of the build logic to a shared yml file to keep them in sync better.

Align some more of the publish/pr logic on android builds

---

README.md

This simple PR updates the documentation website naming and replaces "Mac" with "macOS" where applicable.

fix macOS and website naming in Readme

---

.ado/templates/apple-job-javascript.yml
.ado/templates/apple-job-react-native.yml
Brewfile
React/Base/RCTDefines.h
package.json

Inside an RCT_PROFILE is the only place we reference RCTProfileTrampoline. We don't actually need this profiler to ship and react-native isn't respecting the _arm64_ macro which would be needed for us to pull in the RCTProfileTrampoline definition.
Leaving it on for iOS for now to reduce the amount of short term changes needed in this area as iOS isn't blocked by this.
[macOS] [Bug] - Disable a profiling macro we don't need
CI passes and builds produce arm64 bits

Disable RCT_PROFILE for macos

---

package.json
yarn.lock

CI was broken. Updating the yarn lock file seems to fix it locally.
[macOS/iOS] [Bug] - Fix CI failure
If CI passes then this works because CI is failing right now

push a new yarn lock file

---

local-cli/generator-macos/templates/macos/Podfile

Hermes is a runtime dependency

[template] Hermes is a runtime dependency

---

package.json

:shipit: 
[macOS] [Added] - Bump to v0.62.0

[package] Bump to v0.62.0

---

React/Base/RCTDefines.h
package.json

A previous commit attempted to compile out all RCT_PROFILE code for macOS using !TARGET_OS_OSX since it wasn't building with Xcode 12 universal and is a severe App Store rejection risk as well as code quality risk due to the swizzling. This successfully removed usage of it in one compilation unit that was indirectly including TargetConditionals.h but not in another where TARGET_OS_OSX was then undefined.
Ultimately we don't want this code lit up on either macOS or iOS in bits we submit to the App Store so let's just compile it out for now with #if 0 and avoid the need for TargetConditionals.h
[iOS] [macOS] [Fixed] - Compile out any code under RCT_PROFILE
Just confirming build and CI since it is just removing debug-only code

Push up intel fixes to RCT_PROFILE

---

.ado/publish.yml
RNTester/Podfile
RNTester/Podfile.lock
package.json
scripts/bump-oss-version.js

* Publish changes to `master` as `0.0.0-canary.x` releases
* Publish changes to `*-stable` as `0.x.y` releases
Next step, if this succeeds, is to create a `0.62-stable` branch and continue onward from `0.62.3`.

Get on that release train

---

.ado/publish.yml
.ado/templates/react-native-macos-init.yml
package.json

Amends the changes from https://github.com/microsoft/react-native-macos/pull/565 to no longer bump the version in `master` nor publish with the `latest` tag.

[ado] Do not bump versions in master nor publish as stable

---

.ado/publish.yml

Switch mechanism used to publish the macOS package to align better with how we publish the init package.

Attempt fix publish builds

---

.ado/publish.yml
package.json

No need for tags of nightly releases—the versions actually have the commit hash encoded.

[ado] Don't tag nightly releases

---

.ado/publish.yml

Allow tagging a stable branch as latest and refactor npm publish task to be more DRY.
This is all per [these ADO docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops), but I couldn't figure out if there’s some tooling to test how these things get evaluated.

[aod] Allow tagging a stable branch as latest

---

.ado/publish.yml

Need to refer to the `variables` global, most probably: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#variables
https://dev.azure.com/ms/react-native/_build/results?buildId=106339&view=results

[ado] Fix variable reference

---

android-patches/patches-0.62.2/BasicBuild/ReactAndroid/ReactAndroid.nuspec

libreactnativeblob.so should be included in the nuget

Internal: Add libreactnativeblob to nuget

---

.ado/publish.yml

Uses a different approach that relies on runtime determination instead of compile time.
It turned out that the variable value was not available at the time of compiling the config. I tried many different variations, but in the end I decided to use task conditions to determine the correct tag and update the tag variable.
See this run https://dev.azure.com/ms/react-native/_build/results?buildId=107618&view=logs&j=6bb1d585-fe16-5108-3aa2-8096d3b89a29&t=4a5e59b1-5470-5cfd-00df-620491cc3a81

[ado] Fix dist-tag determination

---

.ado/publish.yml

While the docs give an example of using a plain script task, I couldn't get the trailing quote to be gone. The only way appears to be to use a bash script.
Also filed a ADO doc PR https://github.com/MicrosoftDocs/azure-devops-docs/pull/9235

[ado] Get rid of trailing quote in npm dist-tag

---

React/Views/RCTView.m
package.json

Fix in master is [here](https://github.com/microsoft/react-native-macos/pull/457). This is a direct port of the change over to our stable branch.
Fixes `overflow:'hidden'` #399 by setting`layer.masksToBounds = self.clipsToBounds;` in the `displayLayer:` method
`overflow: 'hidden'` doesn't work in macOS, but it does work in iOS and Android (not sure about Windows). This change brings functional parity with minimal complexity/conflict.
This also fixes borderRadius on `<Image>` which broke recently because the implementation of `RCTImage` changes from subclass to composition with the image view being a subview and thus now relies on functional clipping behavior.
Note we don't mutate `self.layer.masksToBounds` inside `setClipsToBounds` because modifying `self.layer` is undefined behavior on …

Fix overflow:'hidden' github issue #399 change to 0.60-stable

---

Libraries/Components/Touchable/TouchableBounce.js
Libraries/Components/Touchable/TouchableHighlight.js
Libraries/Components/Touchable/TouchableOpacity.js
Libraries/Components/Touchable/TouchableWithoutFeedback.js
Libraries/Pressability/HoverState.js
RNTester/js/examples/Touchable/TouchableExample.js

This fixes a regression (#588) in 0.62 where `onMouseEnter` and `onMouseLeave` are no longer being called from the `Touchable*` components. It also enables hover callbacks for `Pressability`.
[macOS] [Fixed] - Fix onMouseEnter/Leave on Touchable* components

Fix onMouseEnter/Leave on Touchable* components (#588)

---

Libraries/WebSocket/RCTSRWebSocket.m
React/Views/ScrollView/MacOS/RCTScrollContentLocalData.h

These files would not build on their own without using prefix header, which we don't use in our internal build system.
**Request:** Can we adjust the CI builds to not use any prefix headers to help catch these in the future?
[macOS] [Fixed] - Fixed compilation without prefix headers
Builds without prefix headers.

Fix builds that don't use prefix headers

---

Libraries/Components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Libraries/Components/Touchable/TouchableWithoutFeedback.js

Most of the macOS-specific props should be passed through, but `acceptsKeyboardFocus` and `enableFocusRing` should default to `true` (when not disabled) like the other Touchable components.
[macOS] [Fixed] - Fix passthrough props on TouchableWithoutFeedback
The `TouchableWithoutFeedback` in RNTester is now correctly keyboard focusable.

Fix passthrough props on TouchableWithoutFeedback

---

React/Base/RCTBridge.m

It appears the registration of the reload listener was excluded from macOS before `RCTReloadCommand.m` was updated to support macOS. It's now essential for reloading to work because `RCTTriggerReloadCommandListeners` is called from `RCTDevMenu`.
[macOS] [Fixed] - Fix reloading from dev menu
Right-clicking inside RNTester then selecting **Reload** will now reload (before it would no-op).

Fix reloading from dev menu

---

react-native.config.js
yarn.lock

In https://github.com/react-native-community/cli/pull/1115 I added support to RN cli to modify the default configuration of metro to support out of tree platforms.  This requires that out of tree platforms specify an additional peice of configuration in their react-native.config.js which RN-macOS isn't currently doing.
This is likely the issue with #575 and #564.  We'll want to backport this to 0.62 too.

Provide information to metro to redirect to rn-macos when building macos

---

.ado/android-pr.yml
.ado/apple-pr.yml
.ado/templates/react-native-macos-init.yml
react-native.config.js
scripts/bump-oss-version.js
yarn.lock

[0.62] Provide information to metro to redirect to rn-macos when building macos

---

ReactApple/ReactApple.nuspec

Art is removed so we can't pack what doesn't exist
[Fix] [Bug] - Remove art lib from nuget pack
We can validate in the CI by seeing if the nuget pack gets past the art library.

0.62-stable Art removal to fix nuget publish

---

.ado/templates/react-native-macos-init.yml
scripts/bump-oss-version.js

The `bump-oss-version.js` script is used during npm publishing and during PR testing of the `react-native-macos-init` command line tool.   Both the canary builds and the PR test use the `--nightly` switch which rename the package version to `0.0.0-<commithash>`.
A version number of all zeros in a `.podspec` causes `pod install` to fail, so in `0.62-stable` branch a `--ci` switch was added that changes the version to the passed in string and `react-native-macos-init.yml` passes in `0.62.1000` (https://github.com/microsoft/react-native-macos/pull/596).   In a recent PR to master (https://github.com/microsoft/react-native-macos/pull/603), I made a similar but different fix to add a `--testing` flag that uses the version `1000.0.0` not realizing that this fix was already in the `0.62-stable …

Port `--ci` switch into `bump-oss-version.js` and remove superfluous `--testing` switch.

---

React/Base/RCTConvert.m
React/Base/RCTUIKit.h
React/Views/RCTView.m
React/Views/RCTViewManager.m
React/Views/UIView+React.h
React/Views/UIView+React.m

The previous PR to master https://github.com/microsoft/react-native-macos/pull/603 made several fixes for VoiceOver accessibility.   This change cherry-picks those fixes (commit aac33da5bf3fbb5a6aefb807c0634b86b1e0a508) into the 0.62-stable branch.
[macOS] [fixed] - cherry-pick VoiceOver accessibility issues from master to 0.62-stable
The original PR https://github.com/microsoft/react-native-macos/pull/603 contains comprehensive test notes.

cherry-pick VoiceOver accessibility issues from master to 0.62-stable

---

React/CxxBridge/RCTCxxBridge.mm

This fixes an issue where starting an app already in Chrome debug mode would result in a massive number of RedBoxes being queued up because `devSettings` was being accessed on an invalidated bridge.
[macOS] [Fixed] - Fix unending RedBoxes when starting an app with Chrome debug mode enabled
Our app now loads correctly when Chrome debug mode is already enabled.

Fix unending RedBoxes when starting an app with Chrome debug mode enabled

---

android-patches/patches/Focus/Libraries/Components/View/ReactNativeViewViewConfigAndroid.js
android-patches/patches/Focus/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactClippingViewManager.java
android-patches/patches/Focus/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewFocusEvent.java
android-patches/patches/Focus/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java

We have a small patch lingering for Android focus management for which the JS side config was not authored. The added validateion in 0.62 resulted in a redbox. This change add the JS side configuration of the event.
We have a small patch lingering for Android focus management for which the JS side config was not authored. The added validateion in 0.62 resulted in a redbox. This change add the JS side configuration of the event.
Verified that the red box is no longer popped.

Adding the JS side config for the onFocusChange event on Android

---

React/Base/RCTTouchHandler.m

This change intuitively seemed to have been factored out previously so it could be shared, but perhaps it’s being overloaded from a objc category. Either way, I couldn’t figure that out from the git history or comments, hence this isolated PR.

[defork] Remove unnecessary refactor

---

React/Base/RCTMultipartDataTask.m
React/Base/RCTTouchHandler.m
React/Base/RCTUtils.m
React/CoreModules/RCTAlertManager.mm
React/Views/RCTSegmentedControl.m
React/Views/ScrollView/RCTScrollView.m

RN currently has deployment targets of iOS 10 and macOS 10.13. Office supports the most recent macOS-2 (so 10.13, 10.14, 10.15) and most recent iOS-1 (so iOS13, iOS14).

Remove outdated version guards

---

React/CoreModules/RCTDevSettings.mm

Re-apply fork change to set the right platform in the HMR setup.

Set correct HMR client platform

---

.ado/templates/apple-job-javascript.yml
.ado/templates/apple-job-react-native.yml
Libraries/Image/RCTImageView.mm

The `_imageView` was not being created for macOS. The macro was in the wrong spot. This also adds a check against unnecessarily copying an image inside `RCTFillImagePreservingAspectRatio`.
Confirmed images appearing in RNTester

Fix RCTImageView not rendering images

---

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m
Libraries/Text/TextInput/Multiline/RCTUITextView.m

fixes #639
fixes #611
fixes #639
fixes #611
[macOS] [Fixed] - Fixed bugs #639 and #611 with multiline TextInput
Verify in RNTester > TextInput > Multiline these bugs are fixed.

Fix bugs with multiline TextInput

---

Libraries/StyleSheet/PlatformColorValueTypes.macos.js
Libraries/StyleSheet/PlatformColorValueTypesMacOS.js
Libraries/StyleSheet/PlatformColorValueTypesMacOS.macos.js
Libraries/Text/RCTTextAttributes.m
Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/RCTBackedTextInputViewProtocol.h
Libraries/Text/TextInput/RCTBaseTextInputView.m
Libraries/Text/TextInput/Singleline/RCTUITextField.m
RNTester/Podfile
RNTester/Podfile.lock
RNTester/js/RNTesterApp.ios.js
RNTester/js/examples/PlatformColor/PlatformColorExample.js
index.js
local-cli/generator-macos/templates/macos/Podfile

Related to #621
⚠️  This should not be squashed when merged.

Various post-0.63-merge TODOs

---

Libraries/Text/TextInput/Singleline/RCTSinglelineTextInputView.m

Currently, secure text edit ignores the placeholder text and is always blank. Add that property to secure text input, as well as a couple others.
[General] [Fixed] - Show placeholder in SecureTextInput

Add missing TextInput properties in SecureTextInput

---

RNTester/Podfile.lock
React/Base/RCTTouchHandler.m
React/Base/Surface/RCTSurfaceView.mm
React/CoreModules/RCTLogBox.mm
React/CoreModules/React-CoreModules.podspec
React/Modules/RCTUIManager.m

Related to #621
LogBox is the preferred way to view warnings/errors in v0.63.0.
[macOS] [Added] - NSWindow based version of LogBox
Still minor things to do, but the meat of the patch can be reviewed.

[LogBox] Add NSWindow based version

---

React/CxxBridge/RCTCxxBridge.mm

This method was removed for 0.63, but the `RCTBridge+Cxx.mm` category (which is marked OSS candidate) relies on it existing. This unblocks moving to 0.63, but we will consider upstreaming this to core.

Add back [RCTCxxBridge reactInstance] method

---

local-cli/generator-macos/templates/macos/Podfile

Point to the version that is needed for RN macOS v0.63.0, which includes arm64 support for macOS Big Sur.

[template] Update hermes instruction

---

Libraries/Components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Libraries/Components/Touchable/TouchableBounce.js
Libraries/Components/Touchable/TouchableHighlight.js
Libraries/Components/Touchable/TouchableOpacity.js
Libraries/Components/Touchable/TouchableWithoutFeedback.js
Libraries/Components/Touchable/__tests__/__snapshots__/TouchableHighlight-test.js.snap
Libraries/Components/View/View.js
RNTester/Podfile.lock
RNTester/js/components/RNTesterExampleList.js
RNTester/js/examples/FocusEventsExample/FocusEventsExample.js
React/Base/RCTUIKit.h
React/Views/RCTView.m
React/Views/RCTViewManager.m
React/Views/ScrollView/RCTScrollView.m

Fixes #498
This change adds support for the "focusable" property present in upstream RN, along with react-native-windows and NetUI. We need to reconcile this against the existing acceptsKeyboardFocus property. This is tricky since its usage was untyped. We follow the same strategy as react-native-windows for this.
1. Usages of acceptsKeyboardFocus will continue to work, but will yellowbox
2. Components will prefer to use focusable, and Touchables with slightly different semantics will prefer focusable semantics when present
acceptsKeyboardFocus will redbox in RNW 0.64 instead of yellowbox, but this change should allow xplat code to use focusable and not be effected by that.
[macOS] [Added] - Support focusable, Yellowbox on acceptsKeyboardFocus
Validated setting a view to focusable is …

Support focusable, Yellowbox on acceptsKeyboardFocus

---

React/Views/RCTView.m

For rounded (or partially rounded) buttons, the focus ring would still draw being square. This change allows for focus rings to respect the corner radii.
[macOS] [Fixed] - Use border radius when drawing focus rings
Focus rings draw circular now with border radius. Also confirmed square focus rings for views without border radius set.

Use border radius when drawing focus rings

---

Libraries/Components/Pressable/Pressable.js
Libraries/Components/Pressable/__tests__/__snapshots__/Pressable-test.js.snap
Libraries/Components/TextInput/__tests__/__snapshots__/TextInput-test.js.snap
Libraries/Components/Touchable/TouchableBounce.js
Libraries/Components/Touchable/TouchableHighlight.js
Libraries/Components/Touchable/TouchableOpacity.js
Libraries/Components/Touchable/TouchableWithoutFeedback.js
Libraries/Components/Touchable/__tests__/__snapshots__/TouchableHighlight-test.js.snap
Libraries/Components/View/ReactNativeViewAttributes.js
Libraries/Components/View/ReactNativeViewViewConfigMacOS.js
Libraries/Components/View/ViewPropTypes.js
React/Base/RCTTouchHandler.m
React/Base/RCTUIKit.h
React/Base/macOS/RCTUIKit.m
React/Views/RCTViewManager.m

Presently in RN macOS, clickable views (buttons, etc.) require two clicks when that window is not in the foreground. This counter to the typical behavior on macOS where controls will default to accepting the mouse event even when in the background (and simultaneously bring to the foreground unless the command key is held).
Fixes #531
[macOS] [Added] - acceptsFirstMouse prop on View, Pressable, and Touchable* components
Confirmed in RNTester that we can successfully recognize clicks on buttons while the window is in the background, and this simultaneously brings the window to the foreground.

Support acceptsFirstMouse prop (#531)

---

RNTester/js/components/RNTesterExampleList.js

Wanted to tackle https://github.com/microsoft/react-native-macos/issues/605 which was described as a regression likely when merging upstream virtualized lists changes. However, as I tested this through it turned out that it's the styling override that's to blame, not the actual functionality, which seem to work as intended. 
Fixes https://github.com/microsoft/react-native-macos/issues/605
[macOS] [Fixed] - Fix selection highlight regression in RNTester list
This color doesn't look great in dark mode tho. But I didn't want to diverge too much from the original RNTester. Suggestions welcome.

Fix selection highlight regression in RNTester list

---

.ado/ado-start-verdaccio.sh
.ado/apple-pr.yml
.ado/templates/apple-job-react-native.yml
.ado/templates/apple-node-setup.yml
.ado/templates/react-native-macos-init.yml
.ado/verdaccio/config.yaml
.ado/waitForVerdaccio.js

Change verdaccio server to fix connection refused problem.
[iOS/macOS] [Fix] - verdaccio
if it passes CI then it works

verdaccio host connection refused

---

.ado/ado-start-verdaccio.sh
.ado/apple-pr.yml
.ado/templates/apple-job-react-native.yml
.ado/templates/apple-node-setup.yml
.ado/templates/react-native-macos-init.yml
.ado/waitForVerdaccio.js
React/Base/RCTDefines.h
React/DevSupport/RCTDevLoadingView.m

We can hit a Redbox error in our builds in the init module phase if we error out before we can correctly set up our NSUserDefaults for disabling debugging in the RCTDevSettings module init.
To unblock downstream the fix is to disable debugging on release builds. This is temporary and will hopefully not go into master as we can get a more complete fix in there.
[iOS/macOS] [Fix] - Fix redboxes from showing in release builds
I copied the generated release lib that contains this fix into Word and rebuilt and the scenario no longer redboxes in ship.

Turn off debugging tools for release builds

---

React/CoreModules/RCTDevLoadingView.mm

I thought that the dev loading indicator having rounder corners would look more macOS-like than the one being a rectangle, so here it is. Also moved it 1pt down, so it have a visual distinction from the menu bar. This is purely aesthetic and I understand that it's not worth landing in the core :) It seems nicer though.
||RCTDevLoadingView|
| -- | -- |
|before|<img width="441" alt="Screen Shot 2020-12-05 at 00 55 34" src="https://user-images.githubusercontent.com/5106466/101226766-d36b8c80-3695-11eb-9afb-ff906b6d41de.png">|
|after|<img width="436" alt="Screen Shot 2020-12-05 at 00 51 59" src="https://user-images.githubusercontent.com/5106466/101226762-d23a5f80-3695-11eb-9169-4721dfb401ff.png">|
[macOS] [Changed] - Give RCTDevLoadingView a more macOS look

Give RCTDevLoadingView a more macOS look

---

.ado/android-pr.yml
.ado/templates/prep-android-nuget.yml
RNTester/Podfile.lock
RNTester/RNTesterPods.xcodeproj/xcshareddata/xcschemes/RNTester-macOS Release.xcscheme
React/Base/RCTRedBoxSetEnabled.m
package.json
yarn.lock

Pull in several important fixes to ensure 0.62-stable continues working.
[General] [Fixed] - Update detox to a later version that is compatible with Xcode 12 (cherry picked from #670)
[General] [Fixed] - Disable redboxes on release builds (cherry picked from #671)
[Android] [Fixed] - Fix Android CI (cherry picked from #674) 
RNTester test app still works.

Cherry pick a few commits for 0.62-stable

---

.ado/templates/apple-node-setup.yml
local-cli/runMacOS/runMacOS.js

When running `npx react-native run-macos` (or locally `node node_modules/react-native-macos/local-cli/cli.js run-macos`) and if the target app has spaces in the name, the current call to the `open` macOS command will split the path and only keep the last part as the name in the app, which will fail:
```
...
▸ Build Succeeded
info Launching app "io.sergi.todolist" from "/Users/sergi/Library/Developer/Xcode/DerivedData/Todo_List-efowxgkzzzbxtgeghbplezporgmk/Build/Products/Debug/Todo List.app"
error Failed to launch the app, The file /Users/sergi/code/todo_list/macos/List.app does not exist.
```
This fix  surrounds the path in quotes, which is the standard way to deal with spaces in the path. It solves the issue and introduces no other effects.
[macOS] [Fixed] - Fixes CLI failing to launch …

Enclose the app path in quotes, so that the `open` command doesn't split it if it contains spaces

---

React/Modules/RCTLayoutAnimation.m

(Kinda) Fixes #277 
I decided to take a look at the `LayoutAnimation` implementation and found that it was 99% of the way there already — only needing a single line change in order to opt into implicit CAAnimations. It was so close to working previously that I'm inclined to believe that this was intentional, but without any comments explaining why and the file's history being kind of a mess, I'm submitting this PR so that we can hopefully at the very least get the reasoning documented.
The MacOS implementation of LayoutAnimation uses the closest analog to UIView's animateWithDuration API (what RN on iOS uses) but unfortunately the MacOS API doesn't provide any mechanisms to provide a spring timing function like iOS does. Adding support for the spring timing functions will likely require a …

Complete basic layout animation support

---

.ado/publish.yml

This commit (https://github.com/microsoft/react-native-macos/commit/b2afdfdc8dbb8286417d599255fc8f4049d9729b#diff-8cc88adda4da183aafc286681a96e285509fd92919e0549a163c376f2ee12994) has updated the Android publish task to build with downloaded folly sources. But, the changes to package the downloaded folly headers is not yet available in RN62-stable. Which resulted in ABI mismatch when consuming the RN62 nuget package. 
Devmain SDX features are crashing due to ABI mismatches when using Folly datastructures.
Devmain SDX features are crashing due to ABI mismatches when using Folly datastructures.
This commit (https://github.com/microsoft/react-native-macos/commit/b2afdfdc8dbb8286417d599255fc8f4049d9729b#diff-8cc88adda4da183aafc286681a96e285509fd92919e0549a163c376f2ee12994) has updated the …

Ensuring that the same version of folly is built as well as packaged

---

android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec

Publishing of the Office Android nuget is currently failing due to a malformed nuspec file.

Nuspec has two copies of version tag, and so nuget publish fails

---

React/Base/RCTDefines.h

Undo this for now to unblock other changes getting into devmain. This is likely causing the DevSettings turbo module to not get found in release builds which is breaking.
Can verify once a nuget is produced

Revert RCT_DEV to enabled in release builds to test downstream unblock

---

.ado/templates/apple-job-javascript.yml
.ado/templates/apple-job-react-native.yml
.circleci/config.yml

* Update scripts to publish react-native-macos-init
* Clean up merge markers
* Restored ios:macos RNTester parity except for InputAccessoryView.
* Revert "Restored ios:macos RNTester parity except for InputAccessoryView."
This reverts commit 5a67ae06b01301ac43533e7e20dd7fed24a0937f.
* Remove unnecessary android builds and tar file upload.
* Change verdaccio to run in node 12 instead of node 10.
* Attempt to run verdaccio outside of the `n` context.
* Try node useing UseNode@1
* Use brew to ensure node 12
* Forgot chown step
* Remove duplicated steps to brew install node
* Remove commented out steps
* Disable CCI test that requires a CCI plan which we don't have.
Co-authored-by: React-Native Bot <53619745+rnbot@users.noreply.github.com>

Cherry pick a ci fix into our 0.62 CI branch

---

React/CoreModules/RCTDevSettings.h
React/CoreModules/RCTDevSettings.mm

1. Export the not-debug\noop version of RCTDevSettings. Some Office code expects it to be present and barfs when it doesn't find it.
2. Add a method to export all overridden dev setting keys. There's some (other) Office code that uses a custom data source, but without a way to get all the default keys (and their values) from the default RCTDevSettingsDataSource while replacing it, we end up unintentionally disabling certain things that would've been enabled were we to use the default data source.
1. Verified that the noop version of RCTDevSettings has the desired effect.

Minor tweaks to RCTDevSettings

---

React/Base/RCTDefines.h

This disables debug tools in release builds like redboxing.
This was already tested in Polyester and Devmain earlier. No more redboxing shows up in builds.

Allow exported no-op'd dev settings module in release builds

---

React/CoreModules/RCTDevSettings.h
React/CoreModules/RCTDevSettings.mm

* Export RCTDevSettings noop impl on shipping builds to JS
* Add a protocol method to get all set keys on dev settings
* tag changes

Cherry pick commit b3d41d3 to 0.62 [Minor tweaks to RCTDevSettings]

---

React/CoreModules/RCTDevSettings.mm

This exists upstream so we don't need an explicit comment. We only didn't realize it was gone because of a bad merge from facebook's upstream into our fork.

Remove unnecessary comment

---

Libraries/LinkingIOS/React-RCTLinking.podspec
Libraries/LinkingIOS/macos/RCTLinkingManager.m
Libraries/LinkingIOS/macos/RCTLinkingManager.mm
RNTester/Podfile.lock
android-patches/patches-droid-office-grouped/OfficeRNHost/React/CxxBridge/RCTCxxBridge.mm

Our downstream dependencies need this class- it's currently undefined. This also better aligns our macOS version of this file with the iOS upstream version. It looks like we have everything from [the change](https://github.com/facebook/react-native/commit/1b2992e8b35e500104d07d38adb2ea5a1d98d3ed) that added this except this one export was somehow missed.  To make the fix, some headers we need require the file be an obj-c++ file so we need to rename it to be .mm and then add the class export at the end.
[macOS] [Bug] - Define RCTLinkingManagerCls
Build and nm the build output to verify the symbol now exists.
`0000000000000df0 T __Z20RCTLinkingManagerClsv`

Add missing symbol RCTLinkingManagerCls

---

.ado/android-pr.yml
.ado/apple-pr.yml

Currently the CI loop isn't running on submissions to the 0.63-stable branch.

PR CI should run on all stable branches

---

RNTester/js/examples/KeyboardEventsExample/KeyboardEventsExample.js
React/Views/RCTView.m

This aligns the name to be same as in [react-native-windows](https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp#L282) and the [standard](https://www.w3.org/TR/uievents-key/#keys-ui).
[macOS] [Fixed] - Change key identifier from "Esc" -> "Escape"
Confirmed correct key identifier is logged in the Key Event example in RNTester.

Change key identifier from "Esc" -> "Escape"

---

.ado/android-pr.yml
.ado/apple-pr.yml

This will ensure that the CI builds run on future stable branches.

CI should run on PRs to future stable branches

---

React/Views/ScrollView/RCTScrollView.m

This PR fixes the issue where the scrollbar does not move/animate when scrollToOffset/End is called.
[macOS] [Fixed] - Fixes the issue where the scrollbar does not move/animate when scrollToOffset/End is called
https://user-images.githubusercontent.com/1132214/107857810-9afad400-6de5-11eb-942a-0fff9dc5b693.mov

scroll content with animation

---

Libraries/Text/TextInput/Singleline/RCTSinglelineTextInputView.m

Some props don't always get transferred to the text field instance when the `secureTextEntry` prop is set because of the indeterminate order they get set on the original backing text field. We'll want to find a smarter solution to this, but for now this fixes the rest of the known missing properties.
[macOS] [Fixed] - Fix missing props on secure text inputs
Confirmed this fixes some of the issues we're seeing with properties not getting set when `secureTextEntry={true}`.

Fix missing props on secure text inputs

---

Libraries/Image/RCTAnimatedImage.m
Libraries/Image/RCTUIImageViewAnimated.m
RNTester/js/examples/Image/ImageExample.js

This PR is to enable animated gif playback on Mac
[macOS] [Fixed] - Enable animated gif playback on Mac
https://user-images.githubusercontent.com/1132214/107857248-2ecaa100-6de2-11eb-8890-0e89f83f6597.mov
https://user-images.githubusercontent.com/1132214/108606451-00fbd400-736f-11eb-9a02-45b249a27fb4.mov

Enable animated gif playback on Mac

---

RNTester/Podfile.lock
RNTester/js/examples/KeyboardEventsExample/KeyboardEventsExample.js
React/Views/RCTView.m

Tab is an interesting character to receive a keyboard event for. Tab alone provides an OS event of character @"	" (the width of a tab). However, when paired with the shift modifier key, the Tab event character becomes an empty string modified by the shift bar.
This is likely due to the multiple purposes of the tab key given that tab is used by the OS to traverse between many accessible views.
The easiest fix here is to slot the Tab key along with Escape as a special character that we need to explicitly check the key code for. This also aligns with the [W3 standard](https://www.w3.org/TR/uievents-key/#keys-ui) section 3.3 Whitespace.
After this gets into master I'll make PR's checking it into the 0.62-stable and 0.63-stable branches.
[macOS] [Bug] - Tab keyboard support
Added tab to the …

Add explicit Tab support to keyboarding

---

React/Modules/RCTI18nUtil.h
React/Modules/RCTI18nUtil.m

Note: upstream PR to facebook repo is [here](https://github.com/facebook/react-native/pull/31032)
Internally in Microsoft code, we ran into a deadlock where the main queue and the UIManager queue were both trying to access `[RCTI18nUtil sharedInstance]`, and were blocked on each other. This is similar to an earlier issue with RCTScreenScale decsribed [here](https://github.com/facebook/react-native/issues/18096).
To summarize:
1- RCTShadowView (on the UIManager queue) and RCTView (on the main queue) both try to access `[RCTI18nUtil sharedInstance]`
2- The UIManager thread gets there first, and lazily initializes the sharedInstance. Meanwhile, the main thread is waiting on a lock possessed by the UIManager thread
3- As part of the initialization, we set an NSUserDefault, which seems to …

Fix Deadlock in RCTi18nUtil (iOS)

---

Libraries/Alert/AlertMacOS.js
Libraries/Alert/NativeAlertManager.js
RNTester/NativeModuleExample/ScreenshotMacOS.h
RNTester/NativeModuleExample/ScreenshotMacOS.mm
RNTester/Podfile.lock
RNTester/RNTester-macOS/AppDelegate.mm
ReactTurboModuleCxx/React-TurboModuleCxx-RNW.podspec
ReactTurboModuleCxx/React-TurboModuleCxx-WinRTPort.podspec
ReactTurboModuleCxx/WinRT/Windows.Foundation.h

This fixes a couple issues we had adopting TurboModule initialization on macOS (i.e. `RCTEnableTurboModule(YES)`):
- `AlertMacOS` would error because `RCTAlertManager` was not loaded in a compatible way
- Conflicting `std::hash<std::pair<T, U>>` definition with Folly
This fixes those issues and uses TurboModule initialization from RNTester in much the same as is already being done for the iOS RNTester.
[macOS] [Fixed] - Support TurboModule initialization on macOS
Tested every section of RNTester to confirm no regressions, including testing the Screenshot C++ TurboModule.

Support TurboModule initialization on macOS

---

RNTester/Podfile.lock
React/Modules/RCTI18nUtil.h
React/Modules/RCTI18nUtil.m

Cherry Pick 24c16b1527c071e8f37d8dbdd5319ca992ac4628 into 0.63-stable
[iOS] [Fixed] - Fix deadlock on RCTi18nUtil

Cherry Pick deadlock fix into 063-stable

---

React/Views/RCTViewManager.m

This fixes a regression from when we upgraded to 0.63 where we could no longer call `focus()` or `blur()` on any `View` (including `Text`). This regression was due to a change that dispatches these as commands (to be compatible with Fabric) instead of directly using `UIManager` to change focus. Only the `TextInput` supported these commands.
[macOS] [Fixed] - Fix ability to call focus()/blur() on any view
Confirmed calling `focus()` and `blur()` on `View` and `Text` components now work again.

Fix ability to call focus()/blur() on any view

---

.ado/templates/apple-droid-node-patching.yml
android-patches/patches/ImageColor/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManagersPropertyCache.java
android-patches/patches/ImageColor/ReactAndroid/src/main/java/com/facebook/react/views/image/ReactImageManager.java

This fix will avoid flattening null to '0' when resetting color properties of Image.
I create this [PR](https://github.com/facebook/react-native/pull/31114/) to upstream this change. But later realized there is another active [PR](https://github.com/facebook/react-native/pull/29830) for this issue with similar fix.
This fix will avoid flattening null to '0' when resetting color properties of Image.
This fix will avoid flattening null to '0' when resetting color properties of Image.
Tested.

Fixing bug in Commenting icon disappering on removing tintColor property

---

Libraries/Components/AccessibilityInfo/AccessibilityInfo.android.js
Libraries/Components/AccessibilityInfo/AccessibilityInfo.ios.js
Libraries/Components/AccessibilityInfo/AccessibilityInfo.macos.js
Libraries/Components/AccessibilityInfo/NativeAccessibilityManager.js
RNTester/js/examples/Accessibility/AccessibilityExample.js
React/CoreModules/RCTAccessibilityManager.h
React/Modules/MacOS/RCTAccessibilityManager.m

This adds the `isHighContrastEnabled()` method and `highContrastChanged` event to the `AccessibilityInfo` module. This matches the existing API conventions we have in React Native macOS for other accessibility features. React Native Windows has a [similar API](https://github.com/microsoft/react-native-windows/blob/master/packages/@react-native-windows/tester/src/js/examples-win/Accessibility/AccessibilityExampleWindows.tsx#L45-L59) with its `AppTheme` module, but that module doesn't exist for other React Native platforms and this is more appropriate in `AccessibilityInfo`.
[macOS] [Added] - Add high contrast API to AccessibilityInfo
Tested in RNTester. Observed live updates when changing the **Increase contrast** setting under System Preferences.

Add high contrast API to AccessibilityInfo

---

Libraries/LinkingIOS/macos/RCTLinkingManager.mm

Payloads when handling Linking url events differ between iOS implementation and macOS causing issues with third party libraries like react-navigation. This updates to match the existing react-native url event payload shape.
[macOS] [Fixed] - Fixed discrepancy between Linking url event payloads between iOS and macOS
1. Setup url scheme for iOS and macOS apps
2. Add event listener via Linking.addEventListener('url', handler)
3. Launch apps via url
4. The url event payload should be the same

Match handleOpenURLNotification event payload with iOS

---

Libraries/Animated/src/nodes/AnimatedValue.js

I'm working on a FURN control https://github.com/microsoft/fluentui-react-native/pull/669 that uses the animated library, and there's a bug where animation doesn't loop when the native driver is enabled. There's already a fix https://github.com/facebook/react-native/pull/29585 for the bug but it hasn't been merged to upstream. I want to bring in this fix into our fork to unblock my work.
[Apple] [Bug] - bug fix for Animated
Tested the animation logic in RNTester, I was able to repro the bug and verified that the change fixes the bug.

Fix animation bug 

---

Libraries/Animated/src/nodes/AnimatedValue.js

cherry-pick https://github.com/microsoft/react-native-macos/pull/763
[General] [Fixed] - cherry-pick animation fix

cherry-pick animation fix

---

React/CxxBridge/RCTCxxBridge.mm
ReactCommon/fabric/graphics/platform/ios/Color.cpp
ReactCommon/turbomodule/core/platform/ios/RCTTurboModuleManager.mm

Add Xcode 12.5 support for 0.62-stable. It's my understanding that this different than from what's needed for other versions and we can take those fixes in separately.
`git cherry-pick 8721ee0a6b10e5bc8a5a95809aaa7b25dd5a6043`
[Apple] [Bug] - Xcode 12.5 support
The change was already tested upstream so this is just a cherry-pick.

Xcode12.5 support in 0.62-stable

---

Libraries/Components/Button.js
Libraries/Components/Slider/Slider.js
Libraries/Components/TextInput/TextInput.js
Libraries/Image/ImageProps.js
Libraries/Text/Text.js
Libraries/Text/TextProps.js
RNTester/js/examples/Tooltip/TooltipExample.js
RNTester/js/utils/RNTesterList.ios.js

git cherry-pick https://github.com/microsoft/react-native-macos/pull/701
[macOS] [Added] - Add tooltip support
Ran the RNTester app and made sure tooltip works properly.

Cherry pick tooltip change into 0.62-stable

---

React/Base/RCTDisplayLink.m

Bringing this fix from master to our branch:
`git cherry-pick c9458b9c7f939ae096755a9a2f6d953843141d4d`

Fix display link crash

---

.ado/templates/android-build-office.yml
android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec

Add logic to update the version number from 1000.0.0 to 0.0.0-canary.<commit> when running the internal publish build.  -- This will then be changed to 0.0.0-canary.<commit>-microsoft.0 in a later build step.
Also removed some duplicated lines in the nuspec that was causing the nuget to not get created.

Fix internal canary publishes

---

android-patches/patches/Focus/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewManager.java
android-patches/patches/OfficeRNHost/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java
android-patches/patches/OfficeRNHost/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstance.java
android-patches/patches/OfficeRNHost/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java
android-patches/patches/OfficeRNHost/ReactAndroid/src/main/jni/react/jni/CatalystInstanceImpl.cpp
android-patches/patches/OfficeRNHost/ReactAndroid/src/main/jni/react/jni/CatalystInstanceImpl.h
android-patches/patches/OfficeRNHost/ReactCommon/cxxreact/Instance.h
android-patches/patches/V8/ReactAndroid/src/main/jni/react/jni/Android.mk

These are patches for office's internal usage.  They need to be updated to account for the latest changes synced from react-native.

Update android patches for changes from last merge from core

---

.ado/publish.yml
.ado/templates/android-build-office.yml
.ado/templates/react-native-macos-init.yml
android-patches/build.sh
android-patches/scripts/patch.sh
scripts/vsto-test-ci.sh

The main repo is now using yarn workspaces, with a yarn lockfile.  The various CI tasks need to use yarn to pickup the workspace definition and the lockfile.

Use yarn in a few places that are using npm

---

README.md

I was looking for a package like this, and whilst looking at the README I clicked a dead link.
I found what I think it was supposed to be, and fixed the link.
[General] [Fixed] - Fixed dead link in README.md
No code changes were made.

Fix RNTester folder name in README

---

package.json

- [*] I am making a change required for Microsoft usage of react-native
The android folder got missing in the files section of package.json during 0.64 merge from upstream.
Due to this the internal builds which were dependent on this folder being present in internal npm package were failing

Add the missing android folder to files in package.json

---

.ado/gitTagRelease.js
.ado/npmOfficePack.js
.ado/publish.yml
.ado/versionUtils.js
scripts/bump-oss-version.js

Porting various fixes I made to the 0.64-stable branch to get publishing working again.
In particular makes publish update the version numbers of various files that were not being bumped before, and the RNTester pod lock file will get updated when the version of its dependencies gets bumped.  -- which was previously causing publish to break the lock file, which would cause PRs to start failing.

Fixes for publishing from stable branches

---

React/Base/RCTJSInvokerModule.h

Some downstream dependencies have non null checks that fail here if we don't tag appropriately. This is also a virtuous change as it adds clarity to the method header.
[Bug] [iOS/macOS] - Nonnull compatibility check
No functional change

[0.64] Fix nonnull compat issue

---

android-patches/scripts/downloadDependencies.py

Office has special build variables that allow specifying paths to flavor specific binaries at a single location. In order for this to work however, it is expected that the directories are named debug and ship, instead of debug and release. This change simply renames the directory that hermes release .so files are copied to from "release" to "ship".
[Android] [Fixed] - Copy release hermes related binaries to a directory named ship instead of release
Created a draft PR which published the android nuget package, which I then copied locally and ran a ship build to ensure the build works as expected.

Rename directory for ship .so files to be ship instead of release

---

.ado/templates/apple-droid-node-patching.yml
android-patches/patches/RootViewAttach/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java

This is a revert of this PR: https://github.com/facebook/react-native/commit/2c896d35782cd04c873aefadc947447cc30a7f60#diff-c6c68fb9580db5698d241fdd97b31a25ca1fdc061023a1bf1959f64fc4a00743
The PR mentioned above is breaking assumption taken by our RNHost. Hence reverting the commit until we have a better solution.
The PR mentioned above (https://github.com/facebook/react-native/commit/2c896d35782cd04c873aefadc947447cc30a7f60#diff-c6c68fb9580db5698d241fdd97b31a25ca1fdc061023a1bf1959f64fc4a00743) is breaking assumption taken by our RNHost. Hence reverting the commit until we have a better solution.
Verified the functioning of LPC and commenting in devmain.

Attaching RootView to instance in RootView.startReactApplication

---

React/Base/RCTJSInvokerModule.h
packages/rn-tester/Podfile.lock

We have more strict warning -> error checks downstream and one of the checks requires the block pointer to have a nullability type.
[Bug] [iOS/macOS] - Add nullability check
Just fixes up a warning- if CI passes then everything should be clear.

Add nullability type

---

React/Modules/RCTEventEmitter.h
packages/rn-tester/Podfile.lock

There's one more spot we need a nullable type specifier due to downstream deps having the `-Wnullability-completeness` flag enabled.
Shouldn't affect user scenarios, but if it builds then should be all set.

Add a nullable check

---

React/Modules/RCTEventEmitter.h
packages/rn-tester/Podfile.lock

There's one more spot we need a nullable type specifier due to downstream deps having the `-Wnullability-completeness` flag enabled.
Shouldn't affect user scenarios, but if it builds then should be all set.

Add nullable check

---

Libraries/Image/RCTImageLoader.mm
React/Base/RCTDefines.h
React/Base/RCTRootView.m
React/CoreModules/RCTDevLoadingView.mm
React/CoreModules/RCTDevMenu.mm
React/CoreModules/RCTDevSettings.h
React/CoreModules/RCTDevSettings.mm
React/CxxBridge/RCTCxxBridge.mm
packages/rn-tester/Podfile.lock

Years ago we added in a runtime setting to allow third-party SDX clients to control if they're in debug mode on any builds, regardless of flavor. For the following reasons I'd like to revert this change:
1) Having this diff with FB upstream caused confusion with clients who don't realize we have this macOS repo specific change
2) After 3+ years we have zero clients who have communicated using this feature
3) Debug mode running by accident on ship builds has happened on multiple occasions
4) We've hit ship related crashers to being on debug mode in ship builds by accident
[iOS/macOS] [Feature] - Disabling debugging of ship builds
I can no longer launch the debug menu from ship builds in rn-tester

Disable dev mode on ship builds

---

android-patches/patches/OfficeRNHost/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactBridge.java

- [👍] I am making a change required for Microsoft usage of react-native
This change was there in RN63 and was removed in RN64 as an optimization.
However, this is a probable root cause for a regression. Hence adding the
patch again
Modified the ReactBridge.java through a patch file in android-patches folder

Load Required Libraries in ReactBridge's static init

---

.ado/apple-integration.yml

Add a pipeline for consuming react-native-macos outside of the repository. This should help catch issues earlier (such as #860 or [FBReactNativeSpec not being generated](https://github.com/microsoft/react-native-test-app/runs/4042871673?check_suite_focus=true)).
Backports #878
[Internal] [Added] - Add a pipeline for consuming react-native-macos outside the repository
The newline pipeline should successfully build react-native-macos.

ci: add a pipeline for consuming react-native-macos

---

React/CoreModules/RCTAlertController.m
React/CoreModules/RCTAlertManager.mm

We hit a bug downstream with the existing implementation where we use Scenes in our app which require alerts to be presented from a window associated with the app's UIWindowScene.
Currently without this fix, when we attempt to create a new UIWindow and UIViewController to present a modal alert, that UIWindow isn't associated with any of the app's scenes which results in the app silently failing to show the alert.
The fix is to more or less revert the incriminating part of [this](https://github.com/facebook/react-native/commit/f319ff321c4b7c0929b99e3ebe7e1ce1fa50b34c) change. This is the least intrusive way to make a safe fix, but once this is in, I'd like to make a fuller fix where we find a reasonable way to pair the new UIWindow with the app's scene and continue using that instead. …

Scene support for alerts

---

Libraries/Components/Pressable/Pressable.js
RNTester/Podfile.lock
RNTester/js/examples/Pressable/PressableExample.js

Same as #884 except targeting the 0.63-stable branch.

[0.63] Pull in upstream fixes to expose hover props on Pressable #884

---

Libraries/Components/Pressable/Pressable.js
packages/rn-tester/Podfile.lock
packages/rn-tester/js/examples/Pressable/PressableExample.js

Same as #884 except targeting the 0.64-stable branch.

[0.64] Pull in upstream fixes to expose hover props on Pressable #884

---

.ado/android-pr.yml
.ado/npmOfficePack.js
.ado/publish.yml
android-patches/patches/Build/ReactAndroid/release.gradle

- [👍 ] I am making a change required for Microsoft usage of react-native
The native .so files were missing from AAR packaging. This change adds it back
Remove excludeLibs parameter from build command

Package .so files in AAR File

---

ReactCommon/jsi/jsi/jsi.h

- [x ] I am making a change required for Microsoft usage of react-native
When running clang static analysis on any project that includes jsi.h, we hit an error:
jsi.h:940:28: Forwarding reference passed to std::move(), which may unexpectedly cause lvalues to be moved; use std::forward() instead
In clang's static-analyzer, this is classified as a `[bugprone-move-forwarding-reference]`. From all the docs and source code I can find, I can't find a way to suppress this error in the static analysis invocation because this seems like it is a clang-tidy check that somehow clang's analyzer also checks.
I'm not positive std::forward is the right way to move forward here, so let's just suppress for now to minimize risk while unblocking use of the static-analyzer (unblocked = "it passes on every run …

Disable a bugprone-move-forwarding-reference error when running static analysis against jsi.h

---

Libraries/Components/TextInput/TextInput.js
Libraries/Text/TextInput/Singleline/RCTSinglelineTextInputView.m
Libraries/Text/TextInput/Singleline/RCTUITextField.h
Libraries/Text/TextInput/Singleline/RCTUITextField.m

Implements `enableFocusRing` for TextInput component. Solves https://github.com/microsoft/react-native-macos/issues/795
[macOS] [Fixed #795] - add ability to disable focus ring for TextInput component https://github.com/microsoft/react-native-macos/issues/795
I've created fresh new react-native-macos app and add 2 TextInput components to the App.tsx
```typescript
...
<SafeAreaView style={backgroundStyle}>
<StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
<TextInput
enableFocusRing={false}
style={{
width: 200,
borderBottomColor: isDarkMode ? 'white' : 'gray',
borderBottomWidth: 1,
alignItems: 'center',
justifyContent: 'center',
flexDirection: 'row',
}}
/>
<TextInput
style={{
width: 200,
borderBottomColor: isDarkMode ? 'white' : 'gray',
borderBottomWidth: 1,
alignItems: …
```

add enableFocusRing feature for TextInput component

---

ReactCommon/jsi/jsi/jsi.h

- [ x ] I am making a change required for Microsoft usage of react-native
Cherry pick #934 to 0.64-stable to unblock static analyzer usage
[General] [Fixed] Suppress errors running static analysis when including jsi.h
See #934

Disable a bugprone-move-forwarding-reference static analysis error

---

Libraries/Components/TextInput/TextInput.js
Libraries/Text/TextInput/Singleline/RCTSinglelineTextInputView.m
Libraries/Text/TextInput/Singleline/RCTUITextField.h
Libraries/Text/TextInput/Singleline/RCTUITextField.m

Bringing a [change from master](https://github.com/microsoft/react-native-macos/pull/932) over to our 0.64-stable branch.
`git cherry-pick 053c2b4be5517e57473f922d36ea73975814f880`
This was tested in master.

Add enableFocusRing feature for TextInput component (#932)

---

.ado/android-pr.yml
.ado/publish.yml

- [👍] I am making a change required for Microsoft usage of react-native
In PR#933, to resolve an internal bug, we removed included the library files in the react-native AAR. However, its not required in the nuget package consumed by office. This change removes the binaries from nuget publish

Exclude Libraries from the AAR published in Office Nuget

---

scripts/run-ci-e2e-tests.js

The `Flow Check` phase of our End to End Circle CI tests fails. This _seems_ to be because the E2E test is installing _react-native-macos` version 0.63 instead of latest (which is missing the `Colors.darker` variable, which is how I figured that out. I haven't figured it out yet (perhaps #944 will help?), but this is blocking PRs quite a bit. Let's comment it out for now
[Internal] [Removed] - Removed Flow check test from E2E tests temporarily

Comment out failing circle ci test

---

.ado/apple-integration.yml

Our main branch isn't stable yet. I think this is because we've been doing our 0.66 merge  in the [fb66merge branch](https://github.com/HeyImChris/react-native-macos/tree/fb66merge) of @HeyImChris 's fork.
While main isn't stable,  let's disable another failing CI check to not unblock merges. We **should** track fixing this test (along with the disabled test in #945 ) because we will need nightly builds passing eventually.

Disable Integration job on main branch

---

Libraries/Components/Pressable/Pressable.js
Libraries/Pressability/Pressability.js
packages/rn-tester/js/examples/Pressable/PressableExample.js

Closes #518 
Pressable was missing the `onFocus/onBlur` callbacks, I guess we missed this when we first added those props to `Touchable`. Let's go explicitly add them. I based my code off of the React Native Windows fork of Pressable.
In the future, I would also like to add Space/Enter keyboarding defaults to Pressable like React Native Windows has, where onKey(Down|Up) of Space/Enter on a Pressable is equivalent to onPress(In|Out). However, that would need me to make significant changes to how keyboard events work on macOS, so I'll just be sure to expose them now and leave it for later. 
[macOS] [Fixed] - Pressable didn't expose onFocus/onBlur
Added tests to rn-tester which indeed show onFocus/onBlur are fired.

Add onFocus/onBlur/onKeyDown/onKeyUp to Pressable

---

Libraries/Text/TextNativeComponent.js

A client was reporting that tooltip wasn't showing up on the text component. This seems to be a simple one line fix.
[macOS] [Fixed] - Fix Tooltip on Text not showing up
Checked the tooltip test page that tooltip on <Text> shows up.

Fix Tooltip on Text not showing up

---

Libraries/Text/TextNativeComponent.js

Cherry pick #960 into 0.64-stable
=========================
A client was reporting that tooltip wasn't showing up on the text component. This seems to be a simple one line fix.
[macOS] [Fixed] - Fix Tooltip on Text not showing up
Checked the tooltip test page that tooltip on <Text> shows up.

[0.64] Expose text tooltip

---

Libraries/Components/Pressable/Pressable.js
Libraries/Pressability/Pressability.js
packages/rn-tester/js/examples/Pressable/PressableExample.js

Cherry pink #962 into 0.64-stable
==========================
Closes #518 
Pressable was missing the `onFocus/onBlur` callbacks, I guess we missed this when we first added those props to `Touchable`. Let's go explicitly add them. I based my code off of the React Native Windows fork of Pressable.
In the future, I would also like to add Space/Enter keyboarding defaults to Pressable like React Native Windows has, where onKey(Down|Up) of Space/Enter on a Pressable is equivalent to onPress(In|Out). However, that would need me to make significant changes to how keyboard events work on macOS, so I'll just be sure to expose them now and leave it for later. 
[macOS] [Fixed] - Pressable didn't expose onFocus/onBlur
Added tests to rn-tester which indeed show onFocus/onBlur are fired.

[0.64] Add onFocus/onBlur/onKeyDown/onKeyUp to Pressable

---

.ado/apple-integration.yml
packages/rn-tester/Podfile.lock

Reverts microsoft/react-native-macos#947
Closes #948

Revert "Disable Integration job on main branch"

---

.ado/versionUtils.js

Previous publish build failed due to incorrect args to publish script.

Fix publish script

---

third-party-podspecs/RCT-Folly.podspec

react-native-macos fails to build if Hermes is enabled:
```
Undefined symbols for architecture x86_64:
"folly::exception_ptr_get_type(std::exception_ptr const&)", referenced from:
folly::exception_wrapper::ExceptionPtr::type_(folly::exception_wrapper const*) in libRCT-Folly.a(ExceptionWrapper.o)
folly::exceptionStr(std::exception_ptr const&) in libRCT-Folly.a(ExceptionString.o)
"folly::exception_ptr_get_object(std::exception_ptr const&, std::type_info const*)", referenced from:
std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libReact-hermes.a(Connection.o)
std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libRCT-Folly.a(ExceptionWrapper.o)
std::exception* …
```

fix: Hermes no longer builds without `Exception.cpp`

---

.ado/templates/android-build-office.yml
android-patches/patches/OfficeRNHost/ReactAndroid/src/main/jni/react/jni/CatalystInstanceImpl.cpp
scripts/bump-oss-version.js

Add an `--autogenerateVersionNumber` flag to scripts/bump-oss-version.js.
Some CI checks have been failing due to a change in this script. We still have some old invocations that assume the script will generate an ad-hoc version number. This change helps make the transition easier. If we so desire, we can change our CI scripts as needed in the future.

Add --autogenerateVersionNumber option to bump-oss-version.js

---

.ado/publish.yml

Add the `--autogenerateVersionNumber` flag for the bump-oss-version.js invocation in publish.yml.
This new flag was introduced with #989. While this ADO task won't get run in a non-main branch, we're still making it here for the sake of correctness.

Add --autogenerateVersionNumber flag for canary version in publish.yml

---

.ado/templates/react-native-macos-init.yml
Libraries/Text/Text/RCTTextView.m

By default, `-[RCTTextView description]` works by adding information specific to `RCTTextView` in its superclass's description. However, the current implementation depends on the existence of a semicolon in the superclass's description. This assumption appears to hold on iOS, but it doesn't hold on macOS, which can cause `-[NSString stringByReplacingCharactersInRange:withString:]` to do some weird stuff on macOS.
This fix addresses this problem by checking that the result of `[superDescription rangeOfString:@";"]` is valid before trying to replace it.

Add a safety check in -[RCTTextView description]

---

.github/CODEOWNERS

One thing I noticed is that whenever a new PR is opened @alloy gets assigned as codeowner to review. (the reason why it was only him is because the 3 owners were in 3 separate lines, see: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
I've updated the file to reflect the current status (as far as I can tell) of who is in charge of this repo at this point in time.
N/A
N/A

[chore] address codeowners to reflect current status

---

docs/hermes-jan-2020.md

These were handoff notes from @alloy with some alterations to make suitable for public viewing. Add them to the repo for safe-keeping.

Add Docs for Hermes Handoff Jan 2020

---

android-patches/patches/Build/ReactAndroid/Android-prebuilt.mk

This change adds a patch to update the boost version to 1.68 to ensure boost headers are searched for in the proper directories when building the rn-tester app for android.
[Android] [Fixed] - Ensure rn-tester for android builds successfully
Built via the commands in the pr pipeline for android, and then ran `./gradlew :packages:rn-tester:android:app:assemblehermesdebug` which built successfully

Adding patch to ensure rn-tester for android builds successfully

---

React/CoreModules/RCTDevSettings.h
React/Modules/RCTEventEmitter.h

A couple of fixes that would result in compilation errors in the main branch

Fix a couple of compilation errors present in the main branch

---

.ado/templates/android-build-office.yml
.ado/templates/apple-node-setup.yml
.circleci/config.yml
Brewfile
package.json

Currently, the CI setup is still using Node 12, which is 2-LTS(s) old. The current [LTS is 16](https://nodejs.org/en/), so I'm updating all the references to match that.
~While doing so, I've noticed that there's a local brewfile but that is clearly not used - since the end of the lock shows that it was last "run & commited" back when `"Xcode": "11.5",` was the used version. So I've removed it to declutter a bit.~
NVM it looks like it's used on CI and it doesn't seem to matter of the lock is outdated 🤷‍♂️
N/A
CI is the test, locally everything seems to be running fine.

[chore] bump all references to Node 16

---

React/CoreModules/RCTAlertController.m

This is a follow-up to #917.
In iOS 14, if we call `-[UIWindow makeKeyAndVisible]` from a `UIWindow` that isn't part of the app, the current key window gets made non-key. This can result in `RCTKeyWindow()`, and thusly, `RCTPresentedViewController()`, to come back as `nil`, which means that the alert never shows up.
The fix here is to ensure that we don't try to make the alert window key unless it's actually tracked by the application.
Validated in a downstream app on iOS 14.

fix (iOS): Only try to make the alert window key if the app recognizes it

---

React/CoreModules/RCTAlertController.m

This is a cherry-pick of 5c51f7dd6c93f19b65b6a61bfeb87a9ab0f19584 into 0.66-stable.

fix (iOS): Only try to make the alert window key if the app recognizes it (#1008)

---

React/CoreModules/RCTDevSettings.h
React/Modules/RCTEventEmitter.h

This cherry-picks the two commits from #1004 into 0.66-stable to fix downstream compilation errors.

Cherry pick #1004 into 0.66-stable

---

.ado/publish.yml

Add required steps to generate an [SBOM](https://en.wikipedia.org/wiki/Software_bill_of_materials) manifest and archive the manifest.
[Internal] [Added] - Add SBom Manifest Generation
None, This change has been made to many other repo's. I'll wait for the release pipeline to run and monitor it.

Add SBom manifest

---

third-party-podspecs/RCT-Folly.podspec

react-native-macos fails to build if Hermes is enabled:
```
Undefined symbols for architecture x86_64:
"folly::exception_ptr_get_type(std::exception_ptr const&)", referenced from:
folly::exception_wrapper::ExceptionPtr::type_(folly::exception_wrapper const*) in libRCT-Folly.a(ExceptionWrapper.o)
folly::exceptionStr(std::exception_ptr const&) in libRCT-Folly.a(ExceptionString.o)
"folly::exception_ptr_get_object(std::exception_ptr const&, std::type_info const*)", referenced from:
std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libReact-hermes.a(Connection.o)
std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libRCT-Folly.a(ExceptionWrapper.o)
std::exception* …
```

fix: Hermes no longer builds without `Exception.cpp` (#982)

---

.ado/templates/apple-droid-node-patching.yml
android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec
android-patches/patches/JniUtils/ReactAndroid/src/main/java/com/facebook/react/fabric/jni/Android.mk
android-patches/patches/JniUtils/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni/Android.mk
android-patches/patches/JniUtils/ReactAndroid/src/main/jni/react/jni/Android.mk
android-patches/patches/JniUtils/ReactCommon/react/renderer/components/progressbar/Android.mk
android-patches/patches/JniUtils/ReactCommon/react/renderer/components/slider/Android.mk
android-patches/patches/JniUtils/ReactCommon/react/renderer/components/switch/Android.mk
android-patches/patches/JniUtils/ReactCommon/react/renderer/textlayoutmanager/Android.mk
android-patches/patches/OfficeRNHost/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactBridge.java
android-patches/patches/RootViewAttach/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java

1. Patches already applied in 0.64 but weren't brought to main
2. New patches to bring new SO files to devmain

[Main] Adding patches required for running RN66 in Office apps

---

.ado/templates/apple-droid-node-patching.yml
android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec
android-patches/patches/JniUtils/ReactAndroid/src/main/java/com/facebook/react/fabric/jni/Android.mk
android-patches/patches/JniUtils/ReactAndroid/src/main/java/com/facebook/react/turbomodule/core/jni/Android.mk
android-patches/patches/JniUtils/ReactAndroid/src/main/jni/react/jni/Android.mk
android-patches/patches/JniUtils/ReactCommon/react/renderer/components/progressbar/Android.mk
android-patches/patches/JniUtils/ReactCommon/react/renderer/components/slider/Android.mk
android-patches/patches/JniUtils/ReactCommon/react/renderer/components/switch/Android.mk
android-patches/patches/JniUtils/ReactCommon/react/renderer/textlayoutmanager/Android.mk
android-patches/patches/OfficeRNHost/ReactAndroid/src/main/java/com/facebook/react/bridge/ReactBridge.java
android-patches/patches/RootViewAttach/ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java

Patches already applied in 0.64 but weren't brought to main
New patches to bring new SO files to devmain
This change is cherry picked from main
`git cherry-pick cadd8890f761d4e2e4a331a0db0d4ce2c9c91d85`
Patches already applied in 0.64 but weren't brought to main
New patches to bring new SO files to devmain
This change is cherry picked from main
`git cherry-pick cadd8890f761d4e2e4a331a0db0d4ce2c9c91d85`

[0.66-stable]Adding patches required for running RN66 in Office apps

---

React/Base/RCTBridgeModule.h
packages/rn-tester/Podfile.lock

We've seen a downstream compilation error where RCTBundleManager's bundleURL property isn't given a good memory management attribute. Making this property strong seems like the right thing to do here, since if someone is interested in knowing this URL they might as well hold a strong reference to it.
Validated that RNTester still compiles.

Make RCTBundleManager's bundleURL a strong property

---

.github/CODEOWNERS

Updating the android code owner to a github group under microsoft org. This is required for EO compliance.
Updating the android code owner to a github group under microsoft org. This is required for EO compliance.

Updating the android code owner to a microsoft github group

---

React/Base/RCTBridgeModule.h

Cherry pick of the two commits in #1025.

[0.66-stable cherry pick #1025] Make RCTBundleManager's bundleURL a strong property

---

.ado/android-pr.yml
.ado/templates/android-build-office.yml

Trying to execute the PR steps locally (via an automatically generated script) can result in errors when invoking the generated script multiple times. This PR attempts to fix that, and also perform some additional clean up like giving a display name to a step, generating RNTesterApp.android.bundle to the expected location, and use Unix style paths instead of windows paths
[Android] [Fixed] - Cleaning up Android PR to allow for repeated executions without error.
Running the PR pipeline and executing locally.

Cleaning up parts of android-pr.yml

---

React/Views/RCTView.h
React/Views/RCTView.m

This change makes the macOS fork compatible with react-native-core and the current RTCBridge implementation.
It changed in react-native-core in https://github.com/facebook/react-native/commit/ea93151f21003df6f65dd173dd5dcb3135b0ae94
[macOS] [Fixed] - Use RCTEventDispatcherProtocol in RCTView.h/.m (instead of RCTEventDispatcher*)
Ran rn-tester app
Used at Meta Inc. for Facebook Messenger macOS

Use RCTEventDispatcherProtocol in RCTView

---

android-patches/patches/Build/ReactAndroid/NuGet.Config
android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec
android-patches/patches/Build/ReactAndroid/packages.config
android-patches/patches/Focus/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewFocusEvent.java
android-patches/patches/OfficeRNHost/ReactCommon/cxxreact/PlatformBundleInfo.h
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/Android.mk
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/OnLoad.cpp
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8Executor.java
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8ExecutorFactory.cpp
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8ExecutorFactory.h
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8ExecutorFactory.java
android-patches/patches/V8/ReactAndroid/src/main/jni/third-party/v8jsi/Android.mk

This change regenerates some of the android specific patches related to newly created files. Currently, if we were to reapply patching, this would result in content being duplicated, due to how the patch was generated. With the new patches, content is not repeated on subsequent applies. The main advantage of this is that it avoids cryptic build errors in the scenario that a developer applies the patches multiple times (for instance through use of an auto generated script).
[Android] [Fixed] - Allow patches to be applied multiple times without issue.
Built locally and was able to build successfully after applying the patches multiple times.

AB#5839699 - Repeated application of android patches should not duplicate changes

---

.ado/apple-integration.yml

Ccache is interfering with how Xcode finds `libclang_rt.ubsan_osx_dynamic.dylib` in the integration pipeline.
[Internal] [Fixed] - Disable Ccache to fix Xcode not being able to find `libclang_rt.ubsan_osx_dynamic.dylib`
Integration pipeline should be green.

ci: disable Ccache in integration pipeline

---

.ado/apple-integration.yml

Ccache is interfering with how Xcode finds `libclang_rt.ubsan_osx_dynamic.dylib` in the integration pipeline.
Cherry-picks #1043
[Internal] [Fixed] - Disable Ccache to fix Xcode not being able to find `libclang_rt.ubsan_osx_dynamic.dylib`
Integration pipeline should be green.

ci: disable Ccache in integration pipeline (#1043)

---

android-patches/patches/Build/ReactAndroid/NuGet.Config
android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec
android-patches/patches/Build/ReactAndroid/packages.config
android-patches/patches/Focus/ReactAndroid/src/main/java/com/facebook/react/views/view/ReactViewFocusEvent.java
android-patches/patches/OfficeRNHost/ReactCommon/cxxreact/PlatformBundleInfo.h
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/Android.mk
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/OnLoad.cpp
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8Executor.java
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8ExecutorFactory.cpp
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8ExecutorFactory.h
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8ExecutorFactory.java
android-patches/patches/V8/ReactAndroid/src/main/jni/third-party/v8jsi/Android.mk

This change regenerates some of the android specific patches related to newly created files. Currently, if we were to reapply patching, this would result in content being duplicated, due to how the patch was generated. With the new patches, content is not repeated on subsequent applies. The main advantage of this is that it avoids cryptic build errors in the scenario that a developer applies the patches multiple times (for instance through use of an auto generated script).
[Android] [Fixed] - Allow patches to be applied multiple times without issue.
Built locally and was able to build successfully after applying the patches multiple times.

AB#5847131 Cherry pick patch generation to 0.66-stable

---

.circleci/config.yml
scripts/run-ci-e2e-tests.js

This test never worked well, and I got tired of seeing red X's
[Internal] [Changed] - Disabled failing CircleCI tests

Disable failing CircleCI test

---

packages/rn-tester/RNTesterUnitTests/RCTConvert_NSColorTests.m

In #1028 I removed RCTDynamicColor.h/.m . There was still an explicit reference to the class in our unit tests. I'm not sure why that wasn't caught. 
[macOS] [Fixed] - Removed reference to RCTDynamicColor in our unit tests. 

remove references to RCTDynamicColor

---

React/Base/macOS/RCTDynamicColor.h
React/Base/macOS/RCTDynamicColor.m
packages/rn-tester/RNTesterUnitTests/RCTConvert_NSColorTests.m

EDIT: Due to integration issues, I'll need to add back the RCTDynamicColor class to 0.66 as downstream components reference it. 
(Same as #1060 but ported to 0.66-stable)
In #1028 I removed RCTDynamicColor.h/.m . There was still an explicit reference to the class in our unit tests. I'm not sure why that wasn't caught. 
[macOS] [Fixed] - Removed reference to RCTDynamicColor in our unit tests. 

[0.66] Add back RCTDynamicColor, but remove references

---

React/Views/RCTModalHostView.h
React/Views/RCTModalHostViewManager.m

We're hitting a Redbox downstream that `Component 'RCTModalHostView' re-registered bubbling event 'topDismiss' as a direct event moduleConstantsForComponent`. In our js files the object is defined as a direct event but the view manager defines it as a bubbling event. I checked Fb's upstream and they have this mismatch as well so we could probably push a fix up to their repo too.
[macOS/iOS] [Bug] - Fix bubbling event Redbox
Won't impact the product but the redbox should go away

[0.66] onDismiss is a direct event

---

.ado/publish.yml

Backport SBOM generation and mark validation step as [test].
The pipeline is passing, and running but with warnings at the moment.
[Internal] [changed] - Message
N/A

[0.66] Backport SBom generation

---

.gitignore

GitIgnore SBOM _manifest  folder to prevent it from being pushed
[Internal] [Changed] - Git ignore SBOM Manifest folder
N/!

GitIgnore SBOM _manifest folder to prevent it from being pushed

---

React/Base/macOS/RCTPlatformDisplayLink.m

In #1071 , we added some usages of the API `OSSpinLockLock` and `OSSpinLockUnlock`. Xcode warns me those are deprecated, and to use `os_unfair_lock_lock` and `os_unfair_lock_unlock` instead.
[macOS] [Fixed] - Fix usage of deprecated API "OSSpinLockLock"
Honestly, I have no idea how to test this 🤷🏾

Fix usage of deprecated API "OSSpinLockLock"

---

Libraries/Text/TextInput/Multiline/RCTUITextView.m

Calling `self.font` would report `AppleColorEmojiUI` after entering an emoji, which would mess up placeholder drawing. This changes the macOS implementation to use the `_placeholderTextAttributes` method. This also prevents `NSTextView` from overriding `typingAttributes` to a value other than what we want (`_defaultTextAttributes`), which fixes an issue where the font would change after inserting an emoji.
Reviewed By: ackchiu
Differential Revision: D27443488
Co-authored-by: Scott Kyle skyle@fb.com
[macOS] [Fixed] - Fix buggy styling of placeholder in TextInput
https://user-images.githubusercontent.com/484044/156862523-fa0af232-d4eb-49ef-a437-c52df788e189.mov

Fix buggy styling of placeholder in TextInput

---

Libraries/Text/Text/RCTTextView.m
Libraries/Text/TextInput/Multiline/RCTUITextView.m

Since React Native macOS relies entirely on layer-backed views, there's unfortunately a bit of dark magic (setting `canDrawSubviewsIntoLayer` in the right places) required for getting text to render clearly on non-retina displays.
See: https://stackoverflow.com/questions/3917871/creating-a-label-using-nstextfield-is-blurry
Co-authored-by: Scott Kyle <skyle@fb.com>
[macOS] [Fixed] - Fix blurry text on non-retina displays
Before
After
Before
After
Before
After

Fix blurry text on non-retina displays

---

package.json
yarn.lock

Hermes 0.10 has invalid bitcode which results in instant rejection from Apple's app store. As a result we need to revert back to 0.9. 
[Android] [Fixed] - Revert hermes-engine to 0.9 to avoid instant rejection from Apple app store

Revert hermes engine to 0.9

---

React/Base/RCTConvert.m

This looks like a simple typo. It just changes what voiceover reads out "You are on a menu _bar_ item" vs "you are on a menu item". In both cases you can press Contol+Option+Space to interact with the element. 
[macOS] [Fixed] - Fixed Menu Item accessibility role
Tested locally in FluentUI React Native's test app

Fix AccessibilityRole of MenuItem

---

Libraries/Components/AccessibilityInfo/AccessibilityInfo.js

Adjust the logic in AccessibilityInfo.js so it behaves nicely on macOS.
We received a bug report saying that trying to check for an iOS-only accessibility feature results in a rejected promise. It's much more elegant to just fulfill the promise and return `false`, just like we would do on Android.
Upstream, it doesn't matter whether we check for `Platform.OS === 'android'` or `Platform.OS === 'ios'`, since the platform is limited to these two options. But when we add a third platform into the mix, it makes things more complicated. This is something we could theoretically push upstream.
While we're here, we might as well add macOS tags to `isHighContrastEnabled`, a macOS-only accessibility feature.
[macOS] [Fix] - Improve macOS logic for iOS-only accessibility features

Rearrange the logic in AccessibilityInfo.js to ensure it works nicely with macOS

---

.flowconfig
.flowconfig.android
.flowconfig.macos
jest.config.js
metro.config.js

The `android-patches` directory contains patches where the patch files is named as the same as the file that will be patched. This causes issues when trying to patch `package.json`, as various tools try to operate on any file that is named `package.json` unless explicitly ignored.
[Android] [Fixed] - Ignore `android-patches` directory for `jest`, `metro` and `flow`.
Ensuring all PR checks succeed is sufficient.

Ignore android-patches directory for jest, metro and flow

---

.flowconfig
.flowconfig.android
.flowconfig.macos
jest.config.js
metro.config.js

The `android-patches` directory contains patches where the patch files is named as the same as the file that will be patched. This causes issues when trying to patch `package.json`, as various tools try to operate on any file that is named `package.json` unless explicitly ignored.
[Android] [Fixed] - Ignore `android-patches` directory for `jest`, `metro` and `flow`.
Ensuring all PR checks succeed is sufficient.

Backport - Ignore android-patches directory for jest, metro and flow

---

.ado/templates/apple-droid-node-patching.yml
android-patches/patches/Hermes/package.json
android-patches/patches/Hermes/yarn.lock

In order to consume Hermes in Office for Android, we need a fix that made it into version 0.10. Due to an issue in 0.10, we decided to bump to 0.11 as there wouldn't be any breaking API changes. 
[Android] [Added] - Upgrade Hermes to 0.11 for android only via a patch
Tested via the Hermes variant of RN tester.

AB#5902056 - Upgrade hermes to 0.11 for Android only

---

React/Views/RCTShadowView.m

Passing 0 to `YGConfigSetPointScaleFactor()` turns off layout rounding entirely, which makes things look blurry.  While it would be nice to use the backing scale factor of the window, that would be a very involved change.  Instead, hardcode 1x alignment.  On 2x displays, this just means that views cannot sit on half-point boundaries.  (They're still *rendered* at 2x, though.)
[macOS] [Fixed] - Use 1x frame alignment
Ran a React Native demo project on macOS 10.15.7 / MacBookAir6,2.
Before:
After:

RCTShadowView: use 1x alignment

---

.ado/templates/apple-droid-node-patching.yml
android-patches/README.md

As part of some follow up work in rnx-kit https://github.com/microsoft/rnx-kit/pull/1189 we changed the name of the patcher tool to be less misleading, from `draft-patch-rnmacos` to `patcher-rnmacos`.
This PR updates macos to use the new name. I don't think we'll have to cherry pick this into 0.66 branch.
Commands run fine locally, CI should be ✅

chore(android-patches): use new name for patching tool for android

---

bots/package.json
bots/yarn.lock

Cherry pick of 297a43de995537be350eed32c4dc02c8fd7310ba.
This resolves a ReDoS issue in `websocket-extensions`, an indirect dependency of `firebase`. See [here](https://blog.jcoglan.com/2020/06/02/redos-vulnerability-in-websocket-extensions/) for more information.

RN: Upgrade `bots/` Dependencies

---

.ado/publish.yml

On main branch https://github.com/microsoft/react-native-macos/commits/main , there's a job that always fails CI `microsoft.react-native-macos` on ADO. This is because it fails on `React-Native GitHub Publish to Office` on the task `Bump package version`. This happens because by definition, this task is only meant to run *not* on main:
This error is caused by `scripts/bump-oss-version.js` at L86->89
So basically we have a failing CI on main branch that is meant to be red by definition because it's main branch.
To address this, it sounds like it'd be just easier to prevent this entire job from running (and saving CI resources) by adding a filter to only run on `-stable` branches. I discussed this option with @acoates-ms and he gave me the 👍 since it's only for the RN publish to office so …

fix(ci): change "React-Native GitHub Publish to Office" to only run on stable branches, not main

---

.ado/publish.yml

Fixes the wrongly added method `eq()` in L187 added here  - https://github.com/microsoft/react-native-macos/pull/1105
It's enough to verify if the branch name contains -stable to proceed, the eq was most likely a leftover from a different implementation I attempted at an earlier stage 🥲
N/A

fix(ci): fix condition on YML publish

---

package.json
packages/rn-tester/package.json
repo-config/package.json
yarn.lock

lodash 4.17.20 has [several known security vulnerabilities](https://snyk.io/test/npm/lodash/4.17.20) that are resolved in 4.17.21.
The version of `detox` we were previously using, 16.7.2, appears to indirectly refer to an older version of lodash. Bumping the version appears to get rid of one of the references (and it resolves [other known vulnerabilities](https://snyk.io/test/npm/detox/16.7.2)), but yarn.lock is still holding on to some old versions, so we also run `yarn upgrade`.
Overall, this reduces the number of existing vulnerabilities reported by `yarn audit` from 42 to 6.
[Internal] [Security] - Update dependencies to remove security issues
RNTester still appears to work fine. As long as the rest of the CIs pass, we should be good to go.

Remove references to lodash 4.17.20

---

packages/eslint-config-react-native-community/yarn.lock

Run `yarn upgrade` in `packages/eslint-config-react-native-community`
As a follow-up to #1111, we found a reference to lodash 4.17.20 in this directory's yarn.lock file, so it needs to be given the `yarn upgrade` treatment as well.
[Internal] [Security] - Remove stale packages in yarn.lock file
Running `yarn audit` from within `packages/eslint-config-react-native-community` now results in 0 issues coming up.

Run `yarn upgrade` in eslint-config-react-native-community

---

.ado/templates/apple-node-setup.yml

Our "Verify react-native-macos-init" loop is failing in 0.66-stable because the latest version of react-native, 0.68, requires a minimum Node version of 14.
The main branch currently uses Node v16, but I figure that only upgrading to 14 is a more minimal change that should get everything working. 
If the CI passes, we know it works :-)

chore: Use node 14 for Apple test loops

---

package.json
yarn.lock

An internal policy prevents us from using package with protest ware. 
Packages of es5-ext after 0.10.54 and at the moment up until 0.10.59 contain a protest message. 
Therfore downgrading to the latest release without the message to comply with policies.
[Interanl] [Changed] - Downgrade es5-ext
N/A

Downgrade es5-ext pacakge to comply with policies

---

Libraries/Text/TextInput/RCTBaseTextInputView.m

We've seen a crash downstream where `-[NSString stringByReplacingCharactersInRange:withString:]` receives a `nil` value as the replacement string. This is not good, since we expect that argument to be non-null.
We believe that a cause of this is that `-[RCTUITextField textView:shouldChangeTextInRange:replacementString:]` is being called with `nil` as the replacement string. (This is legal, as per [Apple's documentation](https://developer.apple.com/documentation/appkit/nstextviewdelegate/1449325-textview?language=objc).) Right now, the only check that this delegate method does is enforcing the `maxLength` parameter if it exists, and changes in attributes shouldn't affect the length of the string.
[macOS] [Fixed] - `-[RCTUITextField textView:shouldChangeTextInRange:replacementString:]` no …

Add a nil check to prevent a crash

---

ReactCommon/hermes/inspector/tools/msggen/package.json
ReactCommon/hermes/inspector/tools/msggen/yarn.lock
package.json
repo-config/package.json
yarn.lock

This resolves security issues in `async` and `ansi-regex` as explained [here](https://snyk.io/test/npm/async/3.2.1) and [here](https://snyk.io/test/npm/ansi-regex/4.1.1) respectively.

Several more compliance fixes

---

ReactCommon/hermes/inspector/tools/msggen/package.json
ReactCommon/hermes/inspector/tools/msggen/yarn.lock
package.json
repo-config/package.json
yarn.lock

Cherry-pick of 2e53ac8, b6496c0 db5db0c, f22664d, and 2f81083. See #1122.
Conflicts in yarn.lock files were resolved by running `yarn upgrade` as needed.

0.66: Several more compliance fixes

---

React/DevSupport/RCTInspectorDevServerHelper.mm

We saw a downstream ASan crash in `+[RCTInspectorDevServerHelper connectWithBundleURL:]`.
It's not clear exactly what's causing the crash, but the stack trace includes a reference to `-[__NSDictionaryM setObject:forKeyedSubscript:]` along with the message "Hint: address points to the zero page." Since `NSDictionary` is known to misbehave when we try passing in `nil` as a key or value, one easy fix we can do is to add some `nil` checks and bail out in case we're about to do something sketchy.
[Internal] [Fix] - bug fixes

Add nil checks to `+[RCTInspectorDevServerHelper connectWithBundleURL:]`

---

.circleci/config.yml
scripts/validate-ios-test-env.sh

bump Node references from 12/14 to 14/16 (#32980)

---

.circleci/config.yml
React/DevSupport/RCTInspectorDevServerHelper.mm
scripts/validate-ios-test-env.sh

Cherry-pick of the commits in #1124 and #1125.

[0.66-stable] Add nil checks to `+[RCTInspectorDevServerHelper connectWithBundleURL:]`, and bump Node

---

.ado/templates/apple-job-react-native.yml

Apple tests are currently flakey, which leads to PR checks failing often. Ideally, these tests are fixed up to be more robust, but in the interim, adding a retry on failure will help with engineering velocity.
[Internal] [Added] - Adding retry of Apple tests in PR pipeline.
Will rely on running the pipeline from this PR.

Adding auto retry of Apple tests

---

bots/package.json
bots/yarn.lock

Cherry pick of fbb9d33ceeb28ca106a0410704307a650eb53362, followed by `yarn upgrade`.
This resolves the security issue with old versions of `danger` as described here: https://github.com/microsoft/react-native-macos/security/dependabot/75.

Update Danger JS to v11

---

React/Views/ScrollView/RCTScrollContentView.m
React/Views/ScrollView/RCTScrollView.m
packages/rn-tester/Podfile.lock

React Native's ScrollView component defines two props for iOS and Android: `showsVerticalScrollIndicator` and `showsHorizontalScrollIndicator`. These are designed to be user overridable (I.E: the user could make a vertical scrolling list that never shows a vertical indicator). macOS has equivalent props: `hasVerticalScroller` and `hasVerticalScroller`, but we would set them ourselves in code and not respect the user choice. We can simplify our code _and_ respect the user choice by removing bits where we manually set whether our scroll view has vertical and horizontal scrollers or not. I also set `autoHidesScrollbars = true` to better match the existing behavior and because I think it's a better default to have. 
[macOS] [Fixed] - ScrollView respects props showsVerticalScrollIndicator, …

ScrollView - Respect the `shows<Horizontal | Vertical>ScrollIndicator` props on macOS

---

React/Views/ScrollView/RCTScrollContentView.m
React/Views/ScrollView/RCTScrollView.m

Backport of #1135 to 0.66-stable

[0.66] ScrollView - Respect the shows<Horizontal | Vertical>ScrollIndicator props on macOS

---

Libraries/WebSocket/RCTSRWebSocket.m

We've gotten reports of an uncommon crash in `RCTSRWebSocket`. While we're not sure what exactly is causing it, we can at least add some logging to help better see when certain problems might come up.
[Internal]
RNTester still compiles on macOS and iOS.

Add debug logging to -[RCTSRWebSocket _connect]

---

.ado/android-pr.yml
.ado/publish.yml
.ado/templates/download-android-dependencies.yml

We have a publish pipeline on stable branches that I was unaware of, which had yaml duplicated. As a result, the publish pipeline is now failing after making changes to the download android dependencies task
[Android] [Internal] - Factor out download android dependencies into a template
PR pipeline succeeding and publish pipeline succeed will indicate success.

Factor out dependency download task so it can be shared across pipelines

---

.ado/android-pr.yml
.ado/publish.yml
.ado/templates/download-android-dependencies.yml

The publish pipeline needs to authenticate to a different feed in order to consume maven-dependency-utils
[Android] [Internal] - Parameterize feed for pip auth
PR build succeeds.

Parameterizing the feed for pip auth

---

.ado/templates/download-android-dependencies.yml

Hardcoding the version of maven-dependency-utils to avoid accidental regressions
Hardcoding the version of maven-dependency-utils to avoid accidental regressions
Hardcoding the version of maven-dependency-utils to avoid accidental regressions

Hardcoding the version of maven-dependency-utils to avoid accidental regressions

---

.ado/templates/download-android-dependencies.yml

Cherry-picking the change from main. Hardcoding the version of maven-dependency-utils to avoid accidental regression
Hardcoding the version of maven-dependency-utils to avoid accidental regression
Hardcoding the version of maven-dependency-utils to avoid accidental regression
Verified builds

[Cherry-pick] Hardcoding the version of maven-dependency-utils to avoid accidental regression

---

.ado/downloadAndroidDependencies.py
.ado/templates/download-android-dependencies.yml

Square has incorrectly published their module metadata for okio 2.9.0 which leads to pulling the wrong artifact. To get around this we need it ignore grade's metadata redirection annotations in the pom file. Furthermore, for office consumption, we need to avoid resolving all dependencies to a single version, in order to build libraries. This change updates maven-dependency-utils to a version that supports both features and updates the consumption here to make use of them.
[Android] [Internal] - Update maven-dependency-utils
PR succeeds

Update maven-dependency-utils to 1.17.0 and use new flags

---

package.json
yarn.lock

This addresses the following vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-25865
[Internal] [Security]

Resolve workspace-tools to at least 0.18.4

---

React/CoreModules/RCTAppearance.mm

Steps to repro the bug in RNTester:
1. Boot RNTester and navigate to the Appearance Test page under APIs
2. Switch appearance (opposite to the current appearance)
3. Reload window
In the screenshot above, you can see that the UI elements are shown in light mode in spite of the window background is apparently in dark mode. Before this change, we initialize currentColorScheme by calling currentDrawingAppearnace, which describes the current drawing from a view. My speculation is that since JS caches the layout of the UI elements, when the window gets reloaded nothing is being drawn hence the confusion. The fix is to use the shared instance to make appearance API calls.
[macOS] [Fixed] - Use the application instance to make appearance API calls
Tested the repro steps in RNTester and ensured …

Fix for appearance not working properly on a corner case

---

.circleci/config.yml

We're seeing some dependabot PR failures (#1167 and #1169) due to a missing job definition, so let's reintroduce that definition to make everyone happy.

Readd test_docker to .circleci/config.yml

---

template/Gemfile.lock

This updates the `bundler` version in the template to its latest version as of now. The version previously recorded here has [a security vulnerability](https://security.snyk.io/vuln/SNYK-RUBY-BUNDLER-2313646), so this removes that.

Update template bundler version to 2.3.14

---

.circleci/Dockerfiles/Dockerfile.android
v8-docker-build/Dockerfile

Remove the FROM line of the android docker file since we don't have that image in an approved registry.
This makes the file invalid, but the test is already disabled from the .circleCI tests. So added comments to the file
on how to make it compliant when #774 is addressed.
Updated the V8 test to use mcr.microsoft.com registry.
[Internal] [Change] - Message
N/A

Address compliance concerns for docker files using non-approved registries

---

.ado/downloadAndroidDependencies.py
.ado/templates/download-android-dependencies.yml

This is just some refactoring, where the original code has been moved to maven-dependency-utils.
[Android] [Internal] - Use maven-dependency-utils native extraction module
Will use the built nupkg to try a local build and ensure it succeeds.

Switch downloadAndroidDependencies.py to use native extraction module

---

.ado/downloadAndroidDependencies.py
.ado/templates/download-android-dependencies.yml

This is just some refactoring, where the original code has been moved to maven-dependency-utils.
[Android] [Internal] - Use maven-dependency-utils native extraction module
Will use the built nupkg to try a local build and ensure it succeeds.

cherry-pick - switch to extract_native_modules

---

.ado/publish.yml
scripts/set-rn-version.js

This makes two improvements to our CI scripts:
* Always print the branch we're in if we're trying to update it. We've seen [a CI failure](https://app.circleci.com/pipelines/github/microsoft/react-native-macos/4317/workflows/7d64d001-1b13-4135-b62d-d03fd0324c7c/jobs/24972) where we weren't doing this, so the terminal output was somewhat useless. This should help a little bit at least.
* Run `bundle install` as part of our publish CI script. We need this now that we're using gem to handle Ruby dependencies for us.

Two improvements to our CI scripts

---

.ado/publish.yml
Brewfile

Our publishing pipeline for 0.68 ran into [a failure](https://office.visualstudio.com/ISS/_build/results?buildId=14025019&view=logs&j=6bb1d585-fe16-5108-3aa2-8096d3b89a29&t=724b1392-3080-5f36-5e5f-8aef20dce6a9&l=14) due to conflicting Ruby versions. Our solution is to use `rbenv` in our pipelines to ensure that we use the right version.

Use `rbenv` when running `bundle install`

---

.ado/publish.yml

This resolves the following issue seen in one of our build loops as a result of #1216:
rbenv: version `2.7.5' is not installed (set by /Users/runner/work/1/s/.ruby-version)
This should fix that.

Ensure we have Ruby 2.7.5 installed for our ADO loops

---

.ado/publish.yml
.ado/rigorousBundleInstall.js

With the latest publishing pipeline changes, we're still seeing problems installing the right version of Ruby. Therefore, our solution is to introduce a script that runs `bundle install` in a way that handles all of the errors we've seen so far.
The logic is as follows:
* If an initial run of `bundle install` fails due to a Ruby mismatch version, attempt to install the correct version using `rbenv`.
* If `rbenv install` succeeds, great. If it doesn't, remove the dependency on a specific version of Ruby so `rbenv` will default to the system version of Ruby.
* Try running `bundle install` under `rbenv`, which will either point to the correctly installed version or the system version, depending what happened in the last bullet point.

Incorporate a more rigorous version of `bundle install` in our publishing pipeline

---

.ado/publish.yml

Apparently #1218 had a spacing issue that slipped by. This fixes that.

Fix spacing in publish.yml

---

.ado/templates/react-native-macos-init.yml

Cherry-pick of c45fb1b834522a0ca8283923463e0ea960d0256d as seen in #1212.
The release of RN 0.69 seems to have broken our pipeline that validates `react-native-macos-init`, so for now we'll explicitly specify the RN version number we try to grab for this.

Ensure we use 0.68 for testing new apps, not 0.69 or later

---

package.json
yarn.lock

This resolves a security vulnerability:
https://snyk.io/test/npm/shell-quote/1.6.1
A nicer fix would be to upgrade our React Native CLI tools to ^8.0.0, but this is more compatible with RN 0.69 as per [the README](https://github.com/react-native-community/cli#compatibility), so this fix should suffice in the meantime.

Upgrade shell-quote to ^1.7.3

---

android-patches/patches/V8/packages/rn-tester/android/app/build.gradle
android-patches/patches/V8/packages/rn-tester/android/app/src/main/java/com/facebook/react/uiapp/RNTesterApplication.java

The current set of android patches results in the hermes variant of rn-tester working incorrectly, due to the default js engine being set to v8. The patches here will ensure the appropriate executor is used, and also creates a variant for V8 so that it is easy to test across all 3 executors.
[Android] [Internal] - Add patches for V8 rn-tester variant
Tested each built apk and verified the appropriate executor was being used

Add patches to create rn-tester variants for V8, JSC and Hermes

---

scripts/update_podfile_lock.sh

We've seen another failure at the `pod install` phase of our pre-publish pipeline. While we're not 100% sure why things are particularly bad here, we can mitigate it by following the instructions on [RNTester's original README](https://github.com/facebook/react-native/tree/main/packages/rn-tester#running-on-ios) a bit more closely.

Run `bundle install` before running `pod install`

---

.gitignore

Our latest publish pipeline fails to tag new versions on GitHub because we're trying to commit a large file that we don't need.
The solution is to adjust our .gitignore file to account for new changes to the repo and the publish pipeline:
* Add any files that are part of the SBoM manifest to .gitignore. We don't have a reason to keep these under version control.
* Add any residual files created as a result of #1233 to .gitignore.

Add files to .gitignore to get NPM publish pipeline fully working

---

Libraries/Core/ReactNativeVersion.js
React/Base/RCTVersion.m
ReactAndroid/gradle.properties
ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java
ReactCommon/cxxreact/ReactNativeVersion.h
package.json
scripts/set-rn-template-version.js
template/package.json

Due to some pipeline issues, we were able to publish 0.68.3 to NPM, but we weren't able to commit the version bump to GitHub. This manual version bump should do the trick, so the next time we try to bump the version number, we'll proceed to 0.68.4.
We also adjust our script to set the template version number, since 7100756bb8b0b1ac85ccaa32c0ce5c1cc70d524f changed our template package.json file to use `react-native-macos` instead of `react-native`. This shouldn't have too much of an impact since we basically use the template from upstream as our baseline, but we might as well adjust this for the sake of completeness.

Manually bump to 0.68.3

---

scripts/set-rn-version.js

Our invocation of `update_pods` depends on `bash` to determine where RNTester lives (due to the presence of `BASH_SOURCE`), so let's make sure we're using `bash` whenever we try to run `update_pods`.

Do all `update_pods` actions in `bash`

---

android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8ExecutorFactory.cpp

- [👍 ] I am making a change required for Microsoft usage of react-native
The bundle evaluation of metro-built bundler fails as property nativeperformancenow is not defined in global scope by V8.
Hermes's onLoad.cpp exports this property, but in V8 this was missing. 
In this change we add the property to the global object of V8

Add NativePerformanceNow to V8 Global objects

---

.ado/android-pr.yml

There was a regression in 0.68-stable that causes building rn-tester multiple times to fail on the second attempt. I was able to verify this by trying it on facebook/react-native. I ended up filing this issue https://github.com/facebook/react-native/issues/34168 to track a proper upstream fix. It seems that the issue has to do with trying to build debug and release variants of rn-tester in the same gradle invocation. As a temporary work around, we build debug and release in separate gradle invocations.
[Android] [Internal] - Split rn-tester into separate debug and release builds
Ran the build steps multiple times and ensured the build succeeded.

Split rn-tester build into debug and release

---

.ado/android-pr.yml
.ado/publish.yml
.ado/templates/android-build-office.yml

To simplify our validation process, we are publishing rn-tester apks and bundles to build artifacts, so that we can test without having to perform a build.
[Android] [Internal] - Publish rn-tester apks and bundle to build artifacts
Verify the PR pipeline succeeds

Publish rn-tester apks and bundle to build artifacts

---

.ado/publish.yml

This adds the installation of Bundler to one of our publishing pipelines, since `set-rn-version.js` depends on it.
An equivalent change was tested in a separate branch, and it seems to work, so here's hoping it translates well! 🙏

Install bundler as part of Office publish pipeline

---

.ado/publish.yml

The publish pipeline runs on ADO, and needs to use the Office internal feed.
[Android] [Internal] - Change feed for pip authenticate
Will run the publish pipeline after merging to verify the pipeline succeeds.

Use the Office feed for the publish pipeline

---

.ado/android-pr.yml
.ado/publish.yml
.ado/templates/android-build-office.yml
.ado/templates/download-android-dependencies.yml

Cherry-picking several changes performed on the 0.68-stable branch related to publishing rn-tester as an artifact.
[Android] [Internal] - Cherry-pick rn-tester publishing related changes to main
PR builds successfully.

Cherry pick 0.68 fixes for rn-tester publishing

---

package.json
packages/react-native-macos-init/package.json
yarn.lock

`beachball@2.25.0` resolves some security issues as seen [here](https://github.com/microsoft/beachball/pull/683). This brings these into react-native-macos.
We also remove a forced resolution of `workspace-tools` that we don't need anymore now that our tools are up to date.

Update beachball to 2.25.0

---

package.json
packages/react-native-macos-init/package.json
yarn.lock

We had some component governance improvements in the main branch, and now we're bringing them over to 0.68-stable.

Bring over some component governance improvements to 0.68-stable

---

ReactCommon/hermes/inspector/tools/msggen/package.json
ReactCommon/hermes/inspector/tools/msggen/yarn.lock
bots/package.json
bots/yarn.lock

We're still holding on to an old version of `string_decoder` in some places. We get rid of them by doing the following:
* For the one in `bots/`, we have this dependency because of `firebase`, and even the latest version of `firebase` depends on the old `string_decoder`, so the solution here is to resolve `readable-stream` (the module that actually pulls in `string_decoder`) to at least 4.0.0 (similar to what we had to do in #1252).
* For the one in `ReactCommon/hermes/inspector/tools/msggen/`, we just need to upgrade `webpack` to the latest version and we're all set.

Remove old versions of `string_decoder`

---

Libraries/Components/ScrollView/ScrollView.js
Libraries/Lists/VirtualizedList.js
React/Views/ScrollView/RCTScrollView.m
React/Views/UIView+React.m
packages/rn-tester/js/components/ListExampleShared.js
packages/rn-tester/js/examples/FlatList/FlatList-basic.js

Cherry pick #1258 to 0.68-stable

[0.68] Keyboard navigation in Flatlist (#1258)

---

Libraries/Components/ScrollView/ScrollView.js
Libraries/Lists/VirtualizedList.js
React/Views/ScrollView/RCTScrollView.m
React/Views/UIView+React.m
packages/rn-tester/js/components/ListExampleShared.js
packages/rn-tester/js/examples/FlatList/FlatListExample.js

Cherry pick #1258 to 0.66-stable

[0.66] Keyboard navigation in Flatlist (#1258)

---

Libraries/Text/TextInput/Singleline/RCTUITextField.m

This adds the appropriate override for AppKit (`setAccessibilityElement:`) so that the `NSTextField` will not get set to be accessible, since its cell instead is already accessible and performs the correct VoiceOver behaviors.
VoiceOver now reads as you type in a single-line `TextInput`
[macOS] [Fixed] - Fix VoiceOver for single-line TextInput
Didn't announce the search field 
`Search...`
instead
`You are currently on a text field`
was shown
BEFORE
https://user-images.githubusercontent.com/484044/180339597-035d5f21-0567-4e5f-91f2-d9f60722ffdf.mov
AFTER
https://user-images.githubusercontent.com/484044/180339668-e566278c-b59c-4a90-b44d-3a1ab7a9613a.mov
Didn't announce the search term
BEFORE
https://user-images.githubusercontent.com/484044/180339728-d9cf208f-0826-4998-a67e-3c0ea3c45363.mov …

Fix VoiceOver for single-line TextInput

---

React/Modules/RCTUIManager.m

These calls are only needed for a temporary Fabric workaround and would result in a deadlock since we also call `RCTUnsafeExecuteOnUIManagerQueueSync` from the main thread during window resize.
This is needed for now in Fabric only to call the temporary `componentViewName_DO_NOT_USE_THIS_IS_BROKEN` workaround on views, which we don't have on desktop since we're a way off from using Fabric (and hopefully this workaround will be gone then).
It was originally added here https://github.com/facebook/react-native/commit/ffc7ec992c66417039b0fa14f1afd54a9cd2f882
At Meta we have disabled these lines since May 2021 to fix crashes in production.
[macOS] [Fixed] - Avoid RCTUnsafeExecuteOnMainQueueSync from RCTUIManager
Ran rn-tester.
Crash no longer observed

Avoid RCTUnsafeExecuteOnMainQueueSync from RCTUIManager

---

Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m
Libraries/Text/TextInput/RCTBaseTextInputView.m

Setting `allowsUndo = YES` and having the `NSTextView` delegate return a stable `NSUndoManager` mostly makes undo/redo work, but we also need to register an undo action whenever the input contents was changed to something unexpected by JS.
This also breaks undo coalescing in a couple key places to make the input behave naturally like other apps.
[macOS] [Added] - Add undo/redo support for TextInput
Note: Bottom left corner casts key strokes from my keyboard
https://user-images.githubusercontent.com/484044/180468578-a70a072c-1926-4350-9c49-1c2d2c22aa60.mov
https://user-images.githubusercontent.com/484044/180468667-23f92c9d-e4de-4218-84f4-bbb7e5eb51dd.mov

Add undo/redo support for TextInput

---

Libraries/Components/ScrollView/ScrollView.js

Already works on macOS (as it does on iOS).
Doesn't work on Android or Windows.
[macOS] [Changed] - Allow scrollResponderZoomTo() on macOS
I have used the following sample in rn-tester in ScrollViewExample.js
```
const HorizontalScrollView = (props: {direction: 'ltr' | 'rtl'}) => {
const {direction} = props;
const scrollRef = React.useRef<?React.ElementRef<typeof ScrollView>>();
const [scale, setScale] = useState(20);
const [coord, setCoord] = useState(0);
const title = direction === 'ltr' ? 'LTR Layout' : 'RTL Layout';
return (
<View style={{direction}}>
<Text style={styles.text}>{title}</Text>
<ScrollView
ref={scrollRef}
automaticallyAdjustContentInsets={false}
horizontal={true}
style={[styles.scrollView, styles.horizontalScrollView]}
testID={'scroll_horizontal'}
> …
```

Allow scrollResponderZoomTo() on macOS

---

Libraries/Lists/FlatList.js
Libraries/Lists/VirtualizedList.js
packages/rn-tester/js/examples/FlatList/FlatList-basic.js

[0.68] Flatlist keyboard navigation: Mouse can move selection

---

React/Base/macOS/RCTPlatformDisplayLink.m

This fixes leaking `_RCTTimer` instances. The runloop does not push/pop autorelease pools for you with `CFRunLoopPerformBlock`. A similar autorelease pool is setup for the same reason in `RCTMessageThread`.
https://github.com/facebook/react-native/commit/948cbfdacc42f8d2640e69f61df55f6adb823fcf
[macOS] [Fixed] - Fix missing autorelease pool in RCTPlatformDisplayLink
Confirmed expected number of `_RCTTimer` instances in Xcode memory graph.

Fix missing autorelease pool in RCTPlatformDisplayLink

---

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m
React/Base/RCTUIKit.h
React/Base/macOS/RCTUIKit.m

Cherry-pick 96396375600fae8ec92cd01efba9e863beafeefa to 0.68-stable.

[0.68-stable] Cherry-pick focus fix for multiline text input

---

Libraries/Text/TextInput/Singleline/RCTUITextField.m

Cherry-pick f6b4c1e712c0f3a993baff029e86bb1c64985af3 to 0.66-stable.

[0.66-stable] Fix VoiceOver for single-line TextInput

---

Libraries/Text/TextInput/Singleline/RCTUITextField.m

Cherry-pick f6b4c1e712c0f3a993baff029e86bb1c64985af3 to 0.68-stable.

[0.68-stable] Fix VoiceOver for single-line TextInput

---

Folly/build/fbcode_builder/utils.py

Cherry pick 721b8126231cb094b8acbdf8c5c16907e451c3ca into 0.66-stable

[0.66] Add inline comments to suppress a security analysis (bandit) rule for Folly

---

React/Base/RCTTouchHandler.m

This fixes an issue on macOS where the `locationX`/`Y` properties would incorrectly match `pageX`/`Y` unlike iOS (see lines 218/219 in the same file) and other platforms.
[macOS] [Fixed] - Fix event.locationX/Y to be in view's coordinate space
Confirmed `locationX`/`Y` is now correctly reported in the view's coordinate space.
Before
After

Fix event.locationX/Y to be in view's coordinate space

---

React/CoreModules/RCTDevLoadingView.mm

This fixes a copy/paste mistake where the loading panel is being shown after it fades out instead of being closed. This manifested as app exposé showing a transparent window and these panels showing up in the UI debugger (thus leaking).
[macOS] [Fixed] - Fix RCTDevLoadingView never actually closing
Confirmed the loading panels actually now go away and app exposé behaves reasonably now.

Fix RCTDevLoadingView never actually closing

---

Libraries/Text/TextInput/Multiline/RCTUITextView.m

This bug was due to some code in multiline TextInput which disabled all text checking types by default.
We now match the system default instead.
[macOS] [Fixed] - Fix text replacement not working in multiline TextInput
Before
https://user-images.githubusercontent.com/484044/180833106-5f84f672-46e8-4970-bdbf-366c73b31e61.mov
After
https://user-images.githubusercontent.com/484044/180833087-4224b1d1-fa20-4894-98fc-4ebc084f4178.mov

Fix text replacement not working in multiline TextInput

---

React/Base/RCTTouchHandler.m

This will ignore "touches" (clicks) on `NSScroller` such that JS does not process them resulting in a press event.
[macOS] [Changed] - Don't send events when clicking on scrollbars
Confirmed clicking scrollbar in rn-tester does not result in a click on the items underneath.
Both scrollView scroller and content clicks are processed
https://user-images.githubusercontent.com/484044/180582981-78612f6f-fc07-4dd0-b858-bb339162463a.mov
Clicking onto the scrollView scroller > click is ignored
Clicking into the the scrollView > no change of behavior
https://user-images.githubusercontent.com/484044/180582997-e0e02fad-7323-44d0-a8b5-e7f3c739364c.mov

Don't send events when clicking on scrollbars

---

Libraries/Components/TextInput/RCTTextInputViewConfig.js
Libraries/Components/TextInput/TextInput.js
Libraries/Text/TextInput/RCTBaseTextInputViewManager.m
Libraries/Text/TextInput/Singleline/RCTUITextField.h
Libraries/Text/TextInput/Singleline/RCTUITextField.m

Similar to https://github.com/microsoft/react-native-macos/pull/1292 this adds a macOS only property to toggle grammarCheck on RCTUITextField
[macOS] [Added] - Pass grammarCheck to text input views for Mac
Using this sample
```
{
title: 'Auto-focus',
render: function (): React.Node {
return (
<>
<TextInput
spellCheck={true}
style={{backgroundColor: 'white', margin: 10}}
accessibilityLabel="spellCheck"
/>        
<TextInput
grammarCheck={true}
style={{backgroundColor: 'white', margin: 10}}
accessibilityLabel="grammarCheck"
/>
<TextInput
autoCorrect={true}
style={{backgroundColor: 'white', margin: 10}}
accessibilityLabel="autoFocus"
/>
<View style={{margin: 50, width:200, height:100, backgroundColor: 'red'}} />
<TextInput
spellCheck={false}
style={{backgroundColor: 'white', margin: 10}} …
```

Pass grammarCheck to text input views for Mac

---

Libraries/Text/TextInput/Singleline/RCTSinglelineTextInputView.m

This diff fixes 2 bugs with TextInput:
1. The default macOS behavior for single line text inputs is that they scroll horizontally when they overflow. react-native-macOS was making it paginate instead
2. Single line text input allowed pressing Ctrl+Enter to insert a new line
[macOS] [Fixe] - Single line TextInput fixes (prevent newLines, support horizontal overflow)
CTRL + W > adds new line
Text paginates
https://user-images.githubusercontent.com/484044/180829204-a9cc5ceb-c0bf-41ab-9b3b-f938a88bec34.mov
No new lines
Text overflows
https://user-images.githubusercontent.com/484044/180829238-b55318fc-957e-425f-8dc8-35b540b2b9c8.mov

Single line TextInput fixes (prevent newLines, support horizontal overflow)

---

android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec

Facebook changed the ndk build step to use a gradle plugin, which lead to the libraries being produced to different paths. As a result, we fail to find the libraries when performing a nuget pack.
[Android] [Internal] - Update binary paths
Will verify the nuget pack task doesn't fail to find any of the expected files.

update paths to binaries

---

.ado/android-pr.yml
.ado/publish.yml
.ado/templates/android-nuget-pack.yml

Trying to perform a nuget pack can result in a failure if a specified path doesn't exist. This should result in the nuget pack task failing. However, due to the use of a semi-colon delimited list for the properties, the command is incorrectly broken up, leading to the exit code not reflecting that of the nuget pack command.
[Android] [Internal] - Escape semi-colon in bash command
Will verify that the pipeline fails, where it was succeeding before. I will then submit this after submitting a fix to the failing pack task.

Escape semi-colon in bash command

---

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m

This fixes a regression introduced in https://github.com/microsoft/react-native-macos/pull/1276
We should respect the boolean flag sent from JS to enable/disable the focusRing
[macOS] [Fixed] - Honor enableFocusRing flag for multiline textFields
Used this example
```
{
title: 'Multiline true',
render: function(): React.Node {
return (
<TextInput
multiline={true}
accessibilityLabel="I am the accessibility label for text input"
/>
);
},
},
{
title: 'Multiline true, enableFocusRing true',
render: function(): React.Node {
return (
<TextInput
multiline={true}
enableFocusRing={true}
accessibilityLabel="I am the accessibility label for text input"
/>
);
},
},    
{
title: 'Multiline true, enableFocusRing false',
render: function(): React.Node {
return (
<TextInput
multiline={true} …
```

Honor enableFocusRing flag for multiline textFields

---

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m

Cherry-pick 825d334e8b9341a1a6c6c35916976ed8fe131fd1 to 0.68-stable.

[0.68-stable] Fix enableFocusRing also enabled for multiline textFields (#1301)

---

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m

Cherry-pick 825d334e8b9341a1a6c6c35916976ed8fe131fd1 to 0.66-stable.

[0.66-stable] Fix enableFocusRing also enabled for multiline textFields

---

Libraries/Components/ScrollView/ScrollView.js
Libraries/Lists/FlatList.js
Libraries/Lists/VirtualizedList.js
React/Views/ScrollView/RCTScrollView.m
React/Views/UIView+React.m
packages/rn-tester/js/components/ListExampleShared.js
packages/rn-tester/js/examples/FlatList/FlatListExample.js

Reverts microsoft/react-native-macos#1269

Revert Flatlist changes

---

.ado/publish.yml

Increase Office publish timeout to 120 minutes

---

Libraries/Text/RCTTextAttributes.m
packages/rn-tester/js/examples/Text/TextExample.ios.js

This seems to due RN Mac commits that fix text colors for dark mode:
- https://github.com/microsoft/react-native-macos/commit/8ed55a866a7a71b696da6de464f7a32d99065153
- https://github.com/microsoft/react-native-macos/commit/731a535dca3b16d09ce0288c5cd804ecaba29c98
It works on iOS, web .... so it should behave the same on macOS as well
[macOS] [Fixed] - Fix nested Text components not inheriting foreground color from parent
Before
After
iOS - as reference

Fix nested Text components not inheriting foreground color from parent

---

packages/rn-tester/Podfile
packages/rn-tester/RNTester-macOS/AppDelegate.mm

On RN Core, Hermes for iOS can be enabled by setting a flag in the Podfile & running `pod install`
https://reactnative.dev/docs/hermes#ios
> Since React Native 0.64, Hermes also runs on iOS. To enable Hermes for iOS, edit your ios/Podfile file and make the change illustrated below:
```
use_react_native!(
:path => config[:reactNativePath],
:hermes_enabled => true
)
```
In Core RNTester for iOS, ~~Hermes is enabled by default~~ 
Not until 0.70 - https://github.com/facebook/react-native/blob/0.70-stable/scripts/react_native_pods.rb#L41
```
def use_react_native! (
path: "../node_modules/react-native",
fabric_enabled: false,
new_arch_enabled: ENV['RCT_NEW_ARCH_ENABLED'] == '1',
production: ENV['PRODUCTION'] == '1',
hermes_enabled: true,
flipper_configuration: FlipperConfiguration.disabled, …
```

[RN][macos] Enable Hermes for RNTester

---

.ado/templates/android-nuget-pack.yml
.ado/templates/prep-android-nuget.yml
android-patches/patches/Build/ReactAndroid/build.gradle
android-patches/patches/Build/build.gradle.kts

After switching from building native libraries by manually invoking ndk-build, to using the Android gradle plugin, the method of querying which ndk is being no longer works. To address this, we will hardcode, via a patch, which ndk is being used. This will also ensure that we are using the same ndk that Office is being built with.
[Android] [Internal] - Hardcode ndk version
Ensure that the ndk is properly queried.

Hardcode ndk

---

React/Base/RCTRootView.m
React/Modules/RCTUIManager.m

This change reverts https://github.com/microsoft/react-native-macos/pull/439 - but still tries to address the original issues:
- https://github.com/microsoft/react-native-macos/issues/422
- https://github.com/microsoft/react-native-macos/issues/322
and the follow up https://github.com/microsoft/react-native-macos/issues/459
This also addresses an issue when programmatically resizing windows where the ```RCTRootContentView``` may end up at the wrong size because an in-flight layout gets resolved after the resize on the main thread.
We now keep sync dispatch on the shadow queue for live resizing windows (to prevent tearing) but also dispatch async (as done on iOS) so the latest new size is sure to win.
The block has a check to bail if the size doesn't change, so this isn't a perf drain …

Revert "Alleviate excessive layout jittering when resizing window (#439)"

---

React/CxxBridge/RCTJSIExecutorRuntimeInstaller.mm
ReactAndroid/src/main/java/com/facebook/react/JSInterpreter.java
ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java
ReactAndroid/src/main/java/com/facebook/react/ReactRootView.java
ReactAndroid/src/main/jni/react/jni/NativeTime.cpp
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/JSInterpreter.java
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java
android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/v8executor/V8Executor.java
packages/react-native-codegen/package.json

Brining newer commits from upstream and making the fixes to patches
Brining newer commits from upstream and making the fixes to patches
Made sure the code is building

Refreshing 0.68-stable with upstream

---

Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/Singleline/RCTUITextField.m

We should not be setting the insertionPointColor by default.
Let the OS do its thing.
Later we can consider exposing a prop for this but the default should be to not set it.
[macOS] [Changed] - Remove TextInput setting insertionPointColor
Setting a purple ```selectionColor``` on the texInput fields
```
selectionColor='purple'
```

Remove TextInput setting insertionPointColor

---

.ado/publish.yml
.ado/templates/apple-job-javascript.yml
.ado/templates/apple-job-react-native.yml

See https://classic.yarnpkg.com/lang/en/docs/cli/install/
We should pass `--frozen-lockfile` to any `yarn install` invocation to make sure we respect the locally checked in lock file.
[Internal] [Fixed] - Ensure we pass `--frozen-lockfile` for reproducible CI
CI should pass

Ensure we pass `--frozen-lockfile` for reproducible CI

---

Libraries/Image/RCTImageCache.m

The cache's `totalCostLimit` and the `_cacheStaleTimes` ivar were not getting set for Mac, presumably due to a merge mistake. I'm not sure what (if any) positive impact this will realistically have on memory consumption.
[macOS] [Fixed] - Fix RCTImageCache on macOS
Tested rn-tester scrolling through several threads with lots of images. Everything works well.

Fix RCTImageCache on macOS

---

Libraries/Text/TextInput/RCTBaseTextInputShadowView.m

Shadow views are used to calculate the container's size using NSTextContainer + NSLayoutManager + NSTextStorage according to https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/TextLayout/Tasks/StringHeight.html.
However, when typing certain text, the TextView itself overflows, but its container doesn't.
This means our shadow view isn't tracking the TextView correctly.
Root cause was that we added a 1px lineFragmentPadding in https://github.com/microsoft/react-native-macos/pull/640, but we didn't add the save padding in our shadow view.
[macOS] [Fixed] - Add fragmentLinePadding for multiline shadow view to track TextView correctly
- Shrink app to minimum width
- Type some text which overflows
https://user-images.githubusercontent.com/484044/183131964-82a32954-3420-4d …

Add fragmentLinePadding for multiline shadow view to track TextView correctly

---

Libraries/Text/TextInput/Multiline/RCTUITextView.m
React/Views/UIView+React.m

This bug happens because `RCTUITextView` (which multiline TextInput uses) was overriding NSTextView's `becomeFirstResponder` method and didn't call `[super becomeFirstResponder]`.
This seems to mess with AppKit's logic of drawing the cursor initially.
This is alluded to in the [docs](https://developer.apple.com/documentation/appkit/nstextview/1807130-becomefirstresponder?language=objc#) for `[NSTextView becomeFirstResponder]`:
> If the previous first responder was not a text view on the same layout manager as the receiving text view, this method draws the selection and updates the insertion point if necessary.
Simply switching to call `[super becomeFirstResponder]` led to a cryptic exception within AppKit. This was likely because in the `reactFocus` (and `reactFocusIfNeeded`) we were …

Fix cursor not showing when tabbing into multiline TextInput

---

Libraries/Components/TextInput/TextInput.js
Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/RCTBackedTextInputDelegate.h
Libraries/Text/TextInput/RCTBaseTextInputView.h
Libraries/Text/TextInput/RCTBaseTextInputView.m
Libraries/Text/TextInput/RCTBaseTextInputViewManager.m
packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js

When users change spellCheck, grammarCheck or autoCorrect in the context menu, one of 3 callbacks for MULTILINE inputs are called:
- toggleGrammarChecking
- toggleContinuousSpellChecking
- toggleAutomaticSpellingCorrection
If JS is going to be the source of truth for text proofing settings, we should have a way to notify JS when these settings are changed from the native side.
[macOS] [Added] - Pass callbacks for when grammarCheck, spellCheck and autoCorrect are changed on macOS
Added Example
https://user-images.githubusercontent.com/484044/182961942-8b747b59-1c43-4e73-8349-742f77f7aac7.mov

Pass callbacks for when grammarCheck, spellCheck and autoCorrect are changed on macOS

---

React/Base/RCTRootView.m
React/CoreModules/RCTAppearance.mm

This fixes the `Appearance.getColorScheme()` API to return the application-level appearance instead of the last appearance of any root view, which breaks down in multi-window applications.
In Messenger Desktop we always respect the OS appearance for main and setting windows, but force a darkTheme in the calling UI.
W/o this change returning from the calling UI would result in a wrong appearance setting on light theme OS setting.
[macOS] [Fixed] - Fix Appearance module to observe application appearance
I have added this snippet to RNTester-macOS/ViewController.m
```
- (void)viewWillAppear {
[super viewWillAppear];
NSAppearance* appearance = [NSAppearance appearanceNamed:NSAppearanceNameVibrantLight];
self.view.window.appearance = appearance;
}
```
The macOS appearance was set to darkTheme. …

Fix Appearance module to observe application appearance

---

React/Views/RCTView.h
React/Views/RCTView.m
React/Views/RCTViewKeyboardEvent.h
React/Views/RCTViewKeyboardEvent.m
packages/rn-tester/js/examples/KeyboardEventsExample/KeyboardEventsExample.js

This refactors / simplifies certain keyUp|Down event handling.
It will make a later change (adding textInput handling for textInput fields) easier (to review)
[macOS] [Changed] - Refactor handling of keyDown/keyUp
Note: The button example is not working ...
Before
https://user-images.githubusercontent.com/484044/183511767-faeda05f-a4fe-44b0-8e62-3cf867b31767.mov
After
https://user-images.githubusercontent.com/484044/183511929-5ccf002b-262d-4153-9ce8-85305a4237c9.mov

Refactor handling of keyDown/keyUp

---

React/Base/RCTUtils.m

This introduces a cache for local image on macOS. There are no predefined limits set here (at least yet) since presumably we are loading a finite number of resources and we have the benefit of virtual memory swap on desktop so we don't really need to sweat a few extra megabytes of in-memory cache for images we know we'll need to repeatedly load.
Local images don't use the shared RN image cache, and on macOS there's no automatic in-memory cache for local resources (other than the OS-level disk cache) so the `RCTImageFromLocalBundleAssetURL` function will synchronously access the disk on the main thread many times when switching throw an app's UI or when reloading the app.
[macOS] [Added] - Cache local images into memory
Added logging to confirmed cache works as expected in rn-tester, and …

Cache local images into memory

---

React/Views/RCTView.m

Pull request #1227 mostly fixed the consistency issue but had a problem with the shadow opacity. There isn't a shadowOpacity property on NSShadow, the shadow opacity from the layer needed to be passed into the alpha channel of the NSShadow shadowColor property.
Fixes #824 
This fix was tested with the fluentui-react-native tester app.
Before:
https://user-images.githubusercontent.com/78454019/184040031-20bab19d-8ed6-42ff-98aa-c04977b8d786.mov
After:
https://user-images.githubusercontent.com/78454019/184040044-730c62db-f871-4007-80b8-0cb7945bbea0.mov

Fix inconsistent shadows

---

Libraries/Lists/FlatList.js
Libraries/Lists/__tests__/__snapshots__/FlatList-test.js.snap
React/Base/RCTConvert.m
React/Views/RCTViewManager.m
React/Views/ScrollView/RCTScrollContentView.m
React/Views/ScrollView/RCTScrollView.m

Cherry-picking https://github.com/microsoft/react-native-macos/commit/a019ab91650fbb94a377084c64ab18f4ea813fc3 to 0.68-stable.

[0.68] Improve VoiceOver accessibility support for Flatlist (#1341)

---

Libraries/Lists/FlatList.js
Libraries/Lists/__tests__/__snapshots__/FlatList-test.js.snap
React/Base/RCTConvert.m
React/Views/RCTViewManager.m
React/Views/ScrollView/RCTScrollContentView.m
React/Views/ScrollView/RCTScrollView.m

Cherry-picking a019ab91650fbb94a377084c64ab18f4ea813fc3 to 0.66-stable.

[0.66] Improve VoiceOver accessibility support for Flatlist (#1341)

---

React/Views/RCTView.h
React/Views/RCTView.m
React/Views/RCTViewManager.m

Partial fix for issue #1363, where it looks like there are two issues: 1) when switching between dark and light mode the opacity seems to sometimes get set back to 1, and 2) when switching between dark and light mode, and a different shadow is specified for dark vs. light mode, the shadow doesn't get updated properly (ex. see the light mode shadow in dark mode or the dark mode shadow in light mode). This PR is just fixing the first problem, the second problem is a bug with dynamicColoriOS that should be fixed in RNCore.
On the FURN Tester side (where the original fix for the inconsistent shadows bug was tested) this was actually repro'ing as well but was not obvious because the test page would get refreshed every time we switched between dark/light mode. However after taking a closer …

Fix for shadow opacity getting set to 1 when appearance changes

---

Libraries/LinkingIOS/RCTLinkingManager.h
Libraries/LinkingIOS/macos/RCTLinkingManager.mm

Messenger Desktop is a multi-window application (chat, calling, settings, …) and we maintain the various windows with a windowNativeModule which allows JS interaction.
When receiving deep-links from other apps we don’t want to necessary re-open the lastWindow open as the deep-link might contain information about a particular scenario (open login page, start a call). Hence, we need to disable this behavior app wide and use our windowNativeModule to foreground the specific window related to the deep link.
- This change has 0 effect on other apps
- We could make this property an ivar, but then we need to manually register RCTLinkingManager.mm in ReactBridgeFactory-macOS.mm ….
- We could append a special url property to deep-links, but I think that would make the ‘API’ harder to use`
To use …

Provide option to not blindly foreground app's lastWindow from deepLinks

---

Libraries/Text/TextInput/RCTBackedTextInputViewProtocol.h
Libraries/Text/TextInput/RCTBaseTextInputView.m
Libraries/Text/TextInput/Singleline/RCTUITextField.m

The bug happened anywhere we set a onChangeText event handler on TextInput, and rewrite the inflight text such as shown in
https://github.com/microsoft/react-native-macos/blob/main/packages/rn-tester/js/examples/TextInput/TextInputSharedExamples.js#L137
To fix we have to ignore changes to text if we have incomplete conversions.
[macOS] [Fixed] - Fix TextInput interfering with Japanese conversion
Go to macOS Preferences > Keyboard > Input Sources > add "Japanese Romaji". Use traditional conversion per https://support.apple.com/guide/japanese-input-method/enter-japanese-text-jpim10265/mac.
In the textInput type "watashi", select first auto complete option (e.g. press SPACE), then type "tachi", and confirm you get "私たち":
私阿知
https://user-images.githubusercontent.com/484044/184256082-21773286- …

Fix TextInput interfering with Japanese conversion

---

Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m

Cherry-picking 96be39d8cddcc57c2dcfef737808c07402a3f24d to the 0.66-stable branch.

[0.66] Add scrollbar to multiline TextInput (#1366)

---

React/Modules/RCTUIManager.m

[0.68-stable] Move `RCTRootShadowView` creation to main thread

---

packages/rn-tester/js/components/ListExampleShared.js
packages/rn-tester/js/examples/FlatList/FlatList-basic.js

We show the Switch to enable Keyboard Navigation on all platforms. Let's make it only macOS, the only platform we validated. Also, let's change some styles used only by the test app to have a fallback non-platform color if we're not on macOS, should someone manage to enable the switch anyway. 
[macOS] [Fixed] - Only show the Flatlist keyboard navigation switch on macOS
Switch no longer shows up on iOS
If I force it to be true on iOS, the test app isn't too broken:
https://user-images.githubusercontent.com/6722175/186742896-b60f80ab-3bcc-4725-b2eb-b9b929473410.mov

RNTester: Only show the Flatlist keyboard navigation switch on macOS

---

packages/rn-tester/Podfile
scripts/generate-artifacts.js

Cherry pick #1320
[macOS] [Fix] Don't try and build Fabric example when USE_CODEGEN_DISCOVERY=1

[0.68] Fix build errors with codegen discovery flag enabled

---

android-patches/patches/Build/ReactAndroid/build.gradle
android-patches/patches/Build/ReactAndroid/packages.config

As part of the RN bump to 0.68, we need to update to a corresponding version of V8Jsi.
[Android] [Internal] - Update V8 JSI version for 0.68-stable
Ensure Android PR pipeline build successfully. This version of the v8 jsi has functionally the same headers as the previous version, so we do not expect any runtime changes.

update v8jsi version

---

android-patches/patches/Build/ReactAndroid/ReactAndroid.nuspec
android-patches/patches/Build/ReactAndroid/build.gradle

During migration to 0.68, we lost a patch responsible for not packaging any SOs in the react native aar, as we extract them ourselves and package the ones we need. As a result we are observing size regressions. The fix is to add the patch back in.
[Android] [Internal] - Restore patch to not package SO files in aar
PR pipelines build successfully and will try building locally.

restore exclude so

---

.ado/templates/apple-droid-node-patching.yml
android-patches/patches/ErrorToWarning/Libraries/Components/View/View.js

In order to unblock the RN68 bump for Office, we will temporarily need to patch RN to issue a warning instead of error for use of acceptsKeyboardFocus. Once we are able to consume fixed bundles that do not make use of the deprecated property, we will revert the patch.
[Android] [Internal] - Temporarily patch RN Android to issue warnings instead of errors for use of acceptsKeyboardFocus
Test built nuget package on local office build and ensure currently broken bundles render.

Add patch to issue warning instead of error for acceptsKeyboardFocus

---

android-patches/patches/ErrorToWarning/Libraries/Components/View/View.js

Adds an import statement that was missing in https://github.com/microsoft/react-native-macos/pull/1404
[Android] [Internal] - Add missing import statement for warnOnce
Ensure PR build succeeds.

fix missing import

---

Libraries/Lists/VirtualizedList.js

There was a bug if you set `initialSelectedIndex` to 0 on Flatlist. Turns out this was the issue:
```javascript
0 || -1; // returns -1
0 ?? -1; // returns 0
```
Derp
[macOS] [Fixed] - Fixed issue with setting initialSelectedIndex to 0 on Flatlist
Tested the cases `undefined, 0, 1, 2`
https://user-images.githubusercontent.com/6722175/187560479-977f4d92-98a9-4ad5-9150-80bd188db388.mov

Fix issue with setting initialSelectedindex to 0 in Flatlist

---

Libraries/Lists/VirtualizedList.js

Backport of #1399 
[macOS] [Fix] - Fixed issue with setting initialSelectedindex to 0 in Flatlist

[0.68] Fix issue with setting initialSelectedindex to 0 in Flatlist

---

Libraries/Lists/VirtualizedList.js

Backport of #1399 
[macOS] [Fix] - Fixed issue with setting initialSelectedindex to 0 in Flatlist

[0.66] Fix issue with setting initialSelectedindex to 0 in Flatlist

---

Libraries/Lists/VirtualizedList.js
packages/rn-tester/js/examples/FlatList/FlatList-basic.js

With `enableSelectionOnKeyPress` set to true, I made the Flatlist by default focusable and show the focus ring. This matches the behavior of some NSTableViews in macOS, but not all. There are cases where the overall table is focusable and does not show a focus ring (showing the selected cells with a highlight instead) like in sidebars. 
Let's allow the user to override `focusable` and `enableFocusRing` on Flatlist, so that they have more control over the UX. Turns out all this needed was moving `{...props}` _after_ `keyboardNavigationProps`, so that the users passed in props could overwrite the defaults. 
[macOS] [Fixed] - Allow clients to override keyboard focus props on FlatList
Added two switches to the test page to test the combos of props. …

Allow clients to override keyboard focus props on FlatList

---

Libraries/Lists/VirtualizedList.js
packages/rn-tester/js/examples/FlatList/FlatList-basic.js

Cherry pick of #1403
[macOS] [Fixed] - Allow clients to override keyboard focus props on FlatList

[0.68] Allow clients to override keyboard focus props on FlatList 

---

Libraries/Lists/VirtualizedList.js
packages/rn-tester/js/examples/FlatList/FlatListExample.js

Cherry pick of #1403
[macOS] [Fixed] - Allow clients to override keyboard focus props on FlatList

[0.66] Allow clients to override keyboard focus props on FlatList

---

React/Views/RCTActivityIndicatorView.m

For whatever reason, I need to update these headers to build on macOS 13 Ventura, Beta 4. 
Error message before update:
> error build: Definition of 'CIFilter' must be imported from module 'CoreImage.CIFilter' before it is required
[macOS] [Fixed] - Fix macOS 13 build error 
Builds on my local machine. I'm hoping the CI will inform me whether this change is valid on older macOS versions.

Fix macOS 13 build error 

---

React/Views/RCTActivityIndicatorView.m

Backport of #1408
[macOS] [Fixed] - Fix macOS 13 build error

[0.68] Fix macOS 13 build error

---

React/Views/RCTActivityIndicatorView.m

Backport of #1408
[macOS] [Fixed] - Fix macOS 13 build error

[0.66] Fix macOS 13 build error

---

Libraries/Components/ScrollView/ScrollView.js
Libraries/Components/ScrollView/__tests__/__snapshots__/ScrollView-test.js.snap
Libraries/Components/View/ViewPropTypes.js
Libraries/Lists/FlatList.js
Libraries/Lists/VirtualizedList.js
React/Views/ScrollView/RCTScrollContentView.h
React/Views/ScrollView/RCTScrollContentView.m
React/Views/ScrollView/RCTScrollContentViewManager.m
React/Views/ScrollView/RCTScrollView.h
React/Views/ScrollView/RCTScrollView.m
React/Views/ScrollView/RCTScrollViewManager.m
packages/rn-tester/js/examples/ScrollView/ScrollViewExample.js

Allow to render a scrollView's content in inverted order which is especially helpful in messaging applications.
Co-authored-by: Scott Kyle [skyle@fb.com](mailto:skyle@fb.com)
[macOS] [Added] - Support inverted ScrollView on macOS
Added RNTester example
https://user-images.githubusercontent.com/484044/180100444-ca02296a-6e12-4374-b348-6c4fde63d96c.mov
Default, non-inverted example
https://user-images.githubusercontent.com/484044/180100638-503d98ea-9a00-4efe-8f09-56ef483c1ab6.mov

Support inverted ScrollView on macOS

---

Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/RCTBackedTextInputDelegate.h
Libraries/Text/TextInput/RCTBaseTextInputView.m
packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js

This allows `MultilineTextInput` to also accept and respond to the same drag and drop props as `View` (and as SingleLineTextInput) which is discussed here https://github.com/microsoft/react-native-macos/issues/842
[macOS] [Added] - Add MultilineTextInput drag/drop support
Using this customized example from https://github.com/microsoft/react-native-macos/blob/main/packages/rn-tester/js/examples/Touchable/TouchableExample.js#L523-L538
```
<TouchableOpacity
style={styles.wrapper}
testID="touchable_feedback_mouse_events_button"
accessibilityLabel="touchable feedback mouse events"
onPressIn={e => this._appendEvent('MouseIn', e.nativeEvent)}
onPressOut={e => this._appendEvent('MouseOut', e.nativeEvent)}
draggedTypes={'fileUrl'}
onDragEnter={e =>
this._appendEvent('TouchableOpacityEnter', …
```

Add MultilineTextInput drag/drop support

---

packages/rn-tester/Podfile
packages/rn-tester/Podfile.lock
packages/rn-tester/RNTesterPods.xcodeproj/project.pbxproj

These cocoapod targets are a relic of when this repo was closed source. Downstream we have a copy of these targets, and no longer need them in the open source repo
[macOS] [Removed] - Remove redundant podfile targets
If this breaks stuff downstream, I'll back it out.

Remove redundant podfile targets

---

Libraries/Components/TextInput/TextInput.js
Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/RCTBackedTextInputDelegate.h
Libraries/Text/TextInput/RCTBackedTextInputDelegateAdapter.m
Libraries/Text/TextInput/RCTBaseTextInputView.h
Libraries/Text/TextInput/RCTBaseTextInputView.m
Libraries/Text/TextInput/RCTBaseTextInputViewManager.m
React/Base/RCTConvert.m
React/Views/RCTView.h
React/Views/RCTView.m
packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js

This adds an `onPaste` event for `MultilineTextInput` that is fired when a pasting into the input, and includes the same `dataTransfer` info as the `onDrop` callback which is discussed here https://github.com/microsoft/react-native-macos/issues/842
This also fixes a typo in the API name
This also adds logic to extract image size info from pasted images
- ```onPaste``` exists atm only for macOS, but we have the corresponding change to also add it rnw if that is desired
- Should we also add a property ```pasteTypes``` similar to drag&drag ```drag(ged)Types```?
[macOS] [Added] - Add MultilineTextInput paste support
Using this example with a paste handler. CMD+C, CMD+V
```
<TextInput
autoFocus={true}
multiline={true}
onPaste={e => console.log(e.nativeEvent.dataTransfer)} …
```

Add  MultilineTextInput paste support

---

React/CoreModules/RCTPerfMonitor.mm

We've seen an issue on iOS when doing remote web debugging while using [integrated RN](https://reactnative.dev/docs/integration-with-existing-apps) with a custom `RCTDevSettingsDataSource` that doesn't persist globally (unlike [the default](https://github.com/microsoft/react-native-macos/blob/b0aff93e9f804ef399737a8af5b48dd1761bf7de/React/CoreModules/RCTDevSettings.h#L15-L39) which uses `NSUserSettings`), a scenario useful when simultaneously running multiple RN instances with different dev settings.
When we reload the bridge upon establishing a remote debugging connection, we reinitialize all our modules. On iOS this includes `PerfMonitor`, which depends on `DevSettings`, which attempts to load the current values using the default `NSUserSettings`-based dev settings when it gets …

Grab RCTPerfMonitor's devSettings from the bridge

---

React/CoreModules/RCTPerfMonitor.mm

[0.68-stable] Grab RCTPerfMonitor's devSettings from the bridge

---

React/CoreModules/RCTPerfMonitor.mm

[0.66-stable] Grab RCTPerfMonitor's devSettings from the bridge

---

packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js

This fixes an rn-tester only warning introduced in https://github.com/microsoft/react-native-macos/pull/1350 as the image.source.uri should not be empty
[macOS] [Fixed] - Fix rn-tester TextInput warning for missing image.source.uri
Before
After
https://user-images.githubusercontent.com/484044/189795744-f755c92d-f182-4d44-912c-938cd2e567f1.mov

Fix rn-tester TextInput warning for missing image.source.uri

---

packages/react-native-macos-init/package.json
yarn.lock

Upgrade beachball to 2.30.1.
This bumps parse-url, an indirect dependency, to the latest version, thereby resolving [this vulnerability](https://security.snyk.io/package/npm/parse-url/7.0.2).

Bump beachball to 2.30.1

---

Libraries/Components/TextInput/TextInput.js
Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/RCTBackedTextInputDelegate.h
Libraries/Text/TextInput/RCTBaseTextInputView.h
Libraries/Text/TextInput/RCTBaseTextInputView.m
Libraries/Text/TextInput/RCTBaseTextInputViewManager.m
packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js

This brings macOS parity with react-native-windows https://github.com/microsoft/react-native-windows/pull/7333 for MultilineTextInput fields See react-native-windows PR for desired feature set.
We can't do it for SinglelineTextInput fields (at least not w/o hacks) as it does not support overriding the keyDown event :-( https://stackoverflow.com/a/6076492
[macOS] [Added] - Adds declarative props to clear/submit MultilineTextInput
https://user-images.githubusercontent.com/484044/189212524-3e1cee6e-a123-46c3-94c5-4e30f5917d5c.mov

Adds declarative props to clear/submit MultilineTextInput

---

Libraries/Components/TextInput/TextInput.js
Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.h
Libraries/Text/TextInput/Multiline/RCTMultilineTextInputView.m
Libraries/Text/TextInput/Multiline/RCTMultilineTextInputViewManager.m
Libraries/Text/TextInput/Multiline/RCTUITextView.h
Libraries/Text/TextInput/Multiline/RCTUITextView.m
Libraries/Text/TextInput/RCTBaseTextInputView.m
React/Base/RCTConvert.m
packages/rn-tester/js/examples/TextInput/TextInputExample.ios.js

There are use cases in which we want to ignore the base class [NSTextView readablePasteboardTypes] return values, which mostly, include RTF and formatted URL types.
We want to ignore them in favor of plain text (NSPasteboardTypeString).
This change allows to opt into a custom list of supported paste types.
This is a follow-up to https://github.com/microsoft/react-native-macos/pull/1350
[macOS] [Added] - Add option to enforce pasting plain text
No rich text formatting anymore
https://user-images.githubusercontent.com/484044/189237527-a2ef333b-ba3e-41ea-aae7-111d897d4626.mov
Test case from https://github.com/microsoft/react-native-macos/pull/1350 still work
https://user-images.githubusercontent.com/484044/189237558-56cc6fb3-15be-4c12-802d-a43f9def3562.mov

Add option to enforce pasting plain text

---

React/Base/RCTUtils.m

We ran into an issue that our production app was crashing on certain devices as we opened too many file descriptors (> 256). See some details here: https://wilsonmar.github.io/maximum-limits/
We found that macOS will keep image files handles open for `NSImage` lifetime in some cases:
```
// this will keep file open only if image is loaded from app bundle
NSString *path = [[NSBundle mainBundle] pathForResource:@"slider" ofType:@"png" inDirectory:@"assets"];
_image = [[NSImage alloc] initWithContentsOfFile:path];
// this will not keep file open
_image = [[NSImage alloc] initWithContentsOfFile:@"/Users/theUser/Downloads/slider.png"];
// this will not keep file open
NSData *data = [NSData dataWithContentsOfFile:path];
_image = [[NSImage alloc] initWithData:data];
```
This can be documented …

Workaround to open file handles for loaded assets

---

Libraries/Image/RCTImageView.mm

Since `RCTResizeModeCover` is implemented manually on macOS (iOS benefits from `UIViewContentModeScaleAspectFill` API), we need to reprocess the image any time the bounds of the view update. The `updateImage:` method was already called on resize, so this instead stores the original image in an ivar so it can call `RCTFillImagePreservingAspectRatio` from `updateImage:` instead.
[macOS] [Fixed] - Fix resizeMode="cover" when image is resized
Look at the images labeled 'Cover' and observe how they don't properly resize
https://user-images.githubusercontent.com/484044/180457216-88a05f6f-3aef-40a6-af45-8e3e2f4feef7.mov
https://user-images.githubusercontent.com/484044/180457246-2b09e140-1dfe-489c-8d43-56bff5e53740.mov
Another demo, done internally …

Fix resizeMode="cover" when image is resized

---

.ado/publish.yml

Homebrew has been removed from GHA, see https://github.com/actions/runner-images/issues/6283
Let's add a step for adding homebrew to PATH.
[macOS] [Fixed] - Update yaml to add Homebrew to PATH
CI

Update yaml to add homebrew to PATH

---

.ado/publish.yml

https://github.com/microsoft/react-native-macos/pull/1441 added a step for adding Homebrew to PATH. Turns out brew is needed for earlier steps like apple-node-setup, so let's bump it up.
[macOS] [Fixed] - Message
Just CI, will make necessary changes if anything goes wrong.

Bump brew script up

---

android-patches/patches/V8/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java

Reverting the old_logic codepath in engine selection to old behaviour
There were some changes in the JS engine selection logic in RN68, which conflicted with our V8 patched. When rebasing patches we ended up with some subtle behaviour difference which broke commenting test app. 
This patch ensures that any apps without a custom JS executor will use V8.
There were some changes in the JS engine selection logic in RN68, which conflicted with our V8 patched. When rebasing patches we ended up with some subtle behaviour difference which broke commenting test app. 
This patch ensures that any apps without a custom JS executor will use V8.

AB#6796163: Reverting the old logic in engine selection to old behaviour

---

.ado/templates/download-android-dependencies.yml

The latest version of maven-dependency-utils automatically pulls in transitive python dependencies, so we do not need to explicitly pip install requests, which is never used directly.
[Android] [Internal] - Bump maven-dependency-utils and remove explicit dependency on requests
Ensure PR build succeeds.

Update to new version of maven-dependency-utils

---

Libraries/Text/TextInput/RCTBaseTextInputView.m
React/Base/RCTConvert.m

In https://github.com/microsoft/react-native-macos/pull/1429 I had naively assumed that `NSPasteboardTypeFileURL` is 1:1 replacement for the deprecated `NSFilenamesPboardType` property. It is not. It causes drag and drop of files from Finder to stop working when a `pastedTypes` property is set.
[macOS][Fixed] - Fix drag and drop of files in multiline textfield when a custom draggedType property is used
Before
https://user-images.githubusercontent.com/484044/195694913-2bdfa768-4e84-4e2e-9788-7eb5948f009c.mov
After
https://user-images.githubusercontent.com/484044/195694931-66821d49-81ff-4ceb-aeaf-055322648f6e.mov

Fix drag and drop of files in multiline textfield when a custom draggedType property is used

---

React/Views/RCTView.m

Copy of #1437 into 0.68-stable

[0.68] Refactor how focusable is handled in RCTView

---

Libraries/Lists/VirtualizedList.js

We have a client who would like the ArrowUp/Down event to bubble at the top and bottom of Flatlist (so that a super view like FocusZone can handle it). This is a simple change to make that happen. 
[macOS] [Fixed] - Flatlist: Let ArrowUp/ArrowDown bubble at the top/bottom of list
(I didn't include the test code in this PR)
Added a simple `validKeysDown/onKeyDown` test to the View that wraps `<Flatlist>` in the Flatlist test page to verify that the event did bubble. 
https://user-images.githubusercontent.com/6722175/198132559-082ca8e0-af82-4d1e-90d1-05a75f72d3df.mov

Flatlist: Let ArrowUp/ArrowDown bubble at the top/bottom of list

---

Libraries/Core/ReactNativeVersion.js
React/Base/RCTVersion.m
ReactAndroid/gradle.properties
ReactAndroid/src/main/java/com/facebook/react/modules/systeminfo/ReactNativeVersion.java
ReactCommon/cxxreact/ReactNativeVersion.h
package.json
packages/rn-tester/Podfile.lock
template/package.json

Force an update to 0.68.56.
A couple of days ago, our version bump pipeline failed to run to completion due to a merge conflict, so 0.68.56 published to NPM, but the version changes didn't get checked into the repo.
This fixes that. The next version bump to 0.68.57 should clean things up if all goes well.

Force update to 0.68.56

---

React/React-RCTFabric.podspec
ReactCommon/React-Fabric.podspec
ReactCommon/React-rncore.podspec
ReactCommon/react/renderer/graphics/React-graphics.podspec

Right now running:
in packages/rn-tester fails as certain targets are not enabled for macOS 10.15
This fixes the .podspec files - Fabric related code does not compile - but at least we can build rn-iOS with Fabric now.
If you ever build with Fabric enabled and then switch to a non Fabric workspace > there is a huge change the Xcode will produce funky compile errors.
Follow https://reactnative.dev/docs/the-new-architecture/use-app-template#troubleshooting
[macOS] [Fixed] - Enable .podspec files for Fabric
Pod installation complete! There are 69 dependencies from the Podfile and 57 total pods installed.
[!] The Podfile contains framework or static library targets (iosDeviceBuild, iosSimulatorBuild, macOSBuild), for which the Podfile …

Enable .podspec files for Fabric

---

React/Fabric/RCTSurfacePresenter.mm

When enabling the Fabric podspec files
https://github.com/microsoft/react-native-macos/pull/1460 we can't even compile rn-iOS.
Here is the 1st of 2 necessary fixes
[iOS] [Fixed] - Fix compile errors when building with Fabric on rn-iOS
https://user-images.githubusercontent.com/484044/198394877-f9a70a11-41e9-41c7-a3ac-d749a2ef933a.mov

Fix compile errors when building with Fabric on rn-iOS

---

React/Fabric/Mounting/ComponentViews/View/RCTViewComponentView.mm

This is the last change we need to make to enable Fabric + iOS
[macOS] [Fixed] - Add missing scaleFactor argument to Fabric RCTViewComponentView.mm
in packages/rn-tester run:
`
`
Open Xcode and run on iOS Simulator
https://user-images.githubusercontent.com/484044/199705740-ea057fd9-c986-4975-876d-a0eff9aac4fb.mov

Add missing scaleFactor argument to Fabric RCTViewComponentView.mm

---

ReactCommon/react/utils/ManagedObjectWrapper.h
ReactCommon/react/utils/ManagedObjectWrapper.mm

This class is used by Fabric - but does not compile on macOS yet.
Now it does.
Pull Request resolved: https://github.com/facebook/react-native/pull/35146
[macOS][Fixed] Make ManagedObjectWrapper compile on macOS
Xcode Preference's > General > Continue after build errors
No compile errors for ManagedObjectWrapper usage when building for macOS:

Cherry-pick: Enable ManagedObjectWrapper on react-native-macOS (#35146)

---

React/Fabric/RCTSurfaceTouchHandler.mm

Pull Request resolved: https://github.com/facebook/react-native/pull/35131
[macOS][Fixed] - Remove unused #import <UIKit/UIGestureRecognizerSubclass.h> import which breaks macOS
Not used for macOS
Would not work on macOS
rn-iOS + Fabric still works:

Cherry-pick: Remove unused #import <UIKit/UIGestureRecognizerSubclass.h> import which breaks macOS (#35131)

---

React/Fabric/RCTConversions.h

https://github.com/facebook/react-native/commit/538636440b8
For embedded React Native screens, we need to calculate the intrinsic size. To do that, we need to pass Yoga value `YGUndefined`. However, if available size was `CGFLOAT_MAX` (which is not inifinity), we would pass it to Yoga and it would calculate layout with available height/width `CGFLOAT_MAX`.
To fix this, we convert `CGFLOAT_MAX` to infinity. Which in YogaLayoutableShadowNode gets converted to YGUndefined.
changelog: [internal]
Code is only used for Fabric - which is not enabled yet for react-native-macOS

Cherry-pick: Convert CGFLOAT_MAX to infinity

---

React/Base/RCTAssert.h
React/Base/RCTAssert.m
React/Base/RCTBridge.m
React/Fabric/Mounting/ComponentViews/LegacyViewManagerInterop/RCTLegacyViewManagerInteropComponentView.mm
React/Views/RCTViewManager.m

https://github.com/facebook/react-native/commit/3c4850d76b8
- Set `RCTEnableNewArchitectureViolationReporting` to YES in app-wide Bridgeless mode.
- Rename `RCTWarnNotAllowedForNewArchitecture` to `RCTErrorNotAllowedForNewArchitecture`, and use `RCTLogError` instead of `RCTLogWarn` so the error goes to Logview.
Build and run rn-tester-iOS

Cherry-pick: (Easy) Log errors to Logview when Bridge is used in Bridgeless

---

React/Fabric/RCTLocalizationProvider.mm

https://github.com/facebook/react-native/commit/18196512db6
We've seen a couple of `EXC_BAD_ACCESS` crashes in [`RCTParagraphComponentAccessibilityProvider.mm:L125`](https://github.com/facebook/react-native/blob/52d8a797e7a6be3fa472f323ceca4814a28ef596/React/Fabric/Mounting/ComponentViews/Text/RCTParagraphComponentAccessibilityProvider.mm#L125), most likely explained by [RCTLocalizationProvider RCTLocalizedString] returning nil, which will happen in the case that a language pack has no entry for the input string.
This is a small defensive change to fall back to the input if there's no better alternative.
Changelog:
[iOS][Fixed] - `RCTLocalizationProvider` Fall back to input when no localization is available
Build …

Cherry-pick: Fall back to non-localized string if no translation is available

---

React/Fabric/Mounting/RCTMountingManager.h
React/Fabric/Mounting/RCTMountingManager.mm
React/Fabric/RCTSurfacePresenter.mm

Cherry-pick a **react-native@0.70** commit into the current main branch:
https://github.com/facebook/react-native/commit/baada4e2990
Noticed we were copying ShadowView, where a reference should suffice.
Compile rn-tester-iOS with Fabric enabled via
```
```

Cherry-pick: Remove shadowview copy in setIsJSResponder
